// Add Seattle as new city - 25 verified restaurants (all confirmed open April 2026)
// Sources: James Beard 2026, Seattle Times, The Infatuation, Resy, Eater Seattle
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");

const base = {phone:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",suburb:false,reserveUrl:"",menuUrl:""};

const SEATTLE_DATA = [
  {...base,id:9001,name:"Canlis",cuisine:"Pacific Northwest Tasting Menu",neighborhood:"Queen Anne",score:98,price:4,tags:["Fine Dining","Exclusive","Awards","Date Night","Celebrations","Tasting Menu"],indicators:[],hh:"",reservation:"Tock",awards:"James Beard Outstanding Restaurant, James Beard Best Chef Northwest",description:"Seattle's iconic fine dining restaurant since 1950. Family-owned, perched above Lake Union in a stunning mid-century modern space. Five-course tasting menu at $180/person.",dishes:["5-Course Tasting Menu","Peter Canlis Prawns","Wagyu","Seasonal Dessert"],address:"2576 Aurora Ave N, Seattle WA 98109",lat:47.6432,lng:-122.3471,instagram:"@canlisrestaurant",website:"https://canlis.com",res_tier:5},
  {...base,id:9002,name:"Archipelago",cuisine:"Filipino-American Tasting Menu",neighborhood:"Hillman City",score:96,price:4,tags:["Fine Dining","Exclusive","Awards","Date Night","Tasting Menu"],indicators:[],hh:"",reservation:"Tock",awards:"James Beard Outstanding Chef Semifinalist 2026",description:"Chef Aaron Verzosa's 8-seat counter serving 10-12 course Filipino-American tasting menu using only Pacific Northwest ingredients. A Social Purpose Corporation connected to Seattle Public Schools.",dishes:["Tasting Menu","Heritage Filipino Courses","PNW Seafood","Seasonal Foraging"],address:"5607 Rainier Ave S, Seattle WA 98118",lat:47.5508,lng:-122.2867,instagram:"@archipelagoseattle",website:"https://www.archipelagoseattle.com",res_tier:5},
  {...base,id:9003,name:"The Walrus and the Carpenter",cuisine:"Seafood / Oyster Bar",neighborhood:"Ballard",score:94,price:3,tags:["Seafood","Oysters","Date Night","Local Favorites","Happy Hour","Cocktails"],indicators:[],hh:"Mon-Fri 4-5PM $3 oysters",reservation:"OpenTable",awards:"James Beard Semifinalist",description:"Renee Erickson's beloved Ballard oyster bar. Pacific Northwest seafood and muscadet in a lively, intimate space on Ballard Ave. Walk-in focused with a great happy hour.",dishes:["Raw Oysters","Steak Tartare","Pan-Roasted Mussels","Grilled Sardines"],address:"4743 Ballard Ave NW, Seattle WA 98107",lat:47.6637,lng:-122.3840,group:"Sea Creatures",instagram:"@thewalrusbar",website:"https://thewalrusbar.com",res_tier:2},
  {...base,id:9004,name:"Homer",cuisine:"New American",neighborhood:"Beacon Hill",score:93,price:3,tags:["Date Night","Critics Pick","Awards","Local Favorites","Cocktails"],indicators:[],hh:"",reservation:"Resy",awards:"James Beard Semifinalist 2026",description:"Chef Logan Cox's Beacon Hill restaurant serving Pacific Northwest cuisine with global influences. Repeat James Beard semifinalist known for inventive seasonal cooking.",dishes:["Seasonal Tasting Plates","Wood-Fired Fish","Heritage Pork","Housemade Bread"],address:"3013 Beacon Ave S, Seattle WA 98144",lat:47.5706,lng:-122.3083,instagram:"@homerseattle",website:"https://www.homerseattle.com",res_tier:3},
  {...base,id:9005,name:"Musang",cuisine:"Filipino",neighborhood:"Beacon Hill",score:93,price:2,tags:["Date Night","Critics Pick","Awards","Local Favorites","Casual"],indicators:[],hh:"",reservation:"Resy",awards:"James Beard Semifinalist 2026",description:"Chef Melissa Miranda's Beacon Hill Filipino restaurant. Community-driven dining with kamayan feasts and a la carte dishes celebrating Filipino heritage with PNW ingredients.",dishes:["Kamayan Feast","Sinigang","Lumpia","Ube Desserts"],address:"2524 Beacon Ave S, Seattle WA 98144",lat:47.5745,lng:-122.3083,instagram:"@musangseattle",website:"https://www.musangseattle.com",res_tier:2},
  {...base,id:9006,name:"Cascina Spinasse",cuisine:"Italian",neighborhood:"Capitol Hill",score:92,price:3,tags:["Italian","Date Night","Local Favorites","Cocktails","Fine Dining"],indicators:[],hh:"",reservation:"OpenTable",awards:"James Beard Semifinalist",description:"Piedmontese Italian on Capitol Hill. Handmade tajarin pasta and seasonal Northern Italian dishes in a warm, intimate setting. One of the best Italian restaurants on the West Coast.",dishes:["Tajarin al Ragù","Risotto","Seasonal Antipasti","Panna Cotta"],address:"1531 14th Ave, Seattle WA 98122",lat:47.6148,lng:-122.3141,instagram:"@cascinaspinasse",website:"https://www.spinasse.com",res_tier:3},
  {...base,id:9007,name:"Joule",cuisine:"Korean Fusion",neighborhood:"Wallingford",score:92,price:3,tags:["Date Night","Cocktails","Critics Pick","Awards","Local Favorites"],indicators:[],hh:"",reservation:"OpenTable",awards:"James Beard Semifinalist (Rachel Yang & Seif Chirchi)",description:"Chefs Rachel Yang and Seif Chirchi's Korean-influenced restaurant in Wallingford. Bold flavors blending Korean, French, and PNW cuisines. The relocation Wagyu is legendary.",dishes:["Relocation Wagyu","Korean Fried Chicken","Dungeness Crab","Tofu Steak"],address:"3506 Stone Way N, Seattle WA 98103",lat:47.6512,lng:-122.3425,instagram:"@jouleseattle",website:"https://www.joulerestaurant.com",res_tier:2},
  {...base,id:9008,name:"Rupee Bar",cuisine:"Indian Street Food",neighborhood:"Capitol Hill",score:91,price:2,tags:["Indian","Casual","Cocktails","Late Night","Local Favorites","Critics Pick"],indicators:[],hh:"",reservation:"walk-in",awards:"James Beard Semifinalist",description:"Chef Sapna Punjabi-Gupta's vibrant Indian street food bar on Capitol Hill. Chaat, dosas, and creative cocktails in a fun, casual setting. One of Seattle's most exciting restaurants.",dishes:["Chaat","Dosa","Lamb Keema Pav","Mango Lassi Cocktail"],address:"722 E Pike St, Seattle WA 98122",lat:47.6140,lng:-122.3213,instagram:"@rupeebar",website:"https://www.rupeebar.com",res_tier:1},
  {...base,id:9009,name:"How to Cook a Wolf",cuisine:"Mediterranean",neighborhood:"Queen Anne",score:91,price:3,tags:["Italian","Date Night","Local Favorites","Cocktails","Patio"],indicators:[],hh:"",reservation:"OpenTable",awards:"",description:"Ethan Stowell's Queen Anne Mediterranean restaurant. Small plates, handmade pasta, and a seasonal menu in a cozy, energetic setting. Named after MFK Fisher's wartime cookbook.",dishes:["Handmade Pasta","Brussels Sprouts","Seasonal Crudo","Wood-Fired Pizza"],address:"2208 Queen Anne Ave N, Seattle WA 98109",lat:47.6378,lng:-122.3568,group:"Ethan Stowell Restaurants",instagram:"@howtocookawolf",website:"https://ethanstowellrestaurants.com/locations/how-to-cook-a-wolf/",res_tier:2},
  {...base,id:9010,name:"Shaker + Spear",cuisine:"Pacific Northwest Seafood",neighborhood:"Belltown",score:90,price:3,tags:["Seafood","Date Night","Cocktails","Hotel"],indicators:[],hh:"",reservation:"OpenTable",awards:"",description:"Inside the Palladian Hotel, serving PNW seafood with Spanish influences. A stunning Art Deco-inspired space in Belltown with an excellent raw bar and craft cocktails.",dishes:["Oysters","Whole Roasted Fish","Seafood Paella","Craft Cocktails"],address:"2000 2nd Ave, Seattle WA 98121",lat:47.6131,lng:-122.3458,instagram:"@shakerandspear",website:"https://shakerandspear.com",res_tier:2},
  {...base,id:9011,name:"Le Caviste",cuisine:"French Wine Bar",neighborhood:"Capitol Hill",score:91,price:3,tags:["French","Wine Bar","Date Night","Cocktails","Awards"],indicators:[],hh:"",reservation:"Resy",awards:"James Beard Outstanding Wine Program Semifinalist 2026",description:"A French wine bar and restaurant on Capitol Hill with a James Beard-nominated wine program. Natural wines, charcuterie, and seasonal French plates in a romantic setting.",dishes:["Charcuterie Board","Steak Frites","Escargot","French Cheese Selection"],address:"1919 E Madison St, Seattle WA 98122",lat:47.6160,lng:-122.3053,instagram:"@lecavisteseattle",website:"https://www.lecavisteseattle.com",res_tier:2},
  {...base,id:9012,name:"Taylor Shellfish Farms",cuisine:"Seafood / Oyster Bar",neighborhood:"Capitol Hill",score:90,price:2,tags:["Seafood","Oysters","Casual","Local Favorites","Happy Hour"],indicators:[],hh:"3-5pm daily",reservation:"walk-in",awards:"",description:"Family-owned since 1890 — the oldest shellfish farm in Washington state. Capitol Hill outpost serving pristine oysters, Dungeness crab, and geoduck straight from their farms.",dishes:["Oysters on the Half Shell","Dungeness Crab","Geoduck Sashimi","Manila Clams"],address:"1521 Melrose Ave, Seattle WA 98122",lat:47.6148,lng:-122.3281,instagram:"@taylorshellfish",website:"https://www.taylorshellfish.com",res_tier:0},
  {...base,id:9013,name:"Din Tai Fung",cuisine:"Taiwanese / Dumplings",neighborhood:"University Village",score:91,price:2,tags:["Chinese","Casual","Family Friendly","Local Favorites"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"The Seattle outpost of the legendary Taiwanese dumpling house. Known worldwide for perfect xiao long bao (soup dumplings). Lines form daily but move fast.",dishes:["Xiao Long Bao","Shrimp & Pork Wontons","Chicken Fried Rice","Green Beans"],address:"2621 NE 46th St, Seattle WA 98105",lat:47.6620,lng:-122.2990,instagram:"@dintaifungusa",website:"https://www.dintaifungusa.com",res_tier:0},
  {...base,id:9014,name:"Dick's Drive-In",cuisine:"Burgers",neighborhood:"Capitol Hill",score:89,price:1,tags:["Burgers","Casual","Local Favorites","Late Night","Quick Bite"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"Seattle's beloved burger chain since 1954. Cash-only, no-frills burgers, fries, and milkshakes that are woven into the city's identity. Sir Mix-a-Lot and Macklemore both name-dropped it.",dishes:["Dick's Deluxe","Cheeseburger","Hand-Cut Fries","Milkshake"],address:"115 Broadway E, Seattle WA 98102",lat:47.6193,lng:-122.3218,instagram:"@dicksdrivein",website:"https://www.ddir.com",res_tier:0},
  {...base,id:9015,name:"Pike Place Chowder",cuisine:"Seafood / Chowder",neighborhood:"Pike Place Market",score:89,price:2,tags:["Seafood","Casual","Local Favorites","Quick Bite"],indicators:[],hh:"",reservation:"walk-in",awards:"Nation's Best Chowder — Great Chowder Cook-Off",description:"Multiple award-winning chowder at Pike Place Market. New England clam chowder and smoked salmon chowder are must-orders. A Seattle visitor essential.",dishes:["New England Clam Chowder","Smoked Salmon Chowder","Seafood Bisque","Bread Bowl"],address:"1530 Post Alley, Seattle WA 98101",lat:47.6097,lng:-122.3425,instagram:"@pikeplacechowder",website:"https://www.pikeplacechowder.com",res_tier:0},
  {...base,id:9016,name:"Cafe Juanita",cuisine:"Italian",neighborhood:"Kirkland",score:93,price:4,tags:["Italian","Fine Dining","Date Night","Awards"],indicators:[],hh:"",reservation:"OpenTable",awards:"James Beard Best Chef Northwest (Holly Smith)",description:"Chef Holly Smith's James Beard Award-winning Italian restaurant in Kirkland. Northern Italian cuisine focused on game, offal, and housemade pasta in an intimate cottage setting.",dishes:["Wild Boar Ragù","Handmade Pasta","Seasonal Game","Italian Cheese Course"],address:"9702 NE 120th Pl, Kirkland WA 98034",lat:47.7054,lng:-122.1802,suburb:true,instagram:"@cafejuanita",website:"https://www.cafejuanita.com",res_tier:3},
  {...base,id:9017,name:"The Corson Building",cuisine:"Farm-to-Table",neighborhood:"Georgetown",score:92,price:4,tags:["Fine Dining","Date Night","Local Favorites","Patio"],indicators:[],hh:"",reservation:"Resy",awards:"Resy Hit List 2026",description:"Chef Emily Crawford Dann's hyper-seasonal farm-to-table restaurant in a converted Georgetown house. Multi-course dinners celebrate PNW bounty with painterly precision.",dishes:["Multi-Course Dinner","Seasonal Vegetables","Heritage Grains","Wood-Fired Bread"],address:"5609 Corson Ave S, Seattle WA 98108",lat:47.5489,lng:-122.3230,instagram:"@thecorsonbuilding",website:"https://www.thecorsonbuilding.com",res_tier:3},
  {...base,id:9018,name:"Westward",cuisine:"Mediterranean Seafood",neighborhood:"Wallingford",score:91,price:3,tags:["Seafood","Patio","Date Night","Brunch","Cocktails"],indicators:[],hh:"",reservation:"OpenTable",awards:"",description:"Waterfront Mediterranean seafood on Lake Union. The heated outdoor patio with fire pits and kayak dock is one of Seattle's most magical dining settings. Brunch is exceptional.",dishes:["Oysters","Wood-Fired Fish","Sunday Brunch","Fire Pit S'mores"],address:"2501 N Northlake Way, Seattle WA 98103",lat:47.6516,lng:-122.3312,group:"Sea Creatures",instagram:"@westwardseattle",website:"https://www.westwardseattle.com",res_tier:2},
  {...base,id:9019,name:"Communion",cuisine:"New American",neighborhood:"Georgetown",score:91,price:3,tags:["Date Night","Brunch","Local Favorites","Cocktails"],indicators:[],hh:"",reservation:"Resy",awards:"",description:"Modern American cuisine with PNW influences in Georgetown. Seasonal menu with a commitment to local sourcing. Weekend brunch is a neighborhood institution.",dishes:["Seasonal Menu","Fried Chicken","Heritage Pork","Sunday Brunch"],address:"6324 6th Ave S, Seattle WA 98108",lat:47.5414,lng:-122.3230,instagram:"@communionseattle",website:"https://www.communionseattle.com",res_tier:2},
  {...base,id:9020,name:"Paseo",cuisine:"Caribbean / Cuban",neighborhood:"Fremont",score:91,price:1,tags:["Caribbean","Casual","Local Favorites"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"Seattle's legendary Caribbean sandwich shop. The roasted pork shoulder pressed sandwich on a toasted baguette is frequently called the best sandwich in Seattle. Cash only.",dishes:["Caribbean Roast Pork Sandwich","Midnight Cuban","Scallop Sandwich","Black Beans & Rice"],address:"4225 Fremont Ave N, Seattle WA 98103",lat:47.6601,lng:-122.3502,instagram:"@paseoseattle",website:"https://www.paseorestaurants.com",res_tier:0},
  {...base,id:9021,name:"Eden Hill",cuisine:"New American Tasting Menu",neighborhood:"Queen Anne",score:93,price:4,tags:["Fine Dining","Date Night","Exclusive","Tasting Menu"],indicators:[],hh:"",reservation:"Tock",awards:"",description:"Chef Maximillian Petty's intimate 16-seat counter serving a seasonal multi-course tasting menu. Hyper-local PNW ingredients in one of Seattle's most exciting fine dining experiences.",dishes:["Tasting Menu","Seasonal Courses","PNW Seafood","Foraged Ingredients"],address:"2209 Queen Anne Ave N, Seattle WA 98109",lat:47.6379,lng:-122.3570,instagram:"@edenhillrestaurant",website:"https://www.edenhillrestaurant.com",res_tier:4},
  {...base,id:9022,name:"Kedai Makan",cuisine:"Malaysian",neighborhood:"Capitol Hill",score:90,price:2,tags:["Malaysian","Casual","Local Favorites","Critics Pick"],indicators:[],hh:"",reservation:"walk-in",awards:"Eater Seattle Essential",description:"Authentic Malaysian street food on Capitol Hill. Nasi lemak, laksa, and roti canai made with precision and care. One of the most unique restaurants in the Pacific Northwest.",dishes:["Nasi Lemak","Laksa","Roti Canai","Teh Tarik"],address:"1802 Bellevue Ave, Seattle WA 98122",lat:47.6161,lng:-122.3260,instagram:"@kedaimakan",website:"https://www.kedaimakan.com",res_tier:1},
  {...base,id:9023,name:"Ma'ono Fried Chicken & Whisky",cuisine:"Hawaiian / Fried Chicken",neighborhood:"West Seattle",score:89,price:2,tags:["Casual","Local Favorites","Brunch"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"Mark Fuller's Hawaiian-inspired fried chicken joint in West Seattle. The spiced buttermilk fried chicken and Hawaiian plates are neighborhood favorites. Great brunch too.",dishes:["Buttermilk Fried Chicken","Spam Musubi","Hawaiian Plate Lunch","Brunch Menu"],address:"4437 California Ave SW, Seattle WA 98116",lat:47.5617,lng:-122.3871,instagram:"@maonofriedchicken",website:"https://www.maono.com",res_tier:0},
  {...base,id:9024,name:"Cafe Besalu",cuisine:"French Bakery",neighborhood:"Ballard",score:90,price:1,tags:["Bakery/Coffee","Brunch","Casual","Local Favorites"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"Beloved Ballard French bakery known for the best croissants in Seattle. Everything is made by hand daily — when they sell out, they close. Lines form before opening.",dishes:["Butter Croissant","Pain au Chocolat","Ham & Cheese Croissant","Seasonal Danish"],address:"5909 24th Ave NW, Seattle WA 98107",lat:47.6699,lng:-122.3883,instagram:"",website:"",res_tier:0},
  {...base,id:9025,name:"Cafe Suliman",cuisine:"East African",neighborhood:"Capitol Hill",score:90,price:2,tags:["African","Casual","Critics Pick","Awards"],indicators:[],hh:"",reservation:"walk-in",awards:"James Beard Emerging Chef Semifinalist 2026",description:"Ahmed Suliman's casual Capitol Hill spot in Melrose Market. East African-inspired dishes that earned a 2026 James Beard Emerging Chef semifinalist nod. One of Seattle's most exciting new voices.",dishes:["East African Plates","Spiced Lamb","Seasonal Vegetable Dishes","Coffee Service"],address:"1531 Melrose Ave, Seattle WA 98122",lat:47.6148,lng:-122.3278,instagram:"@cafesuliman",website:"",res_tier:1},
];

// Add neighborhood data for Seattle
const SEATTLE_NEIGHBORHOODS = {
  'Capitol Hill':{emoji:'🎸',vibe:'Seattle\'s cultural hub. Bars, restaurants, live music, and the city\'s LGBTQ+ heart. The densest dining neighborhood in the Pacific Northwest.',bestFor:'Nightlife, Cocktails, Diverse Dining',knownFor:'Pike/Pine corridor, independent bookshops, live music, cocktail bars',mustVisit:'Cascina Spinasse, Rupee Bar, Le Caviste, Taylor Shellfish, Canon (whiskey bar)',tip:'Walk Pike/Pine between Broadway and 12th Ave for the best concentration of restaurants and bars.'},
  'Ballard':{emoji:'🦐',vibe:'Former Scandinavian fishing village turned brewpub and seafood mecca. Old Ballard Avenue is the dining strip.',bestFor:'Seafood, Breweries, Brunch',knownFor:'Ballard Ave restaurants, breweries, Sunday farmers market, locks',mustVisit:'The Walrus and the Carpenter, Cafe Besalu, Stoneburner, Reuben\'s Brews',tip:'The Ballard Farmers Market (Sundays) is the best in Seattle. Walk from there to Ballard Ave for lunch.'},
  'Pike Place Market':{emoji:'🐟',vibe:'The soul of Seattle since 1907. Fish throwing, flower stands, and the original Starbucks. Tourist-heavy but still essential.',bestFor:'Local Favorites, Quick Bite, Seafood',knownFor:'Fish Market, flower stands, Pike Place Chowder, original Starbucks',mustVisit:'Pike Place Chowder, Piroshky Piroshky, Matt\'s in the Market, Beecher\'s Cheese',tip:'Go before 9 AM to see the market like locals do. The lower levels (DownUnder) have hidden gems.'},
  'Fremont':{emoji:'🚀',vibe:'Self-proclaimed "Center of the Universe." Quirky, creative, with great casual restaurants and the famous Fremont Troll.',bestFor:'Casual, Quirky, Brunch',knownFor:'Fremont Troll, Lenin statue, Sunday market, Theo Chocolate factory',mustVisit:'Paseo, Revel, Eve, Manolin',tip:'Paseo\'s Caribbean roast pork sandwich is one of the best sandwiches in America. Cash only.'},
  'Wallingford':{emoji:'🏡',vibe:'A residential neighborhood with surprisingly excellent restaurants along 45th Street. Where Seattle chefs eat on their nights off.',bestFor:'Date Night, Neighborhood Gems',knownFor:'Joule, Westward waterfront, Stone Way restaurants',mustVisit:'Joule, Westward, Kisaku Sushi, Brimmer & Heeltap',tip:'Westward\'s heated waterfront patio with fire pits is magical — book for sunset.'},
  'Beacon Hill':{emoji:'🌏',vibe:'Seattle\'s most diverse neighborhood. Filipino, Vietnamese, Ethiopian, and cutting-edge fine dining side by side along Beacon Ave.',bestFor:'International, Fine Dining, Local Favorites',knownFor:'Archipelago, Musang, Homer, Light Rail access, diverse food scene',mustVisit:'Archipelago, Musang, Homer, Perihelion Brewery',tip:'Archipelago only seats 8 per night — book months ahead. Musang\'s kamayan feast is a communal dining experience.'},
};

// Insert SEATTLE_DATA before DALLAS_DATA
const insertPoint = html.indexOf("const DALLAS_DATA");
const seattleJS = "const SEATTLE_DATA=" + JSON.stringify(SEATTLE_DATA) + ";\n";
html = html.slice(0, insertPoint) + seattleJS + html.slice(insertPoint);

// Add Seattle to CITY_DATA
html = html.replace(
  "const CITY_DATA = {",
  "const CITY_DATA = {'Seattle':SEATTLE_DATA,"
);

// Add Seattle neighborhoods to CITY_NEIGHBORHOODS (find the closing of the object)
const nbhdInsert = "    'Seattle':" + JSON.stringify(SEATTLE_NEIGHBORHOODS) + ",\n";
html = html.replace(
  "const CITY_NEIGHBORHOODS = {",
  "const CITY_NEIGHBORHOODS = {\n" + nbhdInsert
);

// Add Seattle to CITY_COORDS for map
const coordsInsert = "'Seattle':[47.6062,-122.3321],";
if (!html.includes("'Seattle':[47")) {
  html = html.replace("const CITY_COORDS={", "const CITY_COORDS={" + coordsInsert);
}

fs.writeFileSync("index.html", html);
console.log("Seattle: " + SEATTLE_DATA.length + " restaurants added");
console.log("Seattle neighborhoods: " + Object.keys(SEATTLE_NEIGHBORHOODS).length);
console.log("Added to CITY_DATA, CITY_NEIGHBORHOODS, and CITY_COORDS");
console.log("Done!");
