// Add 25 Chicago restaurants - new city dataset
// All verified open, Michelin status confirmed for 2025/2026
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");

const CHICAGO_DATA = [
  {id:8001,name:"Alinea",cuisine:"Progressive American",neighborhood:"Lincoln Park",score:98,price:4,tags:["Fine Dining","Exclusive","Awards","Date Night","Celebrations","Tasting Menu"],indicators:[],hh:"",reservation:"Tock",awards:"Michelin 3-Star, James Beard Outstanding Chef (Grant Achatz)",description:"Grant Achatz's boundary-pushing 3-Michelin-star restaurant. Multi-sensory tasting menu with edible balloons, table desserts, and dishes that defy convention. One of the most important restaurants in America.",dishes:["Edible Balloon","Black Truffle Explosion","Alinea Table Dessert"],address:"1723 N Halsted St, Chicago IL 60614",hours:"Wed-Sun",lat:41.9133,lng:-87.6484,bestOf:["#1 Best Overall"],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Alinea Group",instagram:"@aaboreal",website:"https://www.alinearestaurant.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:5,phone:""},
  {id:8002,name:"Smyth",cuisine:"New American Tasting Menu",neighborhood:"West Loop",score:97,price:4,tags:["Fine Dining","Exclusive","Awards","Date Night","Tasting Menu"],indicators:[],hh:"",reservation:"Tock",awards:"Michelin 2-Star, James Beard Best Chef Great Lakes",description:"Chefs John and Karen Shields serve a hyper-seasonal tasting menu sourced from their own Midwest farm. Two Michelin stars and a James Beard Award for deeply personal, ingredient-driven cooking.",dishes:["Farm Tasting Menu","Seasonal Vegetables","Heritage Grains"],address:"177 N Ada St #101, Chicago IL 60607",hours:"Wed-Sat",lat:41.8846,lng:-87.6610,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@smythchicago",website:"https://www.smythrestaurant.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:5,phone:""},
  {id:8003,name:"Ever",cuisine:"New American Tasting Menu",neighborhood:"West Loop",score:97,price:4,tags:["Fine Dining","Exclusive","Awards","Date Night","Tasting Menu"],indicators:[],hh:"",reservation:"Tock",awards:"Michelin 2-Star",description:"Chef Curtis Duffy's intimate West Loop tasting menu. Two Michelin stars for exquisite multi-course dinners that balance artistry with deep flavor. Previously of Grace.",dishes:["Tasting Menu","Seasonal Compositions","Wagyu"],address:"1340 W Fulton St, Chicago IL 60607",hours:"Tue-Sat",lat:41.8866,lng:-87.6631,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@everrestaurant",website:"https://www.everrestaurant.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:5,phone:""},
  {id:8004,name:"Oriole",cuisine:"French-Japanese Tasting Menu",neighborhood:"West Loop",score:97,price:4,tags:["Fine Dining","Exclusive","Awards","Date Night","Tasting Menu"],indicators:[],hh:"",reservation:"Tock",awards:"Michelin 2-Star",description:"Hidden down a West Loop alley, Chef Noah Sandoval's 16-course tasting menu blends French technique with Japanese precision. Two Michelin stars in an unmarked space.",dishes:["16-Course Tasting Menu","A5 Wagyu","Caviar Service"],address:"661 W Walnut St, Chicago IL 60661",hours:"Tue-Sat",lat:41.8867,lng:-87.6450,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@oriolechicago",website:"https://www.oriolechicago.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:5,phone:""},
  {id:8005,name:"Girl & the Goat",cuisine:"New American",neighborhood:"West Loop",score:94,price:3,tags:["Date Night","Cocktails","Local Favorites","Critics Pick","Awards"],indicators:["women-owned"],hh:"",reservation:"Resy",awards:"James Beard Best Chef Great Lakes (Stephanie Izard), Top Chef Winner",description:"Stephanie Izard's flagship restaurant that helped launch Chicago's West Loop dining scene. Bold, playful dishes built around goat, vegetables, and fearless flavor combinations.",dishes:["Goat Empanadas","Wood Oven Roasted Pig Face","Kohlrabi Salad","Escargot Raviolo"],address:"809 W Randolph St, Chicago IL 60607",hours:"Sun-Thu 4:30-10, Fri-Sat 4:30-11",lat:41.8841,lng:-87.6474,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Girl & the Goat",instagram:"@girlandthegoat",website:"https://www.girlandthegoat.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:3,phone:""},
  {id:8006,name:"Au Cheval",cuisine:"American / Burgers",neighborhood:"West Loop",score:93,price:2,tags:["Casual","Local Favorites","Late Night","Critics Pick","Awards"],indicators:[],hh:"",reservation:"walk-in",awards:"Bon Appetit Best Burger in America",description:"Brendan Sodikoff's legendary diner serves what many call the best burger in America. The double cheeseburger with dijonnaise and a fried egg on top draws hour-long waits nightly.",dishes:["Double Cheeseburger","Chopped Chicken Liver","Hash Browns","Fried Bologna"],address:"800 W Randolph St, Chicago IL 60607",hours:"Daily 11am-late",lat:41.8842,lng:-87.6470,bestOf:["#1 Best Burgers"],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Hogsalt",instagram:"@auchevaldiner",website:"https://auchevaldiner.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:0,phone:""},
  {id:8007,name:"Topolobampo",cuisine:"Modern Mexican",neighborhood:"River North",score:95,price:4,tags:["Fine Dining","Mexican","Awards","Date Night","Critics Pick"],indicators:[],hh:"",reservation:"Tock",awards:"Michelin 1-Star, James Beard Outstanding Chef (Rick Bayless)",description:"Rick Bayless's fine-dining Mexican restaurant featuring seasonal tasting menus rooted in deep Mexican culinary traditions. One Michelin star and multiple James Beard Awards.",dishes:["Seasonal Tasting Menu","Oaxacan Mole","Bayless Guacamole"],address:"445 N Clark St, Chicago IL 60654",hours:"Tue-Sat dinner",lat:41.8906,lng:-87.6312,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Bayless Restaurants",instagram:"@taborestaurants",website:"https://www.rickbayless.com/restaurants/topolobampo/",suburb:false,reserveUrl:"",menuUrl:"",res_tier:4,phone:""},
  {id:8008,name:"Monteverde",cuisine:"Italian",neighborhood:"West Loop",score:94,price:3,tags:["Italian","Date Night","Critics Pick","Awards","Local Favorites"],indicators:["women-owned"],hh:"",reservation:"Resy",awards:"James Beard Semifinalist, Michelin Recommended",description:"Chef Sarah Grueneberg's handmade pasta restaurant in the West Loop. Every pasta is made in-house daily, from corzetti to tortellini. One of Chicago's hardest reservations.",dishes:["Cacio e Pepe","Tortellini in Brodo","Rigatoni Diavola","Tiramisu"],address:"1020 W Madison St, Chicago IL 60607",hours:"Tue-Sun",lat:41.8817,lng:-87.6538,bestOf:["#1 Best Italian"],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@monteverdechicago",website:"https://www.monteverdechicago.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:4,phone:""},
  {id:8009,name:"The Aviary",cuisine:"Craft Cocktails",neighborhood:"West Loop",score:93,price:4,tags:["Cocktails","Date Night","Exclusive","Late Night"],indicators:[],hh:"",reservation:"Tock",awards:"James Beard Outstanding Bar Program",description:"Grant Achatz's cocktail lounge applies molecular gastronomy techniques to drinks. Cocktails served in custom vessels with theatrical presentation. The Office speakeasy is below.",dishes:["Molecular Cocktails","Bar Snacks","The Office Speakeasy"],address:"955 W Fulton Market, Chicago IL 60607",hours:"Wed-Sun 5pm-midnight",lat:41.8866,lng:-87.6522,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Alinea Group",instagram:"@theaviary",website:"https://www.theaviary.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:4,phone:""},
  {id:8010,name:"Bavette's Bar & Boeuf",cuisine:"Steakhouse",neighborhood:"River North",score:93,price:4,tags:["Steakhouse","Date Night","Cocktails","Late Night","Fine Dining"],indicators:[],hh:"",reservation:"OpenTable",awards:"",description:"A glamorous throwback steakhouse with jazz-age decor, dim lighting, and impeccable cuts of beef. The bone-in ribeye and tableside Caesar are iconic Chicago dining experiences.",dishes:["Bone-In Ribeye","Tableside Caesar","Shrimp DeJonghe","Double-Cut Bacon"],address:"218 W Kinzie St, Chicago IL 60654",hours:"Daily 5pm-late",lat:41.8895,lng:-87.6351,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Hogsalt",instagram:"@bavetteschicago",website:"https://bavetteschicago.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:3,phone:""},
  {id:8011,name:"RPM Italian",cuisine:"Italian",neighborhood:"River North",score:92,price:4,tags:["Italian","Date Night","Fine Dining","Cocktails","Celebrations"],indicators:[],hh:"",reservation:"OpenTable",awards:"",description:"Bill and Giuliana Rancic's celebrity Italian restaurant with show-stopping tableside presentations and a power-dining atmosphere. The lobster cavatelli and veal chop are signatures.",dishes:["Lobster Cavatelli","Veal Chop","Tableside Caesar","Burrata"],address:"52 W Illinois St, Chicago IL 60654",hours:"Mon-Sat dinner, Sun brunch",lat:41.8910,lng:-87.6316,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Lettuce Entertain You",instagram:"@rpmitalian",website:"https://www.rpmrestaurants.com/rpm-italian/",suburb:false,reserveUrl:"",menuUrl:"",res_tier:3,phone:""},
  {id:8012,name:"Joe's Seafood, Prime Steak & Stone Crab",cuisine:"Seafood / Steakhouse",neighborhood:"River North",score:91,price:4,tags:["Seafood","Steakhouse","Fine Dining","Date Night","Celebrations"],indicators:[],hh:"",reservation:"OpenTable",awards:"",description:"The Chicago outpost of Miami's legendary Joe's Stone Crab. Massive stone crab claws flown in daily from Florida, plus prime steaks and classic sides in an upscale setting.",dishes:["Stone Crab Claws","Prime NY Strip","Key Lime Pie","Creamed Spinach"],address:"60 E Grand Ave, Chicago IL 60611",hours:"Daily lunch & dinner",lat:41.8916,lng:-87.6254,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Lettuce Entertain You",instagram:"@joesseafoodchicago",website:"https://www.joes.net/chicago/",suburb:false,reserveUrl:"",menuUrl:"",res_tier:2,phone:""},
  {id:8013,name:"Gibsons Bar & Steakhouse",cuisine:"Steakhouse",neighborhood:"Gold Coast",score:91,price:4,tags:["Steakhouse","Date Night","Local Favorites","Cocktails","Celebrations"],indicators:[],hh:"",reservation:"OpenTable",awards:"",description:"Chicago's most iconic steakhouse since 1989. A power-dining institution where sports stars, politicians, and Chicago elite converge over massive USDA Prime steaks and stiff martinis.",dishes:["WR Chicago Cut Ribeye","Gibsons Bone-In Filet","Turtle Pie","Jumbo Shrimp Cocktail"],address:"1028 N Rush St, Chicago IL 60611",hours:"Daily lunch & dinner",lat:41.9011,lng:-87.6283,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Gibsons Restaurant Group",instagram:"@gibsonssteakhouse",website:"https://www.gibsonssteakhouse.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:2,phone:""},
  {id:8014,name:"Lou Malnati's Pizzeria",cuisine:"Deep Dish Pizza",neighborhood:"River North",score:90,price:1,tags:["Pizza","Casual","Local Favorites","Family Friendly"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"The most beloved deep dish pizza in Chicago since 1971. The buttercrust deep dish with sausage is the gold standard. A Chicago institution with locations across the city.",dishes:["Buttercrust Deep Dish","Sausage Deep Dish","Thin Crust","Chocolate Chip Cookie"],address:"439 N Wells St, Chicago IL 60654",hours:"Daily 11am-11pm",lat:41.8903,lng:-87.6340,bestOf:["#1 Best Deep Dish"],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Lou Malnati's",instagram:"@loumalnatis",website:"https://www.loumalnatis.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:0,phone:""},
  {id:8015,name:"Portillo's",cuisine:"Chicago Hot Dogs / Italian Beef",neighborhood:"River North",score:88,price:1,tags:["Casual","Local Favorites","Family Friendly","Quick Bite"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"The quintessential Chicago fast-food experience since 1963. Italian beef dipped with hot giardiniera, Chicago-style hot dogs, and chocolate cake shakes are non-negotiable Chicago eating.",dishes:["Italian Beef (Dipped, Hot)","Chicago Hot Dog","Chocolate Cake Shake","Cheese Fries"],address:"100 W Ontario St, Chicago IL 60654",hours:"Daily 10am-11pm",lat:41.8936,lng:-87.6319,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Portillo's",instagram:"@portilloshotdogs",website:"https://www.portillos.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:0,phone:""},
  {id:8016,name:"Frontera Grill",cuisine:"Mexican",neighborhood:"River North",score:92,price:3,tags:["Mexican","Local Favorites","Critics Pick","Awards","Brunch"],indicators:[],hh:"",reservation:"walk-in",awards:"James Beard Outstanding Restaurant, James Beard Outstanding Chef (Rick Bayless)",description:"Rick Bayless's original casual Mexican restaurant, winner of the James Beard Outstanding Restaurant award. Regional Mexican dishes with ingredients sourced from small Mexican farms.",dishes:["Bayless Guacamole","Street Tacos","Mole Dishes","Churros"],address:"445 N Clark St, Chicago IL 60654",hours:"Tue-Sat lunch & dinner",lat:41.8906,lng:-87.6312,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"Bayless Restaurants",instagram:"@taborestaurants",website:"https://www.rickbayless.com/restaurants/frontera-grill/",suburb:false,reserveUrl:"",menuUrl:"",res_tier:1,phone:""},
  {id:8017,name:"Virtue",cuisine:"Southern American",neighborhood:"Hyde Park",score:93,price:3,tags:["Date Night","Local Favorites","Critics Pick","Awards","Brunch"],indicators:[],hh:"",reservation:"Resy",awards:"James Beard Best Chef Great Lakes (Erick Williams)",description:"Chef Erick Williams' celebration of Southern cuisine on the South Side. James Beard Best Chef winner for soulful dishes rooted in African American culinary traditions.",dishes:["Catfish","Short Rib","Smoked Chicken","Peach Cobbler"],address:"1462 E 53rd St, Chicago IL 60615",hours:"Tue-Sun",lat:41.7994,lng:-87.5865,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@virtuerestaurant",website:"https://www.virtuerestaurant.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:3,phone:""},
  {id:8018,name:"Kasama",cuisine:"Filipino-American",neighborhood:"Ukrainian Village",score:95,price:3,tags:["Brunch","Fine Dining","Awards","Critics Pick","Date Night"],indicators:[],hh:"",reservation:"Tock",awards:"Michelin 1-Star, James Beard Best Chef Great Lakes 2022",description:"The first Filipino restaurant to earn a Michelin star. By day, a casual bakery with legendary ube crinkle cookies. By night, an intimate tasting menu of Filipino fine dining.",dishes:["Ube Crinkle Cookie","Longanisa Breakfast","Filipino Tasting Menu","Lumpia"],address:"1001 N Winchester Ave, Chicago IL 60622",hours:"Wed-Sun brunch, Thu-Sat dinner",lat:41.8995,lng:-87.6756,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@kasamachicago",website:"https://www.kasamachicago.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:4,phone:""},
  {id:8019,name:"Parachute",cuisine:"Korean-American",neighborhood:"Avondale",score:93,price:3,tags:["Date Night","Critics Pick","Awards","Local Favorites"],indicators:[],hh:"",reservation:"Resy",awards:"Michelin 1-Star, James Beard Best Chef Great Lakes Nominee",description:"Husband-and-wife chefs Beverly Kim and Johnny Clark blend Korean flavors with American Midwest ingredients. The bing bread with butter is one of Chicago's most iconic dishes.",dishes:["Bing Bread","Wagyu Tartare","Duck Confit","Sesame Cake"],address:"3500 N Elston Ave, Chicago IL 60618",hours:"Tue-Sat dinner",lat:41.9459,lng:-87.7105,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@parachute_chi",website:"https://www.parachuterestaurant.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:3,phone:""},
  {id:8020,name:"Avec",cuisine:"Mediterranean",neighborhood:"West Loop",score:92,price:3,tags:["Date Night","Local Favorites","Critics Pick","Awards","Happy Hour"],indicators:[],hh:"3-5pm daily",reservation:"Resy",awards:"James Beard Outstanding Restaurant Nominee",description:"Communal cedar-walled wine bar serving bold Mediterranean small plates since 2003. The chorizo-stuffed medjool dates are one of Chicago's most famous dishes.",dishes:["Chorizo-Stuffed Dates","Focaccia","Wood-Roasted Fish","Seasonal Vegetables"],address:"615 W Randolph St, Chicago IL 60661",hours:"Daily dinner",lat:41.8843,lng:-87.6440,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"One Off Hospitality",instagram:"@avecrestaurant",website:"https://avecrestaurant.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:2,phone:""},
  {id:8021,name:"Superkhana International",cuisine:"Indian-American",neighborhood:"West Town",score:92,price:2,tags:["Casual","Critics Pick","Awards","Local Favorites"],indicators:[],hh:"",reservation:"Resy",awards:"Michelin Bib Gourmand, James Beard Semifinalist",description:"Chef Zeeshan Shah's inventive Indian-American cooking in a vibrant corner spot. Playful takes on desi classics with American diner influences. Michelin Bib Gourmand for outstanding value.",dishes:["Kheema Pav","Chili Paneer","Lamb Seekh Kebab","Gulab Jamun"],address:"3059 W Diversey Ave, Chicago IL 60647",hours:"Tue-Sun",lat:41.9317,lng:-87.7048,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@superkhana",website:"https://www.superkhanainternational.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:2,phone:""},
  {id:8022,name:"Pequod's Pizza",cuisine:"Deep Dish Pizza",neighborhood:"Lincoln Park",score:90,price:1,tags:["Pizza","Casual","Local Favorites","Late Night"],indicators:[],hh:"",reservation:"walk-in",awards:"",description:"The caramelized cheese crust is what sets Pequod's apart from every other deep dish in Chicago. Crispy, cheesy edges that shatter when you bite into them. Many locals prefer it to Lou Malnati's.",dishes:["Caramelized Crust Deep Dish","Sausage Pizza","Pan Pizza"],address:"2207 N Clybourn Ave, Chicago IL 60614",hours:"Daily 11am-2am",lat:41.9213,lng:-87.6643,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@pequodspizza",website:"https://pequodspizza.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:0,phone:""},
  {id:8023,name:"Mott St",cuisine:"Asian-American",neighborhood:"Wicker Park",score:91,price:2,tags:["Late Night","Casual","Local Favorites","Critics Pick","Cocktails"],indicators:[],hh:"",reservation:"Resy",awards:"Eater Chicago Essential",description:"Late-night Asian-American cooking from Edward Kim in a dark, moody Wicker Park space. The whole roasted chicken and crab rangoon are cult favorites that keep the bar packed past midnight.",dishes:["Whole Roasted Chicken","Crab Rangoon","Rice Cakes","Pork & Chive Dumplings"],address:"1401 N Ashland Ave, Chicago IL 60622",hours:"Tue-Sun 5pm-late",lat:41.9070,lng:-87.6695,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@maboroshi.chi",website:"",suburb:false,reserveUrl:"",menuUrl:"",res_tier:2,phone:""},
  {id:8024,name:"Big Jones",cuisine:"Southern / Creole",neighborhood:"Andersonville",score:90,price:3,tags:["Brunch","Date Night","Local Favorites","Critics Pick"],indicators:[],hh:"",reservation:"OpenTable",awards:"James Beard Semifinalist",description:"Chef Paul Fehribach's celebration of Southern heritage cuisine in Andersonville. Meticulous historical recipes from the pre-Civil War South to modern Lowcountry. Weekend brunch is outstanding.",dishes:["Fried Chicken","Shrimp & Grits","Buttermilk Biscuits","Pecan Pie"],address:"5347 N Clark St, Chicago IL 60640",hours:"Tue-Sun",lat:41.9787,lng:-87.6686,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@bigjones5347",website:"https://www.bigjoneschicago.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:1,phone:""},
  {id:8025,name:"Lula Cafe",cuisine:"Farm-to-Table American",neighborhood:"Logan Square",score:91,price:3,tags:["Brunch","Date Night","Local Favorites","Critics Pick"],indicators:[],hh:"",reservation:"Resy",awards:"James Beard Semifinalist",description:"Logan Square's original farm-to-table restaurant since 2000. Chef Jason Hammel's Monday tasting menus are a Chicago institution. Weekend brunch with seasonal dishes draws devoted regulars.",dishes:["Monday Tasting Menu","Farm Egg Scramble","Seasonal Pasta","Chocolate Pot de Creme"],address:"2537 N Kedzie Blvd, Chicago IL 60647",hours:"Mon, Wed-Sun",lat:41.9273,lng:-87.7078,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",instagram:"@lulacafe",website:"https://www.lulacafe.com",suburb:false,reserveUrl:"",menuUrl:"",res_tier:2,phone:""},
];

// Insert CHICAGO_DATA before DALLAS_DATA in the HTML
const insertPoint = html.indexOf("const DALLAS_DATA");
if (insertPoint === -1) { console.log("ERROR: DALLAS_DATA not found"); process.exit(1); }

const chicagoJS = "const CHICAGO_DATA=" + JSON.stringify(CHICAGO_DATA) + ";\n";
html = html.slice(0, insertPoint) + chicagoJS + html.slice(insertPoint);

// Update CITY_DATA to include Chicago
html = html.replace(
  "const CITY_DATA = {",
  "const CITY_DATA = {'Chicago':CHICAGO_DATA,"
);

fs.writeFileSync("index.html", html);
console.log("Chicago: " + CHICAGO_DATA.length + " restaurants added");
console.log("CITY_DATA updated with Chicago");
console.log("Done!");
