// Add 25 new Austin restaurants - verified open April 2026
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");
const match = html.match(/const AUSTIN_DATA\s*=\s*(\[[\s\S]*?\]);/);
const data = eval(match[1]);
const maxId = Math.max(...data.map(r => r.id));
let nextId = maxId + 1;

const base = {phone:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,group:"",suburb:false,reserveUrl:"",menuUrl:""};

const newRestaurants = [
  {...base,id:nextId++,name:"Birdie's",cuisine:"French-American",neighborhood:"East Austin",score:95,price:3,address:"2944 E 12th St, Austin, TX 78702",lat:30.2768,lng:-97.7083,tags:["Fine Dining","Date Night","Critics Pick","Awards","Local Favorites"],indicators:["women-owned"],awards:"James Beard Finalist 2025, Food & Wine Restaurant of the Year 2023",description:"Counter-service neighborhood restaurant and wine bar serving a daily-changing menu of seasonal American food. Chef Tracy Malechek-Ezekiel's prix fixe dinners have earned national acclaim.",dishes:["Prix Fixe Dinner","Seasonal Crudo","Handmade Pasta","Natural Wine Pairings"],reservation:"OpenTable",website:"https://www.birdiesaustin.com",instagram:"@birdiesaustin",hh:"",res_tier:4},
  {...base,id:nextId++,name:"Craft Omakase",cuisine:"Japanese Omakase",neighborhood:"Rosedale",score:96,price:4,address:"4400 N Lamar Blvd #102, Austin, TX 78756",lat:30.3127,lng:-97.7386,tags:["Fine Dining","Date Night","Exclusive","Critics Pick","Awards","Japanese"],indicators:[],awards:"Michelin Star 2024",description:"Intimate 12-seat omakase counter with 22-course seasonal tasting menu. Earned a Michelin star within 11 months of opening.",dishes:["22-Course Omakase","Seasonal Nigiri","A5 Wagyu","Uni Course"],reservation:"Tock",website:"https://craftomakase.com",instagram:"@craftomakase",hh:"",res_tier:5},
  {...base,id:nextId++,name:"InterStellar BBQ",cuisine:"BBQ",neighborhood:"Northwest Austin",score:95,price:2,address:"12233 Ranch Rd 620 N #105, Austin, TX 78750",lat:30.4614,lng:-97.8150,tags:["BBQ","Casual","Local Favorites","Critics Pick","Awards"],indicators:[],awards:"Michelin Star 2024",description:"Pitmaster John Bates serves post-oak-smoked barbecue that earned one of the first Michelin stars awarded to a BBQ joint.",dishes:["Brisket","Beef Ribs","Housemade Sausage","Smoked Turkey"],reservation:"walk-in",website:"https://www.theinterstellarbbq.com",instagram:"@interstellarbbq",hh:"",res_tier:0},
  {...base,id:nextId++,name:"LeRoy and Lewis",cuisine:"BBQ",neighborhood:"South Austin",score:95,price:2,address:"5621 Emerald Forest Dr, Austin, TX 78745",lat:30.2098,lng:-97.7963,tags:["BBQ","Casual","Local Favorites","Critics Pick","Awards"],indicators:[],awards:"Michelin Star 2024, James Beard Semifinalist 2025",description:"Pitmaster Evan LeRoy's innovative BBQ earned a Michelin star for pushing Central Texas traditions in creative directions.",dishes:["Brisket","Beef Cheeks","Smoked Beet","Loaded Potato"],reservation:"walk-in",website:"https://leroyandlewisbbq.com",instagram:"@leroyandlewis",hh:"",res_tier:0},
  {...base,id:nextId++,name:"Canje",cuisine:"Caribbean",neighborhood:"East Austin",score:94,price:3,address:"1914 E 6th St, Austin, TX 78702",lat:30.2631,lng:-97.7240,tags:["Date Night","Cocktails","Critics Pick","Awards","Local Favorites"],indicators:[],awards:"James Beard Semifinalist, NY Times Best Restaurants",description:"Chef Tavel Bristol-Joseph's celebration of Caribbean cuisine draws on Guyanese heritage. Named one of the best restaurants in America by the New York Times.",dishes:["Curry Goat","Pepper Pot","Jerk Chicken","Rum Punch"],reservation:"Resy",website:"https://canjeatx.com",instagram:"@canjeatx",hh:"",res_tier:3},
  {...base,id:nextId++,name:"Justine's Brasserie",cuisine:"French",neighborhood:"East Austin",score:91,price:3,address:"4710 E 5th St, Austin, TX 78702",lat:30.2598,lng:-97.7072,tags:["Late Night","Date Night","Cocktails","Patio","Local Favorites"],indicators:[],awards:"",description:"Bohemian East Austin institution since 2009, serving classic French brasserie fare until the wee hours in a romantically lit, vintage-filled space.",dishes:["Steak Frites","Moules Mariniere","Escargot","Creme Brulee"],reservation:"OpenTable",website:"https://justines1937.com",instagram:"@justinesbrasserie",hh:"",res_tier:2},
  {...base,id:nextId++,name:"Intero",cuisine:"Italian",neighborhood:"East Austin",score:90,price:3,address:"2612 E Cesar Chavez St, Austin, TX 78702",lat:30.2525,lng:-97.7174,tags:["Italian","Date Night","Local Favorites","Critics Pick"],indicators:[],awards:"Eater Austin Essential",description:"Cozy East Austin Italian focused on whole-animal butchery and seasonal Texas ingredients. Handmade pastas and house chocolates.",dishes:["Handmade Pasta","Whole Animal Charcuterie","Seasonal Risotto","House Chocolates"],reservation:"OpenTable",website:"https://www.interorestaurant.com",instagram:"@interorestaurant",hh:"",res_tier:2},
  {...base,id:nextId++,name:"Red Ash",cuisine:"Italian",neighborhood:"Downtown",score:91,price:4,address:"303 Colorado St #200, Austin, TX 78701",lat:30.2657,lng:-97.7447,tags:["Italian","Fine Dining","Date Night","Cocktails"],indicators:[],awards:"Eater Austin Essential",description:"Chef John Carver's downtown Italian showpiece pairs 50-day dry-aged steaks with handmade pastas and wood-grilled seafood.",dishes:["50-Day Dry-Aged Ribeye","Cacio e Pepe","Wood-Grilled Branzino","Burrata"],reservation:"Tock",website:"https://www.redashgrill.com",instagram:"@redashatx",hh:"",res_tier:3},
  {...base,id:nextId++,name:"Veracruz All Natural",cuisine:"Mexican",neighborhood:"East Austin",score:89,price:1,address:"2505 Webberville Rd, Austin, TX 78702",lat:30.2633,lng:-97.7105,tags:["Mexican","Casual","Local Favorites","Brunch"],indicators:["women-owned"],awards:"Food Network Top 5 Tacos in America",description:"Sisters Reyna and Maritza Vazquez built an Austin taco empire from a tiny trailer. Migas tacos and fresh corn tortillas are iconic.",dishes:["Migas Taco","Al Pastor Taco","Fresh Juices","Elote"],reservation:"walk-in",website:"https://www.veracruzallnatural.com",instagram:"@veracruzallnatural",hh:"",res_tier:0},
  {...base,id:nextId++,name:"Fonda San Miguel",cuisine:"Interior Mexican",neighborhood:"North Loop",score:93,price:3,address:"2330 W North Loop Blvd, Austin, TX 78756",lat:30.3189,lng:-97.7469,tags:["Mexican","Fine Dining","Date Night","Local Favorites","Brunch"],indicators:[],awards:"James Beard America's Classics Award",description:"Pioneer of interior Mexican cuisine in the US since 1975. Refined regional dishes in a hacienda-style setting. Sunday brunch buffet is legendary.",dishes:["Mole Poblano","Cochinita Pibil","Sunday Brunch Buffet","Chiles en Nogada"],reservation:"OpenTable",website:"https://www.fondasanmiguel.com",instagram:"@fondasanmiguel",hh:"",res_tier:2},
  {...base,id:nextId++,name:"Wink",cuisine:"New American",neighborhood:"Old West Austin",score:90,price:4,address:"1014 N Lamar Blvd #E, Austin, TX 78703",lat:30.2730,lng:-97.7536,tags:["Fine Dining","Date Night","Cocktails","Critics Pick","Local Favorites"],indicators:[],awards:"Austin Chronicle Restaurant Poll Winner",description:"Austin's original farm-to-table fine dining since 2001. 5 and 7 course tasting menus with 50+ wines by the glass.",dishes:["5-Course Tasting Menu","Seasonal Crudo","Pan-Seared Duck","Artisan Cheese Course"],reservation:"Resy",website:"https://www.winkrestaurant.com",instagram:"@winkrestaurant",hh:"",res_tier:3},
  {...base,id:nextId++,name:"Le Calamar",cuisine:"French",neighborhood:"Bouldin Creek",score:92,price:3,address:"1600 S 1st St #100, Austin, TX 78704",lat:30.2468,lng:-97.7549,tags:["Fine Dining","Date Night","Cocktails","Critics Pick","Awards"],indicators:[],awards:"Michelin Recommended 2025",description:"French bistro with Texan sensibility. Elegant yet affordable prix fixe menu in a romantic Bouldin Creek setting.",dishes:["Prix Fixe Menu","Duck Confit","Steak Tartare","Chocolate Souffle"],reservation:"OpenTable",website:"https://www.le-calamar.com",instagram:"@le_calamar_",hh:"",res_tier:3},
  {...base,id:nextId++,name:"Mercado Sin Nombre",cuisine:"Mexican Cafe",neighborhood:"East Austin",score:92,price:1,address:"408 N Pleasant Valley Rd, Austin, TX 78702",lat:30.2617,lng:-97.7139,tags:["Mexican","Casual","Brunch","Critics Pick","Awards"],indicators:[],awards:"Michelin Bib Gourmand 2025, James Beard Semifinalist 2026",description:"East Austin cafe exploring heirloom Mexican corn and specialty coffee. The 100-hour biscuit and masa twinkie earned national acclaim.",dishes:["100-Hour Biscuit","Masa Twinkie","Masa Pancakes","Mexican Coffee"],reservation:"walk-in",website:"https://www.mercadosinnombre.com",instagram:"@mercadosinnombre",hh:"",res_tier:0},
  {...base,id:nextId++,name:"Parish Barbecue",cuisine:"Cajun BBQ",neighborhood:"East Austin",score:91,price:2,address:"3220 Manor Rd, Austin, TX 78723",lat:30.2872,lng:-97.7032,tags:["BBQ","Casual","Local Favorites","Critics Pick","Awards"],indicators:[],awards:"Michelin Bib Gourmand 2025, Texas Monthly Top BBQ",description:"Pitmaster Holden Fulco blends Cajun spice with Central Texas BBQ tradition. A Franklin and InterStellar alum.",dishes:["Cajun Brisket","Boudin Sausage","Dirty Rice","Smoked Pork Ribs"],reservation:"walk-in",website:"https://parishbarbecue.com",instagram:"@parishbarbecue",hh:"",res_tier:0},
  {...base,id:nextId++,name:"Bufalina",cuisine:"Neapolitan Pizza",neighborhood:"East Austin",score:89,price:2,address:"2215 E Cesar Chavez St, Austin, TX 78702",lat:30.2551,lng:-97.7197,tags:["Italian","Casual","Date Night","Patio","Local Favorites"],indicators:[],awards:"",description:"Austin's original Neapolitan pizza destination since 2013, firing pies at 900+ degrees in a Stefano Ferrara oven. Natural wine and intimate patio.",dishes:["Margherita Pizza","Cacio e Pepe Pizza","Burrata","Seasonal Antipasti"],reservation:"Resy",website:"https://www.bufalinapizza.com",instagram:"@bufalinapizza",hh:"",res_tier:2},
  {...base,id:nextId++,name:"Aba Austin",cuisine:"Mediterranean",neighborhood:"South Congress",score:88,price:3,address:"1011 S Congress Ave, Austin, TX 78704",lat:30.2502,lng:-97.7498,tags:["Date Night","Patio","Cocktails","Brunch","Happy Hour"],indicators:[],awards:"",description:"Lettuce Entertain You's Texas outpost brings modern Mediterranean cooking to South Congress with a sprawling rooftop patio.",dishes:["Whipped Feta Dip","Lamb Kebabs","Grilled Branzino","Hummus"],reservation:"Tock",website:"https://www.abarestaurants.com/austin",instagram:"@abarestaurant",hh:"4-6pm Mon-Fri",res_tier:2},
  {...base,id:nextId++,name:"Micklethwait Barbecue",cuisine:"BBQ",neighborhood:"East Austin",score:90,price:2,address:"4602 Tanney St, Austin, TX 78721",lat:30.2731,lng:-97.6902,tags:["BBQ","Casual","Local Favorites","Critics Pick"],indicators:[],awards:"Michelin Recommended",description:"Tom Micklethwait has smoked exemplary Central Texas BBQ since 2012. Now in a converted church. Handmade sausages are standouts.",dishes:["Brisket","Jalapeno Cheese Sausage","Smoked Chicken","Pecan Pie"],reservation:"walk-in",website:"https://www.craftmeatsaustin.com",instagram:"@craftmeats",hh:"",res_tier:0},
  {...base,id:nextId++,name:"Moonshine Patio Bar & Grill",cuisine:"Southern",neighborhood:"Downtown",score:86,price:2,address:"303 Red River St, Austin, TX 78701",lat:30.2634,lng:-97.7378,tags:["Brunch","Patio","Happy Hour","Casual","Local Favorites"],indicators:[],awards:"",description:"Beloved Austin brunch institution since 2003 in one of the city's oldest buildings. All-you-care-to-eat Sunday brunch buffet.",dishes:["Sunday Brunch Buffet","Corn Dog Shrimp","Green Chile Mac","Chicken Fried Steak"],reservation:"OpenTable",website:"https://moonshinegrill.com",instagram:"@moonshine_atx",hh:"3-5:30pm Mon-Fri",res_tier:1},
  {...base,id:nextId++,name:"Bird Bird Biscuit",cuisine:"American Breakfast",neighborhood:"East Austin",score:87,price:1,address:"2701 Manor Rd, Austin, TX 78722",lat:30.2850,lng:-97.7140,tags:["Brunch","Casual","Local Favorites"],indicators:[],awards:"",description:"Oversized biscuit sandwiches loaded with fried chicken and creative toppings. Cult favorite with perpetual lines.",dishes:["The Nelly","The Lindsey","Biscuit Sandwich","Tots"],reservation:"walk-in",website:"https://www.birdbirdbiscuit.com",instagram:"@birdbirdbiscuit",hh:"",res_tier:0},
  {...base,id:nextId++,name:"Eldorado Cafe",cuisine:"Mexican",neighborhood:"Allandale",score:88,price:2,address:"3300 W Anderson Ln, Austin, TX 78757",lat:30.3623,lng:-97.7423,tags:["Mexican","Casual","Local Favorites","Brunch"],indicators:[],awards:"",description:"Family-owned neighborhood favorite serving Mexico-inspired comfort food. Queso, enchiladas, and five-salsa sampler draw devoted regulars.",dishes:["Queso","Mashed Potato Enchiladas","Quesa Birria","Five-Salsa Sampler"],reservation:"Resy",website:"https://www.eldoradocafeatx.com",instagram:"@eldoradocafeatx",hh:"",res_tier:1},
  {...base,id:nextId++,name:"Lutie's Garden Restaurant",cuisine:"New American",neighborhood:"Hyde Park",score:91,price:4,address:"4100 Red River St, Austin, TX 78751",lat:30.3010,lng:-97.7264,tags:["Fine Dining","Brunch","Patio","Date Night","Cocktails"],indicators:[],awards:"",description:"Set within the stunning Commodore Perry Estate, serving Texas heritage fare amid manicured gardens and grand architecture.",dishes:["Pain au Chocolat","Kouign Amann","Pan-Seared Redfish","Heritage Pork Chop"],reservation:"OpenTable",website:"https://auberge.com/commodore-perry/dine/luties",instagram:"@luties_austin",hh:"5-6pm Mon-Thu & Sun",res_tier:2},
  {...base,id:nextId++,name:"Soto",cuisine:"Japanese",neighborhood:"South Lamar",score:90,price:4,address:"1100 S Lamar Blvd #2115, Austin, TX 78704",lat:30.2542,lng:-97.7656,tags:["Japanese","Fine Dining","Date Night","Cocktails"],indicators:[],awards:"",description:"Acclaimed sushi and omakase destination on South Lamar serving pristine seasonal fish and chef-selected courses.",dishes:["Omakase Menu","Otoro Nigiri","Lobster Tempura","Seasonal Sashimi"],reservation:"OpenTable",website:"https://sotosouthlamar.com",instagram:"@soto_restaurant_atx",hh:"",res_tier:3},
  {...base,id:nextId++,name:"Asti Trattoria",cuisine:"Italian",neighborhood:"Hyde Park",score:88,price:3,address:"408 E 43rd St #C, Austin, TX 78751",lat:30.3043,lng:-97.7269,tags:["Italian","Date Night","Local Favorites","Patio"],indicators:[],awards:"Eater Austin Essential",description:"Charming Hyde Park neighborhood Italian with seasonally changing menus. Warm, romantic institution.",dishes:["Osso Buco","Handmade Pappardelle","Grilled Lamb Chops","Tiramisu"],reservation:"OpenTable",website:"https://astiaustin.com",instagram:"@asti_trattoria",hh:"",res_tier:2},
  {...base,id:nextId++,name:"The Peached Tortilla",cuisine:"Asian-Southern Fusion",neighborhood:"Allandale",score:86,price:2,address:"5520 Burnet Rd #100, Austin, TX 78756",lat:30.3388,lng:-97.7376,tags:["Brunch","Casual","Patio","Happy Hour","Local Favorites"],indicators:[],awards:"",description:"Started as a food truck in 2010, now a full-service restaurant blending Asian fusion with Southern comfort. Weekend brunch is a local staple.",dishes:["Brisket Hash","Korean Steak & Eggs","Chicken Katsu Curry","Bao Buns"],reservation:"OpenTable",website:"https://www.thepeachedtortilla.com",instagram:"@thepeachedtortilla",hh:"4-6pm Tue-Fri",res_tier:1},
  {...base,id:nextId++,name:"24 Diner",cuisine:"American Diner",neighborhood:"West Austin",score:85,price:2,address:"600 N Lamar Blvd #200, Austin, TX 78703",lat:30.2697,lng:-97.7527,tags:["Brunch","Late Night","Casual","Local Favorites"],indicators:[],awards:"Bon Appetit Best Diners in America",description:"24-hour urban diner serving chef-driven comfort food with local and organic ingredients. Belgian waffles and chicken fried steak are Austin brunch staples.",dishes:["Belgian Waffle","Chicken Fried Steak","Roasted Beet Salad","Burgers"],reservation:"walk-in",website:"https://www.24diner.com",instagram:"@24dineratx",hh:"",res_tier:0},
];

data.push(...newRestaurants);
console.log("Austin: " + data.length + " restaurants (added " + newRestaurants.length + ")");

const newData = JSON.stringify(data);
html = html.replace(match[0], "const AUSTIN_DATA=" + newData + ";");
fs.writeFileSync("index.html", html);
console.log("Done!");
