// Austin Batch 4: Classics, Korean, Indian, suburban, more bars, coffee, food trucks
// Run: node scripts/austin-batch-4.js

const fs = require('fs');
const file = require('path').join(__dirname, '..', 'index.html');
let html = fs.readFileSync(file, 'utf8');
const s = html.indexOf('const AUSTIN_DATA');
const a = html.indexOf('[', s);
let d=0,e=a;
for(let i=a;i<html.length;i++){if(html[i]==='[')d++;if(html[i]===']')d--;if(d===0){e=i+1;break;}}
const arr = JSON.parse(html.slice(a, e));
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let nextId = Math.max(...arr.map(r=>r.id||0))+1, added = 0;

function add(s) {
  if(existing.has(s.name.toLowerCase()))return;
  arr.push({id:nextId++,name:s.name,phone:s.phone||'',cuisine:s.cuisine,neighborhood:s.neighborhood,score:s.score,price:s.price,tags:s.tags,indicators:s.indicators||[],hh:'',reservation:s.reservation||'walk-in',awards:s.awards||'',description:s.description,dishes:s.dishes,address:s.address,hours:'',lat:s.lat,lng:s.lng,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:s.trending||false,group:s.group||'',instagram:s.instagram||'',website:s.website||'',suburb:s.suburb||false,reserveUrl:'',menuUrl:'',res_tier:s.res_tier||2});
  existing.add(s.name.toLowerCase());added++;
}

// === AUSTIN CLASSICS / INSTITUTIONS ===
add({name:"Kerbey Lane Cafe",cuisine:"American / Diner",neighborhood:"Central Austin",score:85,price:1,tags:["Brunch","Breakfast","Casual","Classic","Family","Late Night","Local Favorites"],description:"Austin's beloved 24-hour diner since 1980, started in a 1930s bungalow on Kerbey Lane. Pancakes (including the famous gingerbread), queso, and migas are Austin rites of passage. Multiple locations but the original on Kerbey Lane is the one. Open all night — a 2am essential.",dishes:["Gingerbread Pancakes","Queso","Migas","Breakfast Plates"],address:"3704 Kerbey Ln, Austin, TX 78731",phone:"(512) 451-1436",lat:30.3050,lng:-97.7540,instagram:"kerbeylane",website:"https://kerbeylanecafe.com"});

add({name:"Magnolia Cafe",cuisine:"American / Diner",neighborhood:"South Congress",score:85,price:1,tags:["Brunch","Breakfast","Casual","Classic","Late Night","Local Favorites"],description:"South Congress all-day diner with the motto 'Sorry, We're Open.' Serving Austin since 1988 with giant portions, gingerbread pancakes, and Love Migas. The neon signs and kitschy decor are peak Austin weird. Open early and late, every day.",dishes:["Love Migas","Gingerbread Pancakes","Enchiladas","Late Night Menu"],address:"1920 S Congress Ave, Austin, TX 78704",phone:"(512) 445-0000",lat:30.2430,lng:-97.7496,instagram:"magnoliacafeatx",website:"https://www.magnoliacafeaustin.com"});

add({name:"Chili's Original",cuisine:"American / Bar & Grill",neighborhood:"South Lamar",score:82,price:1,tags:["American","Casual","Classic","Family","Local Favorites"],description:"The original Chili's — the very first one, opened in 1975 on Greenville Avenue in Dallas, but the brand's spiritual home is Austin where HQ is based. The South Lamar flagship embodies the chain's Texas roots. A fun novelty for first-timers.",dishes:["Baby Back Ribs","Fajitas","Queso","Margaritas"],address:"1401 S Lamar Blvd, Austin, TX 78704",phone:"(512) 707-3500",lat:30.2500,lng:-97.7681,instagram:"chilis",website:"https://www.chilis.com"});

// === KOREAN ===
add({name:"Oseyo",cuisine:"Korean",neighborhood:"East Austin",score:88,price:2,tags:["Korean","Date Night","Cocktails","Local Favorites"],reservation:"Tock",description:"East Austin Korean restaurant bringing refined Korean flavors to Cesar Chavez. Bibimbap, Korean fried chicken, and banchan are elevated with quality ingredients and careful technique. The cocktail program adds Korean-inspired drinks. One of Austin's best Korean dining experiences.",dishes:["Bibimbap","Korean Fried Chicken","Banchan","Soju Cocktails"],address:"1628 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 920-1388",lat:30.2583,lng:-97.7276,instagram:"oseyoaustin",website:"https://www.oseyoaustin.com"});

add({name:"Chi'Lantro BBQ",cuisine:"Korean-Mexican Fusion",neighborhood:"Multiple Locations",score:85,price:1,tags:["Korean","Mexican","Casual","Food Truck","Local Favorites","Viral"],description:"The Korean-Tex-Mex fusion concept that became famous on Shark Tank. Kimchi fries are the signature — a pile of fries topped with Korean BBQ, kimchi, cheese, and Sriracha mayo. Started as a food truck and grew into a multi-location operation. Pure Austin food truck success story.",dishes:["Kimchi Fries","Korean BBQ","Burritos","Tacos"],address:"1509 S Lamar Blvd, Suite 575, Austin, TX 78704",phone:"(512) 382-0123",lat:30.2490,lng:-97.7681,instagram:"chilantro",website:"https://www.chilantrobbq.com"});

// === CHINESE / DIM SUM ===
add({name:"Ling Wu",cuisine:"Chinese / Dim Sum",neighborhood:"Southwest Austin",score:87,price:2,tags:["Chinese","Dim Sum","Family","Date Night"],reservation:"Resy",description:"Austin's best dim sum experience with two locations. Cart service on weekends with har gow, siu mai, and BBQ pork buns. The dinner menu spans Cantonese, Sichuan, and Hunan traditions. A much-needed addition to Austin's Chinese food scene.",dishes:["Dim Sum","Har Gow","Peking Duck","Mapo Tofu"],address:"7415 Southwest Pkwy, Austin, TX 78735",phone:"(512) 386-8999",lat:30.2420,lng:-97.8280,instagram:"lingwulantana",website:"https://lingwulantana.com"});

// === SEAFOOD ===
add({name:"Perla's Seafood & Oyster Bar",cuisine:"Seafood / Oyster Bar",neighborhood:"South Congress",score:88,price:3,tags:["Seafood","Oysters","Brunch","Patio","Date Night","Local Favorites"],reservation:"Resy",description:"South Congress seafood restaurant with one of Austin's most coveted patios — shaded by heritage oaks and perfect for people-watching. Gulf oysters, lobster rolls, and fresh fish in a coastal-chic setting. Weekend brunch draws a devoted crowd. Part of the McGuire Moorman Lambert group.",dishes:["Gulf Oysters","Lobster Roll","Grilled Fish","Brunch"],address:"1400 S Congress Ave, Austin, TX 78704",phone:"(512) 291-7300",lat:30.2496,lng:-97.7493,instagram:"perlasaustin",website:"https://www.perlasaustin.com",group:"McGuire Moorman Lambert"});

add({name:"Clark's Oyster Bar",cuisine:"Oyster Bar / Seafood",neighborhood:"West Austin",score:87,price:3,tags:["Seafood","Oysters","Date Night","Cocktails","Classic"],reservation:"Resy",description:"Sophisticated oyster bar in a historic Clarksville bungalow. Gulf and East Coast oysters, lobster rolls, and champagne in a refined but relaxed setting. The McGuire Moorman Lambert touch is evident in every detail. One of Austin's most polished casual dining experiences.",dishes:["Oysters","Lobster Roll","Trout Almondine","Champagne"],address:"1200 W 6th St, Austin, TX 78703",phone:"(512) 297-2525",lat:30.2720,lng:-97.7590,instagram:"clarksoysterbar",website:"https://www.clarksoysterbar.com",group:"McGuire Moorman Lambert"});

// === SOUTHERN / COMFORT ===
add({name:"Hoover's Cooking",cuisine:"Southern / Soul Food",neighborhood:"East Austin",score:86,price:1,tags:["Southern","Casual","Brunch","Family","Local Favorites"],description:"East Austin Southern comfort food institution serving chicken fried steak, catfish, and meatloaf since 2000. Hoover Alexander's cooking draws from Texas, Cajun, and Southern traditions. The jalapeño creamed corn is legendary. A neighborhood anchor that's fed East Austin for decades.",dishes:["Chicken Fried Steak","Catfish","Jalapeño Cream Corn","Meatloaf"],address:"2002 Manor Rd, Austin, TX 78722",phone:"(512) 479-5006",lat:30.2757,lng:-97.7195,instagram:"hooverscooking",website:"https://www.hooverscooking.com"});

add({name:"Gus's World Famous Fried Chicken",cuisine:"Fried Chicken",neighborhood:"Downtown",score:86,price:1,tags:["Southern","Fried Chicken","Casual","Local Favorites"],description:"Memphis-born fried chicken chain with a devoted Austin following. The spicy, crispy fried chicken is cooked to order and worth the wait. The white beans, coleslaw, and pickles complete the experience. Simple, perfect fried chicken in downtown Austin.",dishes:["Spicy Fried Chicken","White Beans","Coleslaw","Pickles"],address:"117 San Jacinto Blvd, Austin, TX 78701",phone:"(512) 474-4877",lat:30.2660,lng:-97.7400,instagram:"gaborasfriedchicken",website:"https://www.gusfriedchicken.com"});

// === BURGERS ===
add({name:"P. Terry's Burger Stand",cuisine:"Burgers / Fast Casual",neighborhood:"Multiple Locations",score:85,price:1,tags:["Burgers","Casual","Cheap Eats","Family","Local Favorites"],description:"Austin's beloved fast-casual burger chain — fresh, never-frozen patties, hand-cut fries, and real milkshakes at drive-through prices. Founded in 2005 and now with 20+ locations across Austin. The double with cheese and a shake is the move. Austin's answer to In-N-Out.",dishes:["P. Terry's Burger","Hand-Cut Fries","Milkshakes","Veggie Burger"],address:"404 S Lamar Blvd, Austin, TX 78704",phone:"(512) 473-2217",lat:30.2600,lng:-97.7681,instagram:"pterrys",website:"https://www.pterrys.com"});

add({name:"Dai Due Butcher Shop & Supper Club",cuisine:"Butcher / American",neighborhood:"East Austin",score:88,price:2,tags:["American","Butcher","Farm-to-Table","Local Favorites","Awards"],reservation:"walk-in",awards:"Michelin Bib Gourmand, Michelin Green Star",description:"Already exists as Dai Due.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

// === MORE BARS / NIGHTLIFE ===
add({name:"Half Step",cuisine:"Cocktail Bar",neighborhood:"Rainey Street",score:87,price:2,tags:["Cocktails","Bar","Date Night","Late Night","Local Favorites"],description:"Rainey Street cocktail bar in a converted bungalow with a covered patio and craft cocktail program that's among Austin's best. The bartenders are serious about their craft but the vibe is Rainey Street casual. A great starting point for a Rainey crawl.",dishes:["Craft Cocktails","Seasonal Menu","Bar Snacks"],address:"75 Rainey St, Austin, TX 78701",phone:"(512) 391-1877",lat:30.2576,lng:-97.7406,instagram:"halfstepbar",website:"https://www.halfstepbar.com"});

add({name:"Bangers Sausage House & Beer Garden",cuisine:"Beer Garden / Sausages",neighborhood:"Rainey Street",score:85,price:1,tags:["Beer Garden","Craft Beer","Sausages","Patio","Family","Live Music"],description:"Massive Rainey Street beer garden with 100+ craft beers on tap, house-made sausages, and a dog-friendly patio. Live music, communal picnic tables, and a family-friendly vibe during the day. One of Rainey Street's most popular and spacious spots.",dishes:["House Sausages","100+ Craft Beers","Pretzels","Loaded Fries"],address:"79 Rainey St, Austin, TX 78701",phone:"(512) 386-1656",lat:30.2576,lng:-97.7406,instagram:"bangersaustin",website:"https://www.bangersaustin.com"});

add({name:"Empire Control Room",cuisine:"Live Music Venue / Club",neighborhood:"Downtown",score:85,price:1,tags:["Live Music","Entertainment","Club","Late Night","Nightlife"],description:"Downtown live music venue and nightclub with multiple rooms hosting indie, electronic, hip-hop, and comedy. The Garage and The Control Room offer different vibes under one roof. A SXSW favorite and a key player in Austin's Red River Cultural District.",dishes:["Live Music","DJ Sets","Bar"],address:"606 E 7th St, Austin, TX 78701",phone:"(512) 651-4690",lat:30.2674,lng:-97.7350,instagram:"empirecontrolroom",website:"https://www.empireatx.com"});

add({name:"Antone's Nightclub",cuisine:"Live Music Venue / Blues",neighborhood:"Downtown",score:87,price:2,tags:["Live Music","Entertainment","Blues","Jazz Club","Iconic"],description:"Austin's legendary blues club since 1975 — the 'Home of the Blues.' Stevie Ray Vaughan, Muddy Waters, and B.B. King all played here. Now on East Fifth, Antone's continues to book world-class blues, soul, and roots acts. A shrine to the music that makes Austin the Live Music Capital.",dishes:["Live Blues","Cocktails","Music History"],address:"305 E 5th St, Austin, TX 78701",phone:"(512) 814-0361",lat:30.2668,lng:-97.7410,instagram:"antonesnightclub",website:"https://www.antonesnightclub.com"});

// === COFFEE / BAKERY ===
add({name:"Flitch Coffee",cuisine:"Specialty Coffee",neighborhood:"East Austin",score:85,price:1,tags:["Coffee","Casual","Local Favorites"],description:"East Austin specialty coffee trailer with some of the best espresso drinks in the city. The cortado is perfection and the seasonal specials are creative. The trailer setup is very Austin — order your coffee and sit under the trees. A neighborhood coffee ritual.",dishes:["Cortado","Espresso","Seasonal Specials","Cold Brew"],address:"2700 E 12th St, Austin, TX 78702",phone:"",lat:30.2729,lng:-97.7170,instagram:"flitchcoffee",website:"https://www.flitchcoffee.com"});

add({name:"Quack's 43rd Street Bakery",cuisine:"Bakery / Coffee",neighborhood:"Hyde Park",score:85,price:1,tags:["Bakery","Coffee","Breakfast","Casual","Local Favorites"],description:"Hyde Park neighborhood bakery and coffee shop serving fresh-baked pastries, cookies, and sandwiches since the 1990s. The chocolate chip cookie is enormous and the morning crowd is a who's-who of Austin's creative class. A Hyde Park institution with genuine neighborhood soul.",dishes:["Chocolate Chip Cookie","Pastries","Coffee","Sandwiches"],address:"411 E 43rd St, Austin, TX 78751",phone:"(512) 453-3399",lat:30.3050,lng:-97.7270,instagram:"quacksbakery",website:"https://www.quacksbakery.com"});

// === FOOD TRUCKS ===
add({name:"Dee Dee",cuisine:"Thai / Northern Thai",neighborhood:"East Austin",score:88,price:1,tags:["Thai","Food Truck","Casual","Awards","Local Favorites"],reservation:"walk-in",awards:"Michelin Recommended",description:"Michelin-recommended Northern Thai food truck serving Isaan and Chiang Mai-style dishes from a tiny East Austin trailer. The pad kra pao, khao soi, and sai oua sausage are deeply flavored and authentic. One of the few food trucks in the country with Michelin recognition.",dishes:["Pad Kra Pao","Khao Soi","Sai Oua Sausage","Papaya Salad"],address:"4200 E Martin Luther King Jr Blvd, Austin, TX 78721",phone:"",lat:30.2801,lng:-97.7050,instagram:"deedeeatx",website:"https://www.deedeeatx.com"});

add({name:"Taqueria Diez",cuisine:"Mexican / Tacos",neighborhood:"East Austin",score:87,price:1,tags:["Mexican","Tacos","Food Truck","Cheap Eats","Local Favorites","Awards"],reservation:"walk-in",awards:"Yelp Top 100 2026",description:"East Austin taqueria that made Yelp's nationwide Top 100 restaurants list. Al pastor, barbacoa, and carnitas tacos on handmade tortillas with salsas that pack real heat. Cash-friendly, fast, and genuinely excellent. The kind of taqueria Austin does better than anywhere.",dishes:["Al Pastor","Barbacoa","Carnitas","Handmade Tortillas"],address:"1811 E 7th St, Austin, TX 78702",phone:"(512) 710-5737",lat:30.2626,lng:-97.7240,instagram:"taqueriadiez",website:""});

// === SUBURBAN / DOMAIN ===
add({name:"North Italia",cuisine:"Italian",neighborhood:"Domain",score:85,price:2,tags:["Italian","Date Night","Casual","Patio"],reservation:"OpenTable",description:"Polished Italian at the Domain serving handmade pastas, thin-crust pizzas, and a Prosecco brunch that draws the North Austin crowd. The patio is gorgeous and the bar serves Italian cocktails. A reliable chain that executes well in the Domain setting.",dishes:["Handmade Pasta","Pizza","Prosecco Brunch","Italian Cocktails"],address:"11506 Century Oaks Terrace, Suite B113, Austin, TX 78758",phone:"(512) 814-2000",lat:30.4020,lng:-97.7260,instagram:"northitalia",website:"https://www.northitalia.com"});

add({name:"Perry's Steakhouse & Grille",cuisine:"Steakhouse",neighborhood:"Domain",score:88,price:4,tags:["Steakhouse","Fine Dining","Date Night","Celebrations"],reservation:"OpenTable",awards:"Wine Spectator Award",description:"Domain NORTHSIDE fine dining steakhouse known for the famous pork chop — a caramelized, roasted bone-in chop that's become a Texas legend. Prime steaks, seafood, and an award-winning wine program. The most polished dining option at the Domain. Friday lunch pork chop special is a cult favorite.",dishes:["Famous Pork Chop","Prime Steaks","Seafood","Wine Program"],address:"114 W 7th St, Suite 420, Austin, TX 78701",phone:"(512) 474-6300",lat:30.2674,lng:-97.7470,instagram:"perryssteakhouse",website:"https://perryssteakhouse.com"});

add({name:"Salt Traders Coastal Cooking",cuisine:"Seafood / Coastal",neighborhood:"Round Rock",score:85,price:2,tags:["Seafood","Casual","Family","Patio"],reservation:"walk-in",description:"Round Rock seafood restaurant serving sustainably sourced Gulf and coastal fare. Fresh oysters, shrimp po-boys, and fish tacos in a relaxed, patio-friendly setting. Working with fishermen and farms for quality ingredients. A solid suburban seafood option.",dishes:["Gulf Oysters","Shrimp Po-Boy","Fish Tacos","Cioppino"],address:"3016 Esperanza Crossing, Austin, TX 78758",phone:"(512) 339-7258",lat:30.4020,lng:-97.7160,instagram:"salttraders",website:"https://www.salttraders.com"});

// === DESSERT / ICE CREAM ===
add({name:"Amy's Ice Creams",cuisine:"Ice Cream",neighborhood:"Multiple Locations",score:86,price:1,tags:["Dessert","Ice Cream","Casual","Local Favorites","Family"],description:"Austin's homegrown ice cream institution since 1984. The Mexican Vanilla is the classic, but the rotating flavors and the counter staff's crush'n'mix technique make every visit a show. Multiple locations — the SoCo shop is the most atmospheric. An Austin institution for four decades.",dishes:["Mexican Vanilla","Crush'n'Mix","Seasonal Flavors","Shakes"],address:"1012 W 6th St, Austin, TX 78703",phone:"(512) 480-0673",lat:30.2700,lng:-97.7530,instagram:"amysicecreams",website:"https://www.amysicecreams.com"});

add({name:"Lick Honest Ice Creams",cuisine:"Ice Cream",neighborhood:"South Congress",score:86,price:1,tags:["Dessert","Ice Cream","Local Favorites","Casual"],description:"Farm-to-cone ice cream with ingredients from local Texas farms. Goat cheese, thyme & honey and dark chocolate with olive oil & sea salt are signatures that push ice cream boundaries. Multiple locations but the SoCo shop is the classic. Hormone-free, organic, and genuinely delicious.",dishes:["Goat Cheese Thyme Honey","Dark Chocolate Olive Oil","Seasonal Flavors"],address:"1100 S Congress Ave, Austin, TX 78704",phone:"(512) 462-6600",lat:30.2530,lng:-97.7493,instagram:"lickicecreams",website:"https://www.ilikelick.com"});

// Write back
html = html.slice(0, a) + JSON.stringify(arr) + html.slice(e);
fs.writeFileSync(file, html, 'utf8');
console.log('Austin: ' + arr.length + ' spots (added ' + added + ')');
console.log('Need', 250 - arr.length, 'more to hit 250');
