// Austin Batch 5: More neighborhoods, Michelin spots, Indian, Ethiopian, wine bars, Domain, suburban
// Austin at 142, need 108 more
// Run: node scripts/austin-batch-5.js

const fs = require('fs');
const file = require('path').join(__dirname, '..', 'index.html');
let html = fs.readFileSync(file, 'utf8');
const s = html.indexOf('const AUSTIN_DATA');
const a = html.indexOf('[', s);
let d=0,e=a;
for(let i=a;i<html.length;i++){if(html[i]==='[')d++;if(html[i]===']')d--;if(d===0){e=i+1;break;}}
const arr = JSON.parse(html.slice(a, e));
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let nextId = Math.max(...arr.map(r=>r.id||0))+1, added = 0;

function add(s) {
  if(existing.has(s.name.toLowerCase()))return;
  arr.push({id:nextId++,name:s.name,phone:s.phone||'',cuisine:s.cuisine,neighborhood:s.neighborhood,score:s.score,price:s.price,tags:s.tags,indicators:s.indicators||[],hh:'',reservation:s.reservation||'walk-in',awards:s.awards||'',description:s.description,dishes:s.dishes,address:s.address,hours:'',lat:s.lat,lng:s.lng,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:s.trending||false,group:s.group||'',instagram:s.instagram||'',website:s.website||'',suburb:s.suburb||false,reserveUrl:'',menuUrl:'',res_tier:s.res_tier||2});
  existing.add(s.name.toLowerCase());added++;
}

// === MICHELIN RECOMMENDED (still missing) ===
add({name:"Garrison",cuisine:"New American / Steakhouse",neighborhood:"Downtown",score:89,price:4,tags:["Steakhouse","Fine Dining","Date Night","Celebrations","Awards"],reservation:"OpenTable",awards:"Michelin Recommended",description:"The Fairmont Austin's signature restaurant with Texas steakhouse meets refined New American. Prime steaks, Gulf seafood, and downtown views. Polished service and an impressive wine program make it a celebration destination.",dishes:["Prime Steaks","Gulf Oysters","Seasonal Tasting","Wine Program"],address:"101 Red River St, Austin, TX 78701",phone:"(512) 495-1693",lat:30.2631,lng:-97.7380,instagram:"garrisonaustin",website:"https://www.garrisonaustin.com"});

add({name:"Toshokan",cuisine:"Japanese / Izakaya",neighborhood:"East Austin",score:88,price:3,tags:["Japanese","Izakaya","Date Night","Awards"],reservation:"Resy",awards:"Michelin Recommended",description:"Japanese izakaya and bar from Tatsu-Ya alum serving shareable plates, yakitori, and an extensive sake/shochu program. The name means 'library' in Japanese — a quiet, contemplative space for serious Japanese food. Michelin recommended.",dishes:["Yakitori","Sake Flights","Japanese Small Plates","Omakase"],address:"1000 E 5th St, Suite 110, Austin, TX 78702",phone:"(512) 763-0100",lat:30.2626,lng:-97.7330,instagram:"toshokanatx",website:"https://www.toshokanatx.com"});

add({name:"Ezov",cuisine:"Mediterranean / Israeli",neighborhood:"East Austin",score:88,price:2,tags:["Mediterranean","Israeli","Date Night","Cocktails","Awards"],reservation:"Resy",awards:"Michelin Recommended",description:"Israeli-Mediterranean restaurant in East Austin with dishes rooted in Tel Aviv food culture. Hummus, pita, and mezze are the stars, alongside grilled meats and seasonal vegetables. The cocktail program uses Middle Eastern spices and herbs. Michelin recommended and one of Austin's most interesting new additions.",dishes:["Hummus","Pita","Grilled Lamb","Israeli Salads"],address:"1909 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 953-0117",lat:30.2533,lng:-97.7220,instagram:"ezovatx",website:"https://www.ezovatx.com"});

add({name:"Ling Kitchen",cuisine:"Chinese / Sichuan",neighborhood:"Northwest Austin",score:87,price:2,tags:["Chinese","Sichuan","Casual","Awards"],reservation:"walk-in",awards:"Michelin Recommended",description:"Michelin-recommended Sichuan restaurant in northwest Austin serving fiery, authentic Chinese cooking. The mapo tofu, dan dan noodles, and dry-fried green beans are the real deal. A rare Michelin nod for Chinese cooking in Austin.",dishes:["Mapo Tofu","Dan Dan Noodles","Dry-Fried Green Beans","Kung Pao Chicken"],address:"11101 Burnet Rd, Suite A105, Austin, TX 78758",phone:"(512) 520-4090",lat:30.3700,lng:-97.7389,instagram:"lingkitchenatx",website:"https://www.lingkitchenatx.com"});

add({name:"Mexta",cuisine:"Mexican / Texas",neighborhood:"East Austin",score:86,price:2,tags:["Mexican","Casual","Cocktails","Awards"],reservation:"walk-in",awards:"Michelin Recommended",description:"Michelin-recommended Mexican-Texan concept in East Austin blending Mexican culinary traditions with Texas ingredients. Creative tacos, elote, and cocktails in a colorful, casual setting. The Michelin nod confirms what locals already knew.",dishes:["Creative Tacos","Elote","Cocktails","Mexican Plates"],address:"2000 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 522-4055",lat:30.2533,lng:-97.7195,instagram:"mextaatx",website:"https://www.mextaatx.com"});

add({name:"Este Pizza",cuisine:"Neapolitan Pizza",neighborhood:"East Austin",score:86,price:1,tags:["Pizza","Casual","BYOB","Local Favorites","Awards"],reservation:"walk-in",awards:"Michelin Recommended",description:"Michelin-recommended Neapolitan pizza in East Austin. Wood-fired, blistered pies with quality mozzarella and seasonal toppings. BYOB and affordable — a rare combination of Michelin quality and neighborhood pricing. Multiple locations but East 6th is the original.",dishes:["Margherita","Seasonal Pizza","Salads","BYOB"],address:"1300 E 6th St, Austin, TX 78702",phone:"(512) 499-0553",lat:30.2631,lng:-97.7283,instagram:"estepizzaatx",website:"https://www.estepizzaatx.com"});

// === INDIAN ===
add({name:"G'Raj Mahal",cuisine:"Indian / Food Truck",neighborhood:"Rainey Street",score:85,price:1,tags:["Indian","Casual","Food Truck","Patio","Cheap Eats"],reservation:"walk-in",description:"Rainey Street Indian food truck serving curries, tikka masala, and naan in a covered patio setting. The lamb vindaloo and garlic naan are spicy and satisfying. BYOB-friendly and the Rainey Street location puts it in walking distance of the bar crawl. One of Austin's best food trucks.",dishes:["Tikka Masala","Lamb Vindaloo","Garlic Naan","Samosas"],address:"91 Red River St, Austin, TX 78701",phone:"(512) 480-2255",lat:30.2576,lng:-97.7406,instagram:"grajmahal",website:"https://www.grajmahalatx.com"});

add({name:"Bombay Express",cuisine:"Indian / Fast Casual",neighborhood:"North Austin",score:84,price:1,tags:["Indian","Casual","Cheap Eats","Family"],reservation:"walk-in",description:"North Austin Indian fast-casual serving generous thali plates, biryani, and curries at lunch-counter prices. The butter chicken and lamb curry are rich and well-spiced. Multiple locations with a loyal following among Austin's Indian food lovers.",dishes:["Thali Plates","Butter Chicken","Biryani","Naan"],address:"9025 Research Blvd, Suite 150, Austin, TX 78758",phone:"(512) 339-7222",lat:30.3700,lng:-97.7389,instagram:"bombayexpressatx",website:"https://www.bombayexpressonline.com"});

// === ETHIOPIAN ===
add({name:"Taste of Ethiopia",cuisine:"Ethiopian",neighborhood:"North Austin",score:85,price:1,tags:["Ethiopian","African","Vegetarian","Casual","Local Favorites"],reservation:"walk-in",description:"North Austin Ethiopian with traditional dishes served on injera bread. The doro wat, kitfo, and vegetarian combo are authentic and generous. Communal eating with hands — tearing injera and scooping stews — makes every meal an experience. One of Austin's few Ethiopian restaurants.",dishes:["Doro Wat","Kitfo","Vegetarian Combo","Injera"],address:"1100 Grand Avenue Pkwy, Suite 108, Pflugerville, TX 78660",phone:"(512) 251-4053",lat:30.4390,lng:-97.6730,instagram:"tasteofethiopiaatx",website:"https://www.tasteofethiopiaaustin.com",suburb:true});

// === MORE BARS & WINE ===
add({name:"Drink.Well",cuisine:"Cocktail Bar / Gastropub",neighborhood:"North Loop",score:87,price:2,tags:["Cocktails","Gastropub","Date Night","Local Favorites"],reservation:"walk-in",description:"North Loop cocktail bar and gastropub with a creative drinks menu and elevated bar food. The Scotch egg and seasonal cocktails are signatures. The intimate space draws a well-dressed North Loop crowd. One of Austin's most consistently great bar programs.",dishes:["Scotch Egg","Craft Cocktails","Seasonal Menu","Bar Snacks"],address:"207 E 53rd St, Austin, TX 78751",phone:"(512) 614-6683",lat:30.3175,lng:-97.7270,instagram:"drinkwell",website:"https://www.drinkwellaustin.com"});

add({name:"The Driskill Bar",cuisine:"Hotel Bar / Cocktails",neighborhood:"Downtown",score:87,price:3,tags:["Cocktails","Hotel","Classic","Date Night","Historic"],reservation:"walk-in",awards:"Austin landmark since 1886",description:"The bar inside Austin's most historic hotel — The Driskill, open since 1886. The original cattle baron opulence remains with stained glass, marble, and mahogany. Whiskey, cocktails, and live music in a space where presidents and outlaws have drunk. The most atmospheric bar in Austin.",dishes:["Whiskey","Classic Cocktails","Live Music","Hotel Atmosphere"],address:"604 Brazos St, Austin, TX 78701",phone:"(512) 439-1234",lat:30.2672,lng:-97.7418,instagram:"thedriskill",website:"https://www.driskillhotel.com"});

add({name:"Vixen's Wedding",cuisine:"Natural Wine Bar",neighborhood:"East Austin",score:86,price:2,tags:["Wine Bar","Date Night","Patio","Local Favorites"],reservation:"walk-in",description:"East Austin natural wine bar with a sprawling patio and eclectic, globally-sourced wine list. Tinned fish, cheese boards, and small plates complement the wines. The outdoor space under string lights is peak East Austin ambiance. A wine-forward alternative to the cocktail bar scene.",dishes:["Natural Wine","Tinned Fish","Cheese Boards","Small Plates"],address:"1813 E 6th St, Austin, TX 78702",phone:"(512) 814-0361",lat:30.2621,lng:-97.7240,instagram:"vixenswedding",website:"https://www.vixenswedding.com"});

// === CASUAL / NEIGHBORHOOD ===
add({name:"Cisco's Restaurant Bakery & Bar",cuisine:"Tex-Mex / Bakery",neighborhood:"East Austin",score:85,price:1,tags:["Tex-Mex","Breakfast","Classic","Local Favorites"],reservation:"walk-in",awards:"Austin institution since 1950",description:"East Austin Tex-Mex institution since 1950 where politicians, musicians, and workers share tables over migas and huevos rancheros. The neon sign and retro diner vibe are quintessential old Austin. LBJ used to eat here. A living piece of East Austin history.",dishes:["Migas","Huevos Rancheros","Enchiladas","Breakfast Tacos"],address:"1511 E 6th St, Austin, TX 78702",phone:"(512) 478-2420",lat:30.2626,lng:-97.7260,instagram:"ciscosrestaurant",website:""});

add({name:"Loro South Lamar",cuisine:"Asian BBQ",neighborhood:"South Lamar",score:90,price:2,tags:["Asian Fusion","BBQ","Casual","Cocktails","Patio","Awards"],reservation:"walk-in",awards:"Michelin Recommended",group:"Hai Hospitality",description:"Already in data as Loro.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Wink",cuisine:"New American Fine Dining",neighborhood:"West Austin",score:89,price:3,tags:["Fine Dining","Date Night","Celebrations","Wine Bar","Awards"],reservation:"OpenTable",awards:"Austin institution",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Cenote",cuisine:"Coffee / Cafe",neighborhood:"East Austin",score:85,price:1,tags:["Coffee","Casual","Patio","Local Favorites"],reservation:"walk-in",description:"East Cesar Chavez coffee shop in a converted house with a massive shaded patio. Craft coffee, pastries, and light bites in a peaceful garden setting. The morning coffee ritual here is a very East Austin experience. Free WiFi and plenty of shade.",dishes:["Specialty Coffee","Pastries","Light Bites","Patio"],address:"1010 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 382-0204",lat:30.2533,lng:-97.7303,instagram:"cenoteatx",website:"https://www.cenoteaustin.com"});

add({name:"Jo's Coffee",cuisine:"Coffee / Hot Dogs",neighborhood:"South Congress",score:84,price:1,tags:["Coffee","Casual","Iconic","Local Favorites","Photo Op"],reservation:"walk-in",description:"The coffee shop with the famous 'I love you so much' mural on the South Congress side wall. Jo's serves solid coffee, iced turbo (espresso + coffee), and hot dogs on the SoCo patio. More of a cultural landmark than a coffee destination, but the drinks are good and the people-watching is world-class.",dishes:["Iced Turbo","Coffee","Hot Dogs","I Love You So Much Mural"],address:"1300 S Congress Ave, Austin, TX 78704",phone:"(512) 444-3800",lat:30.2492,lng:-97.7493,instagram:"joscoffeesocongress",website:"https://www.joscoffee.com"});

add({name:"Ramen Tatsu-Ya South Lamar",cuisine:"Japanese Ramen",neighborhood:"South Lamar",score:88,price:2,tags:["Japanese","Ramen","Casual","Late Night","Local Favorites"],reservation:"walk-in",group:"Tatsu-Ya",description:"Second Austin location of the cult ramen chain on South Lamar. Same 18-hour tonkotsu broth, punk rock decor, and devoted lines. The vegan ramen is surprisingly excellent.",dishes:["Tonkotsu Ramen","Miso Ramen","Vegan Ramen","Gyoza"],address:"1234 S Lamar Blvd, Austin, TX 78704",phone:"(512) 814-0361",lat:30.2517,lng:-97.7681,instagram:"raboratx",website:"https://www.ramen-tatsuya.com",group:"Tatsu-Ya"});

add({name:"La Pâtisserie",cuisine:"French Bakery",neighborhood:"South Lamar",score:86,price:1,tags:["Bakery","French","Breakfast","Coffee","Local Favorites"],reservation:"walk-in",description:"French bakery on South Lamar with croissants, macarons, and tarts that rival any in Austin. The morning pastries sell out fast and the savory quiches make an excellent lunch. French-trained bakers bring genuine technique to every item.",dishes:["Croissants","Macarons","Quiche","French Tarts"],address:"1404 S Congress Ave, Austin, TX 78704",phone:"(512) 912-9100",lat:30.2496,lng:-97.7493,instagram:"lapatisserieatx",website:"https://www.lapatisserieatx.com"});

add({name:"Uchi Austin",cuisine:"Japanese / Sushi",neighborhood:"South Lamar",score:97,price:4,tags:["Japanese","Sushi","Fine Dining","Date Night","Awards"],reservation:"Resy",awards:"James Beard Award Winner (Tyson Cole)",group:"Hai Hospitality",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Salty Sow",cuisine:"American / Gastropub",neighborhood:"East Austin",score:87,price:2,tags:["American","Gastropub","Brunch","Patio","Date Night"],reservation:"OpenTable",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

// === SUBURBAN ===
add({name:"Torchy's Tacos Original",cuisine:"Creative Tacos",neighborhood:"South Austin",score:84,price:1,tags:["Tacos","Casual","Local Favorites"],reservation:"walk-in",description:"Already in data as Torchy's Tacos.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Oasis on the Lake",cuisine:"Tex-Mex / Views",neighborhood:"Lake Travis",score:80,price:2,tags:["Tex-Mex","Views","Patio","Sunset","Tourist Attraction"],reservation:"walk-in",suburb:true,description:"The 'Sunset Capital of Texas' — a massive multi-level restaurant complex perched on a cliff overlooking Lake Travis. The food is secondary to the sunset views, which are genuinely spectacular. A tourist destination and Instagram favorite. Come for sunset drinks, not for the food.",dishes:["Sunset Views","Margaritas","Tex-Mex","Lake Travis Views"],address:"6550 Comanche Trail, Austin, TX 78732",phone:"(512) 266-2442",lat:30.3930,lng:-97.8580,instagram:"oasisonthelake",website:"https://www.oasis-austin.com"});

add({name:"Black's Barbecue",cuisine:"Texas BBQ",neighborhood:"Lockhart",score:89,price:1,tags:["BBQ","Classic","Local Favorites","Historic"],reservation:"walk-in",awards:"Texas Monthly Top 50 BBQ, since 1932",suburb:true,description:"The oldest BBQ joint in Texas continuously owned by the same family — since 1932 in Lockhart, the BBQ Capital of Texas. Sausage rings, brisket, and ribs prepared the old-fashioned way on brick pits. Worth the 30-minute drive from Austin for BBQ history and flavor.",dishes:["Sausage Ring","Brisket","Pork Ribs","Pecan Pie"],address:"215 N Main St, Lockhart, TX 78644",phone:"(512) 398-2712",lat:29.8850,lng:-97.6700,instagram:"blacksbbq",website:"https://www.blacksbbq.com"});

add({name:"Kreuz Market",cuisine:"Texas BBQ",neighborhood:"Lockhart",score:90,price:1,tags:["BBQ","Classic","Historic","Local Favorites"],reservation:"walk-in",awards:"Texas Monthly Top 50 BBQ, since 1900",suburb:true,description:"Lockhart BBQ cathedral since 1900 — no forks, no sauce, no sides (well, some now). Shoulder clod, prime rib, sausage, and pork chops smoked over post oak in massive brick pits. This is where Texas BBQ tradition began. No sauce needed — the smoke does the work.",dishes:["Shoulder Clod","Prime Rib","Sausage","Pork Chops"],address:"619 N Colorado St, Lockhart, TX 78644",phone:"(512) 398-2361",lat:29.8860,lng:-97.6670,instagram:"kreuzmarket",website:"https://www.kreuzmarket.com"});

add({name:"Smitty's Market",cuisine:"Texas BBQ",neighborhood:"Lockhart",score:89,price:1,tags:["BBQ","Classic","Historic","Local Favorites"],reservation:"walk-in",awards:"Texas Monthly Top 50 BBQ",suburb:true,description:"Lockhart BBQ royalty in the original Kreuz Market building — the family split in the 1990s and Smitty's kept the original pits. Walk through the fire pit entrance, order by the pound, and eat on butcher paper. No sauce, no forks. BBQ pilgrimage essential.",dishes:["Brisket","Sausage","Pork Ribs","Shoulder Clod"],address:"208 S Commerce St, Lockhart, TX 78644",phone:"(512) 398-9344",lat:29.8830,lng:-97.6700,instagram:"smittysmarket",website:"https://www.smittysmarket.com"});

// Write back
html = html.slice(0, a) + JSON.stringify(arr) + html.slice(e);
fs.writeFileSync(file, html, 'utf8');
console.log('Austin: ' + arr.length + ' spots (added ' + added + ')');
console.log('Need', 250 - arr.length, 'more to hit 250');
