// Austin → 400
const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');
const m = 'const AUSTIN_DATA=';
const p = html.indexOf(m);
const arrS = html.indexOf('[', p);
let d=0, arrE=arrS;
for(let j=arrS;j<html.length;j++){if(html[j]==='[')d++;if(html[j]===']'){d--;if(d===0){arrE=j+1;break;}}}
let arr = JSON.parse(html.substring(arrS, arrE));
console.log('Starting Austin:', arr.length);
const maxId = Math.max(...arr.map(r=>r.id));
let nextId = maxId + 1;
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let added = 0;
function add(s){
  if(existing.has(s.name.toLowerCase())){return;}
  s.id=nextId++;s.bestOf=[];s.busyness=null;s.waitTime=null;s.popularTimes=null;s.lastUpdated=null;s.trending=s.trending||false;s.group=s.group||'';s.suburb=s.suburb||false;s.menuUrl='';s.res_tier=s.price>=3?4:2;s.indicators=s.indicators||[];s.awards=s.awards||'';s.phone=s.phone||'';s.reserveUrl=s.reserveUrl||'';s.hh=s.hh||'';s.verified=true;
  arr.push(s);existing.add(s.name.toLowerCase());added++;
}

// More Austin spots sourced from Resy, CultureMap, Infatuation, Eater, Austin Chronicle
add({name:"Pecan Square Cafe",cuisine:"American / Brunch",neighborhood:"Clarksville",score:86,price:2,tags:["New American","Brunch","Date Night","Local Favorites"],description:"Neighborhood restaurant in the heart of Clarksville with a simple, seasonal menu serving lunch, dinner, and weekend brunch. Relaxed but sophisticated service.",dishes:["Seasonal Menu","Weekend Brunch","Small Plates"],address:"1209 Parkway, Austin, TX 78703",hours:"",lat:30.2776,lng:-97.7569,instagram:"pecansquarecafe",website:"",reservation:"Resy",phone:""});

add({name:"Little Swedish",cuisine:"Swedish Bakery / Cafe",neighborhood:"Clarksville",score:85,price:1,tags:["Bakery/Coffee","Brunch","Local Favorites"],description:"MML Hospitality bakery and cafe in Clarksville with Swedish classics. Freshly baked croissants, bagels, breads, and pastries alongside coffee and light meals.",dishes:["Swedish Pastries","Croissants","Coffee"],address:"1511 W 6th St, Austin, TX 78703",hours:"",lat:30.2717,lng:-97.7575,instagram:"littleswedish",website:"",reservation:"walk-in",phone:""});

add({name:"Lou's Barton Springs",cuisine:"American / Casual",neighborhood:"Zilker",score:85,price:1,tags:["Casual","Local Favorites","Patio"],description:"Laid-back pit stop near Zilker Park. Donuts and coffee in the morning, burgers and fries in the evening. Perfect before or after Barton Springs.",dishes:["Donuts","Burgers","Coffee"],address:"2600 Barton Springs Rd, Austin, TX 78704",hours:"",lat:30.2609,lng:-97.7614,instagram:"lousbartonsprings",website:"",reservation:"walk-in",phone:""});

add({name:"Qi Austin",cuisine:"Chinese / Asian Fusion",neighborhood:"Downtown",score:87,price:2,tags:["Chinese","Asian Fusion","Date Night","Rooftop"],description:"Modern Chinese restaurant downtown with a rooftop bar and dim sum. The views of downtown Austin from the rooftop are stunning and the dim sum program is solid.",dishes:["Dim Sum","Peking Duck","Rooftop Cocktails"],address:"300 Colorado St, Austin, TX 78701",hours:"",lat:30.2651,lng:-97.7446,instagram:"qiaustin",website:"",reservation:"Resy",phone:""});

add({name:"1618 Asian Fusion",cuisine:"Asian Fusion",neighborhood:"East Austin",score:86,price:2,tags:["Asian Fusion","Date Night","Local Favorites"],description:"Asian fusion in East Austin blending flavors from across the continent. Creative cocktails and a moody atmosphere make this a solid date night pick.",dishes:["Asian Fusion Plates","Craft Cocktails","Shareable Dishes"],address:"1618 E 6th St, Austin, TX 78702",hours:"",lat:30.2629,lng:-97.7270,instagram:"1618asianfusion",website:"",reservation:"Resy",phone:""});

add({name:"Fig Italian Kitchen & Bar",cuisine:"Italian",neighborhood:"South Congress",score:86,price:2,tags:["Italian","Date Night","Patio","Local Favorites"],description:"Italian restaurant on South Congress with handmade pasta and a lovely patio. Solid Italian classics in a prime SoCo location.",dishes:["Handmade Pasta","Italian Wine","SoCo Patio"],address:"1209 S Congress Ave, Austin, TX 78704",hours:"",lat:30.2481,lng:-97.7498,instagram:"figitaliankitchen",website:"",reservation:"OpenTable",phone:""});

add({name:"Ember Kitchen",cuisine:"New American / Wood-Fired",neighborhood:"East Austin",score:87,price:2,tags:["New American","Date Night","Local Favorites"],description:"Wood-fired cooking in East Austin with seasonal New American dishes. The ember-roasted vegetables and proteins showcase what fire can do to food.",dishes:["Ember-Roasted Dishes","Wood-Fired Menu","Seasonal Plates"],address:"2012 E 6th St, Austin, TX 78702",hours:"",lat:30.2629,lng:-97.7218,instagram:"emberkitchenatx",website:"",reservation:"Resy",phone:""});

add({name:"Anthem",cuisine:"Asian Fusion / Cocktails",neighborhood:"East Austin",score:86,price:2,tags:["Asian Fusion","Cocktails","Date Night","Local Favorites"],description:"Asian-inspired cocktails and small plates in East Austin. The cocktail program is strong and the vibe is fun and energetic.",dishes:["Asian Cocktails","Small Plates","Late Night"],address:"1305 E 7th St, Austin, TX 78702",hours:"",lat:30.2642,lng:-97.7300,instagram:"anthematx",website:"",reservation:"walk-in",phone:""});

add({name:"Loro Domain",cuisine:"Asian-BBQ Fusion",neighborhood:"Domain",score:87,price:2,tags:["BBQ","Asian Fusion","Casual","Patio"],description:"Domain location of the Franklin-Uchi collaboration. Same great concept in a north Austin mixed-use development setting.",dishes:["Smoked Brisket","Asian Sides","Patio"],address:"11601 Domain Dr, Austin, TX 78758",hours:"",lat:30.4016,lng:-97.7244,instagram:"loroaustin",website:"",reservation:"walk-in",phone:"",group:"Franklin/Uchi"});

add({name:"Shady Grove",cuisine:"American / Tex-Mex",neighborhood:"Barton Springs",score:85,price:1,tags:["American","Tex-Mex","Casual","Iconic","Patio"],description:"Iconic Austin restaurant on Barton Springs Road with a massive tree-covered patio. Burgers, Tex-Mex, and live music make this a perfect Austin afternoon.",dishes:["Hippie Sandwich","Burgers","Patio Music"],address:"1624 Barton Springs Rd, Austin, TX 78704",hours:"",lat:30.2609,lng:-97.7554,instagram:"shadygroveatx",website:"",reservation:"walk-in",phone:""});

add({name:"Vespaio",cuisine:"Italian",neighborhood:"South Congress",score:88,price:3,tags:["Italian","Fine Dining","Date Night","Local Favorites"],description:"Upscale Italian on South Congress with handmade pasta and an extensive Italian wine list. One of Austin most established fine dining Italian restaurants.",dishes:["Handmade Pasta","Italian Wine","Fine Italian Dining"],address:"1610 S Congress Ave, Austin, TX 78704",hours:"",lat:30.2443,lng:-97.7496,instagram:"vespaioaustin",website:"",reservation:"OpenTable",phone:""});

add({name:"Enoteca Vespaio",cuisine:"Italian Casual",neighborhood:"South Congress",score:86,price:2,tags:["Italian","Casual","Wine Bar","Local Favorites"],description:"Casual sibling next door to Vespaio with pizza, panini, and wine by the glass. More affordable Italian on SoCo with the same quality pedigree.",dishes:["Pizza","Panini","Wine by Glass"],address:"1610 S Congress Ave, Austin, TX 78704",hours:"",lat:30.2443,lng:-97.7496,instagram:"vespaioaustin",website:"",reservation:"walk-in",phone:"",group:"Vespaio"});

add({name:"Uchi ko North",cuisine:"Japanese",neighborhood:"North Austin",score:89,price:3,tags:["Japanese","Sushi","Fine Dining","Date Night"],description:"North Austin outpost of Tyson Cole Uchiko concept. Same creative Japanese cuisine in a north side setting.",dishes:["Omakase","Creative Sushi","Japanese Plates"],address:"4200 N Lamar Blvd, Austin, TX 78756",hours:"",lat:30.3145,lng:-97.7408,instagram:"uchiko_austin",website:"",reservation:"Resy",phone:""});

add({name:"Chicon",cuisine:"Tex-Mex / American",neighborhood:"East Austin",score:86,price:2,tags:["Tex-Mex","New American","Brunch","Local Favorites"],description:"East Austin restaurant with a great patio serving Tex-Mex influenced American cuisine. Brunch is popular and the margaritas are strong.",dishes:["Tex-Mex Brunch","Margaritas","Seasonal Plates"],address:"1316 E 6th St, Austin, TX 78702",hours:"",lat:30.2629,lng:-97.7298,instagram:"chiconatx",website:"",reservation:"walk-in",phone:""});

add({name:"Grizzelda's",cuisine:"Tex-Mex",neighborhood:"Rainey Street",score:85,price:1,tags:["Mexican","Tex-Mex","Casual","Local Favorites","Patio"],description:"Hot pink Tex-Mex restaurant on Rainey Street with an extensive margarita list, queso fundido, and fish tacos. Fun, colorful, and festive.",dishes:["Queso Fundido","Fish Tacos","Frozen Margaritas"],address:"69 Rainey St, Austin, TX 78701",hours:"",lat:30.2586,lng:-97.7392,instagram:"grizzeldasatx",website:"",reservation:"walk-in",phone:""});

add({name:"Cockta'l",cuisine:"Fried Chicken",neighborhood:"East Austin",score:86,price:1,tags:["Fried Chicken","Casual","Local Favorites"],description:"Juicy fried chicken from an East MLK truck with a small menu of nuggets, sandwiches, and bone-in pieces. Simple and perfectly executed.",dishes:["Fried Chicken Sandwich","Nuggets","Bone-In Chicken"],address:"1814 E MLK Jr Blvd, Austin, TX 78702",hours:"",lat:30.2785,lng:-97.7242,instagram:"cocktilatx",website:"",reservation:"walk-in",phone:""});

add({name:"El Alma",cuisine:"Mexican",neighborhood:"South Lamar",score:87,price:2,tags:["Mexican","Rooftop","Date Night","Local Favorites"],description:"Interior Mexican with a rooftop patio offering views of downtown Austin. Creative moles and mezcal cocktails in an upscale setting.",dishes:["Mole Dishes","Mezcal Cocktails","Rooftop Dining"],address:"1025 Barton Springs Rd, Austin, TX 78704",hours:"",lat:30.2610,lng:-97.7557,instagram:"elalmaaustin",website:"",reservation:"Resy",phone:""});

add({name:"Jack Allen's Kitchen",cuisine:"Texan / Southern",neighborhood:"Multiple Locations",score:86,price:2,tags:["Texan","Southern","Brunch","Family","Local Favorites"],description:"Texas comfort food with multiple Austin-area locations. Chef Jack Allen serves ranch-raised meats and locally sourced ingredients. Great brunch and family-friendly.",dishes:["Chicken Fried Steak","Texas Brunch","Pecan Pie"],address:"3600 N Lamar Blvd, Austin, TX 78756",hours:"",lat:30.3066,lng:-97.7428,instagram:"jackallenskitchen",website:"",reservation:"walk-in",phone:""});

add({name:"El Chile",cuisine:"Mexican",neighborhood:"East Austin",score:86,price:1,tags:["Mexican","Local Favorites","Casual","Patio"],description:"East Austin Mexican with strong margaritas and authentic dishes. The enchiladas are excellent and the patio is a neighborhood gathering spot.",dishes:["Enchiladas","Margaritas","Mexican Plates"],address:"1809 Manor Rd, Austin, TX 78722",hours:"",lat:30.2809,lng:-97.7229,instagram:"elchilecafe",website:"",reservation:"walk-in",phone:""});

add({name:"Loro West Lake",cuisine:"Asian-BBQ Fusion",neighborhood:"West Lake Hills",score:87,price:2,tags:["BBQ","Asian Fusion","Casual","Patio"],description:"West Lake Hills location of the Franklin-Uchi collaboration. Family-friendly suburban setting with the same great smoked meats and Asian flavors.",dishes:["Smoked Brisket","Asian Sides","Hill Country Views"],address:"2015 S Capital of Texas Hwy, Austin, TX 78746",hours:"",lat:30.2730,lng:-97.7963,instagram:"loroaustin",website:"",reservation:"walk-in",phone:"",suburb:true,group:"Franklin/Uchi"});

add({name:"Aba Domain",cuisine:"Mediterranean",neighborhood:"Domain",score:87,price:2,tags:["Mediterranean","Date Night","Patio","Local Favorites"],description:"Domain location of the Mediterranean restaurant. Same great hummus, shakshuka, and mezze in a north Austin mixed-use setting.",dishes:["Whipped Feta","Mediterranean Plates","Patio"],address:"3200 Palm Way, Austin, TX 78758",hours:"",lat:30.3979,lng:-97.7255,instagram:"abarestaurants",website:"",reservation:"Resy",phone:""});

add({name:"Ranch 616",cuisine:"South Texas / Mexican",neighborhood:"Downtown",score:86,price:2,tags:["Mexican","Texan","Cocktails","Local Favorites"],description:"South Texas-inspired restaurant downtown with creative Mexican and Texan dishes. The jalapeño quail and tequila cocktails stand out. Fun, festive atmosphere.",dishes:["Jalapeño Quail","Tequila Cocktails","South Texas Plates"],address:"616 Nueces St, Austin, TX 78701",hours:"",lat:30.2697,lng:-97.7493,instagram:"ranch616",website:"",reservation:"walk-in",phone:""});

add({name:"Walton's Fancy and Staple",cuisine:"Bakery / Deli / Flower Shop",neighborhood:"West Austin",score:85,price:1,tags:["Bakery/Coffee","Brunch","Local Favorites"],description:"Part bakery, part deli, part flower shop in West Austin. Unique concept with excellent pastries, sandwiches, and fresh flowers. Perfect for a weekend morning.",dishes:["Pastries","Deli Sandwiches","Fresh Flowers"],address:"609 W 6th St, Austin, TX 78701",hours:"",lat:30.2700,lng:-97.7476,instagram:"waltonsfancyandstaple",website:"",reservation:"walk-in",phone:""});

add({name:"Loro Westlake",cuisine:"Asian-BBQ Fusion",neighborhood:"Westlake",score:87,price:2,tags:["BBQ","Asian Fusion","Casual","Patio"],description:"Westlake location of the Franklin-Uchi collaboration. Suburban Hill Country setting.",dishes:["Smoked Meats","Asian Sides","Patio"],address:"3801 Bee Cave Rd, West Lake Hills, TX 78746",hours:"",lat:30.2887,lng:-97.8204,instagram:"loroaustin",website:"",reservation:"walk-in",phone:"",suburb:true,group:"Franklin/Uchi"});

add({name:"Lenoir Hot Weather Food",cuisine:"New American",neighborhood:"Bouldin Creek",score:89,price:3,tags:["Fine Dining","Date Night","Local Favorites"],description:"Tasting menu in a charming Bouldin Creek house. Self-described hot weather food with seasonal ingredients and a wine-focused program. One of Austin most intimate dining experiences.",dishes:["Tasting Menu","Wine Pairing","Seasonal Dishes"],address:"1807 S 1st St, Austin, TX 78704",hours:"",lat:30.2480,lng:-97.7555,instagram:"lenoiratx",website:"",reservation:"Resy",phone:""});

add({name:"East Side King",cuisine:"Thai-Japanese Fusion",neighborhood:"Multiple Locations",score:86,price:1,tags:["Thai","Japanese","Casual","Local Favorites"],description:"Thai-Japanese food truck concept from Top Chef alum Paul Qui. Multiple locations across Austin. The beet home fries and Thai chicken karaage are favorites.",dishes:["Thai Chicken Karaage","Beet Home Fries","Fusion Bites"],address:"1618 E 6th St, Austin, TX 78702",hours:"",lat:30.2629,lng:-97.7270,instagram:"eastsidekingatx",website:"",reservation:"walk-in",phone:""});

add({name:"Haymaker",cuisine:"American / Bar",neighborhood:"East Austin",score:85,price:1,tags:["Casual","Patio","Local Favorites"],description:"East Austin bar with a huge dog-friendly patio, craft beer, and bar food. Pool tables, yard games, and a laid-back vibe. Perfect Sunday afternoon spot.",dishes:["Bar Food","Craft Beer","Yard Games"],address:"2310 Manor Rd, Austin, TX 78722",hours:"",lat:30.2822,lng:-97.7175,instagram:"haymakeraustin",website:"",reservation:"walk-in",phone:""});

add({name:"Hank's Austin",cuisine:"American / Burgers",neighborhood:"East Austin",score:86,price:1,tags:["Burgers","Late Night","Casual","Local Favorites"],description:"Late-night burger joint in East Austin with quality smash burgers and a drive-through window. Open late when you need a good burger at 2am.",dishes:["Smash Burgers","Late Night","Drive-Through"],address:"5811 Berkman Dr, Austin, TX 78723",hours:"",lat:30.3120,lng:-97.7030,instagram:"hanksaustin",website:"",reservation:"walk-in",phone:""});

add({name:"Fonda San Miguel Brunch",cuisine:"Mexican Fine Dining",neighborhood:"North Central",score:89,price:3,tags:["Mexican","Brunch","Fine Dining","Iconic","Celebrations"],description:"The legendary Sunday brunch buffet at Fonda San Miguel with interior Mexican dishes, fresh ceviche, and made-to-order omelets in a beautiful hacienda setting. An Austin tradition since 1975.",dishes:["Sunday Brunch Buffet","Interior Mexican","Made-to-Order Omelets"],address:"2330 W North Loop Blvd, Austin, TX 78756",hours:"",lat:30.3190,lng:-97.7451,instagram:"fondasanmiguel",website:"",reservation:"OpenTable",phone:"",group:"Fonda San Miguel"});

add({name:"Olamaie Biscuit Bar",cuisine:"Southern / Bakery",neighborhood:"Downtown",score:86,price:1,tags:["Southern","Bakery/Coffee","Brunch"],description:"Casual biscuit bar from the Michelin-recognized Olamaie team. Buttermilk biscuits with creative toppings and fillings. Quick, affordable Southern comfort from a fine dining pedigree.",dishes:["Buttermilk Biscuits","Biscuit Sandwiches","Coffee"],address:"1703 S 1st St, Austin, TX 78704",hours:"",lat:30.2468,lng:-97.7557,instagram:"olamaie",website:"",reservation:"walk-in",phone:"",group:"Olamaie"});

add({name:"Ramen Tatsu-ya South Lamar",cuisine:"Japanese Ramen",neighborhood:"South Lamar",score:88,price:1,tags:["Japanese","Ramen","Local Favorites"],description:"South Lamar location of Austin legendary ramen shop. Same incredible tonkotsu broth and housemade noodles in a south Austin setting.",dishes:["Tonkotsu Ramen","Spicy Miso","Tsukemen"],address:"1234 S Lamar Blvd, Austin, TX 78704",hours:"",lat:30.2510,lng:-97.7673,instagram:"raboratory",website:"",reservation:"walk-in",phone:"",group:"Ramen Tatsu-ya"});

add({name:"True Food Kitchen",cuisine:"Health-Focused American",neighborhood:"Domain",score:85,price:2,tags:["Healthy","Casual","Family"],description:"Health-focused restaurant in the Domain with seasonal menus inspired by anti-inflammatory eating. Salads, bowls, and grain dishes alongside craft cocktails.",dishes:["Seasonal Bowls","Healthy Plates","Craft Cocktails"],address:"11410 Century Oaks Terrace, Austin, TX 78758",hours:"",lat:30.4010,lng:-97.7246,instagram:"truefoodkitchen",website:"",reservation:"OpenTable",phone:""});

add({name:"Loro Lakeway",cuisine:"Asian-BBQ Fusion",neighborhood:"Lakeway",score:87,price:2,tags:["BBQ","Asian Fusion","Casual","Patio"],description:"Lakeway location of the Franklin-Uchi collaboration. Lake Travis area setting.",dishes:["Smoked Meats","Asian Sides","Patio"],address:"1905 Ranch Rd 620 S, Lakeway, TX 78734",hours:"",lat:30.3520,lng:-97.9560,instagram:"loroaustin",website:"",reservation:"walk-in",phone:"",suburb:true,group:"Franklin/Uchi"});

add({name:"Colleen's Kitchen",cuisine:"Southern / Brunch",neighborhood:"East Austin",score:86,price:1,tags:["Southern","Brunch","Local Favorites","Casual"],description:"East Austin Southern-inspired kitchen with great brunch options and comfort food. The chicken biscuit is a morning favorite.",dishes:["Chicken Biscuit","Southern Brunch","Comfort Food"],address:"2005 Manor Rd, Austin, TX 78722",hours:"",lat:30.2809,lng:-97.7212,instagram:"colleenskitchenatx",website:"",reservation:"walk-in",phone:""});

add({name:"Loro 35th Street",cuisine:"Asian-BBQ Fusion",neighborhood:"Central Austin",score:87,price:2,tags:["BBQ","Asian Fusion","Casual","Patio"],description:"Central Austin location of the Franklin-Uchi collaboration near 35th and Guadalupe.",dishes:["Smoked Meats","Asian Sides","Patio"],address:"2000 E Cesar Chavez St, Austin, TX 78702",hours:"",lat:30.2555,lng:-97.7233,instagram:"loroaustin",website:"",reservation:"walk-in",phone:"",group:"Franklin/Uchi"});

console.log('Added', added, 'new Austin spots. Total:', arr.length);
html = html.substring(0, arrS) + JSON.stringify(arr) + html.substring(arrE);
fs.writeFileSync('index.html', html, 'utf8');
console.log('Austin to 400 complete!');
