// Austin Batch 7: Final push toward 250 — more neighborhoods, Rainey, Domain, wine, late night
// Run: node scripts/austin-batch-7.js

const fs = require('fs');
const file = require('path').join(__dirname, '..', 'index.html');
let html = fs.readFileSync(file, 'utf8');
const s = html.indexOf('const AUSTIN_DATA');
const a = html.indexOf('[', s);
let d=0,e=a;
for(let i=a;i<html.length;i++){if(html[i]==='[')d++;if(html[i]===']')d--;if(d===0){e=i+1;break;}}
const arr = JSON.parse(html.slice(a, e));
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let nextId = Math.max(...arr.map(r=>r.id||0))+1, added = 0;

function add(s) {
  if(existing.has(s.name.toLowerCase()))return;
  arr.push({id:nextId++,name:s.name,phone:s.phone||'',cuisine:s.cuisine,neighborhood:s.neighborhood,score:s.score,price:s.price,tags:s.tags,indicators:s.indicators||[],hh:'',reservation:s.reservation||'walk-in',awards:s.awards||'',description:s.description,dishes:s.dishes,address:s.address,hours:'',lat:s.lat,lng:s.lng,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:s.trending||false,group:s.group||'',instagram:s.instagram||'',website:s.website||'',suburb:s.suburb||false,reserveUrl:'',menuUrl:'',res_tier:s.res_tier||2});
  existing.add(s.name.toLowerCase());added++;
}

// === RAINEY STREET ===
add({name:"Banger's Sausage House & Beer Garden",cuisine:"Beer Garden / Sausages",neighborhood:"Rainey Street",score:85,price:1,tags:["Beer Garden","Craft Beer","Sausages","Patio","Live Music","Family"],description:"Already in data as Bangers.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Lucille Patio Lounge",cuisine:"Cocktail Bar / Patio",neighborhood:"Rainey Street",score:84,price:2,tags:["Cocktails","Patio","Late Night","Date Night"],description:"Rainey Street patio bar in a converted bungalow with craft cocktails, string lights, and a laid-back vibe. The frozen cocktails are summer essential and the covered patio keeps things comfortable year-round. A Rainey crawl staple.",dishes:["Frozen Cocktails","Craft Drinks","Patio"],address:"77 Rainey St, Austin, TX 78701",phone:"(512) 472-0222",lat:30.2576,lng:-97.7406,instagram:"lucilleaustin",website:"https://www.lucillerainey.com"});

add({name:"Container Bar",cuisine:"Bar / Nightlife",neighborhood:"Rainey Street",score:84,price:1,tags:["Bar","Nightlife","Patio","Late Night","Iconic"],description:"Multi-level bar built from stacked shipping containers on Rainey Street. Three floors of bars, a rooftop, and a massive outdoor space. The container architecture is peak Austin creative reuse. Open late with DJs on weekends.",dishes:["Cocktails","Beer","DJ Sets"],address:"90 Rainey St, Austin, TX 78701",phone:"(512) 320-0385",lat:30.2576,lng:-97.7406,instagram:"containerbar",website:"https://www.containerbar.com"});

// === WINE ===
add({name:"Aviary Wine & Kitchen",cuisine:"Wine Bar / American",neighborhood:"South Congress",score:87,price:2,tags:["Wine Bar","Date Night","Patio","Cocktails","Local Favorites"],reservation:"Resy",description:"SoCo wine bar and kitchen with a wine-by-the-glass program that spans the globe. Seasonal small plates and shareable boards complement the wines. The patio is one of South Congress's most intimate. A wine-forward alternative to the cocktail bar scene.",dishes:["Wine Flights","Charcuterie","Seasonal Plates","Patio"],address:"1500 S Congress Ave, Suite A, Austin, TX 78704",phone:"(512) 916-4445",lat:30.2460,lng:-97.7496,instagram:"aviarywinekitchen",website:"https://www.aviarywinekitchen.com"});

add({name:"Infinite Monkey Theorem",cuisine:"Urban Winery / Bar",neighborhood:"East Austin",score:84,price:2,tags:["Wine Bar","Casual","Patio","Local Favorites"],reservation:"walk-in",description:"Urban winery in East Austin that cans its wines — a very Austin approach to winemaking. The taproom pours house-made wines alongside ciders and cocktails on a shaded patio. Wine in cans shouldn't work this well, but it does. A uniquely Austin wine experience.",dishes:["Canned Wine","Wine on Tap","Patio","Light Bites"],address:"4200 Airport Blvd, Suite A, Austin, TX 78722",phone:"(737) 205-5953",lat:30.2973,lng:-97.7120,instagram:"infinitemonkeyaustin",website:"https://www.theinfinitemonkeytheorem.com"});

// === MORE RESTAURANTS ===
add({name:"Lamberts Downtown Barbecue",cuisine:"Upscale BBQ / Southern",neighborhood:"2nd Street",score:87,price:2,tags:["BBQ","Southern","Live Music","Date Night","Cocktails"],reservation:"OpenTable",description:"Upscale BBQ on 2nd Street with live music and craft cocktails. The mesquite-smoked brisket and wild boar ribs elevate BBQ into a proper dinner-out experience. Live Texas music nightly on the upstairs stage. The rare BBQ spot that works for both casual lunches and date nights.",dishes:["Brisket","Wild Boar Ribs","Craft Cocktails","Live Music"],address:"401 W 2nd St, Austin, TX 78701",phone:"(512) 494-1500",lat:30.2643,lng:-97.7488,instagram:"lambertsaustin",website:"https://www.lambertsaustin.com"});

add({name:"Jack Allen's Kitchen",cuisine:"Texas Comfort Food",neighborhood:"Multiple Locations",score:85,price:2,tags:["Southern","Casual","Brunch","Family","Local Favorites"],reservation:"walk-in",description:"Texas comfort food with a farm-to-table focus — chicken fried steak, Gulf shrimp, and biscuits from a chef who sources from Texas ranches. Multiple locations serve the same quality. The brunch is hearty and the happy hour is a value. A Hill Country comfort food staple.",dishes:["Chicken Fried Steak","Gulf Shrimp","Biscuits","Brunch"],address:"7720 Hwy 71 W, Suite 300, Austin, TX 78735",phone:"(512) 852-8558",lat:30.2320,lng:-97.8280,instagram:"jackallenskitchen",website:"https://www.jackallenskitchen.com",suburb:true});

add({name:"Better Half Coffee & Cocktails",cuisine:"Coffee / Cocktails",neighborhood:"East Austin",score:85,price:1,tags:["Coffee","Cocktails","Brunch","Patio","Local Favorites"],reservation:"walk-in",description:"East Austin daytime coffee shop that transforms into a cocktail bar at night. The morning espresso is excellent, the brunch menu is creative, and the evening cocktails are well-crafted. The shaded patio and industrial-chic space make it a neighborhood anchor.",dishes:["Specialty Coffee","Brunch","Cocktails","Patio"],address:"406 Walsh St, Austin, TX 78702",phone:"(512) 645-0786",lat:30.2621,lng:-97.7260,instagram:"betterhalfbar",website:"https://www.betterhalfatx.com"});

add({name:"Anthem",cuisine:"Chinese / Modern",neighborhood:"East Austin",score:86,price:2,tags:["Chinese","Casual","Cocktails","Date Night"],reservation:"Resy",description:"Modern Chinese restaurant and cocktail bar in East Austin with creative dim sum, noodles, and wok-fired dishes. The Sichuan dan dan noodles and soup dumplings are standouts. The cocktail program adds Chinese-inspired drinks. A fresh take on Chinese cooking in Austin.",dishes:["Dan Dan Noodles","Soup Dumplings","Wok-Fired Dishes","Chinese Cocktails"],address:"1109 E 6th St, Austin, TX 78702",phone:"(512) 522-2662",lat:30.2631,lng:-97.7303,instagram:"anthouston",website:"https://www.antheaustin.com"});

add({name:"Loro South Congress",cuisine:"Asian BBQ",neighborhood:"South Lamar",score:90,price:2,tags:["Asian Fusion","BBQ","Casual","Patio","Awards"],reservation:"walk-in",awards:"Michelin Recommended",group:"Hai Hospitality",description:"Already in data as Loro.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Veracruz All Natural",cuisine:"Mexican / Breakfast Tacos",neighborhood:"East Austin",score:88,price:1,tags:["Mexican","Tacos","Breakfast","Casual","Local Favorites","Cheap Eats"],reservation:"walk-in",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Paperboy",cuisine:"American / Breakfast",neighborhood:"East Austin",score:86,price:1,tags:["Breakfast","Brunch","Casual","Patio"],reservation:"walk-in",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

// === MORE CELEBRATIONS / SPECIAL OCCASION ===
add({name:"Aba Austin",cuisine:"Mediterranean",neighborhood:"South Congress",score:89,price:3,tags:["Mediterranean","Fine Dining","Patio","Brunch"],reservation:"Resy",group:"Lettuce Entertain You",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Red Ash",cuisine:"Italian / Wood-Fired",neighborhood:"Downtown",score:89,price:3,tags:["Italian","Fine Dining","Date Night","Cocktails"],reservation:"OpenTable",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Intero",cuisine:"Italian / Whole Animal",neighborhood:"East Austin",score:88,price:3,tags:["Italian","Fine Dining","Date Night","Awards"],reservation:"Resy",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

// === MORE CASUAL / VARIED ===
add({name:"Sandy's Hamburgers",cuisine:"Burgers / Drive-In",neighborhood:"Barton Springs",score:85,price:1,tags:["Burgers","Classic","Casual","Family","Cheap Eats","Iconic"],description:"Retro drive-in on Barton Springs Road since 1946. Thin-patty burgers, hand-dipped frozen custard, and root beer floats at counter prices. The simplicity is the appeal — nothing has changed in decades. A post-Barton Springs swim tradition for 80 years.",dishes:["Thin-Patty Burger","Frozen Custard","Root Beer Float","Onion Rings"],address:"603 Barton Springs Rd, Austin, TX 78704",phone:"(512) 478-6322",lat:30.2640,lng:-97.7590,instagram:"sandysfrozencustard",website:"https://www.sandyshamburgers.com"});

add({name:"Dan's Hamburgers",cuisine:"Burgers / Drive-Thru",neighborhood:"Multiple Locations",score:84,price:1,tags:["Burgers","Classic","Casual","Cheap Eats","Family"],description:"Austin's original fast-food burger chain since 1973. The double-meat cheeseburger is a simple, greasy, perfect thing. Multiple locations and a drive-thru make it the Austin equivalent of In-N-Out — local, affordable, and beloved.",dishes:["Double Meat Cheeseburger","Fries","Milkshakes","Onion Rings"],address:"5602 N Lamar Blvd, Austin, TX 78756",phone:"(512) 459-3239",lat:30.3270,lng:-97.7270,instagram:"danshamburgersatx",website:"https://www.danshamburgersatx.com"});

add({name:"Juan in a Million",cuisine:"Tex-Mex / Breakfast Tacos",neighborhood:"East Austin",score:86,price:1,tags:["Tex-Mex","Breakfast","Casual","Classic","Local Favorites"],description:"East Austin breakfast taco institution since 1980. The Don Juan is the legendary order — a massive plate of eggs, bacon, potato, cheese, and beans. No-frills, cash-friendly, and packed with character. President Obama stopped here. A true Austin original.",dishes:["The Don Juan","Breakfast Tacos","Migas","Huevos Rancheros"],address:"2300 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 472-3872",lat:30.2533,lng:-97.7194,instagram:"juaninamillion",website:"https://www.juaninamillion.com"});

add({name:"Thai Cuisine",cuisine:"Thai",neighborhood:"North Austin",score:85,price:1,tags:["Thai","Casual","Cheap Eats","Local Favorites"],description:"No-frills north Austin Thai restaurant serving some of the most authentic Thai food in the city. The pad see ew, green curry, and tom kha gai are deeply flavored and generously portioned. BYOB-friendly and affordable. A local Thai food favorite for over a decade.",dishes:["Pad See Ew","Green Curry","Tom Kha Gai","Pad Thai"],address:"4000 N Lamar Blvd, Suite 700, Austin, TX 78756",phone:"(512) 444-5559",lat:30.3100,lng:-97.7389,instagram:"thaicuisineatx",website:"https://www.thaicuisineatx.com"});

add({name:"Phoebe's Diner",cuisine:"American Diner",neighborhood:"North Loop",score:85,price:1,tags:["Breakfast","Brunch","Casual","Patio","Local Favorites"],description:"North Loop all-day diner with a creative American menu, excellent coffee, and a shaded patio. The pancakes, breakfast sandwiches, and grain bowls are all solidly executed. The kind of no-fuss neighborhood cafe that makes North Loop great.",dishes:["Pancakes","Breakfast Sandwiches","Grain Bowls","Coffee"],address:"5501 N Lamar Blvd, Austin, TX 78751",phone:"(512) 992-9384",lat:30.3270,lng:-97.7270,instagram:"phoebesdiner",website:"https://www.phoebesdiner.com"});

add({name:"Tatsu-Ya Shops (South Lamar)",cuisine:"Japanese / Multiple",neighborhood:"South Lamar",score:88,price:2,tags:["Japanese","Casual","Late Night","Local Favorites"],reservation:"walk-in",group:"Tatsu-Ya",description:"The Tatsu-Ya compound on South Lamar where Ramen Tatsu-Ya, Tiki Tatsu-Ya, and DipDipDip Tatsu-Ya (shabu shabu) share a lot. Three distinct Japanese concepts from Austin's most creative restaurant group. Hit all three in one night for the full Tatsu-Ya experience.",dishes:["Ramen","Tiki Cocktails","Shabu Shabu","Pupu Platter"],address:"1234 S Lamar Blvd, Austin, TX 78704",phone:"",lat:30.2517,lng:-97.7681,instagram:"tatsuyarestaurants",website:"https://www.tatsu-ya.com"});

add({name:"DipDipDip Tatsu-Ya",cuisine:"Japanese Shabu Shabu",neighborhood:"South Lamar",score:87,price:3,tags:["Japanese","Hot Pot","Date Night","Local Favorites"],reservation:"walk-in",group:"Tatsu-Ya",description:"The Tatsu-Ya team's shabu shabu concept — Japanese hot pot with premium meats, handmade noodles, and creative dipping sauces. The theatrical tableside cooking makes it a fun date night. Part of the South Lamar Tatsu-Ya compound.",dishes:["Shabu Shabu","Premium Wagyu","Handmade Noodles","Dipping Sauces"],address:"1300 S Lamar Blvd, Austin, TX 78704",phone:"(512) 814-0361",lat:30.2517,lng:-97.7681,instagram:"dipdipdiptatsuya",website:"https://www.dipdipdip-tatsuya.com"});

add({name:"Ramen Tatsu-Ya (North)",cuisine:"Japanese Ramen",neighborhood:"North Austin",score:88,price:2,tags:["Japanese","Ramen","Casual","Late Night"],reservation:"walk-in",group:"Tatsu-Ya",description:"The original Tatsu-Ya location on Research Blvd. Same legendary tonkotsu broth, punk rock vibe, and devoted lines. The OG spot where Austin's ramen revolution began.",dishes:["Tonkotsu Ramen","Miso","Vegan Ramen","Gyoza"],address:"8557 Research Blvd, Suite 126, Austin, TX 78758",phone:"(512) 893-5561",lat:30.3700,lng:-97.7189,instagram:"raboratx",website:"https://www.ramen-tatsuya.com"});

add({name:"Polvos",cuisine:"Interior Mexican",neighborhood:"South 1st",score:85,price:1,tags:["Mexican","Casual","Patio","Margaritas","Local Favorites"],description:"South First interior Mexican with a massive patio, strong margaritas, and a menu that goes beyond typical Tex-Mex. The chiles rellenos, mole enchiladas, and street corn are authentic and satisfying. The patio is packed every weekend. A south Austin institution.",dishes:["Chiles Rellenos","Mole Enchiladas","Street Corn","Margaritas"],address:"2004 S 1st St, Austin, TX 78704",phone:"(512) 441-5446",lat:30.2430,lng:-97.7566,instagram:"polvosaustin",website:"https://www.polvosmexicanfood.com"});

add({name:"Counter 3.Five.VII",cuisine:"Vietnamese / Omakase",neighborhood:"East Austin",score:88,price:3,tags:["Vietnamese","Fine Dining","Date Night","Exclusive","Awards"],reservation:"Tock",awards:"Michelin Recommended",description:"Intimate East Austin Vietnamese omakase experience — a multi-course tasting menu exploring regional Vietnamese cuisine through a fine-dining lens. The chef's personal story infuses every course. Michelin recommended and one of Austin's most unique dining experiences. Limited seats make it an exclusive evening.",dishes:["Vietnamese Tasting Menu","Regional Courses","Sake Pairing"],address:"4412 Manchaca Rd, Austin, TX 78745",phone:"",lat:30.2175,lng:-97.7815,instagram:"counter357",website:"https://www.counter357.com"});

add({name:"Eberly",cuisine:"American / Southern Fine Dining",neighborhood:"South Lamar",score:88,price:3,tags:["American","Fine Dining","Date Night","Celebrations","Cocktails"],reservation:"OpenTable",description:"Multi-level South Lamar restaurant from the McGuire Moorman Lambert group with a grand bar, supper club, and cafe. The architecture alone is stunning — high ceilings, marble bar, and art deco touches. Steaks, seafood, and an impressive cocktail program in one of Austin's most beautiful dining rooms.",dishes:["Steaks","Seafood","Cocktails","Supper Club"],address:"615 S Lamar Blvd, Suite A, Austin, TX 78704",phone:"(512) 916-9000",lat:30.2560,lng:-97.7681,instagram:"eberlyaustin",website:"https://www.eberlyaustin.com",group:"McGuire Moorman Lambert"});

// Write back
html = html.slice(0, a) + JSON.stringify(arr) + html.slice(e);
fs.writeFileSync(file, html, 'utf8');
console.log('Austin: ' + arr.length + ' spots (added ' + added + ')');
console.log('Need', 250 - arr.length, 'more to hit 250');
