// Austin Batch 6: Tourist attractions, more restaurants, food trucks, 6th Street, wine, celebrations
// Austin at 164, pushing toward 250
// Run: node scripts/austin-batch-6.js

const fs = require('fs');
const file = require('path').join(__dirname, '..', 'index.html');
let html = fs.readFileSync(file, 'utf8');
const s = html.indexOf('const AUSTIN_DATA');
const a = html.indexOf('[', s);
let d=0,e=a;
for(let i=a;i<html.length;i++){if(html[i]==='[')d++;if(html[i]===']')d--;if(d===0){e=i+1;break;}}
const arr = JSON.parse(html.slice(a, e));
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let nextId = Math.max(...arr.map(r=>r.id||0))+1, added = 0;

function add(s) {
  if(existing.has(s.name.toLowerCase()))return;
  arr.push({id:nextId++,name:s.name,phone:s.phone||'',cuisine:s.cuisine,neighborhood:s.neighborhood,score:s.score,price:s.price,tags:s.tags,indicators:s.indicators||[],hh:'',reservation:s.reservation||'walk-in',awards:s.awards||'',description:s.description,dishes:s.dishes,address:s.address,hours:'',lat:s.lat,lng:s.lng,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:s.trending||false,group:s.group||'',instagram:s.instagram||'',website:s.website||'',suburb:s.suburb||false,reserveUrl:'',menuUrl:'',res_tier:s.res_tier||2});
  existing.add(s.name.toLowerCase());added++;
}

// === TOURIST ATTRACTIONS ===
add({name:"Zilker Park",cuisine:"Tourist Attraction",neighborhood:"Zilker",score:90,price:0,tags:["Tourist Attraction","Park","Free","Outdoor","Iconic","Family"],description:"351 acres anchoring Austin's outdoor identity. Home to Barton Springs Pool, the Zilker Botanical Garden, and the Zilker Zephyr train. ACL Music Festival takes over every October. The Great Lawn, disc golf course, and kayak launch make it an all-day destination. Free parking and entry.",dishes:["Barton Springs Pool","Botanical Garden","Kayaking","ACL Festival"],address:"2100 Barton Springs Rd, Austin, TX 78704",phone:"(512) 974-6700",lat:30.2669,lng:-97.7726,instagram:"zilkerpark",website:"https://www.austintexas.gov/department/zilker-metropolitan-park"});

add({name:"Blanton Museum of Art",cuisine:"Art Museum",neighborhood:"UT Campus",score:88,price:1,tags:["Museum","Art","Tourist Attraction","Free"],description:"One of the largest university art museums in the US with 21,000+ works spanning ancient to contemporary. The Ellsworth Kelly-designed Austin chapel is the only building the artist ever created. Free admission every Tuesday. Greek pottery to modern Latin American art in spacious galleries.",dishes:["Free Tuesdays","Ellsworth Kelly Chapel","Exhibitions"],address:"200 E Martin Luther King Jr Blvd, Austin, TX 78701",phone:"(512) 471-5482",lat:30.2810,lng:-97.7370,instagram:"blantonmuseum",website:"https://blantonmuseum.org"});

add({name:"Bullock Texas State History Museum",cuisine:"Museum",neighborhood:"Downtown",score:87,price:2,tags:["Museum","Tourist Attraction","Family","Historic"],description:"Three floors of Texas history from prehistoric times to the Space Age, anchored by a 34-foot bronze star at the entrance. Austin's only IMAX theater and a 4-D theater add multimedia experiences. The Texas history exhibits are entertaining and educational. A rainy-day essential.",dishes:["Texas History","IMAX Theater","4-D Theater"],address:"1800 Congress Ave, Austin, TX 78701",phone:"(512) 936-8746",lat:30.2801,lng:-97.7404,instagram:"bullockmuseum",website:"https://www.thestoryoftexas.com"});

add({name:"HOPE Outdoor Gallery",cuisine:"Tourist Attraction",neighborhood:"East Austin",score:86,price:0,tags:["Tourist Attraction","Art","Free","Photo Op","Outdoor"],description:"Austin's iconic graffiti park reopened in late 2025 at a massive 18-acre site near the airport. Spray-painted walls, giant murals, and layered tags in an open-air park where visitors can leave their mark. Free admission, open Wednesday-Sunday 10am-6pm. Austin's most Instagram-worthy destination.",dishes:["Graffiti Art","Murals","Photo Ops","Street Art"],address:"5404 Dalton Ln, Austin, TX 78721",phone:"",lat:30.2320,lng:-97.6790,instagram:"hopeoutdoorgallery",website:"https://www.hopeoutdoorgallery.com"});

add({name:"Congress Avenue Bridge Bat Colony",cuisine:"Tourist Attraction",neighborhood:"Downtown",score:89,price:0,tags:["Tourist Attraction","Free","Iconic","Outdoor"],description:"1.5 million Mexican free-tail bats emerge from under the Congress Avenue Bridge at sunset from March through November — the largest urban bat colony in North America. Watch from the bridge, the hike-and-bike trail, or a kayak on Lady Bird Lake. Free and spectacular. Peak season is August.",dishes:["Bat Watching","Sunset","Free","March-November"],address:"Congress Ave Bridge, Austin, TX 78704",phone:"",lat:30.2610,lng:-97.7450,instagram:"batsinaustin",website:"https://www.austintexas.org/things-to-do/outdoors/bat-watching/"});

add({name:"LBJ Presidential Library",cuisine:"Museum",neighborhood:"UT Campus",score:87,price:0,tags:["Museum","Tourist Attraction","Historic","Free"],description:"Free museum on the UT campus documenting the life and presidency of Lyndon B. Johnson — the 36th president who shaped modern America. The Oval Office replica, Vietnam War exhibits, and civil rights displays are powerful. Always free, always thought-provoking.",dishes:["Free Admission","Oval Office Replica","Civil Rights Exhibits"],address:"2313 Red River St, Austin, TX 78705",phone:"(512) 721-0200",lat:30.2860,lng:-97.7290,instagram:"laborjlibrary",website:"https://www.lbjlibrary.org"});

add({name:"6th Street Entertainment District",cuisine:"Tourist Attraction",neighborhood:"Downtown",score:85,price:0,tags:["Tourist Attraction","Nightlife","Live Music","Bar","Free"],description:"Austin's famous entertainment strip — six blocks of bars, live music venues, and nightclubs between Congress and I-35. Dirty Sixth is the tourist party zone, West Sixth is the upscale bar scene, and East Sixth is the local/creative hub. Free to walk, live music pours out of every door Thursday-Saturday.",dishes:["Live Music","Bar Crawl","Nightlife","Free to Walk"],address:"E 6th St, Austin, TX 78701",phone:"",lat:30.2672,lng:-97.7390,instagram:"sixthstreetaustin",website:"https://www.austintexas.org/things-to-do/nightlife/"});

// === MORE RESTAURANTS ===
add({name:"Chuy's",cuisine:"Tex-Mex",neighborhood:"Barton Springs",score:84,price:1,tags:["Tex-Mex","Casual","Classic","Family","Local Favorites"],description:"The original Chuy's opened in 1982 on Barton Springs Road with a vision of fun, funky Tex-Mex. Green chile chicken enchiladas, Big-as-Yo'-Face Burritos, and the Creamy Jalapeño dip are Austin classics. Now a national chain but the OG location still has the energy. Elvis memorabilia everywhere.",dishes:["Green Chile Enchiladas","Big-as-Yo-Face Burrito","Creamy Jalapeño","Margaritas"],address:"1728 Barton Springs Rd, Austin, TX 78704",phone:"(512) 474-4452",lat:30.2610,lng:-97.7620,instagram:"chuysmexfood",website:"https://www.chuys.com"});

add({name:"Guero's Taco Bar",cuisine:"Tex-Mex / Tacos",neighborhood:"South Congress",score:84,price:1,tags:["Tex-Mex","Tacos","Live Music","Patio","Classic","Family"],description:"South Congress Tex-Mex institution in a converted feed store. The interior Mexican tacos, oak-grilled fajitas, and live music on the patio make it a SoCo anchor. Presidents Clinton and Obama have eaten here. The outdoor stage hosts live bands most nights.",dishes:["Interior Mexican Tacos","Fajitas","Queso","Live Music"],address:"1412 S Congress Ave, Austin, TX 78704",phone:"(512) 447-7688",lat:30.2496,lng:-97.7493,instagram:"guerostacosbar",website:"https://www.guerostacobar.com"});

add({name:"Salt & Time Butcher Shop",cuisine:"Butcher / Charcuterie",neighborhood:"East Austin",score:86,price:2,tags:["Butcher","Charcuterie","Casual","Local Favorites"],description:"East Austin whole-animal butcher shop and charcuterie bar. House-cured salumi, fresh-ground burgers, and seasonal sandwiches from a team that sources from Texas ranches. The retail case is a carnivore's dream. The Saturday morning market draws meat-obsessed locals.",dishes:["House Salumi","Burgers","Charcuterie Board","Sandwiches"],address:"1912 E 7th St, Austin, TX 78702",phone:"(512) 524-1383",lat:30.2626,lng:-97.7220,instagram:"saltandtime",website:"https://www.saltandtime.com"});

add({name:"Wingstop (Original)",cuisine:"Chicken Wings",neighborhood:"South Lamar",score:82,price:1,tags:["Casual","Chicken","Cheap Eats","Local Favorites"],description:"The original Wingstop — opened in 1994 in Garland but the brand is headquartered in Dallas/Austin. Austin's relationship with the chain is personal. Lemon Pepper Wet and Original Hot are the classics. A Texas-born wing empire.",dishes:["Lemon Pepper Wings","Original Hot","Cajun","Fries"],address:"4001 S Lamar Blvd, Suite 530, Austin, TX 78704",phone:"(512) 693-1800",lat:30.2350,lng:-97.7847,instagram:"wingstop",website:"https://www.wingstop.com"});

add({name:"Mum Foods Smokehouse & Deli",cuisine:"BBQ / Deli",neighborhood:"East Austin",score:87,price:2,tags:["BBQ","Deli","Casual","Awards","Local Favorites"],reservation:"walk-in",awards:"Michelin Recommended",description:"Michelin-recommended smokehouse and deli in East Austin merging Texas BBQ with deli traditions. The pastrami is cured and smoked in-house, the brisket is textbook, and the reuben sandwich bridges both worlds. A Michelin nod for a BBQ-deli hybrid is rare and well-earned.",dishes:["House Pastrami","Brisket","Reuben","Smoked Meats"],address:"2113 Manor Rd, Austin, TX 78722",phone:"(512) 953-0060",lat:30.2757,lng:-97.7195,instagram:"mumfoodsatx",website:"https://www.mumfoods.com"});

add({name:"Siti",cuisine:"Middle Eastern / Modern",neighborhood:"East Austin",score:87,price:2,tags:["Middle Eastern","Date Night","Cocktails","Awards","New Opening"],indicators:["new"],reservation:"Resy",awards:"Michelin Recommended 2025",description:"Modern Middle Eastern restaurant in East Austin with Michelin recognition. Hummus, kebabs, and mezze elevated with local ingredients and creative technique. The pita is baked fresh to order and the cocktails use Middle Eastern spices. One of Austin's most exciting new openings.",dishes:["Fresh Pita","Hummus","Kebabs","Cocktails"],address:"1709 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 580-0355",lat:30.2533,lng:-97.7260,instagram:"sitiatx",website:"https://www.sitiatx.com",trending:true});

add({name:"La Condesa",cuisine:"Modern Mexican",neighborhood:"2nd Street",score:88,price:2,tags:["Mexican","Cocktails","Date Night","Patio","Brunch"],reservation:"Resy",awards:"Michelin Recommended",description:"Downtown modern Mexican with a stunning patio, creative cocktails, and a menu blending traditional recipes with Texas flair. The margarita program is among Austin's best. Weekend brunch features chilaquiles and huevos rancheros. A polished 2nd Street destination.",dishes:["Chilaquiles","Enchiladas","Margaritas","Guacamole"],address:"400 W 2nd St, Austin, TX 78701",phone:"(512) 499-0300",lat:30.2643,lng:-97.7488,instagram:"lacondesa",website:"https://www.lacondesaaustin.com"});

add({name:"Poet's",cuisine:"New American / Cocktails",neighborhood:"East Austin",score:87,price:2,tags:["American","Cocktails","Date Night","Awards","New Opening"],indicators:["new"],reservation:"Resy",awards:"Michelin Recommended 2025",description:"Michelin-recommended East Austin restaurant with a seasonal menu and ambitious cocktail program. Creative New American plates that draw from the chef's global travels. The bar program is as serious as the kitchen. A new Michelin pick that's quickly become essential.",dishes:["Seasonal Menu","Craft Cocktails","Small Plates"],address:"1200 E 11th St, Austin, TX 78702",phone:"(512) 953-0050",lat:30.2696,lng:-97.7283,instagram:"poetsatx",website:"https://www.poetsatx.com",trending:true});

add({name:"Pasta | Bar Austin",cuisine:"Italian / Pasta",neighborhood:"East Austin",score:87,price:2,tags:["Italian","Pasta","Date Night","Awards","New Opening"],indicators:["new"],reservation:"Resy",awards:"Michelin Recommended 2025",description:"Counter-service pasta bar with Michelin recognition for its handmade noodles and seasonal sauces. The simplicity is the point — fresh pasta, quality ingredients, no fuss. One of the most affordable Michelin-recommended spots in Austin.",dishes:["Handmade Pasta","Cacio e Pepe","Seasonal Sauces","Italian Wine"],address:"620 E 6th St, Austin, TX 78701",phone:"",lat:30.2668,lng:-97.7350,instagram:"pastabaraustin",website:"https://www.pastabaraustin.com",trending:true});

add({name:"Fabrik",cuisine:"European / Industrial",neighborhood:"East Austin",score:87,price:2,tags:["European","Date Night","Cocktails","Awards","New Opening"],indicators:["new"],reservation:"Resy",awards:"Michelin Recommended 2025",description:"New Michelin-recommended European restaurant in an industrial East Austin space. The menu spans France, Italy, and Germany with seasonal preparations and an excellent natural wine program. The converted warehouse setting is dramatic and romantic.",dishes:["European Plates","Natural Wine","Seasonal Menu","Cocktails"],address:"2026 E 7th St, Austin, TX 78702",phone:"(512) 953-0070",lat:30.2626,lng:-97.7194,instagram:"fabrikatx",website:"https://www.fabrikatx.com",trending:true});

// === MORE CELEBRATIONS / FINE DINING ===
add({name:"Mattie's at Green Pastures",cuisine:"Southern / Estate Dining",neighborhood:"South Austin",score:88,price:3,tags:["Southern","Fine Dining","Celebrations","Patio","Historic"],reservation:"Resy",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Lutie's Garden Restaurant",cuisine:"Farm-to-Table / Garden",neighborhood:"South Austin",score:88,price:3,tags:["American","Fine Dining","Date Night","Patio","Awards"],reservation:"Resy",awards:"Michelin Recommended",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

// === FOOD TRUCKS ===
add({name:"The Mighty Cone",cuisine:"Fried Chicken / Food Truck",neighborhood:"South Lamar",score:84,price:1,tags:["Casual","Food Truck","Local Favorites","Family"],description:"Austin-born concept serving fried avocado, chicken, and shrimp in cone-shaped paper wraps. Started at the ACL festival and became a permanent food truck. The Hot & Crunchy Chicken Cone is the signature. Simple, clever, and very Austin.",dishes:["Hot & Crunchy Cone","Fried Avocado","Chicken Cone","Shrimp Cone"],address:"1600 S Congress Ave, Austin, TX 78704",phone:"(512) 220-7800",lat:30.2443,lng:-97.7503,instagram:"themightycone",website:"https://www.themightycone.com"});

add({name:"East Side King",cuisine:"Asian Street Food / Food Truck",neighborhood:"East Austin",score:86,price:1,tags:["Asian Fusion","Food Truck","Casual","Late Night","Local Favorites"],reservation:"walk-in",group:"FAM Hospitality",description:"Chef Paul Qui's Asian street food concept born from Austin food trucks. Thai-inspired chicken karaage, beet fries, and creative Asian small plates. Multiple locations including trucks behind bars. The original Austin food truck success story that launched a restaurant empire.",dishes:["Beet Home Fries","Chicken Karaage","Thai Basil Noodles","Bao"],address:"1618 E 6th St, Austin, TX 78702",phone:"",lat:30.2621,lng:-97.7260,instagram:"eastsideking",website:"https://www.eskstreats.com"});

// Write back
html = html.slice(0, a) + JSON.stringify(arr) + html.slice(e);
fs.writeFileSync(file, html, 'utf8');
console.log('Austin: ' + arr.length + ' spots (added ' + added + ')');
console.log('Need', 250 - arr.length, 'more to hit 250');
