// Austin Batch 3: Fill gaps — remaining research spots + Korean, Indian, seafood, more bars, food trucks, nightlife
// Austin at 86, need 164 more
// Run: node scripts/austin-batch-3.js

const fs = require('fs');
const file = require('path').join(__dirname, '..', 'index.html');
let html = fs.readFileSync(file, 'utf8');
const s = html.indexOf('const AUSTIN_DATA');
const a = html.indexOf('[', s);
let d=0, e=a;
for(let i=a;i<html.length;i++){if(html[i]==='[')d++;if(html[i]===']')d--;if(d===0){e=i+1;break;}}
const arr = JSON.parse(html.slice(a, e));
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let nextId = Math.max(...arr.map(r=>r.id||0))+1;
let added = 0;

function add(s) {
  if(existing.has(s.name.toLowerCase()))return;
  arr.push({id:nextId++,name:s.name,phone:s.phone||'',cuisine:s.cuisine,neighborhood:s.neighborhood,score:s.score,price:s.price,tags:s.tags,indicators:s.indicators||[],hh:'',reservation:s.reservation||'walk-in',awards:s.awards||'',description:s.description,dishes:s.dishes,address:s.address,hours:'',lat:s.lat,lng:s.lng,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:s.trending||false,group:s.group||'',instagram:s.instagram||'',website:s.website||'',suburb:s.suburb||false,reserveUrl:'',menuUrl:'',res_tier:s.res_tier||2});
  existing.add(s.name.toLowerCase());added++;
}

// === FROM RESEARCH — MISSING SPOTS ===

add({name:"Stiles Switch BBQ & Brew",cuisine:"Texas BBQ",neighborhood:"North Loop",score:90,price:2,tags:["BBQ","Craft Beer","Local Favorites","Family"],reservation:"walk-in",awards:"Texas Monthly Top 50 BBQ",description:"Neighborhood BBQ joint on North Lamar with excellent smoked meats and a solid craft beer selection. Named after a Williamson County community, it serves classic central Texas BBQ without the long lines. The turkey and brisket are standouts. A great low-key alternative to the big-name spots.",dishes:["Brisket","Turkey Breast","Beef Rib","Smoked Chicken"],address:"6610 N Lamar Blvd, Austin, TX 78752",phone:"(512) 380-9199",lat:30.3365,lng:-97.7270,instagram:"stilesswitchbbq",website:"https://stilesswitchbbq.com"});

add({name:"Lucky Robot",cuisine:"Japanese / Asian Fusion",neighborhood:"South Congress",score:86,price:2,tags:["Japanese","Sushi","Casual","Cocktails","Patio"],reservation:"walk-in",description:"Fun, casual Japanese restaurant on South Congress with pop-art interiors, solid sushi and creative rolls. The sake and cocktail program is playful. A reliable SoCo neighborhood spot for casual dinners and late-night bites.",dishes:["Sushi Rolls","Edamame Dumplings","Ramen","Japanese Curry"],address:"1303 S Congress Ave, Austin, TX 78704",phone:"(512) 444-8081",lat:30.2492,lng:-97.7493,instagram:"luckyrobotaustin",website:"https://luckyrobotrestaurant.com"});

add({name:"Casa Colombia",cuisine:"Colombian",neighborhood:"East Austin",score:85,price:2,tags:["Latin","Casual","Brunch","Patio","Local Favorites"],reservation:"walk-in",description:"Authentic Colombian flavors in East Austin — bandeja paisa, arepas, empanadas, and Colombian breakfast staples. The bright, casual space has a warm community feel. A unique addition to Austin's Latin dining scene that goes well beyond typical Tex-Mex.",dishes:["Bandeja Paisa","Arepas","Empanadas","Colombian Breakfast"],address:"1917 E 2nd St, Austin, TX 78702",phone:"(512) 814-2988",lat:30.2574,lng:-97.7220,instagram:"casacolombia.atx",website:"https://www.casacolombia.net"});

add({name:"Counter Cafe",cuisine:"American Breakfast",neighborhood:"East Austin",score:86,price:1,tags:["Breakfast","Brunch","Casual","Local Favorites","Cheap Eats"],reservation:"walk-in",description:"Cozy East Austin breakfast spot serving hearty American classics. Famous for enormous, perfectly made pancakes. Small space fills fast on weekends. A pure, simple Austin breakfast experience beloved by the neighborhood.",dishes:["Giant Pancakes","Migas","Biscuits","Breakfast Plates"],address:"1906 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 382-1864",lat:30.2533,lng:-97.7220,instagram:"countercafeatx",website:""});

add({name:"Jacoby's Restaurant & Mercantile",cuisine:"Southern / Ranch",neighborhood:"East Austin",score:87,price:2,tags:["Southern","Brunch","Patio","Family","Local Favorites"],reservation:"walk-in",description:"Waterfront ranch-to-table restaurant on the Colorado River with genuine agricultural roots. The family raises their own cattle. Brunch is hearty and Texan with biscuits, steaks, and eggs. The mercantile sells house-made goods. A uniquely Austin experience.",dishes:["Brisket & Eggs","Chicken Fried Steak","Biscuits & Gravy","Smoked Beef"],address:"3235 E Cesar Chavez St, Austin, TX 78702",phone:"(512) 366-5808",lat:30.2519,lng:-97.7094,instagram:"jacobysaustin",website:"https://www.jacobysaustin.com"});

add({name:"Pieous",cuisine:"Pizza / BBQ",neighborhood:"Dripping Springs",score:89,price:2,tags:["Pizza","BBQ","Casual","Family","Local Favorites"],reservation:"walk-in",description:"Unique Dripping Springs spot combining wood-fired Neapolitan pizza with house-smoked meats. Makes its own mozzarella in-house and smokes brisket and pastrami daily. The pastrami sandwich rivals any NYC deli. Worth the drive southwest.",dishes:["Margherita Pizza","Smoked Pastrami Sandwich","House Mozzarella","Brisket Pizza"],address:"12005 Hwy 290 W, Austin, TX 78737",phone:"(512) 394-7041",lat:30.2120,lng:-97.8970,instagram:"pieousaustin",website:"https://www.pieous.com",suburb:true});

add({name:"Wanderlust Wine Co.",cuisine:"Wine Bar / Tasting Room",neighborhood:"South Lamar",score:86,price:2,tags:["Wine Bar","Date Night","Patio","Local Favorites"],reservation:"Tock",description:"Texas wine tasting room and bar with multiple Austin locations. Curated flights from Texas Hill Country vineyards alongside small plates. The Barton Springs location has a gorgeous shaded patio. A great introduction to Texas wine.",dishes:["Texas Wine Flights","Cheese Boards","Small Plates"],address:"1601 Barton Springs Rd, Austin, TX 78704",phone:"(512) 265-5275",lat:30.2610,lng:-97.7600,instagram:"wanderlustwineco",website:"https://wanderlustwine.com"});

add({name:"Foreign & Domestic",cuisine:"New American",neighborhood:"North Loop",score:91,price:3,tags:["Fine Dining","Date Night","Awards","Critics Pick","Cocktails"],reservation:"Resy",awards:"Michelin Recommended",description:"Chef-driven North Loop restaurant with constantly changing menus based on seasonal availability. Known for adventurous, technique-driven cooking — bone marrow, unusual offal preparations, and handmade pasta. A restaurant for food lovers who want to be surprised.",dishes:["Bone Marrow","Seasonal Tasting","Offal Dishes","Handmade Pasta"],address:"306 E 53rd St, Austin, TX 78751",phone:"(512) 459-1010",lat:30.3175,lng:-97.7275,instagram:"foreigndomestic",website:"https://www.foreignanddomestic.com"});

add({name:"Cosmic Coffee + Beer Garden",cuisine:"Coffee / Beer Garden",neighborhood:"South Congress",score:85,price:1,tags:["Coffee","Craft Beer","Patio","Food Truck","Local Favorites"],reservation:"walk-in",description:"South Congress coffee shop and beer garden with a massive shaded patio, food truck lot, and live music. Morning coffee transitions to afternoon craft beer and evening cocktails. Multiple food trucks rotate through. The chickens wandering the lot are very Austin.",dishes:["Specialty Coffee","Craft Beer","Food Truck Rotation","Live Music"],address:"121 Pickle Rd, Austin, TX 78704",phone:"(512) 358-8695",lat:30.2375,lng:-97.7678,instagram:"cosmiccoffeebeer",website:"https://www.cosmiccoffee.com"});

add({name:"Whisler's",cuisine:"Cocktail Bar",neighborhood:"East Austin",score:88,price:2,tags:["Cocktails","Bar","Date Night","Late Night","Local Favorites"],reservation:"walk-in",description:"East Sixth cocktail bar in a converted commercial building with a mezcal-focused back patio bar upstairs. The drinks are creative and well-crafted, the atmosphere is moody and intimate. The rooftop mezcaleria is one of Austin's best-kept secrets. A cornerstone of East Austin nightlife.",dishes:["Craft Cocktails","Mezcal Flights","Bar Snacks"],address:"1816 E 6th St, Austin, TX 78702",phone:"(512) 480-0781",lat:30.2621,lng:-97.7240,instagram:"whislersatx",website:"https://www.whislersatx.com"});

add({name:"Zilker Brewing Company",cuisine:"Brewery / Taproom",neighborhood:"East Austin",score:85,price:1,tags:["Brewery","Craft Beer","Patio","Local Favorites"],reservation:"walk-in",description:"East Austin brewery with a relaxed taproom and outdoor patio. The Parks & Rec Pale Ale and Marco IPA are Austin favorites. Regular food truck pop-ups and live music. A solid neighborhood brewery with good vibes.",dishes:["Parks & Rec Pale Ale","Marco IPA","Seasonal Brews"],address:"1701 E 6th St, Austin, TX 78702",phone:"(512) 712-5590",lat:30.2621,lng:-97.7260,instagram:"zilkerbeer",website:"https://zilkerbeer.com"});

add({name:"St. Elmo Brewing Co.",cuisine:"Brewery / Taproom",neighborhood:"South Austin",score:86,price:1,tags:["Brewery","Craft Beer","Patio","Local Favorites"],reservation:"walk-in",description:"South Austin brewery in the St. Elmo neighborhood with excellent lagers and a dog-friendly patio. The Czech-style pilsner and seasonal releases draw a devoted following. Food trucks park outside regularly. Relaxed and community-focused.",dishes:["Czech Pilsner","Seasonal Lagers","Food Trucks"],address:"440 E St Elmo Rd, Austin, TX 78745",phone:"(737) 300-1965",lat:30.2165,lng:-97.7545,instagram:"stelmobrewing",website:"https://www.stelmobrewing.com"});

add({name:"Batch Craft Beer + Kolaches",cuisine:"Brewery / Kolaches",neighborhood:"East Austin",score:85,price:1,tags:["Brewery","Bakery","Breakfast","Casual","Local Favorites"],reservation:"walk-in",description:"East Austin brewery serving house-brewed craft beer alongside fresh-baked Czech kolaches — a uniquely Texas combination. The kolaches come in sweet and savory flavors, and the beer lineup rotates regularly. Breakfast beer and kolaches is a very Austin move.",dishes:["Kolaches","Craft Beer","Breakfast Kolaches","Seasonal Brews"],address:"3220 Manor Rd, Austin, TX 78723",phone:"(512) 401-3025",lat:30.2807,lng:-97.7094,instagram:"batchatx",website:"https://www.batchatx.com"});

add({name:"Clay Pit",cuisine:"Indian / Contemporary",neighborhood:"Downtown",score:87,price:2,tags:["Indian","Date Night","Cocktails","Local Favorites"],reservation:"OpenTable",awards:"Austin institution since 1998",description:"Downtown Austin's premier Indian restaurant since 1998 in a historic building. Contemporary Indian cuisine with traditional flavors — tandoori, biryani, and curries prepared with care. The lunch buffet is one of the best values downtown. Voted best Indian restaurant in Austin multiple times.",dishes:["Tandoori Chicken","Lamb Biryani","Butter Chicken","Lunch Buffet"],address:"1601 Guadalupe St, Austin, TX 78701",phone:"(512) 322-5131",lat:30.2760,lng:-97.7450,instagram:"claypitaustin",website:"https://claypit.com"});

add({name:"Thai Kun",cuisine:"Thai Street Food",neighborhood:"South Congress",score:88,price:2,tags:["Thai","Casual","Local Favorites","Patio"],reservation:"walk-in",awards:"Bon Appetit recognition",description:"Bold, authentic Thai street food with a creative edge from chef Thai Changthong. Pad thai, khao soi, and Thai fried chicken executed with genuine technique. Built a cult following from a food truck behind Whisler's before going brick-and-mortar. Part of the FAM Hospitality group.",dishes:["Pad Thai","Khao Soi","Thai Fried Chicken","Larb"],address:"1600 S Congress Ave, Austin, TX 78704",phone:"(512) 599-8886",lat:30.2443,lng:-97.7503,instagram:"thaikun_og",website:"https://www.thaikunaustin.com",group:"FAM Hospitality"});

// === MORE ESSENTIAL AUSTIN (beyond research) ===

add({name:"Comedor",cuisine:"Mexican Fine Dining",neighborhood:"Downtown",score:90,price:3,tags:["Mexican","Fine Dining","Date Night","Cocktails","Awards"],reservation:"Resy",awards:"Michelin Recommended",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"La Condesa",cuisine:"Modern Mexican",neighborhood:"Downtown",score:88,price:2,tags:["Mexican","Cocktails","Date Night","Patio","Brunch"],reservation:"Resy",awards:"Michelin Recommended",description:"Downtown modern Mexican restaurant with a gorgeous patio and one of Austin's best margarita programs. The menu blends traditional Mexican recipes with Texas ingredients. Weekend brunch is popular for chilaquiles and huevos rancheros. A polished SoCo-adjacent destination.",dishes:["Chilaquiles","Enchiladas","Margaritas","Guacamole"],address:"400 W 2nd St, Austin, TX 78701",phone:"(512) 499-0300",lat:30.2643,lng:-97.7488,instagram:"lacondesa",website:"https://www.lacondesaaustin.com"});

add({name:"Aba Austin",cuisine:"Mediterranean",neighborhood:"South Congress",score:89,price:3,tags:["Mediterranean","Date Night","Patio","Brunch","Cocktails"],reservation:"Resy",awards:"Michelin Recommended",group:"Lettuce Entertain You",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Birdie's",cuisine:"New American / Mediterranean",neighborhood:"East Austin",score:89,price:2,tags:["American","Mediterranean","Wine Bar","Date Night","Awards"],reservation:"Resy",awards:"Michelin Recommended, Food & Wine Best New Restaurant 2022",description:"East Austin neighborhood restaurant with a daily-changing menu inspired by Mediterranean and Southern cooking. Food & Wine named it a Best New Restaurant and Michelin recommended it. The natural wine program is excellent and the intimate space feels like dining at a friend's very talented house.",dishes:["Daily Changing Menu","Natural Wine","Seasonal Plates","House Bread"],address:"2944 E 12th St, Austin, TX 78702",phone:"(512) 523-2723",lat:30.2729,lng:-97.7095,instagram:"birdiesaustin",website:"https://www.birdiesaustin.com"});

add({name:"Garrison",cuisine:"New American / Steakhouse",neighborhood:"Downtown",score:89,price:4,tags:["Steakhouse","Fine Dining","Date Night","Celebrations","Cocktails"],reservation:"OpenTable",awards:"Michelin Recommended",description:"The Fairmont Austin's signature restaurant serving refined New American cuisine with Texas steakhouse sensibilities. Prime steaks, Gulf seafood, and an impressive wine program. The downtown views and polished service make it a celebration destination.",dishes:["Prime Steaks","Gulf Oysters","Seasonal Tasting","Wine Program"],address:"101 Red River St, Austin, TX 78701",phone:"(512) 495-1693",lat:30.2631,lng:-97.7380,instagram:"garrisonaustin",website:"https://www.garrisonaustin.com"});

add({name:"Tiki Tatsu-Ya",cuisine:"Tiki Bar / Asian",neighborhood:"South Lamar",score:87,price:2,tags:["Cocktails","Asian Fusion","Bar","Late Night","Viral"],reservation:"walk-in",group:"Tatsu-Ya",description:"The Tatsu-Ya team's over-the-top tiki bar with theatrical frozen drinks and Asian-inspired bar food. The rum cocktails are elaborate, the decor is immersive, and the pupu platter is massive. One of Austin's most fun bars. Expect a wait on weekends.",dishes:["Tiki Cocktails","Pupu Platter","Frozen Drinks","Asian Bar Snacks"],address:"1300 S Lamar Blvd, Austin, TX 78704",phone:"(512) 814-0361",lat:30.2517,lng:-97.7681,instagram:"tikitatsu_ya",website:"https://www.tikitatsuyaatx.com"});

add({name:"Tsuke Edomae",cuisine:"Japanese Omakase / Sushi",neighborhood:"East Austin",score:91,price:4,tags:["Japanese","Sushi","Omakase","Fine Dining","Date Night","Awards"],reservation:"Tock",awards:"Tastemaker Award Nominee 2026",description:"Intimate edomae-style sushi counter in East Austin focusing on traditional Tokyo-style nigiri technique. Fish sourced from Japan's Tsukiji market and the Gulf. The tsuke (marinated) preparations honor centuries-old technique. A Tastemaker nominee and one of Austin's most refined sushi experiences.",dishes:["Edomae Nigiri","Tsuke Course","Seasonal Sashimi","Sake Pairing"],address:"1601 E 6th St, Austin, TX 78702",phone:"",lat:30.2621,lng:-97.7260,instagram:"tsukeedomae",website:"https://www.tsukeedomae.com",trending:true});

add({name:"Fukumoto",cuisine:"Japanese Izakaya",neighborhood:"East Austin",score:89,price:2,tags:["Japanese","Izakaya","Cocktails","Date Night","Awards"],reservation:"Resy",awards:"Tastemaker Award Nominee 2026",description:"East Austin izakaya from a former Uchi chef serving yakitori, sashimi, and creative Japanese small plates. The robata grill is the centerpiece and the sake/shochu program is the most serious in Austin. Tastemaker nominee and a favorite among chefs.",dishes:["Yakitori","Sashimi","Japanese Small Plates","Sake Flights"],address:"514 Medina St, Austin, TX 78702",phone:"(512) 770-6880",lat:30.2574,lng:-97.7220,instagram:"fukumotoaustin",website:"https://www.fukumotoaustin.com"});

add({name:"Lao'd Bar",cuisine:"Laotian / Southeast Asian",neighborhood:"East Austin",score:88,price:2,tags:["Asian Fusion","Cocktails","Date Night","Awards","Local Favorites"],reservation:"Resy",awards:"Tastemaker Award Nominee 2026",description:"Laotian-inspired bar and restaurant in East Austin from the owners of Whisler's. The menu features Southeast Asian dishes — larb, papaya salad, sticky rice — alongside creative cocktails with Thai and Lao flavors. A unique cultural experience that's become one of East Austin's most celebrated spots.",dishes:["Larb","Papaya Salad","Sticky Rice","Lao Cocktails"],address:"1806 E 12th St, Austin, TX 78702",phone:"",lat:30.2729,lng:-97.7220,instagram:"laodbar",website:"https://www.laodbar.com",trending:true});

add({name:"Eldorado Cafe",cuisine:"Tex-Mex / Brunch",neighborhood:"Mueller",score:86,price:1,tags:["Tex-Mex","Brunch","Casual","Family","Local Favorites"],reservation:"walk-in",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Joe's Bakery & Coffee Shop",cuisine:"Tex-Mex Bakery",neighborhood:"East Austin",score:86,price:1,tags:["Mexican","Breakfast","Bakery","Casual","Local Favorites","Classic"],reservation:"walk-in",awards:"Michelin Recommended",description:"East Austin Tex-Mex bakery and coffee shop that's been feeding the neighborhood since 1962. Breakfast tacos, enchiladas, and fresh pan dulce in a no-frills setting where politicians, musicians, and construction workers share tables. Michelin recommended and a living piece of East Austin history.",dishes:["Breakfast Tacos","Enchiladas","Pan Dulce","Migas"],address:"2305 E 7th St, Austin, TX 78702",phone:"(512) 472-0017",lat:30.2626,lng:-97.7194,instagram:"joesbakeryaustin",website:"https://www.joesbakery.com"});

add({name:"Discada",cuisine:"Mexican / Disco Fries",neighborhood:"East Austin",score:86,price:1,tags:["Mexican","Casual","Late Night","Food Truck","Local Favorites"],reservation:"walk-in",awards:"Michelin Recommended",description:"Michelin-recommended Mexican spot in East Austin serving the iconic discada — a Norteño mixed grill cooked on a repurposed plow disc. The tacos, disco fries, and quesadillas are loaded with flavor. Late-night hours make it an East Side essential. Quality that earned Michelin attention.",dishes:["Discada Plate","Disco Fries","Tacos","Quesadillas"],address:"1319 Rosewood Ave, Austin, TX 78702",phone:"(512) 387-6543",lat:30.2708,lng:-97.7283,instagram:"discadaatx",website:"https://www.discadaatx.com"});

add({name:"Maie Day",cuisine:"Hawaiian / Asian",neighborhood:"South Lamar",score:87,price:2,tags:["Asian Fusion","Hawaiian","Casual","Local Favorites","Awards"],reservation:"walk-in",awards:"Michelin Recommended",description:"Hawaiian-Asian concept from chef Jeff Chanak serving poke, plate lunches, and island-inspired dishes with Austin flair. The spam musubi, garlic shrimp, and shave ice are transportive. Michelin recommended and a refreshing addition to Austin's dining scene.",dishes:["Poke Bowls","Garlic Shrimp","Spam Musubi","Shave Ice"],address:"1610 San Antonio St, Austin, TX 78701",phone:"(512) 945-2188",lat:30.2758,lng:-97.7472,instagram:"maiedayaustin",website:"https://www.maiedayaustin.com"});

add({name:"Apt 115",cuisine:"American / Neighborhood",neighborhood:"East Austin",score:86,price:2,tags:["American","Date Night","Cocktails","Awards"],reservation:"Resy",awards:"Michelin Recommended",description:"Intimate East Austin neighborhood restaurant with a daily-changing menu of New American small plates. The cooking is refined but the vibe is relaxed. The cocktail program is thoughtful and the wine list leans natural. Michelin recommended and a quiet gem.",dishes:["Daily Changing Menu","Small Plates","Natural Wine","Cocktails"],address:"1115 E 6th St, Austin, TX 78702",phone:"(512) 643-1115",lat:30.2631,lng:-97.7289,instagram:"apt115atx",website:"https://www.apt115atx.com"});

add({name:"Tare",cuisine:"Japanese / Noodles",neighborhood:"East Austin",score:87,price:2,tags:["Japanese","Casual","Date Night","Awards"],reservation:"walk-in",awards:"Michelin Recommended",description:"East Austin Japanese noodle shop with Michelin recognition for its handmade udon and soba. The broths are deeply flavored, the tempura is pristine, and the tea program is serious. A more refined ramen alternative. Michelin recommended.",dishes:["Handmade Udon","Soba","Tempura","Japanese Tea"],address:"1200 E 11th St, Suite 160, Austin, TX 78702",phone:"(512) 814-0361",lat:30.2696,lng:-97.7283,instagram:"tareatx",website:"https://www.tareatx.com"});

add({name:"Fish Shop",cuisine:"Seafood / Coastal",neighborhood:"East Austin",score:87,price:2,tags:["Seafood","Casual","Local Favorites","New Opening","Awards"],indicators:["new"],reservation:"walk-in",awards:"Texas Monthly Best New Restaurant 2026",description:"Austin's sole representative on Texas Monthly's 2026 best new list. West Coast-inspired seafood alongside Gulf Coast fare — Dungeness crab cocktails, halibut crudo, and fresh oysters. A much-needed seafood addition to the Austin scene.",dishes:["Dungeness Crab Cocktail","Halibut Crudo","Gulf Oysters","Fish & Chips"],address:"1100 E 6th St, Ste B, Austin, TX 78702",phone:"(512) 580-1044",lat:30.2631,lng:-97.7303,instagram:"fishshopatx",website:"https://www.fishshopaustin.com",trending:true});

add({name:"Soto",cuisine:"Japanese",neighborhood:"South Congress",score:88,price:3,tags:["Japanese","Sushi","Date Night","Cocktails"],reservation:"Resy",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

add({name:"Red Ash",cuisine:"Italian / Wood-Fired",neighborhood:"Downtown",score:89,price:3,tags:["Italian","Fine Dining","Date Night","Cocktails"],reservation:"OpenTable",description:"Already in data.",dishes:[],address:"",lat:0,lng:0,instagram:"",website:""});

// === LIVE MUSIC / NIGHTLIFE ===
add({name:"Mohawk",cuisine:"Live Music Venue",neighborhood:"Red River",score:86,price:1,tags:["Live Music","Entertainment","Bar","Late Night","Iconic"],reservation:"walk-in",description:"Red River Cultural District music venue with indoor and outdoor stages hosting indie, punk, and electronic acts. The rooftop patio has downtown skyline views. A cornerstone of Austin's live music scene and a SXSW staple. The talent booking is consistently excellent.",dishes:["Live Music","Bar","Rooftop"],address:"912 Red River St, Austin, TX 78701",phone:"(512) 666-0877",lat:30.2700,lng:-97.7360,instagram:"mohawkaustin",website:"https://www.mohawkaustin.com"});

add({name:"The White Horse",cuisine:"Honky-Tonk / Bar",neighborhood:"East Austin",score:86,price:1,tags:["Live Music","Bar","Dive Bar","Late Night","Local Favorites"],reservation:"walk-in",description:"East Austin honky-tonk with live country, two-stepping, and cheap Lone Star tallboys. No cover most nights. The most authentic honky-tonk in Austin — real country music, real dancing, real Austin. Open late.",dishes:["Cheap Beer","Live Country Music","Dancing"],address:"500 Comal St, Austin, TX 78702",phone:"(512) 553-6756",lat:30.2621,lng:-97.7270,instagram:"thewhitehorseaustin",website:"https://www.thewhitehorseaustin.com"});

add({name:"Hotel San José",cuisine:"Hotel Bar / Patio",neighborhood:"South Congress",score:86,price:2,tags:["Cocktails","Patio","Date Night","Hotel"],reservation:"walk-in",description:"Liz Lambert's iconic SoCo boutique hotel with a courtyard bar that's one of Austin's most atmospheric drinking spots. Minimalist design, string lights, and craft cocktails under the trees. The lobby bar feels like a private club. A SoCo institution since 2000.",dishes:["Craft Cocktails","Wine","Courtyard Atmosphere"],address:"1316 S Congress Ave, Austin, TX 78704",phone:"(512) 444-7322",lat:30.2492,lng:-97.7493,instagram:"hotelsanjose",website:"https://www.sanjosehotel.com"});

add({name:"Scholz Garten",cuisine:"German Beer Garden",neighborhood:"Downtown",score:85,price:1,tags:["Beer Garden","German","Patio","Classic","Local Favorites","Sports"],reservation:"walk-in",awards:"Texas' oldest beer hall (1866)",description:"Texas' oldest continuously operating business and beer hall since 1866. German food, cold beer, massive patio, and UT Longhorns game-day energy. The sausages and pretzels are solid, but the history and atmosphere are the real draw. A living piece of Austin history.",dishes:["Sausages","Pretzels","Beer","German Plates"],address:"1607 San Jacinto Blvd, Austin, TX 78701",phone:"(512) 474-1958",lat:30.2720,lng:-97.7350,instagram:"scholzgarten",website:"https://www.scholzgarten.com"});

// Write back
html = html.slice(0, a) + JSON.stringify(arr) + html.slice(e);
fs.writeFileSync(file, html, 'utf8');
console.log('Austin: ' + arr.length + ' spots (added ' + added + ')');
console.log('Need', 250 - arr.length, 'more to hit 250');
