// Batch 3: Add parks for all non-Dallas cities (NYC, Chicago, LA, Houston, Austin, SA, Seattle)
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");

const parkStart = html.indexOf("const PARK_DATA");
const parkEnd = html.indexOf("};", parkStart);

const ALL_PARKS = {
  'new york': [
    {id:1,name:"Central Park",neighborhood:"Upper West/East Side",type:"Urban Park",address:"New York, NY 10024",lat:40.7829,lng:-73.9654,score:99,hours:"6AM-1AM daily",admission:"Free",description:"843 acres in the heart of Manhattan. Bethesda Fountain, The Ramble, Bow Bridge, and the Reservoir running loop. The most visited urban park in the US with 42 million annual visitors.",highlights:["Bethesda Fountain & Terrace","The Ramble for bird watching","Reservoir 1.58-mile running loop","Strawberry Fields (John Lennon memorial)","Bow Bridge (most romantic spot)"],insiderTips:["Run the 6-mile loop at sunrise before crowds","Loeb Boathouse rowboats are magical at sunset","The North Woods above 100th St feel like actual wilderness"],bestFor:["Running","Picnic","Date","Photography","Family"]},
    {id:2,name:"The High Line",neighborhood:"Chelsea / Meatpacking",type:"Elevated Park",address:"New York, NY 10011",lat:40.7480,lng:-74.0048,score:95,hours:"7AM-10PM daily",admission:"Free",description:"A 1.45-mile elevated linear park built on a former freight rail line. Stunning architecture views, public art installations, and native plantings 30 feet above street level.",highlights:["Viewing platforms over 10th Ave","Public art installations (rotating)","Native wildflower gardens","Views of Hudson River and city skyline","Connection to Hudson Yards"],insiderTips:["Walk south to north for the best progression","The 10th Ave viewing platform is the best photo spot","Visit on a weekday morning to avoid crowds"],bestFor:["Walking","Photography","Art","Date"]},
    {id:3,name:"Brooklyn Bridge Park",neighborhood:"DUMBO / Brooklyn Heights",type:"Waterfront Park",address:"334 Furman St, Brooklyn NY 11201",lat:40.7024,lng:-73.9967,score:93,hours:"6AM-1AM daily",admission:"Free",description:"85 acres of waterfront park along the East River with jaw-dropping Manhattan skyline views. Includes Jane's Carousel, kayaking, and the famous Pier 1 lawn.",highlights:["Manhattan skyline views","Jane's Carousel (1922 vintage)","Free kayaking in summer","Pier 6 beach and volleyball","DUMBO access and shops"],insiderTips:["Sunset from Pier 1 lawn is the best free view in NYC","Walk across Brooklyn Bridge then down to the park","Free kayaking at Pier 2 on weekends in summer"],bestFor:["Views","Family","Kayaking","Photography"]},
    {id:4,name:"Prospect Park",neighborhood:"Park Slope / Brooklyn",type:"Urban Park",address:"Brooklyn, NY 11215",lat:40.6602,lng:-73.9690,score:91,hours:"5AM-1AM daily",admission:"Free",description:"585 acres designed by Olmsted and Vaux (same architects as Central Park). Brooklyn's backyard with a lake, zoo, farmers market, and the Long Meadow — the longest unbroken meadow in any US city.",highlights:["Long Meadow (90 acres of open green)","Prospect Park Lake and boathouse","Brooklyn Botanic Garden adjacent","Saturday Farmers Market at Grand Army Plaza","Free concerts at Bandshell in summer"],insiderTips:["The Long Meadow on a sunny Saturday is peak Brooklyn","Grand Army Plaza Farmers Market is one of NYC's best","Less crowded than Central Park with more nature"],bestFor:["Running","Picnic","Family","Dog Walking"]}
  ],
  'chicago': [
    {id:1,name:"Millennium Park",neighborhood:"The Loop",type:"Urban Park",address:"201 E Randolph St, Chicago IL 60602",lat:41.8826,lng:-87.6226,score:97,hours:"6AM-11PM daily",admission:"Free",description:"24.5 acres in the heart of downtown featuring Cloud Gate (The Bean), Crown Fountain, and the Jay Pritzker Pavilion. Chicago's most visited attraction with free summer concerts.",highlights:["Cloud Gate (The Bean) — most photographed spot in Chicago","Crown Fountain — two 50-ft LED towers with faces","Jay Pritzker Pavilion — free concerts all summer","Lurie Garden — hidden 2.5-acre garden","Ice skating rink in winter"],insiderTips:["Free concerts at Pritzker Pavilion Thursday evenings in summer — BYOB picnic","The Bean is least crowded at sunrise","Lurie Garden behind the Pavilion is a hidden gem most tourists miss"],bestFor:["Photography","Events","Family","Date"]},
    {id:2,name:"Lincoln Park",neighborhood:"Lincoln Park",type:"Urban Park",address:"Chicago, IL 60614",lat:41.9214,lng:-87.6352,score:94,hours:"6AM-11PM daily",admission:"Free",description:"1,208 acres stretching along 7 miles of Lake Michigan shoreline. Home to Lincoln Park Zoo (free!), North Pond, the Nature Boardwalk, and some of Chicago's best running paths.",highlights:["Lincoln Park Zoo — free admission year-round","North Pond restaurant and nature views","Lakefront Trail — 18 miles of running/biking","Alfred Caldwell Lily Pool — hidden oasis","Theater on the Lake"],insiderTips:["The zoo is free — one of the last free zoos in the US","Run the lakefront path at sunrise for empty trails","North Pond Nature Boardwalk is the most peaceful spot"],bestFor:["Running","Family","Zoo","Photography"]},
    {id:3,name:"Grant Park / Buckingham Fountain",neighborhood:"The Loop",type:"Urban Park",address:"337 E Randolph St, Chicago IL 60601",lat:41.8758,lng:-87.6189,score:91,hours:"6AM-11PM daily",admission:"Free",description:"Chicago's front yard spanning 313 acres along the lakefront. Home to Buckingham Fountain (one of the world's largest), the Art Institute, and the site of Lollapalooza every August.",highlights:["Buckingham Fountain — 20-min light show at dusk","Art Institute of Chicago on the western edge","Lollapalooza venue (August)","Museum Campus connection (Field Museum, Shedd, Adler)","Lakefront running path"],insiderTips:["Buckingham Fountain light show at dusk is free and stunning","Walk from here to Museum Campus for 3 world-class museums","Lollapalooza takes over in August — plan accordingly"],bestFor:["Walking","Events","Photography","Museums"]}
  ],
  'los angeles': [
    {id:1,name:"Griffith Park",neighborhood:"Los Feliz",type:"Urban Park",address:"4730 Crystal Springs Dr, Los Angeles CA 90027",lat:40.6713,lng:-118.3025,score:96,hours:"5AM-10:30PM daily",admission:"Free",description:"4,310 acres — LA's largest park. Home to the Griffith Observatory with free entry and the best views of the Hollywood Sign and LA basin. Hiking trails from easy to strenuous.",highlights:["Griffith Observatory — free admission, best views in LA","Hollywood Sign views from multiple trails","Los Angeles Zoo","Greek Theatre for concerts","Bronson Cave (the Batcave)"],insiderTips:["Hike to the observatory at sunset for golden hour views","Park on Vermont Ave to avoid traffic on the east side","The trail to the Hollywood Sign via Brush Canyon is the quietest route"],bestFor:["Hiking","Photography","Views","Family"]},
    {id:2,name:"Santa Monica Beach & Pier",neighborhood:"Santa Monica",type:"Beach / Pier",address:"200 Santa Monica Pier, Santa Monica CA 90401",lat:34.0094,lng:-118.4973,score:94,hours:"Open 24 hours",admission:"Free",description:"The iconic Santa Monica Pier with its Pacific Park amusement rides, aquarium, and the endpoint of Route 66. Three miles of wide sandy beach with the best sunset in LA.",highlights:["Pacific Park amusement rides on the pier","Route 66 endpoint sign","Muscle Beach outdoor gym","Santa Monica Bike Path (22 miles to Torrance)","Wednesday Farmers Market (where LA chefs shop)"],insiderTips:["The Wednesday Farmers Market on Arizona Ave is where every LA chef shops","Bike the path south to Venice Beach for the full experience","Sunset from the pier is peak LA"],bestFor:["Beach","Family","Cycling","Sunset"]},
    {id:3,name:"Runyon Canyon",neighborhood:"Hollywood",type:"Hiking Trail",address:"2000 N Fuller Ave, Los Angeles CA 90046",lat:34.1066,lng:-118.3488,score:91,hours:"6AM-9PM daily",admission:"Free",description:"160 acres of hiking trails in the Hollywood Hills with panoramic views of the LA basin and the Hollywood Sign. The most popular hike in LA — where celebrities and their dogs go.",highlights:["Panoramic LA views from the summit","Hollywood Sign views","Dog-friendly off-leash areas","Multiple trail difficulty levels","Celebrity sightings"],insiderTips:["Go before 8 AM to beat the crowds and heat","The Fuller Ave entrance is less crowded than the Vista entrance","Bring water — there's no shade on the upper trails"],bestFor:["Hiking","Dog Walking","Views","Exercise"]}
  ],
  'houston': [
    {id:1,name:"Hermann Park",neighborhood:"Museum District",type:"Urban Park",address:"6001 Fannin St, Houston TX 77030",lat:29.7188,lng:-95.3903,score:94,hours:"6AM-11PM daily",admission:"Free (attractions vary)",description:"445 acres in the heart of Houston's Museum District. Home to the Houston Zoo, Miller Outdoor Theatre (free shows), Japanese Garden, and a miniature train. Houston's most beloved green space.",highlights:["Houston Zoo","Miller Outdoor Theatre — free performances year-round","McGovern Centennial Gardens","Japanese Garden","Miniature train ride through the park"],insiderTips:["Miller Outdoor Theatre has free tickets — arrive early for hill seating","The Japanese Garden is the most peaceful spot in Houston","Walk from here to the Menil Collection in 15 minutes"],bestFor:["Family","Culture","Running","Picnic"]},
    {id:2,name:"Buffalo Bayou Park",neighborhood:"Downtown / Montrose",type:"Urban Park / Trail",address:"1800 Allen Pkwy, Houston TX 77019",lat:29.7604,lng:-95.3897,score:93,hours:"Open 24 hours",admission:"Free",description:"160 acres along Buffalo Bayou connecting downtown to the west side. Hike-and-bike trails, kayak rentals, a dog park, and the Barbara Fish Daniel Nature Play Area. Houston's best running path.",highlights:["Johnny Steele Dog Park — Houston's best","Kayak and bike rentals at Lost Lake","The Waugh Drive bat colony (250,000 bats at sunset!)","Barbara Fish Daniel Nature Play Area for kids","Rosemont Pedestrian Bridge views"],insiderTips:["Watch 250,000 bats emerge from under the Waugh Drive bridge at sunset","The 2-mile loop from Sabine to Shepherd is perfect for a run","Rent a kayak at Lost Lake for a unique Houston experience"],bestFor:["Running","Dog Walking","Kayaking","Sunset"]},
    {id:3,name:"Discovery Green",neighborhood:"Downtown",type:"Urban Park",address:"1500 McKinney St, Houston TX 77010",lat:29.7521,lng:-95.3575,score:90,hours:"6AM-11PM daily",admission:"Free",description:"12 acres of green space in downtown Houston adjacent to the convention center. Free concerts, outdoor movies, an interactive fountain, and ice skating in winter. Houston's urban living room.",highlights:["Free concerts and movie nights","Interactive fountain for kids","Kinder Lake with kayaking","Ice skating in winter","Adjacent to GRB Convention Center"],insiderTips:["Check the events calendar — there's almost always something free happening","The Grove restaurant overlooks the park — great for lunch","Walk to Minute Maid Park for Astros games"],bestFor:["Events","Family","Downtown","Quick Break"]}
  ],
  'austin': [
    {id:1,name:"Zilker Park",neighborhood:"Zilker",type:"Urban Park",address:"2100 Barton Springs Rd, Austin TX 78704",lat:30.2669,lng:-97.7729,score:96,hours:"5AM-10PM daily",admission:"Free (Barton Springs $9 adults)",description:"351 acres along Lady Bird Lake and Barton Creek. Home to Barton Springs Pool, ACL Festival, the Zilker Botanical Garden, and Austin's most popular trail system. The soul of Austin's outdoor culture.",highlights:["Barton Springs Pool — 68°F spring-fed swimming year-round","ACL Music Festival venue (October)","Zilker Botanical Garden","Barton Creek Greenbelt access","Lady Bird Lake hike-and-bike trail"],insiderTips:["Barton Springs is $9 but worth every penny — go at sunset for locals-only vibes","The Greenbelt access from here is the best swimming hole trail in Austin","Arrive early for ACL — single-day tickets sell out"],bestFor:["Swimming","Hiking","Festivals","Family"]},
    {id:2,name:"Lady Bird Lake Trail",neighborhood:"Downtown / South Austin",type:"Trail",address:"920 W Riverside Dr, Austin TX 78704",lat:30.2588,lng:-97.7517,score:95,hours:"Open 24 hours",admission:"Free",description:"A 10-mile hike-and-bike trail circling Lady Bird Lake in the heart of Austin. Kayak and paddleboard rentals, running paths, and stunning downtown skyline views. Austin's most popular outdoor activity.",highlights:["10-mile loop trail (paved)","Kayak and SUP rentals at multiple docks","Pfluger Pedestrian Bridge views","Bat colony under Congress Bridge (1.5M bats at sunset)","Boardwalk section on south shore"],insiderTips:["Watch 1.5 million bats emerge from Congress Bridge at sunset (March-October)","The boardwalk section on the south shore is the newest and least crowded","Rent a kayak from Rowing Dock for the best experience"],bestFor:["Running","Kayaking","Cycling","Sunset"]},
    {id:3,name:"Mount Bonnell",neighborhood:"West Austin",type:"Scenic Overlook",address:"3800 Mt Bonnell Rd, Austin TX 78731",lat:30.3210,lng:-97.7734,score:92,hours:"5AM-10PM daily",admission:"Free",description:"The highest point in Austin at 775 feet with panoramic views of Lake Austin, the Hill Country, and the 360 Bridge. A short but steep 102-step climb to the summit.",highlights:["Panoramic Hill Country views","Lake Austin views from the summit","Short 102-step climb","Sunset viewing — one of Austin's best","Picnic areas at the top"],insiderTips:["Go at sunset — the views are spectacular","It's only 102 steps but they're steep — wear good shoes","Less crowded on weekday mornings"],bestFor:["Views","Sunset","Photography","Quick Hike"]},
    {id:4,name:"Barton Creek Greenbelt",neighborhood:"South Austin",type:"Nature Trail",address:"3755 Capital of TX Hwy, Austin TX 78746",lat:30.2613,lng:-97.8028,score:93,hours:"5AM-10PM daily",admission:"Free",description:"12.6 miles of trails through limestone canyons with swimming holes, rock climbing, and mountain biking. The best nature escape within Austin city limits. Sculpture Falls and Twin Falls are the top swimming holes.",highlights:["Sculpture Falls swimming hole","Twin Falls (easy access)","Rock climbing at Seismic Wall","Mountain biking trails","Limestone canyon scenery"],insiderTips:["Check water levels before going — swimming holes dry up in drought","Sculpture Falls trail is 3 miles round trip — bring water","Go after rain for the best waterfall flow"],bestFor:["Swimming","Hiking","Rock Climbing","Nature"]}
  ],
  'san antonio': [
    {id:1,name:"San Antonio River Walk",neighborhood:"Downtown",type:"Urban Waterway / Park",address:"849 E Commerce St, San Antonio TX 78205",lat:29.4241,lng:-98.4936,score:97,hours:"Open 24 hours",admission:"Free",description:"15 miles of walkways along the San Antonio River, one level below street grade. Lined with restaurants, bars, hotels, and shops. The most visited attraction in Texas and San Antonio's defining landmark.",highlights:["Restaurant-lined river channel downtown","River barges and boat tours","Museum Reach extension to the Pearl","Mission Reach to the historic missions","Holiday River Parade and lights (December)"],insiderTips:["Walk north on Museum Reach to the Pearl — it's beautiful and tourist-free","The holiday lights in December are magical — go on a weeknight","Eat at restaurants one block OFF the River Walk for better food and prices"],bestFor:["Walking","Date","Tourist Essential","Dining"]},
    {id:2,name:"San Antonio Missions National Historical Park",neighborhood:"South Side",type:"National Park / UNESCO Site",address:"6701 San Jose Dr, San Antonio TX 78214",lat:29.3601,lng:-98.4808,score:95,hours:"9AM-5PM daily",admission:"Free",description:"Four 18th-century Spanish colonial missions along the San Antonio River — a UNESCO World Heritage Site. The only UNESCO site in Texas. Includes Mission San José (the 'Queen of the Missions').",highlights:["Mission San José — the largest and best preserved","Mission Concepción — oldest unrestored stone church in US","Mission Reach trail connecting all four","UNESCO World Heritage Site designation","Free ranger-led tours daily"],insiderTips:["Bike the Mission Reach trail to visit all four — it's flat and beautiful","Mission San José has the best rose window in colonial architecture","Go early morning for the best photography light"],bestFor:["History","Cycling","Photography","Culture"]},
    {id:3,name:"Brackenridge Park",neighborhood:"Midtown",type:"Urban Park",address:"3910 N St Mary's St, San Antonio TX 78212",lat:29.4585,lng:-98.4737,score:89,hours:"5AM-11PM daily",admission:"Free (zoo and attractions separate)",description:"343 acres along the San Antonio River, home to the San Antonio Zoo, Japanese Tea Garden, Witte Museum, and the DoSeum. San Antonio's oldest park, established in 1899.",highlights:["San Antonio Zoo","Japanese Tea Garden — free admission","Witte Museum","DoSeum children's museum","Sunken Garden Theatre for concerts"],insiderTips:["The Japanese Tea Garden is free and absolutely stunning","Walk from the zoo to the Witte Museum along the river","The Sunken Garden Theatre has free concerts in summer"],bestFor:["Family","Zoo","Gardens","Culture"]}
  ],
  'seattle': [
    {id:1,name:"Discovery Park",neighborhood:"Magnolia",type:"Urban Park / Nature",address:"3801 Discovery Park Blvd, Seattle WA 98199",lat:47.6573,lng:-122.4052,score:94,hours:"4AM-11:30PM daily",admission:"Free",description:"534 acres on a bluff overlooking Puget Sound — Seattle's largest park. Old-growth forest, beaches, a lighthouse, and views of the Olympic Mountains. Feels like wilderness inside the city.",highlights:["West Point Lighthouse on the beach","Old-growth forest trails","Puget Sound and Olympic Mountain views","2.8-mile Loop Trail","Tide pools at low tide"],insiderTips:["The Loop Trail is 2.8 miles — allow 2 hours for the full experience","Check tide charts and visit the lighthouse beach at low tide for tide pools","The south bluff has the best Olympic Mountain views"],bestFor:["Hiking","Nature","Views","Solitude"]},
    {id:2,name:"Kerry Park",neighborhood:"Queen Anne",type:"Viewpoint / Park",address:"211 W Highland Dr, Seattle WA 98119",lat:47.6295,lng:-122.3597,score:93,hours:"Open 24 hours",admission:"Free",description:"A tiny park on Queen Anne Hill with the single most iconic view of the Seattle skyline, Space Needle, and Mount Rainier. Every postcard photo of Seattle is taken from here.",highlights:["The iconic Seattle skyline photo spot","Space Needle framed against Mt. Rainier","Best at sunset and blue hour","Night photography of city lights"],insiderTips:["Sunset on a clear day when Rainier is visible — this is the shot","It's tiny — arrive 30 min before sunset for a spot","Walk down to Marshall Park one block below for a less crowded alternative"],bestFor:["Photography","Views","Sunset","Quick Visit"]},
    {id:3,name:"Gas Works Park",neighborhood:"Wallingford",type:"Urban Park",address:"2101 N Northlake Way, Seattle WA 98103",lat:47.6456,lng:-122.3344,score:91,hours:"4AM-11:30PM daily",admission:"Free",description:"20 acres on the north shore of Lake Union with remnants of the old Seattle Gas Light Company plant. The rusting industrial structures against the skyline are uniquely Seattle. Great kite flying hill.",highlights:["Industrial ruins as public art","Lake Union and skyline views","Kite flying on the great mound","4th of July fireworks viewing spot","Play barn for kids in former compressor building"],insiderTips:["The great mound is the best spot for kite flying in Seattle","4th of July fireworks are watched from here — arrive by noon","Walk or bike here via the Burke-Gilman Trail"],bestFor:["Views","Kite Flying","Photography","Picnic"]},
    {id:4,name:"Volunteer Park",neighborhood:"Capitol Hill",type:"Urban Park",address:"1247 15th Ave E, Seattle WA 98112",lat:47.6303,lng:-122.3155,score:90,hours:"4AM-11:30PM daily",admission:"Free (conservatory $4)",description:"48.3 acres on Capitol Hill featuring the Seattle Asian Art Museum, a Victorian conservatory, and a water tower with 360-degree views. Designed by the Olmsted Brothers (sons of Central Park's designer).",highlights:["Water tower with 360-degree city views","Volunteer Park Conservatory (Victorian greenhouse)","Seattle Asian Art Museum","Dahlia garden","Olmsted Brothers landscape design"],insiderTips:["Climb the water tower for free 360-degree views — 107 steps","The conservatory is $4 and worth it — tropical plants year-round","Walk from here to Capitol Hill restaurants in 10 minutes"],bestFor:["Views","Gardens","Art","Walking"]}
  ]
};

// Insert all park data
let insertText = "";
Object.entries(ALL_PARKS).forEach(([city, parks]) => {
  insertText += ",\n  '" + city + "': " + JSON.stringify(parks);
});

html = html.slice(0, parkEnd) + insertText + "\n" + html.slice(parkEnd);

fs.writeFileSync("index.html", html);
let total = 0;
Object.entries(ALL_PARKS).forEach(([city, parks]) => {
  console.log("  PARK_DATA." + city + ": " + parks.length);
  total += parks.length;
});
console.log("Total parks added: " + total);
console.log("Done!");
