// Batch 2: Add malls/shopping for Houston, Austin, San Antonio, Seattle
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");

const mallStart = html.indexOf("const MALL_DATA");
const mallEnd = html.indexOf("};", mallStart);

const HOUSTON_MALLS = [
  {id:1,name:"The Galleria",tagline:"The Largest Mall in Texas.",tier:"Luxury",neighborhood:"Galleria / Uptown",address:"5085 Westheimer Rd, Houston TX 77056",lat:29.7390,lng:-95.4612,instagram:"@houstonGalleria",hours:"Mon-Sat 10AM-9PM, Sun 11AM-7PM",parking:"Free — 14,000 spaces",score:95,emoji:"🛍",vibe:"2.4 million sq ft with 400+ stores, an ice rink, and two Westin hotels. The largest mall in Texas and 7th largest in the US.",about:"Houston's retail crown jewel since 1970. Four levels anchored by Neiman Marcus, Nordstrom, Saks Fifth Avenue, and Macy's. The full-size ice rink in the center is iconic.",anchors:["Neiman Marcus","Nordstrom","Saks Fifth Avenue","Macy's"],mustVisit:[{name:"Neiman Marcus",note:"Flagship store — excellent shoe department"},{name:"Ice Rink",note:"Full-size rink in the mall center — open year round"},{name:"Tiffany & Co.",note:"Standalone boutique on the luxury wing"}],dining:[{name:"Nobu Houston",type:"Japanese",note:"Inside the Galleria — excellent sushi"},{name:"The Cheesecake Factory",type:"American",note:"Always packed — arrive off-peak"},{name:"True Food Kitchen",type:"Healthy",note:"Great lunch spot between shopping"}],tips:["Park at the Nordstrom garage for easiest luxury wing access","The ice rink is free to watch — skate rentals available","Go on weekday mornings to avoid weekend crowds"],bestFor:["Luxury Shopping","Family","Rainy Day"]},
  {id:2,name:"River Oaks District",tagline:"Houston's Most Stylish Shopping.",tier:"Ultra Luxury",neighborhood:"River Oaks",address:"4444 Westheimer Rd, Houston TX 77027",lat:29.7379,lng:-95.4449,instagram:"@riveroaksdistrict",hours:"Mon-Sat 10AM-7PM, Sun 12-6PM",parking:"Free valet and self-parking",score:93,emoji:"💎",vibe:"An open-air luxury district with Hermès, Tom Ford, and Dior. Houston's answer to Rodeo Drive.",about:"Developed in 2015, this open-air luxury center brought true high-fashion retail to Houston. Anchored by Cartier, Hermès, and Tom Ford with excellent dining options.",anchors:["Hermès","Tom Ford","Dior","Cartier"],mustVisit:[{name:"Hermès",note:"Beautiful standalone boutique"},{name:"Stag Provisions",note:"Best men's store in Houston"},{name:"Warby Parker",note:"Flagship with eye exams"}],dining:[{name:"Le Jardinier",type:"French",note:"Michelin-starred French — inside the district"},{name:"Loch Bar",type:"Seafood",note:"Raw bar and craft cocktails"},{name:"Toulouse",type:"French",note:"French café with excellent pastries"}],tips:["Free valet makes the experience seamless","Best on a weekday afternoon for a leisurely browse","Combine with dinner at Le Jardinier"],bestFor:["Luxury Shopping","Date","Design Lovers"]},
  {id:3,name:"Rice Village",tagline:"Houston's Original Walkable Shopping District.",tier:"Mid-Range",neighborhood:"Rice University / West University",address:"2500 Rice Blvd, Houston TX 77005",lat:29.7157,lng:-95.4103,instagram:"@ricevillagedistrict",hours:"Varies by store — generally 10AM-9PM",parking:"Free street parking and garages",score:88,emoji:"🎓",vibe:"A walkable neighborhood shopping district near Rice University. Independent boutiques, bookstores, and college-town energy.",about:"Houston's oldest shopping district, dating to the 1930s. A mix of local boutiques, national brands, and excellent restaurants surrounding Rice University campus.",anchors:["Half Price Books","Warby Parker","Vans"],mustVisit:[{name:"Half Price Books",note:"Houston's best used bookstore"},{name:"Local boutiques on Rice Blvd",note:"Independent shops you won't find elsewhere"},{name:"Rice University campus",note:"Walk through the beautiful campus"}],dining:[{name:"Uchi Houston",type:"Japanese",note:"James Beard — Houston's best sushi"},{name:"Morningstar",type:"Vietnamese",note:"Excellent pho and banh mi"},{name:"Local Foods",type:"American",note:"Farm-to-table fast casual"}],tips:["Park on University Blvd for free street parking","Walk through Rice University's campus — it's gorgeous","Combine with a visit to the Menil Collection nearby"],bestFor:["Casual Shopping","College Town","Bookworms"]}
];

const AUSTIN_MALLS = [
  {id:1,name:"South Congress (SoCo)",tagline:"Austin's Most Iconic Shopping Street.",tier:"Indie/Eclectic",neighborhood:"South Congress",address:"1400 S Congress Ave, Austin TX 78704",lat:30.2490,lng:-97.7498,instagram:"@socoshopping",hours:"Generally 10AM-7PM, varies by shop",parking:"Free street parking (limited) or paid lots",score:95,emoji:"🤠",vibe:"Austin's signature shopping street. Vintage clothing, local designers, food trucks, and the iconic 'I Love You So Much' mural. The heart of Keep Austin Weird.",about:"South Congress Avenue from the bridge to Oltorf is Austin's most walkable and iconic strip. Local boutiques, vintage shops, boot stores, and street food vendors line both sides. Home to Hotel Saint Cecilia, Hotel San José, and some of Austin's best restaurants.",anchors:["Allen's Boots","Uncommon Objects","Lucy in Disguise"],mustVisit:[{name:"Allen's Boots",note:"Iconic boot shop since 1977 — try on a pair"},{name:"Uncommon Objects",note:"Curated antiques and oddities — you'll spend hours"},{name:"'I Love You So Much' mural",note:"At Jo's Coffee — Austin's most Instagrammed spot"}],dining:[{name:"Home Slice Pizza",type:"Pizza",note:"New York-style slices with a huge patio"},{name:"Torchy's Tacos",type:"Tacos",note:"Austin original — the Trailer Park Trashy is iconic"},{name:"Jo's Coffee",type:"Coffee",note:"The OG SoCo coffee spot with the famous mural"}],tips:["Go on a Saturday for the best people-watching","Street parking is tough — use the paid lot behind Jo's","Walk the whole strip from the bridge to Oltorf for the full experience"],bestFor:["Austin Culture","Vintage Shopping","People Watching","Instagram"]},
  {id:2,name:"Domain Northside",tagline:"Austin's Upscale Open-Air District.",tier:"Luxury",neighborhood:"North Austin / Domain",address:"11600 Century Oaks Terrace, Austin TX 78758",lat:30.4022,lng:-97.7255,instagram:"@thedomainnorthside",hours:"Mon-Sat 10AM-9PM, Sun 12-6PM",parking:"Free — abundant garage and surface parking",score:89,emoji:"🛍",vibe:"Austin's most upscale outdoor shopping center. Louis Vuitton, Tiffany, Restoration Hardware and a growing restaurant scene.",about:"Domain Northside brought luxury retail to Austin with an open-air lifestyle center format. Anchored by Nordstrom, Louis Vuitton, and Restoration Hardware, with multiple dining options.",anchors:["Nordstrom","Louis Vuitton","Restoration Hardware","Tiffany & Co."],mustVisit:[{name:"RH Austin",note:"Three-story Restoration Hardware with rooftop restaurant"},{name:"Nordstrom",note:"Full-line store with excellent shoe department"},{name:"Outdoor art installations",note:"Walkable public art throughout"}],dining:[{name:"North Italia",type:"Italian",note:"Handmade pasta and wood-fired dishes"},{name:"Flower Child",type:"Healthy",note:"Health-forward bowls and salads"},{name:"True Food Kitchen",type:"Healthy",note:"Seasonal menu with great cocktails"}],tips:["RH Rooftop restaurant is a hidden gem — great for brunch","Park at the Nordstrom garage for shade","Combine with dinner at one of the Domain restaurants"],bestFor:["Luxury Shopping","Suburban","Brunch"]},
  {id:3,name:"2nd Street District",tagline:"Downtown Austin's Walkable Village.",tier:"Upscale",neighborhood:"Downtown",address:"200 W 2nd St, Austin TX 78701",lat:30.2640,lng:-97.7470,instagram:"@2ndstreetdistrict",hours:"Varies by store",parking:"Street meters and city garages",score:87,emoji:"🏙",vibe:"A walkable downtown shopping and dining district between Congress Ave and Lamar. Local boutiques, restaurants, and Austin City Hall.",about:"A pedestrian-friendly urban village in the heart of downtown Austin. Mix of local and national retailers with outdoor dining patios and proximity to Lady Bird Lake.",anchors:["Whole Foods Market (flagship)","lululemon","Marine Layer"],mustVisit:[{name:"Whole Foods Flagship",note:"The original — massive rooftop and bar"},{name:"Local boutiques",note:"By George, Service Menswear"},{name:"Austin Public Library",note:"Stunning modern architecture — free rooftop garden"}],dining:[{name:"Aba Austin",type:"Mediterranean",note:"Rooftop patio with Congress Ave views"},{name:"Second Bar + Kitchen",type:"American",note:"Chef David Bull's downtown spot"},{name:"Whole Foods Rooftop Bar",type:"Bar",note:"Craft beer with Lady Bird Lake views"}],tips:["The Whole Foods flagship here is the original — worth exploring","Austin Public Library rooftop garden is free and beautiful","Walk to Lady Bird Lake trail in 5 minutes"],bestFor:["Downtown","Walkable","Local Boutiques"]}
];

const SA_MALLS = [
  {id:1,name:"The Pearl",tagline:"San Antonio's Culinary & Cultural Heart.",tier:"Market / Mixed-Use",neighborhood:"Pearl District",address:"303 Pearl Pkwy, San Antonio TX 78215",lat:29.4428,lng:-98.4796,instagram:"@atpearl",hours:"Shops vary; Farmers Market Sat 9AM-1PM",parking:"Free in Pearl garages",score:96,emoji:"✨",vibe:"A transformed 1880s brewery complex that's now the culinary and cultural heart of San Antonio. Restaurants, shops, the CIA culinary school, Hotel Emma, and the Saturday Farmers Market.",about:"The Pearl is San Antonio's most important development — a 22-acre mixed-use district built in the historic Pearl Brewery complex. Home to Hotel Emma, Bakery Lorraine, the Culinary Institute of America, and the best Saturday Farmers Market in Texas.",anchors:["Hotel Emma","Bakery Lorraine","CIA San Antonio","Farmers Market"],mustVisit:[{name:"Saturday Farmers Market",note:"Best farmers market in Texas — arrive by 9AM"},{name:"Bakery Lorraine",note:"James Beard semifinalist pastries"},{name:"Hotel Emma",note:"Tour the lobby even if you don't stay — stunning brewery conversion"}],dining:[{name:"Bakery Lorraine",type:"Bakery",note:"James Beard semifinalist — get the macarons"},{name:"La Gloria",type:"Mexican",note:"Chef Johnny Hernandez's street food"},{name:"Boiler House",type:"Texas Grill",note:"Wood-fired in the old brewery boiler house"}],tips:["The Saturday Farmers Market is the best in Texas — go early","Walk the River Walk path north from downtown to get here","The CIA campus offers cooking classes open to the public"],bestFor:["Foodie","Farmers Market","Architecture","Date"]},
  {id:2,name:"The Shops at La Cantera",tagline:"Hill Country Luxury Shopping.",tier:"Luxury",neighborhood:"La Cantera / Far North",address:"15900 La Cantera Pkwy, San Antonio TX 78256",lat:29.6000,lng:-96.6200,instagram:"@shopsatlacantera",hours:"Mon-Sat 10AM-9PM, Sun 12-6PM",parking:"Free — abundant",score:90,emoji:"🛍",vibe:"San Antonio's premier outdoor luxury shopping center nestled in the Texas Hill Country. 165+ stores with mountain views.",about:"An open-air shopping center with Hill Country views and 165+ stores including Nordstrom, Neiman Marcus, and Louis Vuitton. The most upscale shopping experience in San Antonio.",anchors:["Nordstrom","Neiman Marcus","Dillard's","Dave & Buster's"],mustVisit:[{name:"Nordstrom",note:"Full-line store with café"},{name:"Neiman Marcus",note:"Last Call + full-line in one center"},{name:"Outdoor fountains",note:"Beautiful evening atmosphere"}],dining:[{name:"J. Alexander's",type:"American",note:"Upscale American grill"},{name:"Yard House",type:"American",note:"100+ beers on tap"},{name:"Kona Grill",type:"Asian-American",note:"Sushi and happy hour"}],tips:["Go in the evening for the best atmosphere with the fountain show","Park near Nordstrom for the luxury wing","Combine with a visit to Six Flags Fiesta Texas next door"],bestFor:["Luxury Shopping","Family","Hill Country"]},
  {id:3,name:"North Star Mall",tagline:"The Giant Boots Mall.",tier:"Mid-Range",neighborhood:"North Central",address:"7400 San Pedro Ave, San Antonio TX 78216",lat:29.5178,lng:-98.4868,instagram:"@northstarmall",hours:"Mon-Sat 10AM-9PM, Sun 12-6PM",parking:"Free — 7,000 spaces",score:83,emoji:"👢",vibe:"Famous for the giant cowboy boots sculpture at the entrance — a San Antonio landmark. Classic enclosed mall with 200+ stores.",about:"North Star Mall is best known for the 40-foot-tall cowboy boots at the entrance, created by artist Bob Wade. It's a San Antonio landmark and Instagram stop. Inside, 200+ stores anchored by Macy's and Dillard's.",anchors:["Macy's","Dillard's","JCPenney"],mustVisit:[{name:"Giant Boots Sculpture",note:"40-foot cowboy boots — the most photographed thing in SA"},{name:"Macy's",note:"Anchor store with wide selection"},{name:"Food Court",note:"Surprisingly good for a mall food court"}],dining:[{name:"The Cheesecake Factory",type:"American",note:"Reliable crowd-pleaser"},{name:"P.F. Chang's",type:"Asian",note:"Solid Chinese-American"},{name:"Food Court",type:"Various",note:"Quick lunch options"}],tips:["Stop for a photo with the boots even if you don't shop","It's a classic mall — come for the boots, stay for AC in summer","Better shopping options at La Cantera, but the boots are iconic"],bestFor:["Instagram","Tourist","Classic Mall"]}
];

const SEATTLE_MALLS = [
  {id:1,name:"Pike Place Market",tagline:"The Soul of Seattle Since 1907.",tier:"Market",neighborhood:"Downtown Waterfront",address:"85 Pike St, Seattle WA 98101",lat:47.6097,lng:-122.3422,instagram:"@piloeplacemarket",hours:"Daily 9AM-6PM (restaurants vary)",parking:"Pike Place Market Garage — $5 early bird",score:98,emoji:"🐟",vibe:"America's oldest continuously operating farmers market. Fish throwing, flower stalls, the original Starbucks, and 500+ vendors across 9 acres.",about:"Pike Place Market has been Seattle's public market since 1907. Over 500 vendors sell fresh produce, fish, flowers, crafts, and food. It's a working market, not a tourist attraction — though 10 million people visit annually.",anchors:["Pike Place Fish Market","Original Starbucks","Rachel the Pig (bronze)"],mustVisit:[{name:"Pike Place Fish Market",note:"The famous fish throwers — don't miss it"},{name:"Original Starbucks",note:"The very first one — 1971"},{name:"Piroshky Piroshky",note:"Russian pastries — the line is worth it"}],dining:[{name:"Pike Place Chowder",type:"Seafood",note:"Award-winning chowder in a bread bowl"},{name:"Matt's in the Market",type:"Pacific NW",note:"Fine dining overlooking the market"},{name:"Beecher's Handmade Cheese",type:"Cheese",note:"Watch them make cheese — the mac & cheese is famous"}],tips:["Go before 9 AM to see the market like locals do","The DownUnder levels have hidden shops and oddities","Park at the Pike Place Garage and validate at market vendors"],bestFor:["Essential Seattle","Foodie","Local Culture","Tourist"]},
  {id:2,name:"University Village",tagline:"Seattle's Outdoor Shopping Village.",tier:"Upscale",neighborhood:"University District",address:"2623 NE University Village St, Seattle WA 98105",lat:47.6620,lng:-122.2975,instagram:"@uaborillage",hours:"Mon-Sat 10AM-9PM, Sun 11AM-6PM",parking:"Free — abundant surface parking",score:88,emoji:"🛍",vibe:"An open-air upscale shopping center near UW campus. Apple, Warby Parker, Din Tai Fung, and excellent people-watching.",about:"A landscaped outdoor shopping village near the University of Washington. Mix of national brands and local boutiques with great dining including Din Tai Fung.",anchors:["Apple","Restoration Hardware","Crate & Barrel","QFC"],mustVisit:[{name:"Apple Store",note:"Bright, airy flagship"},{name:"Din Tai Fung",note:"Best xiao long bao in Seattle"},{name:"Paper Source",note:"Stationery and gift shop"}],dining:[{name:"Din Tai Fung",type:"Taiwanese",note:"Lines daily for soup dumplings — worth the wait"},{name:"Hokkaido Ramen Santouka",type:"Japanese",note:"Rich tonkotsu ramen"},{name:"Veggie Grill",type:"Plant-Based",note:"Excellent vegan fast-casual"}],tips:["Din Tai Fung line is shortest at 3 PM on weekdays","Free and abundant parking — rare for Seattle","Walk to UW campus and the Burke Museum after shopping"],bestFor:["Family","Outdoor Shopping","Dining"]},
  {id:3,name:"Pacific Place",tagline:"Downtown Seattle's Indoor Retreat.",tier:"Mid-Range",neighborhood:"Downtown",address:"600 Pine St, Seattle WA 98101",lat:47.6127,lng:-122.3354,instagram:"@pacificplaceseattle",hours:"Mon-Sat 10AM-8PM, Sun 11AM-6PM",parking:"Garage below — $6 early bird",score:84,emoji:"🏬",vibe:"A four-level indoor shopping center in the heart of downtown. Good rainy-day option with dining and a cinema.",about:"Downtown Seattle's main indoor mall, connected to Nordstrom via skybridge. Four levels with a mix of shopping, dining, and an AMC cinema. Perfect rainy-day destination.",anchors:["Nordstrom (via skybridge)","Barnes & Noble","Tiffany & Co."],mustVisit:[{name:"Nordstrom Flagship",note:"Connected via skybridge — Seattle's hometown store"},{name:"Barnes & Noble",note:"Great Seattle section with local authors"},{name:"AMC Cinema",note:"Catch a movie on a rainy afternoon"}],dining:[{name:"Din Tai Fung",type:"Taiwanese",note:"Second Seattle location — same great dumplings"},{name:"Various food court",type:"Mixed",note:"Multiple quick options on lower level"}],tips:["Connect to Nordstrom via the skybridge on level 3","The garage underneath has great early-bird rates","Best as a rainy-day option — Seattle has plenty of those"],bestFor:["Rainy Day","Downtown","Casual Shopping"]}
];

// Insert all mall data
const insertText = ",\n  'houston': " + JSON.stringify(HOUSTON_MALLS) +
  ",\n  'austin': " + JSON.stringify(AUSTIN_MALLS) +
  ",\n  'san antonio': " + JSON.stringify(SA_MALLS) +
  ",\n  'seattle': " + JSON.stringify(SEATTLE_MALLS);

html = html.slice(0, mallEnd) + insertText + "\n" + html.slice(mallEnd);

fs.writeFileSync("index.html", html);
console.log("Malls added:");
console.log("  Houston: " + HOUSTON_MALLS.length);
console.log("  Austin: " + AUSTIN_MALLS.length);
console.log("  San Antonio: " + SA_MALLS.length);
console.log("  Seattle: " + SEATTLE_MALLS.length);
console.log("Done!");
