// Batch 4: Add museums for all non-Dallas cities
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");

const museumStart = html.indexOf("const MUSEUM_DATA");
const museumEnd = html.indexOf("};", museumStart);

const ALL_MUSEUMS = {
  'new york': [
    {id:1,name:"The Metropolitan Museum of Art",neighborhood:"Upper East Side",type:"Art Museum",address:"1000 5th Ave, New York NY 10028",lat:40.7794,lng:-73.9632,score:99,hours:"Sun-Tue,Thu 10AM-5PM; Fri-Sat 10AM-9PM; Closed Wed",admission:"$30 adults (NY residents pay what you wish)",website:"https://www.metmuseum.org",description:"The largest art museum in the Americas with over 2 million works spanning 5,000 years. From Egyptian temples to Impressionist masterpieces. The rooftop garden bar has Central Park views.",highlights:["Temple of Dendur (Egyptian)","European Paintings galleries","The Costume Institute (Met Gala)","Rooftop garden bar with skyline views","Arms and Armor collection"],insiderTips:["NY/NJ/CT residents pay what you wish — even $1","The rooftop bar in summer is magical","Friday and Saturday evenings are less crowded"],bestFor:["Art Lovers","Date Night","Rainy Day","Family"]},
    {id:2,name:"MoMA - Museum of Modern Art",neighborhood:"Midtown",type:"Art Museum",address:"11 W 53rd St, New York NY 10019",lat:40.7614,lng:-73.9776,score:96,hours:"Sun-Fri 10:30AM-5:30PM; Sat 10:30AM-7PM",admission:"$25 adults (Free Fridays 4-8PM for NYC residents)",website:"https://www.moma.org",description:"The world's most influential modern art museum. Starry Night, Campbell's Soup Cans, Les Demoiselles d'Avignon, and The Persistence of Memory all live here. The sculpture garden is an oasis.",highlights:["Van Gogh's The Starry Night","Warhol's Campbell's Soup Cans","Sculpture Garden","Architecture and Design galleries","Film screenings daily"],insiderTips:["Free for NYC residents on Friday evenings 4-8PM","The sculpture garden is free to enter from 53rd St","Start on the 5th floor and work down"],bestFor:["Art Lovers","Date Night","Rainy Day"]},
    {id:3,name:"American Museum of Natural History",neighborhood:"Upper West Side",type:"Natural History Museum",address:"200 Central Park West, New York NY 10024",lat:40.7813,lng:-73.9740,score:95,hours:"Wed-Sun 10AM-5:30PM",admission:"$28 adults (NY residents pay what you wish)",website:"https://www.amnh.org",description:"Founded in 1869 with 33 million specimens. The blue whale, T-Rex skeleton, Rose Center planetarium, and the new Gilder Center. Night at the Museum was filmed here.",highlights:["94-foot blue whale model","T-Rex and fossil halls","Rose Center for Earth and Space","Gilder Center (opened 2023)","Hall of Ocean Life"],insiderTips:["NY residents pay what you wish","The Gilder Center's butterfly vivarium is stunning","The diorama halls are the hidden gem — truly extraordinary"],bestFor:["Family","Kids","Science","Rainy Day"]},
    {id:4,name:"9/11 Memorial & Museum",neighborhood:"Financial District",type:"Memorial / History Museum",address:"180 Greenwich St, New York NY 10007",lat:40.7115,lng:-74.0134,score:94,hours:"Wed-Mon 9AM-8PM (last entry 6PM)",admission:"$33 adults (memorial pools are free)",website:"https://www.911memorial.org",description:"Built on the World Trade Center site with two massive reflecting pools where the towers stood. The underground museum tells the story through artifacts, recordings, and personal testimonies. Deeply moving.",highlights:["Memorial pools (free, open daily)","Survivor staircase","Last Column ceremony room","In Memoriam exhibition","Foundation Hall with slurry wall"],insiderTips:["The memorial pools are free — visit at night when they're lit","Tuesday after 3PM is free admission to the museum","Allow 2-3 hours minimum — it's emotionally intense"],bestFor:["History","Reflection","Essential NYC"]}
  ],
  'chicago': [
    {id:1,name:"Art Institute of Chicago",neighborhood:"The Loop",type:"Art Museum",address:"111 S Michigan Ave, Chicago IL 60603",lat:41.8796,lng:-87.6237,score:98,hours:"Thu-Mon 11AM-6PM; Closed Tue-Wed",admission:"$35 adults (Illinois residents $20; free for under 14)",website:"https://www.artic.edu",description:"One of the oldest and largest art museums in the US with 300,000 works. Home to A Sunday on La Grande Jatte, American Gothic, Nighthawks, and one of the world's finest Impressionist collections.",highlights:["Seurat's A Sunday on La Grande Jatte","Grant Wood's American Gothic","Hopper's Nighthawks","Modern Wing by Renzo Piano","Thorne Miniature Rooms"],insiderTips:["Illinois residents get discounted admission — bring ID","The Modern Wing has a free bridge to Millennium Park","Thursday evenings are less crowded"],bestFor:["Art Lovers","Date Night","Rainy Day","Essential Chicago"]},
    {id:2,name:"Museum of Science and Industry",neighborhood:"Hyde Park",type:"Science Museum",address:"5700 S DuSable Lake Shore Dr, Chicago IL 60637",lat:41.7906,lng:-87.5831,score:94,hours:"Daily 9:30AM-4PM",admission:"$21.95 adults",website:"https://www.msichicago.org",description:"The largest science museum in the Western Hemisphere, housed in the only remaining building from the 1893 World's Fair. A captured German U-505 submarine, a coal mine tour, and the Science Storms exhibit.",highlights:["U-505 submarine (WWII capture)","Coal Mine tour (underground ride)","Science Storms (tornado, tsunami)","Fairy Castle dollhouse","Christmas Around the World (holiday)"],insiderTips:["The U-505 submarine tour is worth the extra ticket","The building itself is from the 1893 World's Fair — stunning architecture","Free admission days throughout the year — check website"],bestFor:["Family","Kids","Science","History"]},
    {id:3,name:"Field Museum of Natural History",neighborhood:"Museum Campus",type:"Natural History Museum",address:"1400 S DuSable Lake Shore Dr, Chicago IL 60605",lat:41.8662,lng:-87.6170,score:93,hours:"Daily 9AM-5PM",admission:"$30 adults (Illinois residents $22)",website:"https://www.fieldmuseum.org",description:"Home to SUE, the largest and most complete T-Rex ever found. 40 million artifacts spanning 4.6 billion years of Earth's history. The Evolving Planet exhibit traces life from single cells to today.",highlights:["SUE — largest T-Rex skeleton","Evolving Planet exhibit","Ancient Egypt tomb replicas","Máximo — largest dinosaur ever","Underground Adventure (shrink to bug size)"],insiderTips:["SUE is in the main hall — you can't miss her","Combine with Shedd Aquarium and Adler Planetarium on Museum Campus","Free for Illinois residents on certain days — check calendar"],bestFor:["Family","Kids","Science","Dinosaurs"]}
  ],
  'los angeles': [
    {id:1,name:"The Getty Center",neighborhood:"Brentwood",type:"Art Museum",address:"1200 Getty Center Dr, Los Angeles CA 90049",lat:34.0780,lng:-118.4741,score:97,hours:"Tue-Sun 10AM-5:30PM (Sat until 8PM)",admission:"Free (parking $20)",website:"https://www.getty.edu",description:"Richard Meier's stunning hilltop campus with panoramic LA views, Central Garden, and European paintings from the Middle Ages to today. Van Gogh's Irises and Monet's Wheatstacks live here. Free admission — you only pay for parking.",highlights:["Van Gogh's Irises","Central Garden by Robert Irwin","Panoramic LA views from every terrace","European paintings collection","Architecture by Richard Meier"],insiderTips:["Admission is free — only parking costs $20","Saturday evenings until 8PM are magical at sunset","Take the tram up the hill — the ride itself is an experience"],bestFor:["Art Lovers","Views","Date Night","Free Activity"]},
    {id:2,name:"The Broad",neighborhood:"Downtown LA",type:"Contemporary Art Museum",address:"221 S Grand Ave, Los Angeles CA 90012",lat:34.0544,lng:-118.2509,score:94,hours:"Wed-Mon 11AM-5PM (Thu-Sat until 8PM)",admission:"Free (advance reservations required)",website:"https://www.thebroad.org",description:"Eli and Edythe Broad's contemporary art museum with 2,000 works. Yayoi Kusama's Infinity Mirrored Room, Jeff Koons' Balloon Dog, and major Basquiat, Warhol, and Lichtenstein pieces. Free but reserve ahead.",highlights:["Yayoi Kusama's Infinity Mirrored Room","Jeff Koons' Balloon Dog","Basquiat collection","The Veil building design","Free general admission"],insiderTips:["Reserve free tickets online — they go fast","The Infinity Room has a separate timed entry — book immediately","Thursday evenings are less crowded"],bestFor:["Art Lovers","Instagram","Free Activity","Date Night"]},
    {id:3,name:"Natural History Museum of LA County",neighborhood:"Exposition Park",type:"Natural History Museum",address:"900 W Exposition Blvd, Los Angeles CA 90007",lat:34.0170,lng:-118.2887,score:91,hours:"Daily 9:30AM-5PM",admission:"$15 adults",website:"https://nhm.org",description:"One of the largest natural history museums in the US with 35 million specimens. The Dinosaur Hall has over 300 real fossils including a T-Rex growth series. The Nature Gardens outside are a living exhibit.",highlights:["Dinosaur Hall — 300+ real fossils","T-Rex growth series (baby to adult)","Nature Gardens (outdoor)","Gem and Mineral Hall","Becoming Los Angeles exhibit"],insiderTips:["The Dinosaur Hall is the star — start there","First Tuesdays are free (except July and August)","The Nature Gardens are beautiful and often overlooked"],bestFor:["Family","Kids","Dinosaurs","Science"]}
  ],
  'houston': [
    {id:1,name:"Museum of Fine Arts Houston (MFAH)",neighborhood:"Museum District",type:"Art Museum",address:"1001 Bissonnet St, Houston TX 77005",lat:29.7256,lng:-95.3909,score:96,hours:"Wed,Thu,Sat 10AM-5PM; Fri 10AM-9PM; Sun 12:15-5PM",admission:"Free general (special exhibits ticketed)",website:"https://www.mfah.org",description:"One of the largest art museums in the US with 70,000 works across two buildings connected by an underground tunnel. The Nancy and Rich Kinder Building (2020) by Steven Holl is architecturally stunning. Free general admission.",highlights:["Nancy and Rich Kinder Building (Steven Holl)","Underground tunnel with James Turrell installation","Latin American art collection","Cullinan Hall sculpture garden","Free general admission"],insiderTips:["General admission is always free — special exhibits cost extra","The underground tunnel between buildings has a Turrell light installation","Friday evenings until 9PM are great for a date"],bestFor:["Art Lovers","Free Activity","Date Night","Architecture"]},
    {id:2,name:"Space Center Houston",neighborhood:"Clear Lake / NASA",type:"Science Museum",address:"1601 E NASA Pkwy, Houston TX 77058",lat:29.5519,lng:-95.0981,score:95,hours:"Mon-Fri 10AM-5PM; Sat-Sun 10AM-6PM",admission:"$29.95 adults",website:"https://www.spacecenter.org",description:"The official visitor center of NASA's Johnson Space Center. See real spacecraft, touch a moon rock, tour Mission Control, and experience astronaut training simulators. The Saturn V rocket is jaw-dropping.",highlights:["Saturn V rocket (largest rocket ever flown)","Mission Control tour (where Apollo 11 was managed)","Real moon rock you can touch","Astronaut training simulators","Independence shuttle replica"],insiderTips:["The Level 9 tour ($179) goes inside restricted NASA areas — worth it","The tram tour to the real Mission Control is the highlight — go first","Allow 4-5 hours minimum"],bestFor:["Family","Science","Space","Essential Houston"]},
    {id:3,name:"Menil Collection",neighborhood:"Montrose",type:"Art Museum",address:"1533 Sul Ross St, Houston TX 77006",lat:29.7372,lng:-95.3907,score:94,hours:"Wed-Sun 11AM-7PM",admission:"Free",website:"https://www.menil.org",description:"A Renzo Piano-designed museum housing the extraordinary private collection of Dominique and John de Menil. Surrealism, African and Byzantine art, and the nearby Rothko Chapel. Everything is free.",highlights:["Renzo Piano building design","Surrealist collection (Magritte, Ernst)","Rothko Chapel (nearby — free)","Cy Twombly Gallery (separate building)","Byzantine and African art"],insiderTips:["Everything is free — the museum, Rothko Chapel, Cy Twombly Gallery","The Rothko Chapel is a 5-minute walk and profoundly moving","The neighborhood around the Menil is walkable and charming"],bestFor:["Art Lovers","Free Activity","Meditation","Architecture"]}
  ],
  'austin': [
    {id:1,name:"Blanton Museum of Art",neighborhood:"UT Campus",type:"Art Museum",address:"200 E Martin Luther King Jr Blvd, Austin TX 78712",lat:30.2808,lng:-97.7372,score:92,hours:"Wed-Sat 10AM-5PM; Sun 1-5PM",admission:"$12 adults (free Thursdays)",website:"https://www.blantonmuseum.org",description:"The largest university art museum in the US with 21,000 works. Ellsworth Kelly's Austin chapel — a 2,715 sq ft masterpiece of colored light — is the crown jewel. On the UT campus.",highlights:["Ellsworth Kelly's Austin (must-see chapel)","Latin American art collection","European paintings","Contemporary art galleries","Free Thursdays"],insiderTips:["Ellsworth Kelly's Austin is free to enter and absolutely stunning","Free admission every Thursday","Walk from here to the Capitol and South Congress"],bestFor:["Art Lovers","Free Activity","Architecture","UT Campus"]},
    {id:2,name:"Bullock Texas State History Museum",neighborhood:"Downtown",type:"History Museum",address:"1800 Congress Ave, Austin TX 78701",lat:30.2804,lng:-97.7391,score:89,hours:"Mon-Sat 9AM-5PM; Sun 12-5PM",admission:"$13 adults",website:"https://www.thestoryoftexas.com",description:"Three floors telling the story of Texas from prehistoric times to the space age. IMAX theater, a 35-foot star on the exterior, and rotating exhibits. The Texas history deep dive.",highlights:["Three floors of Texas history","IMAX theater","Republic of Texas exhibits","Space exploration gallery","La Belle shipwreck artifacts"],insiderTips:["The IMAX theater is worth the extra ticket","Start on the 3rd floor and work down chronologically","The La Belle French shipwreck is a remarkable artifact"],bestFor:["History","Family","Texas Culture","Rainy Day"]},
    {id:3,name:"LBJ Presidential Library",neighborhood:"UT Campus",type:"Presidential Library",address:"2313 Red River St, Austin TX 78705",lat:30.2861,lng:-97.7293,score:88,hours:"Daily 9AM-5PM",admission:"Free",website:"https://www.lbjlibrary.org",description:"The presidential library of Lyndon B. Johnson on the UT campus. A replica of the Oval Office, Civil Rights Act exhibits, and 45 million pages of historical documents. Free admission.",highlights:["Oval Office replica (7/8 scale)","Civil Rights Act exhibit","Lady Bird Johnson's legacy","Vietnam War decision room","45 million pages of documents"],insiderTips:["Free admission — one of the best free museums in Austin","The Oval Office replica is incredibly detailed","Combine with the Blanton Museum nearby"],bestFor:["History","Free Activity","Politics","UT Campus"]}
  ],
  'san antonio': [
    {id:1,name:"The Alamo",neighborhood:"Downtown",type:"Historic Site",address:"300 Alamo Plaza, San Antonio TX 78205",lat:29.4260,lng:-98.4861,score:96,hours:"Daily 9AM-5:30PM",admission:"Free (timed entry required)",website:"https://www.thealamo.org",description:"The most famous landmark in Texas. The 1836 Battle of the Alamo is foundational to Texas identity. The chapel and Long Barrack date to the 18th century Spanish mission era. A $450M restoration is underway.",highlights:["The Alamo Chapel (1718)","Long Barrack Museum","Battle of the Alamo history","$450M restoration project","Gift shop and grounds"],insiderTips:["Free but timed entry tickets required — book online ahead","Go first thing in the morning to avoid crowds","The Long Barrack has more artifacts than the chapel"],bestFor:["History","Essential San Antonio","Free Activity","Family"]},
    {id:2,name:"San Antonio Museum of Art (SAMA)",neighborhood:"Midtown",type:"Art Museum",address:"200 W Jones Ave, San Antonio TX 78215",lat:29.4373,lng:-98.4821,score:91,hours:"Wed,Fri-Sun 10AM-5PM; Tue,Thu 10AM-9PM",admission:"$20 adults (free Tuesdays 4-9PM)",website:"https://www.samuseum.org",description:"Housed in a former Lone Star Brewery, SAMA has the most comprehensive collection of Latin American art in the US. Egyptian, Greek, Roman, and Asian galleries span 5,000 years. The building itself is an architectural landmark.",highlights:["Latin American art (largest US collection)","Egyptian and antiquities galleries","Lone Star Brewery architecture","Asian art collection","Free Tuesday evenings"],insiderTips:["Free admission Tuesday evenings 4-9PM","The Latin American galleries are the highlight — don't skip","Walk to the Pearl District from here along the river"],bestFor:["Art Lovers","History","Free Evening","Architecture"]},
    {id:3,name:"Witte Museum",neighborhood:"Brackenridge Park",type:"Natural History / Science",address:"3801 Broadway, San Antonio TX 78209",lat:29.4607,lng:-98.4683,score:89,hours:"Mon-Sat 10AM-5PM; Sun 12-5PM",admission:"$14 adults (free Tuesdays 3-8PM)",website:"https://www.wittemuseum.org",description:"South Texas natural history and science with a Texas Wild gallery, dinosaur lab, and outdoor tree houses. The Naylor Family Dinosaur Gallery has a 66-million-year-old Tyrannosaurus rex.",highlights:["Naylor Family Dinosaur Gallery","Texas Wild outdoor exhibit","HEB Body Adventure (health science)","Tree house exhibits for kids","Free Tuesdays 3-8PM"],insiderTips:["Free Tuesdays 3-8PM","The outdoor tree houses are great for kids","Combine with a visit to the Japanese Tea Garden next door"],bestFor:["Family","Kids","Science","Texas History"]}
  ],
  'seattle': [
    {id:1,name:"Museum of Pop Culture (MoPOP)",neighborhood:"Seattle Center",type:"Music / Pop Culture Museum",address:"325 5th Ave N, Seattle WA 98109",lat:47.6215,lng:-122.3481,score:95,hours:"Daily 10AM-5PM",admission:"$28 adults",website:"https://www.mopop.org",description:"Frank Gehry's stunning crumpled-metal building houses exhibits on Jimi Hendrix, Nirvana, sci-fi, horror, indie games, and more. Seattle's music history from grunge to hip-hop. The Guitar Gallery has 600+ instruments.",highlights:["Jimi Hendrix exhibit","Nirvana: Taking Punk to the Masses","Guitar Gallery (600+ instruments)","Science Fiction Museum","Frank Gehry architecture"],insiderTips:["The Jimi Hendrix and Nirvana exhibits are permanent — start there","The Sound Lab lets you play real instruments","Buy a CityPASS for the best deal on multiple attractions"],bestFor:["Music Lovers","Pop Culture","Architecture","Family"]},
    {id:2,name:"Chihuly Garden and Glass",neighborhood:"Seattle Center",type:"Art / Glass Museum",address:"305 Harrison St, Seattle WA 98109",lat:47.6206,lng:-122.3505,score:94,hours:"Sun-Thu 10AM-7PM; Fri-Sat 10AM-8PM",admission:"$32 adults",website:"https://www.chihulygardenandglass.com",description:"Dale Chihuly's breathtaking glass art installations in indoor galleries and an outdoor garden with the Space Needle as backdrop. The Glasshouse centerpiece is a 40-foot sculpture of red, orange, and yellow glass.",highlights:["The Glasshouse (100-ft long, 40-ft tall)","Outdoor garden with Space Needle backdrop","Persian Ceiling room","Mille Fiori room","Glass blowing demonstrations"],insiderTips:["Visit at night when the garden is dramatically lit","The Glasshouse at sunset is magical","Combo ticket with Space Needle saves money"],bestFor:["Art","Photography","Date Night","Essential Seattle"]},
    {id:3,name:"Seattle Art Museum (SAM)",neighborhood:"Downtown",type:"Art Museum",address:"1300 1st Ave, Seattle WA 98101",lat:47.6073,lng:-122.3388,score:90,hours:"Wed-Sun 10AM-5PM (Thu until 9PM)",admission:"$29.99 adults (free first Thursday of month)",website:"https://www.seattleartmuseum.org",description:"Downtown Seattle's major art museum with global collections from Native American art to contemporary. The Olympic Sculpture Park on the waterfront is free and stunning. Three locations including the Asian Art Museum in Volunteer Park.",highlights:["Global art collections","Olympic Sculpture Park (free, waterfront)","Native American art galleries","Asian Art Museum at Volunteer Park","Free first Thursdays"],insiderTips:["Olympic Sculpture Park is free and has amazing sunset views","Free first Thursday of every month","The Asian Art Museum in Volunteer Park is a separate gem"],bestFor:["Art Lovers","Free Activity","Views","Rainy Day"]},
    {id:4,name:"Museum of Flight",neighborhood:"Georgetown",type:"Aviation / Space Museum",address:"9404 E Marginal Way S, Seattle WA 98108",lat:47.5180,lng:-122.2964,score:93,hours:"Daily 10AM-5PM",admission:"$25 adults",website:"https://www.museumofflight.org",description:"The largest private air and space museum in the world. A retired Air Force One, the Concorde, a space shuttle trainer, and Boeing's original Red Barn factory. 175+ aircraft and spacecraft.",highlights:["Air Force One (Eisenhower to Nixon era)","Concorde (walk through it)","Space shuttle trainer","Boeing Red Barn (original factory)","175+ aircraft collection"],insiderTips:["The Air Force One and Concorde tours are included in admission","Boeing connection makes this uniquely Seattle","Allow 3+ hours — it's massive"],bestFor:["Aviation","Family","Science","History"]}
  ]
};

// Insert all museum data
let insertText = "";
Object.entries(ALL_MUSEUMS).forEach(([city, museums]) => {
  insertText += ",\n  '" + city + "': " + JSON.stringify(museums);
});

html = html.slice(0, museumEnd) + insertText + "\n" + html.slice(museumEnd);

fs.writeFileSync("index.html", html);
let total = 0;
Object.entries(ALL_MUSEUMS).forEach(([city, museums]) => {
  console.log("  MUSEUM_DATA." + city + ": " + museums.length);
  total += museums.length;
});
console.log("Total museums added: " + total);
console.log("Done!");
