// Batch 1: Add hotels for Houston, Austin, San Antonio, Seattle
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");

// Find HOTEL_DATA closing bracket
const hotelStart = html.indexOf("const HOTEL_DATA");
const hotelEnd = html.indexOf("};", hotelStart);

const HOUSTON_HOTELS = [
  {id:1,tier:"Ultra Luxury",tierEmoji:"👑",name:"The Post Oak Hotel",tagline:"Houston's Only Five-Star Hotel.",neighborhood:"Galleria / Uptown",address:"1600 West Loop S, Houston TX 77027",lat:29.7516,lng:-95.4614,instagram:"@thepostoakhotel",website:"https://www.thepostoakhotel.com",priceRange:"$500-$2,000+/night",score:97,awards:"Forbes Five-Star | AAA Five Diamond",about:"Tilman Fertitta's crown jewel and Houston's only Forbes Five-Star hotel. 250 rooms with floor-to-ceiling windows, a Rolls-Royce house car, 35,000 sq ft spa, and Mastro's Steakhouse on-site.",highlights:[{icon:"🍽",label:"Mastro's Steakhouse",note:"On-site fine dining — one of Houston's best steaks"},{icon:"💆",label:"Spa & Pool",note:"35,000 sq ft spa with rooftop pool"},{icon:"🚗",label:"Rolls-Royce Service",note:"Complimentary house car within 5 miles"}],insiderTips:["Request a high-floor room facing the Galleria for best views","The rooftop pool is heated year-round","Mastro's butter cake dessert is legendary"],bestFor:["Special Occasion","Business","Ultimate Splurge"]},
  {id:2,tier:"Luxury",tierEmoji:"🏨",name:"Hotel Granduca",tagline:"A Piece of Italy in Houston.",neighborhood:"Galleria / Uptown",address:"1080 Uptown Park Blvd, Houston TX 77056",lat:29.7525,lng:-95.4588,instagram:"@hotelgranduca",website:"https://www.granducahouston.com",priceRange:"$300-$800/night",score:94,awards:"Condé Nast Readers' Choice",about:"An intimate Italian-inspired luxury hotel with 122 suites, each with Italian marble baths and European furnishings. Ristorante Cavour serves refined Northern Italian cuisine.",highlights:[{icon:"🍽",label:"Ristorante Cavour",note:"Elegant Northern Italian dining"},{icon:"🏊",label:"Courtyard Pool",note:"Secluded European-style courtyard"},{icon:"🎩",label:"Butler Service",note:"Personal butler for every guest"}],insiderTips:["Ask for a suite overlooking the courtyard","Sunday brunch at Cavour is a hidden gem","The hotel feels like a private Italian villa"],bestFor:["Romantic Getaway","Anniversary","Quiet Luxury"]},
  {id:3,tier:"Boutique",tierEmoji:"🎨",name:"La Colombe d'Or",tagline:"A Museum You Can Sleep In.",neighborhood:"Montrose",address:"3410 Montrose Blvd, Houston TX 77006",lat:29.7416,lng:-95.3903,instagram:"@lacolombedorhotel",website:"https://www.lacolombedor.com",priceRange:"$250-$600/night",score:92,awards:"",about:"A 1923 mansion turned boutique hotel with an extraordinary private art collection including Picasso, Renoir, and Modigliani originals. Six suites, each uniquely appointed. One of the most romantic hotels in Texas.",highlights:[{icon:"🎨",label:"Private Art Collection",note:"Original Picasso, Renoir, Modigliani on the walls"},{icon:"🌳",label:"Garden Courtyard",note:"Lush grounds with sculpture garden"},{icon:"📍",label:"Montrose Location",note:"Walk to Hugo's, Uchi, and the Menil Collection"}],insiderTips:["Each suite is different — ask which is available and pick your style","The garden is perfect for a quiet morning coffee","Walking distance to the best restaurants in Houston"],bestFor:["Art Lovers","Romantic Getaway","Unique Experience"]},
  {id:4,tier:"Luxury",tierEmoji:"🏨",name:"Hotel ZaZa",tagline:"Boldly Boutique. Unapologetically Luxe.",neighborhood:"Museum District",address:"5701 Main St, Houston TX 77005",lat:29.7242,lng:-95.3863,instagram:"@hotelzaza",website:"https://www.hotelzaza.com/houston",priceRange:"$300-$1,000+/night",score:91,awards:"",about:"A flamboyant luxury hotel in the Museum District with over-the-top themed concept suites (the Rock Star Suite, the Houston We Have a Problem suite). Great pool scene and Monarch restaurant.",highlights:[{icon:"🏊",label:"Pool Scene",note:"Houston's best hotel pool with cabanas and DJs"},{icon:"🍽",label:"Monarch Restaurant",note:"Upscale dining and buzzy bar scene"},{icon:"🎭",label:"Concept Suites",note:"Wildly themed suites — each one unique"}],insiderTips:["Book a Concept Suite for the full experience","The pool on weekends is a scene — arrive early for cabanas","Walk to MFAH, Menil Collection, and Hermann Park"],bestFor:["Cool Factor","Pool Scene","Museum District Access"]},
  {id:5,tier:"Budget",tierEmoji:"💵",name:"The Lancaster Hotel",tagline:"Historic Charm in Downtown Houston.",neighborhood:"Downtown / Theater District",address:"701 Texas Ave, Houston TX 77002",lat:29.7588,lng:-95.3630,instagram:"@lancasterhouston",website:"https://www.thelancaster.com",priceRange:"$150-$350/night",score:86,awards:"Historic Hotels of America",about:"A beautifully restored 1926 hotel in the Theater District. Small and intimate with 93 rooms, original architectural details, and genuine old-world hospitality at a reasonable price.",highlights:[{icon:"🎭",label:"Theater District",note:"Steps from Wortham Theater and Jones Hall"},{icon:"🏛",label:"Historic Building",note:"1926 landmark with original details"},{icon:"📍",label:"Downtown Location",note:"Walk to Market Square Park and Discovery Green"}],insiderTips:["Request a room on the quiet side away from Texas Ave","Great pre-theater dinner base — walk to Xochi or Irma's","One of the best values in downtown Houston"],bestFor:["Budget-Conscious","Theater","History Buffs"]}
];

const AUSTIN_HOTELS = [
  {id:1,tier:"Boutique",tierEmoji:"🎨",name:"Hotel Saint Cecilia",tagline:"Rock & Roll Meets Southern Glamour.",neighborhood:"South Congress",address:"112 Academy Dr, Austin TX 78704",lat:30.2520,lng:-97.7502,instagram:"@hotelsaintcecilia",website:"https://www.hotelsaintcecilia.com",priceRange:"$400-$1,200+/night",score:96,awards:"Condé Nast Hot List",about:"Named after the patron saint of music, this 1888 Victorian estate on South Congress is Austin's most exclusive boutique hotel. Five suites, six poolside bungalows, and three studios. A Bunkhouse property with impeccable vinyl collection and literary library.",highlights:[{icon:"🎵",label:"Vinyl Library",note:"Curated record collection in every room"},{icon:"🏊",label:"Pool & Gardens",note:"Secluded pool surrounded by century-old oaks"},{icon:"📍",label:"South Congress",note:"Walk to SoCo shopping, restaurants, and music venues"}],insiderTips:["Book a bungalow for the most privacy","The pool area is the most Instagrammable spot in Austin","Ask for the vinyl cart to be delivered to your room"],bestFor:["Cool Factor","Honeymoon","Music Lovers"]},
  {id:2,tier:"Luxury",tierEmoji:"🏨",name:"The Driskill",tagline:"Austin's Grand Dame Since 1886.",neighborhood:"Downtown / 6th Street",address:"604 Brazos St, Austin TX 78701",lat:30.2672,lng:-97.7410,instagram:"@thedriskill",website:"https://www.hyatt.com/en-US/hotel/texas/the-driskill/ausub",priceRange:"$300-$800/night",score:93,awards:"Historic Hotels of America | National Register of Historic Places",about:"Austin's most historic hotel, built in 1886 by cattle baron Jesse Driskill. Romanesque architecture, stained glass dome, and the legendary Driskill Bar. Every Texas governor has dined here.",highlights:[{icon:"🥃",label:"The Driskill Bar",note:"Austin's most iconic bar — live music nightly"},{icon:"🏛",label:"Historic Architecture",note:"1886 Romanesque landmark with stained glass dome"},{icon:"📍",label:"6th Street",note:"Steps from live music on Dirty Sixth and Rainey Street"}],insiderTips:["The Driskill Bar is worth visiting even if you don't stay here","Ask for a room facing Brazos Street for the best views","Sunday brunch in the ballroom is an Austin tradition"],bestFor:["History","Live Music","Special Occasion"]},
  {id:3,tier:"Boutique",tierEmoji:"🎨",name:"South Congress Hotel",tagline:"Austin's Creative Class Headquarters.",neighborhood:"South Congress",address:"1603 S Congress Ave, Austin TX 78704",lat:30.2468,lng:-97.7498,instagram:"@southcongresshotel",website:"https://www.southcongresshotel.com",priceRange:"$300-$700/night",score:92,awards:"",about:"A design-forward hotel on SoCo with multiple restaurants, a rooftop pool, and a lobby that doubles as Austin's living room. Central Standard and Café No Sé are destinations on their own.",highlights:[{icon:"🍽",label:"Multiple Restaurants",note:"Central Standard, Café No Sé, Otoko (omakase)"},{icon:"🏊",label:"Rooftop Pool",note:"Pool with downtown skyline views"},{icon:"🛍",label:"SoCo Location",note:"Prime South Congress shopping and dining"}],insiderTips:["Otoko is a hidden 12-seat omakase inside the hotel — book way ahead","Café No Sé is great for breakfast before exploring SoCo","The lobby shop has the best curated Austin gifts"],bestFor:["Design Lovers","South Congress Access","Foodie"]},
  {id:4,tier:"Boutique",tierEmoji:"🎨",name:"Hotel San José",tagline:"Minimalist Cool on South Congress.",neighborhood:"South Congress",address:"1316 S Congress Ave, Austin TX 78704",lat:30.2494,lng:-97.7497,instagram:"@hotelsanjose",website:"https://www.bunkhousehotels.com/hotel-san-jose",priceRange:"$200-$500/night",score:90,awards:"",about:"A converted 1936 motor court reimagined as a minimalist boutique hotel. Courtyard pool, native gardens, and a vibe that captures Austin's effortless cool. Another Bunkhouse gem.",highlights:[{icon:"🏊",label:"Courtyard Pool",note:"Intimate pool surrounded by native plants"},{icon:"🌿",label:"Garden Courtyard",note:"Zen-like grounds with hammocks"},{icon:"📍",label:"SoCo",note:"Heart of South Congress — walk everywhere"}],insiderTips:["Rooms are intentionally small — you're paying for the vibe","The courtyard is the social hub — bring a book","Jo's Coffee next door is an Austin institution"],bestFor:["Cool Factor","Budget Boutique","South Congress"]},
  {id:5,tier:"Luxury",tierEmoji:"🏨",name:"The LINE Austin",tagline:"Lakefront Living on Lady Bird Lake.",neighborhood:"Downtown / Rainey Street",address:"111 E Cesar Chavez St, Austin TX 78701",lat:30.2590,lng:-97.7405,instagram:"@thelinehotel",website:"https://www.thelinehotel.com/austin",priceRange:"$250-$600/night",score:89,awards:"",about:"A lakefront hotel on Lady Bird Lake with floor-to-ceiling windows, rooftop pool, and Arlo Grey restaurant by Top Chef winner Kristen Kish. Walk to Rainey Street bars.",highlights:[{icon:"🍽",label:"Arlo Grey",note:"Top Chef winner Kristen Kish's restaurant"},{icon:"🏊",label:"Rooftop Pool",note:"Infinity pool overlooking Lady Bird Lake"},{icon:"📍",label:"Rainey Street",note:"Walk to Rainey Street bar district"}],insiderTips:["Request a lake-facing room — the sunrise is incredible","Arlo Grey's pasta is the standout","The rooftop pool at sunset is peak Austin"],bestFor:["Lake Views","Foodie","Rainey Street Access"]}
];

const SA_HOTELS = [
  {id:1,tier:"Luxury",tierEmoji:"🏨",name:"Hotel Emma",tagline:"Industrial Luxury at the Pearl.",neighborhood:"Pearl District",address:"136 E Grayson St, San Antonio TX 78215",lat:29.4430,lng:-98.4798,instagram:"@thehotelemma",website:"https://www.thehotelemma.com",priceRange:"$350-$900/night",score:96,awards:"Condé Nast Readers' Choice | Travel + Leisure World's Best",about:"A stunning conversion of a 19th-century Pearl Brewery building into San Antonio's finest hotel. Original industrial details — giant gears, steel tanks, brewing equipment — blended with luxury. Supper restaurant and Sternewirth bar on-site.",highlights:[{icon:"🍽",label:"Supper",note:"American fine dining in the restored brewhouse"},{icon:"🥃",label:"Sternewirth",note:"Atmospheric bar in original brewery equipment"},{icon:"📍",label:"Pearl District",note:"Walk to Bakery Lorraine, Cured, and the Farmers Market"}],insiderTips:["The library lounge has the best quiet corner in the hotel","Saturday Pearl Farmers Market is steps away","Ask for a room with original brewery details visible"],bestFor:["Design Lovers","Pearl District","Special Occasion"]},
  {id:2,tier:"Boutique",tierEmoji:"🎨",name:"Hotel Havana",tagline:"A River Walk Secret Since 1914.",neighborhood:"River Walk",address:"1015 Navarro St, San Antonio TX 78205",lat:29.4271,lng:-98.4890,instagram:"@hotelhavana",website:"https://www.bunkhousehotels.com/hotel-havana",priceRange:"$200-$500/night",score:93,awards:"",about:"A 1914 Mediterranean Revival building on a quiet stretch of the River Walk. Cuban and Pan-Latin influences, vintage furniture, and the rooftop Ocho Lounge with river views. A Bunkhouse property.",highlights:[{icon:"🍽",label:"Ocho Restaurant",note:"Pan-Latin cuisine with River Walk views"},{icon:"🌙",label:"Ocho Lounge",note:"Rooftop bar — magical at night"},{icon:"📍",label:"Quiet River Walk",note:"Peaceful stretch away from tourist crowds"}],insiderTips:["The rooftop lounge at sunset is the most romantic spot in SA","Rooms are small but charming — it's a 1914 building","Walk north along the river to reach the Pearl in 15 minutes"],bestFor:["Romantic Getaway","Boutique Experience","River Walk"]},
  {id:3,tier:"Ultra Luxury",tierEmoji:"👑",name:"The St. Anthony",tagline:"San Antonio's Original Luxury Hotel.",neighborhood:"Downtown",address:"300 E Travis St, San Antonio TX 78205",lat:29.4247,lng:-98.4878,instagram:"@thestanthonyhotel",website:"https://www.thestanthonyhotel.com",priceRange:"$300-$800/night",score:91,awards:"National Register of Historic Places",about:"San Antonio's first luxury hotel, opened in 1909. A Marriott Luxury Collection property with a rooftop pool, ornate lobby, and Rebelle restaurant. Every US president since Teddy Roosevelt has stayed here.",highlights:[{icon:"🏊",label:"Rooftop Pool",note:"Pool with downtown San Antonio views"},{icon:"🏛",label:"Historic Landmark",note:"1909 — every president since Roosevelt stayed here"},{icon:"🍽",label:"Rebelle",note:"Refined American seafood restaurant"}],insiderTips:["The lobby is worth seeing even if you don't stay","Rooftop pool is heated year-round","Walk to the Alamo in 5 minutes"],bestFor:["History","Downtown Access","Special Occasion"]},
  {id:4,tier:"Luxury",tierEmoji:"🏨",name:"Mokara Hotel & Spa",tagline:"River Walk Serenity.",neighborhood:"River Walk",address:"212 W Crockett St, San Antonio TX 78205",lat:29.4233,lng:-98.4932,instagram:"@mokarahotels",website:"https://www.omnihotels.com/hotels/san-antonio-mokara",priceRange:"$350-$700/night",score:92,awards:"AAA Four Diamond",about:"An intimate luxury hotel on the River Walk with a world-class rooftop spa and pool. 99 rooms with river views, balconies, and the most relaxing hotel experience in San Antonio.",highlights:[{icon:"💆",label:"Rooftop Spa",note:"Full-service spa with river views"},{icon:"🏊",label:"Rooftop Pool",note:"Heated pool overlooking the River Walk"},{icon:"📍",label:"River Walk",note:"Prime location — walk to everything downtown"}],insiderTips:["The rooftop spa pool is the most serene spot in downtown SA","Book a river-facing room with a balcony","The Ostra restaurant does excellent Gulf seafood"],bestFor:["Spa","River Walk","Relaxation"]},
  {id:5,tier:"Luxury",tierEmoji:"🏨",name:"Omni La Mansión del Rio",tagline:"Old World Elegance on the River Walk.",neighborhood:"River Walk",address:"112 College St, San Antonio TX 78205",lat:29.4242,lng:-98.4915,instagram:"@omnilmdr",website:"https://www.omnihotels.com/hotels/san-antonio-la-mansion-del-rio",priceRange:"$250-$600/night",score:90,awards:"AAA Four Diamond",about:"A Spanish Colonial-style hotel directly on the River Walk since 1968. Lush courtyards, wrought-iron balconies, and Las Canarias restaurant overlooking the water. The most romantic River Walk hotel.",highlights:[{icon:"🍽",label:"Las Canarias",note:"River Walk dining with candlelit tables"},{icon:"🌺",label:"Courtyards",note:"Spanish Colonial gardens and fountains"},{icon:"📍",label:"River Walk",note:"Prime bend in the river — best location"}],insiderTips:["Request a river-facing room with balcony","Las Canarias brunch on the river is magical","Walk to the Alamo, La Villita, and King William from here"],bestFor:["River Walk","Romantic","Family"]}
];

const SEATTLE_HOTELS = [
  {id:1,tier:"Boutique",tierEmoji:"🎨",name:"Inn at the Market",tagline:"Pike Place Market at Your Doorstep.",neighborhood:"Pike Place Market",address:"86 Pine St, Seattle WA 98101",lat:47.6100,lng:-122.3420,instagram:"@innatthemarket",website:"https://www.innatthemarket.com",priceRange:"$300-$600/night",score:94,awards:"",about:"The only hotel inside Pike Place Market. Rooftop deck with Elliott Bay views, steps from the fish throwers and flower stalls. Intimate 76-room property that feels like a secret.",highlights:[{icon:"📍",label:"Pike Place",note:"Literally inside the market — unbeatable location"},{icon:"🌊",label:"Rooftop Deck",note:"Elliott Bay and Olympic Mountain views"},{icon:"🍽",label:"Restaurant Access",note:"Walk to 100+ market vendors and restaurants"}],insiderTips:["Rooftop deck at sunset with a glass of Washington wine","Request a bay-view room — worth the upgrade","Explore the market before 8 AM when it's locals-only"],bestFor:["Pike Place Access","Views","Unique Experience"]},
  {id:2,tier:"Luxury",tierEmoji:"🏨",name:"The Edgewater",tagline:"Seattle's Only Waterfront Hotel.",neighborhood:"Waterfront / Belltown",address:"2411 Alaskan Way, Seattle WA 98121",lat:47.6127,lng:-122.3563,instagram:"@edgewaterhotel",website:"https://www.edgewaterhotel.com",priceRange:"$300-$800/night",score:92,awards:"",about:"Built on a pier over Elliott Bay — the only Seattle hotel where you can fish from your window. The Beatles stayed here in 1964 (and fished from their room). Rustic lodge meets waterfront luxury.",highlights:[{icon:"🌊",label:"On the Water",note:"Built on a pier — waves literally beneath you"},{icon:"🎸",label:"Rock History",note:"The Beatles fished from Room 272 in 1964"},{icon:"🍽",label:"Six Seven Restaurant",note:"Pacific NW seafood with bay views"}],insiderTips:["Request a waterside room — you'll hear the waves","The fireplace lounge is the coziest spot in Seattle on rainy days","Walk the waterfront path to Pike Place in 10 minutes"],bestFor:["Waterfront","Rock History","Unique Experience"]},
  {id:3,tier:"Boutique",tierEmoji:"🎨",name:"Hotel Sorrento",tagline:"Capitol Hill's Italian Renaissance Gem.",neighborhood:"First Hill / Capitol Hill",address:"900 Madison St, Seattle WA 98104",lat:47.6089,lng:-122.3256,instagram:"@hotelsorrento",website:"https://www.hotelsorrento.com",priceRange:"$250-$500/night",score:91,awards:"Historic Hotels of America",about:"A 1909 Italianate building with mahogany-paneled lobbies, a roaring fireplace, and the Dunbar Room lounge. Walking distance to Capitol Hill's restaurants and bars.",highlights:[{icon:"🥃",label:"Dunbar Room",note:"Intimate lounge with craft cocktails and live music"},{icon:"🏛",label:"1909 Architecture",note:"Italian Renaissance details throughout"},{icon:"📍",label:"Capitol Hill Access",note:"Walk to Seattle's best dining neighborhood"}],insiderTips:["The Dunbar Room is one of Seattle's best-kept secrets","Ask for a corner room with city views","Walk up to Capitol Hill's Pike/Pine corridor for dinner"],bestFor:["History","Cocktails","Capitol Hill Access"]},
  {id:4,tier:"Boutique",tierEmoji:"🎨",name:"Thompson Seattle",tagline:"Rooftop Views. Downtown Cool.",neighborhood:"Downtown",address:"110 Stewart St, Seattle WA 98101",lat:47.6092,lng:-122.3410,instagram:"@thompsonseattle",website:"https://www.hyatt.com/thompson/seattle",priceRange:"$300-$600/night",score:90,awards:"",about:"A sleek downtown hotel with the city's best rooftop bar — Nest — offering 360-degree views of the skyline, Puget Sound, and Mount Rainier. Scout PNW restaurant on the ground floor.",highlights:[{icon:"🌆",label:"Nest Rooftop Bar",note:"360-degree views — best rooftop in Seattle"},{icon:"🍽",label:"Scout PNW",note:"Pacific Northwest seasonal dining"},{icon:"📍",label:"Downtown",note:"Walk to Pike Place and waterfront"}],insiderTips:["Nest rooftop at sunset on a clear day — you'll see Rainier","Scout PNW does an excellent brunch","Book through Hyatt for best rates"],bestFor:["Rooftop Views","Downtown","Design"]},
  {id:5,tier:"Budget",tierEmoji:"💵",name:"Ace Hotel Seattle",tagline:"The Original Ace. Where It All Started.",neighborhood:"Belltown",address:"2423 1st Ave, Seattle WA 98121",lat:47.6133,lng:-122.3477,instagram:"@acehotel",website:"https://www.acehotel.com/seattle",priceRange:"$100-$300/night",score:87,awards:"",about:"The original Ace Hotel that launched the brand in 1999. Minimalist rooms, turntables, and Stumptown Coffee in the lobby. Belltown location with walkable access to everything.",highlights:[{icon:"☕",label:"Stumptown Coffee",note:"Lobby coffee shop — Seattle coffee culture"},{icon:"🎵",label:"Turntables",note:"Record players in every room"},{icon:"📍",label:"Belltown",note:"Walk to Pike Place, restaurants, and nightlife"}],insiderTips:["The cheapest rooms share bathrooms — worth it for the price","Stumptown in the lobby is a social hub","Walk to Shaker + Spear for dinner"],bestFor:["Budget","Cool Factor","First-Time Seattle"]}
];

// Insert all hotel data
const insertText = ",\n  'houston': " + JSON.stringify(HOUSTON_HOTELS) +
  ",\n  'austin': " + JSON.stringify(AUSTIN_HOTELS) +
  ",\n  'san antonio': " + JSON.stringify(SA_HOTELS) +
  ",\n  'seattle': " + JSON.stringify(SEATTLE_HOTELS);

html = html.slice(0, hotelEnd) + insertText + "\n" + html.slice(hotelEnd);

fs.writeFileSync("index.html", html);
console.log("Hotels added:");
console.log("  Houston: " + HOUSTON_HOTELS.length);
console.log("  Austin: " + AUSTIN_HOTELS.length);
console.log("  San Antonio: " + SA_HOTELS.length);
console.log("  Seattle: " + SEATTLE_HOTELS.length);
console.log("Done!");
