const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');

// === HELPER FUNCTION ===
function addToCity(cityKey, isRef, spots){
  let arrS, arrE;
  if(isRef){
    const hdIdx = html.indexOf('const '+cityKey);
    arrS = html.indexOf('[', hdIdx);
  } else {
    const chiIdx = html.indexOf("'"+cityKey+"':", html.indexOf('CITY_DATA'));
    arrS = html.indexOf('[', chiIdx);
  }
  let d=0; arrE=arrS;
  for(let j=arrS;j<html.length;j++){if(html[j]==='[')d++;if(html[j]===']'){d--;if(d===0){arrE=j+1;break;}}}
  let arr = JSON.parse(html.substring(arrS, arrE));
  const maxId = Math.max(...arr.map(r=>r.id));
  let nextId = maxId + 1;
  const existing = new Set(arr.map(r=>r.name.toLowerCase()));
  let added = 0;
  spots.forEach(s => {
    if(existing.has(s.name.toLowerCase())) return;
    s.id=nextId++;s.bestOf=[];s.busyness=null;s.waitTime=null;s.popularTimes=null;s.lastUpdated=null;s.trending=s.trending||false;s.group=s.group||'';s.suburb=s.suburb||false;s.menuUrl='';s.res_tier=s.price>=3?4:2;s.indicators=s.indicators||[];s.awards=s.awards||'';s.phone=s.phone||'';s.reserveUrl=s.reserveUrl||'';s.hh=s.hh||'';
    arr.push(s);existing.add(s.name.toLowerCase());added++;
  });
  html = html.substring(0, arrS) + JSON.stringify(arr) + html.substring(arrE);
  console.log(cityKey+':', added, 'added. Total:', arr.length);
}

// === 18 MORE CHICAGO ===
addToCity('Chicago', false, [
  {name:"Cafe Ba-Ba-Reeba!",cuisine:"Spanish Tapas",neighborhood:"Lincoln Park",score:87,price:2,tags:["Spanish","Date Night","Patio","Local Favorites"],description:"Lincoln Park Spanish tapas that has been the neighborhood sangria-and-patatas-bravas destination since 1985. The paella is shareable, the chorizo in cider is excellent, and the patio in summer is one of the most fun in the city. Groups thrive here.",dishes:["Patatas Bravas","Paella","Sangria"],address:"2024 N Halsted St, Chicago, IL 60614",lat:41.9177,lng:-87.6484,instagram:"cafebabareeba",website:"https://www.cafebabareeba.com",reservation:"OpenTable",phone:"(773) 935-5000"},
  {name:"The Promontory",cuisine:"New American / Live Music",neighborhood:"Hyde Park",score:86,price:2,tags:["Live Music","Date Night","Local Favorites","Cocktails"],description:"Hyde Park restaurant and music venue with stunning views of Jackson Park and a menu that is much better than a music venue has any right to be. Live jazz, DJ nights, and craft cocktails in a gorgeous modern space. The cultural anchor of Hyde Park nightlife.",dishes:["Craft Cocktails","Live Music","Seasonal Menu"],address:"5311 S Lake Park Ave, Chicago, IL 60615",lat:41.7987,lng:-87.5862,instagram:"thepromontory",website:"https://www.promontorychicago.com",reservation:"Resy",phone:"(312) 801-2100"},
  {name:"Dove's Luncheonette",cuisine:"Tex-Mex Diner",neighborhood:"Wicker Park",score:89,price:1,tags:["Brunch","Local Favorites","Casual"],description:"Wicker Park counter-service diner serving elevated Tex-Mex with a killer vinyl soundtrack. The migas are perfect, the chorizo gravy biscuits are a revelation, and the mezcal list is deep for a diner. Sunday brunch is a neighborhood institution.",dishes:["Migas","Chorizo Gravy Biscuits","Mezcal Selection"],address:"1545 N Damen Ave, Chicago, IL 60622",lat:41.9096,lng:-87.6771,instagram:"dovesluncheonette",website:"https://www.doveschicago.com",reservation:"walk-in",phone:"(773) 645-4060"},
  {name:"North Pond",cuisine:"New American / Fine Dining",neighborhood:"Lincoln Park",score:91,price:3,tags:["Fine Dining","Date Night","Patio","Critics Pick"],description:"A former warming house in Lincoln Park transformed into one of the most romantic restaurants in Chicago. The seasonal, farm-driven menu changes frequently, and the views of the park pond are stunning. Michelin-starred and genuinely worth the splurge.",dishes:["Seasonal Tasting","Farm Salad","Duck Breast"],address:"2610 N Cannon Dr, Chicago, IL 60614",lat:41.9298,lng:-87.6381,instagram:"northpondchicago",website:"https://www.northpondrestaurant.com",reservation:"OpenTable",phone:"(773) 477-5845",awards:"Michelin Star"},
  {name:"Pizza Lobo",cuisine:"Tavern-Style Pizza",neighborhood:"Logan Square",score:86,price:1,tags:["Pizza","Casual","Local Favorites","Late Night"],description:"Logan Square tavern-style pizza that nails the thin, crispy Chicago style with creative seasonal toppings. The crust is properly crackery, the cheese edge caramelizes perfectly, and the cocktails are better than any pizza place deserves. Open late.",dishes:["Tavern-Style Cheese","Sausage & Giardiniera","Seasonal Special"],address:"3000 W Fullerton Ave, Chicago, IL 60647",lat:41.9254,lng:-87.7019,instagram:"pizzalobo",website:"https://www.pizzalobo.com",reservation:"walk-in",phone:"(773) 904-8434"},
  {name:"Kitsune",cuisine:"Japanese / Cafe",neighborhood:"Andersonville",score:87,price:1,tags:["Japanese","Bakery/Coffee","Casual","Local Favorites"],description:"Andersonville Japanese cafe and bakery serving onigiri, Japanese curry, and matcha alongside excellent coffee. The onigiri are made fresh, the curry is rich and comforting, and the space is serene. A different kind of cafe experience.",dishes:["Onigiri","Japanese Curry","Matcha Latte"],address:"4957 N Damen Ave, Chicago, IL 60625",lat:41.9718,lng:-87.6790,instagram:"kitsunechicago",website:"https://www.kitsunechicago.com",reservation:"walk-in",phone:"(773) 999-3474"},
  {name:"Boeufhaus",cuisine:"Steakhouse / German",neighborhood:"West Town",score:88,price:2,tags:["Steakhouse","Date Night","Local Favorites"],description:"West Town butcher shop meets steakhouse with a German accent. The dry-aged steaks are excellent, the bone marrow is decadent, and the pretzel with beer cheese is the perfect starter. BYOB makes it one of the best steak values in the city.",dishes:["Dry-Aged Ribeye","Bone Marrow","Pretzel with Beer Cheese"],address:"1012 N Western Ave, Chicago, IL 60622",lat:41.8999,lng:-87.6870,instagram:"boeufhaus",website:"https://www.boeufhaus.com",reservation:"Resy",phone:"(773) 661-2116"},
  {name:"Funkenhausen",cuisine:"German / Southern",neighborhood:"West Town",score:87,price:2,tags:["Local Favorites","Date Night","Casual"],description:"German-meets-Southern comfort food in West Town that sounds crazy but works beautifully. The schnitzel is crispy and huge, the spaetzle with braised pork is heavenly, and the beer list is properly German. The kind of creative mashup that only Chicago could produce.",dishes:["Pork Schnitzel","Spaetzle","German Beer Selection"],address:"1709 W Chicago Ave, Chicago, IL 60622",lat:41.8967,lng:-87.6710,instagram:"funkenhausen",website:"https://www.funkenhausen.com",reservation:"Resy",phone:"(312) 929-4727"},
  {name:"Cafe Marie-Jeanne",cuisine:"French / Cafe",neighborhood:"Humboldt Park",score:88,price:2,tags:["French","Brunch","Local Favorites","Casual"],description:"Humboldt Park French cafe with a counter-service lunch and a proper sit-down dinner that punches way above its weight. The croque madame is perfect, the steak tartare is classic, and the wine list is short but well-chosen. A neighborhood gem.",dishes:["Croque Madame","Steak Tartare","Country Pate"],address:"1001 N California Ave, Chicago, IL 60622",lat:41.8999,lng:-87.6975,instagram:"cafemariejeanne",website:"https://www.cafe-marie-jeanne.com",reservation:"walk-in",phone:"(773) 904-7660"},
  {name:"Owen & Engine",cuisine:"British Gastropub",neighborhood:"Logan Square",score:87,price:2,tags:["Local Favorites","Casual","Cocktails","Late Night"],description:"Logan Square British gastropub with a serious cocktail program and elevated pub food. The burger is one of the best in Chicago, the Scotch egg is a proper rendition, and the whisky list is deep. Dark, moody, and the perfect neighborhood bar-restaurant hybrid.",dishes:["Burger","Scotch Egg","Fish & Chips"],address:"2700 N Western Ave, Chicago, IL 60647",lat:41.9292,lng:-87.6868,instagram:"owenandengine",website:"https://www.owenandengine.com",reservation:"walk-in",phone:"(773) 235-2930"},
  {name:"Table, Donkey and Stick",cuisine:"Alpine European",neighborhood:"Logan Square",score:88,price:2,tags:["Date Night","Local Favorites","Critics Pick"],description:"Alpine-inspired Logan Square restaurant with fondue, raclette, and hearty European mountain food. The raclette melted over potatoes and pickles is a showstopper, the spaetzle is addictive, and the vibe is cozy and warm. The most unique concept in Logan Square.",dishes:["Raclette","Spaetzle","Fondue"],address:"2728 W Armitage Ave, Chicago, IL 60647",lat:41.9173,lng:-87.6958,instagram:"tabledonkeystick",website:"https://www.tabledonkeyandstick.com",reservation:"Resy",phone:"(773) 486-8525"},
  {name:"Margie's Candies",cuisine:"Ice Cream / Diner",neighborhood:"Bucktown",score:85,price:1,tags:["Dessert","Iconic","Local Favorites","Family"],description:"Bucktown ice cream parlor since 1921 serving massive sundaes in actual seashell bowls. Al Capone was reportedly a regular. The hot fudge sundae is the classic order, and the portions are comically large. A Chicago institution that has survived a century for good reason.",dishes:["Hot Fudge Sundae","Banana Split","Turtle Sundae"],address:"1960 N Western Ave, Chicago, IL 60647",lat:41.9171,lng:-87.6868,instagram:"margiescandies",website:"https://www.margiescandies.com",reservation:"walk-in",phone:"(773) 384-1035"},
  {name:"Half Acre Beer Company",cuisine:"Brewery / Taproom",neighborhood:"North Center",score:86,price:1,tags:["Brewery","Casual","Local Favorites","Patio"],indicators:["brewery"],description:"North Center craft brewery with a massive taproom, food menu, and one of the best beer gardens in Chicago. The Daisy Cutter pale ale is a Chicago classic, the rotating IPAs are excellent, and the weekend brunch with beer pairings is genius.",dishes:["Daisy Cutter Pale Ale","Rotating IPAs","Beer Garden Brunch"],address:"4257 N Lincoln Ave, Chicago, IL 60618",lat:41.9579,lng:-87.6843,instagram:"halfacrebeer",website:"https://www.halfacrebeer.com",reservation:"walk-in",phone:"(773) 248-4038"},
  {name:"Pizano's Pizza & Pasta",cuisine:"Deep Dish Pizza",neighborhood:"The Loop",score:85,price:1,tags:["Pizza","Local Favorites","Casual","Family"],description:"Rudy Malnati Jr pizza that some locals argue is better than his brother Lou. The butter crust thin-crust with sausage is the insider order, and the deep dish is reliably excellent.",dishes:["Thin Crust Sausage","Deep Dish","Pasta"],address:"61 E Madison St, Chicago, IL 60602",lat:41.8819,lng:-87.6257,instagram:"pizanoschicago",website:"https://www.pizanos.com",reservation:"walk-in",phone:"(312) 236-1777"},
  {name:"Stan's Donuts & Coffee",cuisine:"Donuts / Coffee",neighborhood:"Wicker Park",score:85,price:1,tags:["Bakery/Coffee","Dessert","Casual","Local Favorites"],description:"Chicago donut chain that makes everything fresh daily with creative flavors like pistachio old fashioned and Biscoff pocket. The glazed donut is simple and perfect, the coffee is well-sourced, and the Wicker Park location has the most energy. Multiple locations.",dishes:["Pistachio Old Fashioned","Biscoff Pocket","Glazed Donut"],address:"1560 N Damen Ave, Chicago, IL 60622",lat:41.9096,lng:-87.6771,instagram:"stansdonuts",website:"https://www.stansdonuts.com",reservation:"walk-in",phone:"(773) 360-7386"},
  {name:"Small Cheval",cuisine:"Burgers",neighborhood:"Wicker Park",score:87,price:1,tags:["Local Favorites","Casual","Late Night"],description:"The casual burger-only sibling of Au Cheval with the same incredible double cheeseburger but without the two-hour wait. The menu is four items: single, double, fries, and a shake. That is all you need. Multiple locations.",dishes:["Double Cheeseburger","Fries","Milkshake"],address:"1732 N Milwaukee Ave, Chicago, IL 60647",lat:41.9121,lng:-87.6838,instagram:"smallcheval",website:"https://www.smallcheval.com",reservation:"walk-in",phone:"(773) 235-0600"},
  {name:"Revival Food Hall",cuisine:"Food Hall",neighborhood:"The Loop",score:86,price:1,tags:["Local Favorites","Casual","Healthy"],description:"Loop food hall with 15 chef-driven stalls that make downtown lunch actually exciting. Smoque BBQ, Antique Taco, Danke, and Harvest Juicery all under one roof. The quality is consistently above average for a food hall, and the Loop crowd keeps it buzzing.",dishes:["Smoque BBQ Brisket","Antique Tacos","Harvest Juice"],address:"125 S Clark St, Chicago, IL 60603",lat:41.8798,lng:-87.6303,instagram:"revivalfoodhall",website:"https://www.revivalfoodhall.com",reservation:"walk-in",phone:"(773) 999-9411"},
  {name:"5 Rabanitos",cuisine:"Mexican / Oaxacan",neighborhood:"Pilsen",score:87,price:1,tags:["Mexican","Local Favorites","Casual","Brunch"],description:"Pilsen Oaxacan restaurant with moles that take days to make and memelitas that are handmade to order. The mole negro is complex and earned, the tlayudas are crispy and loaded, and the mezcal selection is proper. Sunday brunch with live mariachi is a neighborhood event.",dishes:["Mole Negro","Tlayuda","Memelitas"],address:"1758 W 18th St, Chicago, IL 60608",lat:41.8578,lng:-87.6685,instagram:"5rabanitos",website:"https://www.5rabanitos.com",reservation:"walk-in",phone:"(312) 578-9747"}
]);

// === 93 MORE HOUSTON ===
addToCity('HOUSTON_DATA', true, [
  {name:"Uchi Houston",cuisine:"Japanese",neighborhood:"Montrose",score:94,price:3,tags:["Japanese","Sushi","Date Night","Fine Dining","Critics Pick"],description:"Tyson Cole Austin-born Japanese sensation brought to Montrose in a cool bungalow setting. The maguro sashimi with goat cheese and Asian pear is a signature, the omakase is pristine, and the hot and cold tastings are endlessly creative. The best Japanese restaurant in Houston.",dishes:["Maguro Sashimi","Hama Chili","Wagyu Tataki"],address:"904 Westheimer Rd, Houston, TX 77006",lat:29.7447,lng:-95.3887,instagram:"uchihouston",website:"https://www.uchirestaurants.com/uchi/houston",reservation:"Resy",phone:"(713) 522-4808"},
  {name:"Underbelly Hospitality / Georgia James",cuisine:"Steakhouse / BBQ",neighborhood:"Montrose",score:94,price:3,tags:["BBQ","Steakhouse","Critics Pick","Date Night"],description:"Chris Shepherd whole-animal steakhouse smoking prime brisket over Texas post oak. The prime brisket is the centerpiece -- perfectly smoky with a bark that shatters. The beef ribs are massive. James Beard Award-winning and redefined what Houston BBQ could be.",dishes:["Prime Brisket","Beef Ribs","Smoked Sausage"],address:"1100 W Dallas St, Houston, TX 77019",lat:29.7575,lng:-95.3776,instagram:"georgiajamesbbq",website:"https://www.georgiajamesbbq.com",reservation:"Resy",phone:"(713) 862-0100",awards:"James Beard Award"},
  {name:"Le Jardinier",cuisine:"French / Vegetable-Forward",neighborhood:"Museum District",score:91,price:3,tags:["French","Fine Dining","Date Night","Patio","Healthy"],description:"Alain Verzeroli vegetable-forward French inside MFAH. Produce treated with the reverence most places reserve for wagyu. The garden terrace is one of the most elegant dining settings in the city. Seasonal menu with genuine intention.",dishes:["Seasonal Vegetable Tasting","Dover Sole","Garden Terrace Lunch"],address:"1180 Main St, Houston, TX 77002",lat:29.7246,lng:-95.3888,instagram:"lejardinierhouston",website:"https://www.lejardinier-houston.com",reservation:"Resy",phone:"(346) 227-5512"},
  {name:"Pappadeaux Seafood Kitchen",cuisine:"Cajun Seafood",neighborhood:"Multiple Locations",score:86,price:2,tags:["Seafood","Local Favorites","Family","Casual"],description:"Houston Cajun seafood chain that locals swear by. The crawfish etouffee is rich and proper, the blackened redfish is perfectly charred, and the portions are Texas-sized. Multiple locations across the city. The Pappas family knows how to feed Houston.",dishes:["Crawfish Etouffee","Blackened Redfish","Fried Catfish"],address:"6015 Westheimer Rd, Houston, TX 77057",lat:29.7367,lng:-95.4852,instagram:"pappadeaux",website:"https://www.pappadeaux.com",reservation:"walk-in",phone:"(713) 782-6310"},
  {name:"Coltivare",cuisine:"Italian / Farm to Table",neighborhood:"Heights",score:89,price:2,tags:["Italian","Date Night","Local Favorites","Patio"],description:"Heights Italian from Ryan Pera with a working garden out back that supplies the kitchen. The handmade pasta is excellent, the wood-fired pizzas have proper char, and the patio overlooking the garden is one of the most charming in Houston. BYOB-friendly.",dishes:["Handmade Pasta","Wood-Fired Pizza","Garden Salad"],address:"3320 White Oak Dr, Houston, TX 77007",lat:29.7779,lng:-95.3997,instagram:"coltivarehouston",website:"https://www.coltivarehouston.com",reservation:"Resy",phone:"(713) 637-4095"},
  {name:"Pondicheri",cuisine:"Indian / Cafe",neighborhood:"Upper Kirby",score:88,price:2,tags:["Indian","Brunch","Local Favorites","Healthy"],description:"Anita Jaisinghani modern Indian that does breakfast, lunch, and dinner with equal care. The dosa bar at brunch is a Houston original, the naan pizzas are creative, and the chai is properly spiced. Indian food for people who want more than tikka masala.",dishes:["Dosa Bar","Naan Pizza","Masala Chai"],address:"2800 Kirby Dr, Houston, TX 77098",lat:29.7367,lng:-95.4142,instagram:"pondichericafe",website:"https://www.pondicheri.com",reservation:"OpenTable",phone:"(713) 522-2022"},
  {name:"Eight Row Flint",cuisine:"Tex-Mex / Bar",neighborhood:"Heights",score:87,price:1,tags:["Mexican","Local Favorites","Patio","Happy Hour","Casual"],description:"Heights taco and whiskey joint with a tin-roof patio that is the most Houston outdoor dining experience possible. Frozen margaritas, smoked meat tacos, and a vibe that is pure laid-back Texas. The frozen ranch water is dangerously easy to drink.",dishes:["Frozen Ranch Water","Brisket Taco","Smoked Chicken Taco"],address:"1039 Yale St, Houston, TX 77008",lat:29.7889,lng:-95.3963,instagram:"eightrowflint",website:"https://www.eightrowflint.com",reservation:"walk-in",phone:"(713) 864-2386"},
  {name:"Lucille's",cuisine:"Southern / Soul Food",neighborhood:"Museum District",score:89,price:2,tags:["Southern","Brunch","Local Favorites","Critics Pick"],description:"Chris Williams modern Southern honoring his great-grandmother Lucille namesake. The fried chicken is some of the best in the city, the oxtail is braised to perfection, and the Sunday brunch is a Houston institution. Michelin Bib Gourmand and deeply personal.",dishes:["Fried Chicken","Oxtail","Sunday Brunch"],address:"5512 La Branch St, Houston, TX 77004",lat:29.7288,lng:-95.3770,instagram:"lucilleshouston",website:"https://www.lucilleshouston.com",reservation:"Resy",phone:"(713) 568-2505",awards:"Michelin Bib Gourmand"},
  {name:"The Dunlavy",cuisine:"American / Cafe",neighborhood:"Buffalo Bayou Park",score:86,price:2,tags:["Brunch","Patio","Date Night","Local Favorites"],description:"A glass-walled pavilion in Buffalo Bayou Park that is the most beautiful brunch setting in Houston. The seasonal menu is light and fresh, the pastries are excellent, and the bayou views make every meal feel like an event. Weddings book here for a reason.",dishes:["Seasonal Brunch","Pastries","Bayou Views"],address:"3422 Allen Pkwy, Houston, TX 77019",lat:29.7621,lng:-95.3868,instagram:"thedunlavy",website:"https://www.thedunlavy.com",reservation:"OpenTable",phone:"(713) 360-6477"},
  {name:"Riel",cuisine:"Southern / Gulf Coast",neighborhood:"Montrose",score:90,price:2,tags:["Southern","Seafood","Date Night","Critics Pick"],description:"Ryan Lachaine love letter to the Gulf Coast, blending Cajun, Vietnamese, and Texas influences into a menu that is as diverse as Houston itself. The boudin kolache is a genius mashup, the Gulf fish is perfectly prepared, and the cocktails are outstanding.",dishes:["Boudin Kolache","Gulf Fish","Duck Confit"],address:"1927 Fairview St, Houston, TX 77019",lat:29.7454,lng:-95.3938,instagram:"rielrestaurant",website:"https://www.rielrestaurant.com",reservation:"Resy",phone:"(832) 831-9109"},
  {name:"Gatlin's BBQ",cuisine:"Texas BBQ",neighborhood:"Heights",score:90,price:1,tags:["BBQ","Local Favorites","Casual"],description:"Greg Gatlin family BBQ with brisket, ribs, and turkey that puts most BBQ joints to shame. The beef rib on weekends is a showstopper, and the sides (mac and cheese, loaded baked potato salad) are homestyle perfection. A Houston BBQ essential.",dishes:["Brisket","Beef Rib (Weekend)","Mac and Cheese"],address:"3510 Ella Blvd, Houston, TX 77018",lat:29.8108,lng:-95.4126,instagram:"gatlinsbbq",website:"https://www.gatlinsbbq.com",reservation:"walk-in",phone:"(713) 869-4227"},
  {name:"Indigo",cuisine:"Cajun / Southern",neighborhood:"Midtown",score:89,price:2,tags:["Southern","Date Night","Local Favorites","Critics Pick"],description:"Jonny Rhodes Cajun-Southern fine dining that draws from his Afro-Creole heritage and Houston Third Ward upbringing. The boudin is house-made, the gumbo is deeply flavored, and every dish tells a story about the Gulf South. Michelin Bib Gourmand.",dishes:["House-Made Boudin","Seafood Gumbo","Fried Catfish"],address:"517 Berry St, Houston, TX 77022",lat:29.7908,lng:-95.3585,instagram:"indigohouston",website:"https://www.indigohouston.com",reservation:"Resy",phone:"(713) 999-6427",awards:"Michelin Bib Gourmand"},
  {name:"Tiger Den",cuisine:"Chinese / Cantonese",neighborhood:"Chinatown / Bellaire",score:88,price:1,tags:["Chinese","Local Favorites","Casual","Late Night"],description:"Bellaire Blvd Cantonese restaurant that stays packed until midnight. The wonton noodle soup is clean and perfect, the roast duck is properly lacquered, and the congee at 11 PM is the best comfort food in Houston. The Chinatown stalwart that never disappoints.",dishes:["Wonton Noodle Soup","Roast Duck","Congee"],address:"9889 Bellaire Blvd, Houston, TX 77036",lat:29.7061,lng:-95.5571,instagram:"tigerdenhouston",website:"",reservation:"walk-in",phone:"(713) 988-6310"},
  {name:"Nam Giao",cuisine:"Vietnamese",neighborhood:"Midtown",score:87,price:1,tags:["Vietnamese","Local Favorites","Casual","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"Midtown Vietnamese that serves some of the best bun bo hue in Houston -- a spicy, funky, deeply satisfying lemongrass beef noodle soup that is the more complex cousin of pho. The spring rolls are fresh, the vermicelli bowls are excellent, and the prices are a steal.",dishes:["Bun Bo Hue","Spring Rolls","Vermicelli Bowl"],address:"6938 Harrisburg Blvd, Houston, TX 77011",lat:29.7386,lng:-95.3016,instagram:"",website:"",reservation:"walk-in",phone:"(713) 923-3868"},
  {name:"The Pass & Provisions",cuisine:"New American / Fine Dining",neighborhood:"Montrose",score:91,price:3,tags:["Fine Dining","Date Night","Critics Pick"],description:"Two restaurants in one -- The Pass is a 30-seat tasting menu experience, and Provisions is a casual bakery-restaurant. Seth Siegel-Gardner runs both with equal intensity. The tasting menu is one of the most inventive in Houston, and Provisions brunch is outstanding.",dishes:["Tasting Menu (The Pass)","Artisan Bread","Brunch"],address:"807 Taft St, Houston, TX 77019",lat:29.7466,lng:-95.3911,instagram:"thepassandprovisions",website:"https://www.thepassandprovisions.com",reservation:"Resy",phone:"(713) 628-9020"},
  {name:"Feges BBQ",cuisine:"Texas BBQ",neighborhood:"Greenway Plaza",score:89,price:1,tags:["BBQ","Local Favorites","Casual","Healthy"],description:"Patrick Feges and Erin Smith BBQ that brings a chef-driven approach to Texas tradition. The brisket is properly smoked, but the real stars are the creative sides -- smoked turkey salad, elote, and seasonal specials that elevate BBQ beyond meat and white bread.",dishes:["Brisket","Turkey Salad","Elote"],address:"3 Greenway Plaza, Houston, TX 77046",lat:29.7367,lng:-95.4343,instagram:"fegesbbq",website:"https://www.fegesbbq.com",reservation:"walk-in",phone:"(832) 742-7675"},
  {name:"UB Preserv",cuisine:"New American / Asian-Influenced",neighborhood:"Montrose",score:90,price:2,tags:["Local Favorites","Date Night","Critics Pick","Casual"],description:"Chris Shepherd Underbelly Hospitality latest concept in Montrose. The menu draws from Houston diverse immigrant communities, with dishes that honor Korean, Vietnamese, Mexican, and Southern traditions. The Korean braised goat dumplings are a signature. Michelin Bib Gourmand.",dishes:["Korean Goat Dumplings","Charred Carrots","Seasonal Desserts"],address:"1609 Westheimer Rd, Houston, TX 77006",lat:29.7442,lng:-95.3938,instagram:"ubpreserv",website:"https://www.ubpreserv.com",reservation:"Resy",phone:"(346) 406-3663",awards:"Michelin Bib Gourmand"},
  {name:"Tobiuo Sushi & Bar",cuisine:"Japanese / Sushi",neighborhood:"Cypress",score:90,price:2,tags:["Japanese","Sushi","Date Night","Local Favorites"],description:"A suburban sushi bar in Cypress that has no business being this good. Chef Chris Kinjo omakase rivals Montrose spots at half the price. The fish is flown in from Tsukiji, the rice is perfect, and the neighborhood location means no wait. Houston best sushi secret.",dishes:["Omakase","Nigiri Selection","Wagyu Sashimi"],address:"23501 Cinco Ranch Blvd, Katy, TX 77494",lat:29.7369,lng:-95.7550,instagram:"tobiuosushi",website:"https://www.tobiuosushi.com",reservation:"OpenTable",phone:"(281) 394-7156",suburb:true},
  {name:"Roost",cuisine:"Southern / New American",neighborhood:"Montrose",score:88,price:2,tags:["Southern","Date Night","Local Favorites","Brunch"],description:"Kevin Naderi Southern-influenced Montrose restaurant with a gorgeous bar and one of the best brunch menus in the neighborhood. The fried chicken is brined and crispy, the biscuits are flaky, and the patio is perfect for a lazy Saturday morning.",dishes:["Fried Chicken","Biscuits","Saturday Brunch"],address:"1972 Fairview St, Houston, TX 77019",lat:29.7454,lng:-95.3955,instagram:"roosthtx",website:"https://www.iloveroost.com",reservation:"OpenTable",phone:"(713) 523-7667"},
  {name:"Tacos A Go Go",cuisine:"Mexican / Tacos",neighborhood:"Heights",score:85,price:1,tags:["Mexican","Local Favorites","Casual","Brunch","Family"],description:"Houston taco mini-chain that does breakfast tacos with a creativity that goes beyond the standard BEC. The migas taco is the cult order, the green sauce is addictive, and the corn tortillas are properly thick. Multiple locations, Heights original is the best.",dishes:["Migas Taco","Brisket Taco","Green Sauce"],address:"3704 Main St, Houston, TX 77002",lat:29.7431,lng:-95.3816,instagram:"tacosagogo",website:"https://www.tacosagogo.com",reservation:"walk-in",phone:"(713) 807-8226"},
  {name:"Theodore Rex",cuisine:"New American",neighborhood:"East Downtown / EaDo",score:91,price:2,tags:["Fine Dining","Date Night","Critics Pick","Local Favorites"],description:"Justin Yu downtown tasting menu spot that broke boundaries when it opened. The hyper-seasonal menu draws from local farms and global technique, and the open kitchen lets you watch every plate come together. Intimate, inventive, and essential.",dishes:["Seasonal Tasting","Market Fish","Foraged Vegetables"],address:"1302 Nance St, Houston, TX 77002",lat:29.7569,lng:-95.3527,instagram:"theodore_rex_houston",website:"https://www.theodorerex.com",reservation:"Resy",phone:"(713) 228-2525"},
  {name:"Brasserie du Parc",cuisine:"French Brasserie",neighborhood:"Downtown",score:87,price:2,tags:["French","Date Night","Patio"],description:"Downtown French brasserie at Discovery Green with classic bistro fare and one of the best patios in downtown Houston. The steak frites is proper, the moules mariniere are plump, and the outdoor seating overlooking the park makes every meal feel like Paris-by-way-of-Texas.",dishes:["Steak Frites","Moules Mariniere","Croque Monsieur"],address:"1440 Lamar St, Houston, TX 77010",lat:29.7529,lng:-95.3589,instagram:"brasserieduparc",website:"https://www.brasserieduparc.com",reservation:"OpenTable",phone:"(713) 942-7272"},
  {name:"B&B Butchers & Restaurant",cuisine:"Steakhouse",neighborhood:"Washington Corridor",score:91,price:3,tags:["Steakhouse","Date Night","Celebrations","Fine Dining"],description:"Washington Avenue steakhouse with an on-site butcher shop and some of the best dry-aged beef in Houston. The 45-day dry-aged ribeye is extraordinary, the ice cream sandwich dessert is massive, and the rooftop bar has skyline views. A proper Texas steakhouse.",dishes:["45-Day Dry-Aged Ribeye","Rooftop Bar","Ice Cream Sandwich"],address:"1814 Washington Ave, Houston, TX 77007",lat:29.7630,lng:-95.3862,instagram:"bbbutchers",website:"https://www.bbbutchers.com",reservation:"OpenTable",phone:"(713) 862-1814"},
  {name:"Hugo's",cuisine:"Regional Mexican",neighborhood:"Montrose",score:90,price:2,tags:["Mexican","Local Favorites","Critics Pick","Brunch"],description:"Hugo Ortega flagship Montrose Mexican that introduced Houston to the depth of regional Mexican cooking. The moles take days to prepare, the cochinita pibil is wrapped in banana leaves, and the Sunday brunch buffet is a Houston institution.",dishes:["Mole Negro","Cochinita Pibil","Sunday Brunch Buffet"],address:"1600 Westheimer Rd, Houston, TX 77006",lat:29.7442,lng:-95.3931,instagram:"hugosrestaurant",website:"https://www.hugosrestaurant.net",reservation:"OpenTable",phone:"(713) 524-7744"},
  {name:"Underbelly Hospitality / Wild Oats",cuisine:"Southern / Global",neighborhood:"Montrose",score:91,price:2,tags:["Local Favorites","Critics Pick","Casual","Brunch"],description:"Chris Shepherd latest Montrose concept focusing on Southern comfort with global accents. The Korean braised goat is a signature, the bread service is outstanding, and the brunch is one of the most exciting in the city.",dishes:["Korean Braised Goat","Bread Service","Brunch Menu"],address:"3408 Harrisburg Blvd, Houston, TX 77003",lat:29.7385,lng:-95.3480,instagram:"wildoatshouston",website:"https://www.wildoatshouston.com",reservation:"Resy",phone:"(346) 406-3663"},
  {name:"Crawfish & Noodles",cuisine:"Vietnamese-Cajun Crawfish",neighborhood:"Chinatown / Bellaire",score:90,price:1,tags:["Vietnamese","Cajun","Local Favorites","Seafood"],description:"The restaurant that invented Viet-Cajun crawfish and changed Houston food forever. Trong Nguyen garlic butter crawfish with Vietnamese spices is a flavor bomb that spawned a thousand imitators. The original and still the best. Come hungry.",dishes:["Garlic Butter Crawfish","Viet-Cajun Crawfish","Garlic Noodles"],address:"11360 Bellaire Blvd, Houston, TX 77072",lat:29.7038,lng:-95.5755,instagram:"crawfishandnoodles",website:"https://www.crawfishandnoodles.com",reservation:"walk-in",phone:"(281) 988-8098"},
  {name:"Mala Sichuan Bistro",cuisine:"Sichuan Chinese",neighborhood:"Chinatown / Bellaire",score:89,price:1,tags:["Chinese","Local Favorites","Casual"],description:"Bellaire Sichuan that takes the heat seriously -- the mala dry pot is properly numbing, the dan dan noodles are rich and spicy, and the cumin lamb is fragrant. The best Sichuan in Houston and one of the best outside of China. Bring tissues.",dishes:["Mala Dry Pot","Dan Dan Noodles","Cumin Lamb"],address:"9348 Bellaire Blvd, Houston, TX 77036",lat:29.7061,lng:-95.5391,instagram:"malasichuanbistro",website:"https://www.malasichuanbistro.com",reservation:"walk-in",phone:"(713) 773-7718"},
  {name:"Pho Binh",cuisine:"Vietnamese / Pho",neighborhood:"Heights",score:87,price:1,tags:["Vietnamese","Local Favorites","Casual","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"Heights pho shop famous for both its excellent broth and its history -- it was a secret meeting place for South Vietnamese military during the war. The pho is rich and clean, the banh mi is crusty, and the history is written on the walls.",dishes:["Pho Tai","Banh Mi","Spring Rolls"],address:"2200 N Shepherd Dr, Houston, TX 77008",lat:29.7928,lng:-95.4070,instagram:"phobinhheights",website:"",reservation:"walk-in",phone:"(713) 864-3500"},
  {name:"Killen's BBQ",cuisine:"Texas BBQ",neighborhood:"Pearland",score:95,price:1,tags:["BBQ","Local Favorites","Iconic","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"Ronnie Killen turned a Pearland strip mall into one of the most celebrated BBQ joints in Texas. The beef ribs are massive, the brisket has a bark that shatters, and the burnt ends are life-changing. Worth every minute of the line.",dishes:["Beef Ribs","Prime Brisket","Burnt Ends"],address:"3613 E Broadway St, Pearland, TX 77581",lat:29.5583,lng:-95.2728,instagram:"killensbbq",website:"https://www.killensbbq.com",reservation:"walk-in",phone:"(281) 485-2272",suburb:true},
  {name:"The Toasted Coconut",cuisine:"Tiki Bar / Cocktails",neighborhood:"Rice Village",score:87,price:2,tags:["Cocktails","Late Night","Casual","Local Favorites"],description:"Rice Village tiki bar with proper tropical cocktails, a small but excellent food menu, and a vibe that transports you from Houston humidity to a tropical island. The rum punch is dangerously easy, the coconut shrimp is crispy, and the patio is a hidden gem.",dishes:["Rum Punch","Coconut Shrimp","Tiki Cocktails"],address:"5765 Richmond Ave, Houston, TX 77057",lat:29.7300,lng:-95.4503,instagram:"thetoastedcoconut",website:"https://www.thetoastedcoconuthtx.com",reservation:"walk-in",phone:"(832) 742-2478"},
  {name:"Pho Saigon",cuisine:"Vietnamese / Pho",neighborhood:"Chinatown / Bellaire",score:86,price:1,tags:["Vietnamese","Local Favorites","Casual"],description:"Bellaire pho institution that has been serving clean, deeply flavored broth to Houston Viet community for decades. The pho tai is the standard -- rare beef that cooks in the hot broth -- and the portions are enormous for the price. Cash only. No frills. Perfect pho.",dishes:["Pho Tai","Pho Dac Biet","Bun Bo Hue"],address:"8200 Wilcrest Dr, Houston, TX 77072",lat:29.7105,lng:-95.5602,instagram:"",website:"",reservation:"walk-in",phone:"(713) 339-8070"},
  {name:"Xochi",cuisine:"Oaxacan Mexican",neighborhood:"Downtown",score:93,price:3,tags:["Mexican","Fine Dining","Critics Pick","Date Night"],description:"Hugo Ortega love letter to Oaxacan cuisine inside the Marriott Marquis. The mole negro takes days to make. The chocolate desserts are world-class. One of the most important Mexican restaurants in America.",dishes:["Mole Negro","Cacao Nib Crusted Lamb","Chocolate Dessert Tasting"],address:"1777 Walker St, Houston, TX 77010",lat:29.7528,lng:-95.3585,instagram:"xochihouston",website:"https://www.xochihouston.com",reservation:"OpenTable",phone:"(713) 400-3330"},
  {name:"Cafe Annie / The Annie Cafe & Bar",cuisine:"Southwestern",neighborhood:"Galleria",score:90,price:3,tags:["Fine Dining","Local Favorites","Date Night"],description:"Robert Del Grande reinvention of his legendary Cafe Annie at Hotel Granduca. Southwestern menu with famous tamales and Gulf Coast seafood. A Houston dining legend continues.",dishes:["Tamales","Gulf Seafood","Wood-Grilled Ribeye"],address:"1728 Post Oak Blvd, Houston, TX 77056",lat:29.7459,lng:-95.4612,instagram:"theanniehouston",website:"https://www.theanniehouston.com",reservation:"OpenTable",phone:"(713) 840-1111"},
  {name:"Oporto Fooding House",cuisine:"Portuguese / Tapas",neighborhood:"Montrose",score:88,price:2,tags:["Portuguese","Date Night","Local Favorites","Wine Bar"],description:"Montrose Portuguese wine bar and restaurant with pasteis de nata, grilled octopus, and a wine list that goes deep on Portuguese varietals. The patio is gorgeous, the croquettes are crispy, and the vibe is relaxed European. A unique addition to Houston.",dishes:["Pasteis de Nata","Grilled Octopus","Portuguese Croquettes"],address:"3833 Richmond Ave, Houston, TX 77027",lat:29.7337,lng:-95.4325,instagram:"oportofh",website:"https://www.oportofoodinghouse.com",reservation:"OpenTable",phone:"(713) 621-1114"},
  {name:"Kata Robata",cuisine:"Japanese / Sushi",neighborhood:"Upper Kirby",score:91,price:3,tags:["Japanese","Sushi","Date Night","Fine Dining"],description:"Manabu Horiuchi sushi and robata grill that is one of the most consistently excellent Japanese restaurants in Houston. The omakase is pristine, the hot rock wagyu is a signature, and the sake list is one of the deepest in Texas. Serious sushi without the Montrose commute.",dishes:["Omakase","Hot Rock Wagyu","Sake Selection"],address:"3600 Kirby Dr, Houston, TX 77098",lat:29.7326,lng:-95.4142,instagram:"katarobata",website:"https://www.katarobata.com",reservation:"OpenTable",phone:"(713) 526-8858"},
  {name:"BCN Taste & Tradition",cuisine:"Spanish / Catalan",neighborhood:"Montrose",score:90,price:2,tags:["Spanish","Date Night","Local Favorites","Wine Bar"],description:"Michelin Bib Gourmand Spanish bringing authentic Catalan cuisine to Montrose. The paella takes 45 minutes and worth every second, the jamon iberico is carved tableside, and the crema catalana is a perfect closer.",dishes:["Paella","Jamon Iberico","Crema Catalana"],address:"4210 Roseland St, Houston, TX 77006",lat:29.7367,lng:-95.3888,instagram:"bcnhouston",website:"https://www.bcnhouston.com",reservation:"OpenTable",phone:"(713) 588-4239",awards:"Michelin Bib Gourmand"},
  {name:"El Tiempo Cantina",cuisine:"Tex-Mex",neighborhood:"Washington Corridor",score:89,price:2,tags:["Mexican","Local Favorites","Family","Margaritas"],description:"The Laurenzo family Tex-Mex dynasty descended from the original Ninfa. The beef fajitas sizzle louder than anywhere in town, the margaritas are potent, and the green sauce is legendary.",dishes:["Beef Fajitas","Green Sauce","Margaritas"],address:"2814 Navigation Blvd, Houston, TX 77003",lat:29.7541,lng:-95.3517,instagram:"eltiempocantina",website:"https://www.eltiempocantina.com",reservation:"walk-in",phone:"(713) 222-5463"},
  {name:"Goode Company BBQ",cuisine:"Texas BBQ",neighborhood:"West University",score:87,price:1,tags:["BBQ","Local Favorites","Casual","Family","Iconic"],description:"Houston BBQ institution since 1977 with mesquite-smoked brisket, Czech sausage, and pecan pie. The barn-style dining room on Kirby is a landmark. Not the trendiest but the most consistent over four decades.",dishes:["Mesquite Brisket","Czech Sausage","Pecan Pie"],address:"5109 Kirby Dr, Houston, TX 77098",lat:29.7309,lng:-95.4142,instagram:"goodecompany",website:"https://www.goodecompany.com",reservation:"walk-in",phone:"(713) 522-2530"},
  {name:"Pappas Bros. Steakhouse",cuisine:"Steakhouse",neighborhood:"Galleria",score:93,price:4,tags:["Steakhouse","Date Night","Fine Dining","Celebrations"],description:"The best steakhouse in Houston and a genuine contender for best in Texas. Dry-aged prime cuts, lobster bisque, and old-school clubhouse atmosphere. The Pappas family takes steak very seriously.",dishes:["Dry-Aged Prime Bone-In Ribeye","Lobster Bisque","Creamed Spinach"],address:"5839 Westheimer Rd, Houston, TX 77057",lat:29.7367,lng:-95.4888,instagram:"pappasbros",website:"https://www.pappasbros.com",reservation:"OpenTable",phone:"(713) 780-7352"},
  {name:"Ninfa's on Navigation",cuisine:"Tex-Mex",neighborhood:"Navigation District",score:90,price:2,tags:["Mexican","Local Favorites","Iconic","Family"],description:"The original Ninfa -- where fajitas were literally invented in 1973. Mama Ninfa started grilling skirt steak and serving it on tortillas, and changed American food forever. The green sauce is legendary, the tacos al carbon are perfect, and the history is on every wall.",dishes:["Tacos al Carbon","Green Sauce","Fajitas"],address:"2704 Navigation Blvd, Houston, TX 77003",lat:29.7541,lng:-95.3517,instagram:"ninfasonnavigation",website:"https://www.ninfas.com",reservation:"walk-in",phone:"(713) 228-1175"},
  {name:"One Fifth",cuisine:"Rotating Concept",neighborhood:"Montrose",score:91,price:3,tags:["Fine Dining","Date Night","Critics Pick","Local Favorites"],description:"Chris Shepherd innovative concept that completely reinvents itself annually inside a converted church. Each year brings a new cuisine, new menu, new vibe. The constant is the quality -- always excellent, always surprising. Houston most exciting dining concept.",dishes:["Rotating Annual Menu","Craft Cocktails","Seasonal Tasting"],address:"1658 Westheimer Rd, Houston, TX 77006",lat:29.7442,lng:-95.3938,instagram:"onefifthhouston",website:"https://www.onefifthhouston.com",reservation:"Resy",phone:"(713) 955-1024"},
  {name:"March",cuisine:"Mediterranean Tasting Menu",neighborhood:"Montrose",score:93,price:4,tags:["Fine Dining","Date Night","Critics Pick","Exclusive"],description:"Felipe Riccio intimate Montrose tasting menu with 7+ courses of Mediterranean-inspired cooking that is among the best fine dining in Houston. The pasta courses are transcendent, the seafood is pristine, and the wine pairings are thoughtful. Michelin star.",dishes:["Multi-Course Tasting","Handmade Pasta","Seasonal Seafood"],address:"1624 Westheimer Rd, Houston, TX 77006",lat:29.7442,lng:-95.3938,instagram:"marchrestaurant",website:"https://www.marchhouston.com",reservation:"Resy",phone:"(713) 936-7265",awards:"Michelin Star"},
  {name:"Anvil Bar & Refuge",cuisine:"Craft Cocktails",neighborhood:"Montrose",score:91,price:2,tags:["Cocktails","Date Night","Local Favorites","Critics Pick"],description:"Bobby Heugel cocktail bar that put Houston on the national cocktail map. 100 cocktails organized by era and spirit, a team of bartenders who treat every drink as a craft, and a Montrose location that anchors the neighborhood. James Beard Award winner and still the most important bar in Houston.",dishes:["Classic Cocktails","Seasonal Menu","Whiskey Selection"],address:"1424 Westheimer Rd, Houston, TX 77006",lat:29.7450,lng:-95.3919,instagram:"anvilhouston",website:"https://www.anvilhouston.com",reservation:"walk-in",phone:"(713) 523-1622",awards:"James Beard Award"},
  {name:"Lei Low Bar",cuisine:"Tiki Bar",neighborhood:"Heights",score:87,price:2,tags:["Cocktails","Late Night","Local Favorites","Casual"],description:"Heights tiki bar hidden behind a nondescript door that serves some of the most creative tropical cocktails in Houston. The rum selection is massive, the drinks are balanced and strong, and the bamboo-lined space is a proper escape. The Navy Grog is the power order.",dishes:["Navy Grog","Mai Tai","Tiki Punch Bowl"],address:"6412 N Main St, Houston, TX 77009",lat:29.8063,lng:-95.3824,instagram:"leilowbar",website:"https://www.leilowbar.com",reservation:"walk-in",phone:"(713) 869-5409"},
  {name:"Present Company",cuisine:"Wine Bar / American",neighborhood:"Montrose",score:86,price:2,tags:["Wine Bar","Casual","Patio","Local Favorites"],description:"Montrose wine bar with a massive patio and a natural wine list that is one of the best in Houston. The food is elevated bar fare (the burger is excellent), the vibe is relaxed, and the crowd is the Montrose creative community. A perfect neighborhood spot.",dishes:["Natural Wine","Burger","Cheese Plate"],address:"1318 Westheimer Rd, Houston, TX 77006",lat:29.7450,lng:-95.3907,instagram:"presentcompanyhtx",website:"https://www.presentcompanyhtx.com",reservation:"walk-in",phone:"(713) 364-4424"},
  {name:"Moon Tower Inn",cuisine:"Hot Dogs / Beer Garden",neighborhood:"East End",score:85,price:1,tags:["Local Favorites","Casual","Patio","Brewery"],indicators:["outdoor-only"],description:"East End beer garden with exotic hot dogs (rattlesnake, rabbit, wild boar) and a massive outdoor space under string lights. The craft beer selection is deep, the regular beef dog is excellent, and the vibe is pure keep-Houston-weird energy. Cash only. Dogs welcome.",dishes:["Exotic Hot Dogs","Craft Beer","Regular Beef Dog"],address:"3004 Canal St, Houston, TX 77003",lat:29.7539,lng:-95.3402,instagram:"moontowerinn",website:"https://www.moontowerinn.com",reservation:"walk-in",phone:"(713) 227-9392"},
  {name:"Himalaya",cuisine:"Pakistani / Indian",neighborhood:"Hillcroft",score:91,price:1,tags:["Indian","Local Favorites","Critics Pick","Casual","Hole in the Wall"],indicators:["hole-in-the-wall","halal"],description:"Kaiser Lashkari legendary Pakistani-Indian in a Hillcroft strip mall. The lamb biryani is the best in Texas, the nihari is soul food of the highest order, and the fried chicken is a beautiful cross-cultural surprise. James Beard semifinalist.",dishes:["Lamb Biryani","Nihari","Fried Chicken"],address:"6652 Southwest Fwy, Houston, TX 77074",lat:29.7000,lng:-95.5224,instagram:"himalayarestaurant",website:"https://www.himalayarestauranthouston.com",reservation:"walk-in",phone:"(713) 532-2837",awards:"James Beard Semifinalist"}
]);

fs.writeFileSync('index.html', html, 'utf8');
fs.copyFileSync('index.html', 'index');
console.log('Done!');
