// Chicago → 400 — Final big push
const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');
// Chicago is inline in CITY_DATA
const chiStr = "'Chicago':";
const cdStart = html.indexOf('CITY_DATA');
const chiPos = html.indexOf(chiStr, cdStart);
const arrS = html.indexOf('[', chiPos);
let d=0, arrE=arrS;
for(let j=arrS;j<html.length;j++){if(html[j]==='[')d++;if(html[j]===']'){d--;if(d===0){arrE=j+1;break;}}}
let arr = JSON.parse(html.substring(arrS, arrE));
console.log('Starting Chicago:', arr.length);
const maxId = Math.max(...arr.map(r=>r.id));
let nextId = maxId + 1;
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let added = 0;
function add(s){
  if(existing.has(s.name.toLowerCase())){return;}
  s.id=nextId++;s.bestOf=[];s.busyness=null;s.waitTime=null;s.popularTimes=null;s.lastUpdated=null;s.trending=s.trending||false;s.group=s.group||'';s.suburb=s.suburb||false;s.menuUrl='';s.res_tier=s.price>=3?4:2;s.indicators=s.indicators||[];s.awards=s.awards||'';s.phone=s.phone||'';s.reserveUrl=s.reserveUrl||'';s.hh=s.hh||'';s.verified=true;
  arr.push(s);existing.add(s.name.toLowerCase());added++;
}

// 2026 openings from Infatuation, Modern Luxury, Chicago Mag
add({name:"Petite Edith",cuisine:"French Bistro",neighborhood:"River North",score:88,price:2,tags:["French","Date Night","Local Favorites"],description:"Neighborhood bistro from Michelin-starred chef Jenner Tomaska and wife Katrina Bravo. French techniques filtered through a Midwestern sensibility with a wraparound bar.",dishes:["French Bistro Classics","Midwestern-French Fusion","Wine Selection"],address:"316 W Erie St, Chicago, IL 60654",hours:"",lat:41.8940,lng:-87.6368,instagram:"petiteedith",website:"",reservation:"Resy",phone:""});

add({name:"Gibsons Tavern",cuisine:"American",neighborhood:"West Loop",score:87,price:2,tags:["American","Casual","Cocktails","Local Favorites"],description:"Gibsons Restaurant Group headed to Fulton Market with refined takes on classic American cuisine with early 20th century aesthetics.",dishes:["Classic American","Craft Cocktails","Steakhouse Vibes"],address:"Fulton Market, Chicago, IL 60607",hours:"",lat:41.8867,lng:-87.6517,instagram:"gibsonsrestaurant",website:"",reservation:"OpenTable",phone:"",group:"Gibsons",indicators:["coming-soon"]});

add({name:"Kouklas Greek Eatery",cuisine:"Greek",neighborhood:"Niles (Suburban)",score:87,price:2,tags:["Greek","Casual","Local Favorites"],description:"James Beard Award-winning chef Jimmy Bannos Jr. bold contemporary Greek dishes crafted with open-fire cooking techniques. First restaurant venture.",dishes:["Greek Kebabs","Open-Fire Dishes","Greek Salad"],address:"7425 N Harlem Ave, Niles, IL 60714",hours:"",lat:42.0114,lng:-87.8076,instagram:"kouklasgreek",website:"",reservation:"OpenTable",phone:"",suburb:true});

add({name:"SuSu",cuisine:"Steakhouse",neighborhood:"West Loop",score:88,price:3,tags:["Steakhouse","Date Night","Fine Dining"],description:"New steakhouse in the West Loop from the Infatuation newest openings list. A refined steak experience in Fulton Market.",dishes:["Prime Steak","Seafood","Classic Sides"],address:"1101 W Fulton Market, Chicago, IL 60607",hours:"",lat:41.8867,lng:-87.6556,instagram:"susuchicago",website:"",reservation:"Resy",phone:""});

add({name:"Pink Mu",cuisine:"Korean",neighborhood:"River North",score:86,price:2,tags:["Korean","Local Favorites","Casual"],description:"Korean restaurant in River North from Infatuation newest openings. Contemporary Korean dishes in a vibrant setting.",dishes:["Korean BBQ","Bibimbap","Korean Fried Chicken"],address:"644 N Orleans St, Chicago, IL 60654",hours:"",lat:41.8933,lng:-87.6378,instagram:"pinkmuchicago",website:"",reservation:"walk-in",phone:""});

add({name:"Chubby Skewers",cuisine:"Chinese / Skewers",neighborhood:"Chinatown",score:86,price:1,tags:["Chinese","Casual","Late Night","Local Favorites"],description:"Chinese skewer spot in Chinatown from the Infatuation openings list. Grilled skewers and Chinese street food late into the night.",dishes:["Grilled Skewers","Chinese Street Food","Late Night Bites"],address:"2148 S Archer Ave, Chicago, IL 60616",hours:"",lat:41.8534,lng:-87.6350,instagram:"chubbyskewers",website:"",reservation:"walk-in",phone:""});

add({name:"Fried Egg Cafe",cuisine:"Breakfast / American",neighborhood:"Edgewater",score:85,price:1,tags:["Brunch","Casual","Local Favorites"],description:"Edgewater breakfast and brunch spot from the Infatuation openings list. Classic breakfast done well.",dishes:["Eggs","Breakfast Plates","Coffee"],address:"5410 N Broadway, Chicago, IL 60640",hours:"",lat:41.9798,lng:-87.6588,instagram:"friedeggcafe",website:"",reservation:"walk-in",phone:""});

add({name:"Oooh Wee! It Is!",cuisine:"Soul Food",neighborhood:"Chatham",score:86,price:1,tags:["Southern","Soul Food","Casual","Local Favorites","Black-Owned"],description:"Soul food in Chatham from the Infatuation openings list. Comfort food classics from the South Side.",dishes:["Soul Food Plates","Fried Chicken","Mac & Cheese"],address:"8235 S Cottage Grove Ave, Chicago, IL 60619",hours:"",lat:41.7446,lng:-87.6068,instagram:"ooohweeitischicago",website:"",reservation:"walk-in",phone:""});

add({name:"Fatback",cuisine:"American / Comfort",neighborhood:"The Loop",score:85,price:1,tags:["American","Casual","Local Favorites"],description:"Loop restaurant from the Infatuation openings list. Comfort food in a downtown setting.",dishes:["Comfort Food","Sandwiches","American Plates"],address:"155 N Wacker Dr, Chicago, IL 60606",hours:"",lat:41.8844,lng:-87.6373,instagram:"fatbackchicago",website:"",reservation:"walk-in",phone:""});

add({name:"Indgō Mrktō",cuisine:"Mexican-Indian Fusion",neighborhood:"Pilsen",score:87,price:1,tags:["Mexican","Indian","Local Favorites","Casual"],description:"Food hall in Pilsen with multiple concepts from the same chef blending Mexican and Indian backgrounds. From the Infatuation openings.",dishes:["Mexican-Indian Fusion","Multiple Concepts","Creative Dishes"],address:"1852 S Ashland Ave, Chicago, IL 60608",hours:"",lat:41.8574,lng:-87.6660,instagram:"indgomrkto",website:"",reservation:"walk-in",phone:""});

add({name:"Milly's Pizza Lakeview",cuisine:"Pan Pizza",neighborhood:"Lakeview",score:86,price:1,tags:["Pizza","Casual","Local Favorites"],description:"Second Lakeview location of Milly's Detroit-meets-Chicago pan pizza. Caramelized cheese edges and thick pillowy dough.",dishes:["Pan Pizza","Pepperoni Cup","Cheese Pan"],address:"3434 N Broadway, Chicago, IL 60657",hours:"",lat:41.9441,lng:-87.6444,instagram:"millyspizzainthepan",website:"",reservation:"walk-in",phone:""});

add({name:"Thai Me Up Cafe",cuisine:"Thai",neighborhood:"Lakeview",score:85,price:1,tags:["Thai","Casual","Local Favorites"],description:"Casual Thai on Lakeview Broadway strip with larb wings, northern Thai sausage, panang curry and tom yum noodle soup.",dishes:["Larb Wings","Panang Curry","Tom Yum"],address:"3501 N Broadway, Chicago, IL 60657",hours:"",lat:41.9452,lng:-87.6444,instagram:"thaimeupcafe",website:"",reservation:"walk-in",phone:""});

// More neighborhood spots
add({name:"Qing Xiang Yuan Wicker Park",cuisine:"Chinese Dumplings",neighborhood:"Wicker Park",score:87,price:1,tags:["Chinese","Dumplings","Local Favorites","Casual"],description:"Wicker Park location of the beloved Chinatown dumpling house. Hand-wrapped dumplings and noodles.",dishes:["Hand-Wrapped Dumplings","Noodles","Scallion Pancakes"],address:"2002 W Division St, Chicago, IL 60622",hours:"",lat:41.9032,lng:-87.6778,instagram:"qingxiangyuan",website:"",reservation:"walk-in",phone:""});

add({name:"Kasama Ukrainian Village",cuisine:"Filipino / Bakery",neighborhood:"Ukrainian Village",score:92,price:3,tags:["Filipino","Fine Dining","Bakery/Coffee","Critics Pick","Date Night"],description:"Two-Michelin-star Filipino from Tim Flores and Genie Kwon. Bakery by day with incredible pastries, tasting menu at night. Made Chicago dining history.",dishes:["Filipino Tasting Menu","Croissants","Bakery Items"],address:"1001 N Winchester Ave, Chicago, IL 60622",hours:"",lat:41.9002,lng:-87.6753,instagram:"kasamachicago",website:"https://www.kasamachicago.com",reservation:"Tock",phone:"",awards:"Two Michelin Stars"});

add({name:"Maple & Ash",cuisine:"Steakhouse",neighborhood:"Gold Coast",score:90,price:4,tags:["Steakhouse","Fine Dining","Date Night","Celebrations"],description:"Gold Coast steakhouse with chandeliers, candelabras, and a $225 tasting menu. Great for large groups or quiet dinners. One of Chicago most glamorous restaurants.",dishes:["Prime Steak","Tasting Menu","Tableside Service"],address:"8 W Maple St, Chicago, IL 60610",hours:"",lat:41.9010,lng:-87.6291,instagram:"mapleandash",website:"https://www.mapleandash.com",reservation:"Resy",phone:"(312) 944-8888"});

add({name:"Chicago Cut Steakhouse",cuisine:"Steakhouse",neighborhood:"River North",score:89,price:4,tags:["Steakhouse","Fine Dining","Celebrations","Date Night"],description:"Riverside steakhouse with stunning views of the Chicago River and skyline. USDA Prime steaks and an extensive wine list. Power dining at its finest.",dishes:["USDA Prime Steak","River Views","Wine List"],address:"300 N LaSalle Dr, Chicago, IL 60654",hours:"",lat:41.8882,lng:-87.6328,instagram:"chicagocut",website:"https://www.chicagocutsteakhouse.com",reservation:"OpenTable",phone:"(312) 329-1800"});

add({name:"Bavette's Bar & Boeuf",cuisine:"Steakhouse",neighborhood:"River North",score:90,price:4,tags:["Steakhouse","Fine Dining","Date Night","Celebrations","Iconic"],description:"Hogsalt perfected low-lumen aesthetic with tufted leather booths and golden lamplight. Iced shellfish display, prime steaks, and one of Chicago most atmospheric dining rooms.",dishes:["Prime Steak","Shellfish Display","Old Fashioned"],address:"218 W Kinzie St, Chicago, IL 60654",hours:"",lat:41.8893,lng:-87.6350,instagram:"bavettessteakhouse",website:"",reservation:"Resy",phone:"(312) 624-8154",group:"Hogsalt"});

add({name:"RPM Italian",cuisine:"Italian",neighborhood:"River North",score:89,price:3,tags:["Italian","Date Night","Celebrations","Local Favorites"],description:"Modern Italian in a sleek River North space from the Rancic family. The cacio e pepe is tableside and theatrical, the lobster ravioli is rich, and the vibe is very Chicago.",dishes:["Tableside Cacio e Pepe","Lobster Ravioli","Italian Wine"],address:"52 W Illinois St, Chicago, IL 60654",hours:"",lat:41.8909,lng:-87.6313,instagram:"rpmitalian",website:"https://www.rpmrestaurants.com",reservation:"OpenTable",phone:"(312) 222-9500"});

add({name:"Frontera Grill",cuisine:"Mexican",neighborhood:"River North",score:89,price:2,tags:["Mexican","Critics Pick","Date Night","Iconic"],description:"Rick Bayless flagship Mexican restaurant that introduced Chicago to regional Mexican cuisine. James Beard Award-winning. Still one of the best Mexican restaurants in the country.",dishes:["Regional Mexican","Mole","Seasonal Menu"],address:"445 N Clark St, Chicago, IL 60654",hours:"",lat:41.8901,lng:-87.6312,instagram:"fronteragrill",website:"https://www.fronteragrill.com",reservation:"walk-in",phone:"(312) 661-1434",awards:"James Beard Award",group:"Bayless"});

add({name:"Topolobampo",cuisine:"Mexican Fine Dining",neighborhood:"River North",score:92,price:3,tags:["Mexican","Fine Dining","Critics Pick","Date Night","Exclusive"],description:"Rick Bayless Michelin-starred fine dining Mexican. Seasonal tasting menus that showcase the depth and complexity of regional Mexican cuisine. One of the most important Mexican restaurants in America.",dishes:["Mexican Tasting Menu","Seasonal Mole","Wine Pairing"],address:"445 N Clark St, Chicago, IL 60654",hours:"",lat:41.8901,lng:-87.6312,instagram:"topolobampo",website:"https://www.topolobampo.com",reservation:"Tock",phone:"(312) 661-1434",awards:"One Michelin Star",group:"Bayless"});

add({name:"Le Bouchon",cuisine:"French Bistro",neighborhood:"Bucktown",score:87,price:2,tags:["French","Date Night","Local Favorites","Iconic"],description:"Bucktown French bistro staple from the team that later opened Obelix. Classic French bistro fare -- steak frites, onion soup, and escargot in a cozy space. A neighborhood institution.",dishes:["Steak Frites","French Onion Soup","Escargot"],address:"1958 N Damen Ave, Chicago, IL 60647",hours:"",lat:41.9163,lng:-87.6772,instagram:"lebouchonchicago",website:"",reservation:"walk-in",phone:"(773) 862-6600"});

add({name:"Bixi Beer",cuisine:"Chinese / Beer Garden",neighborhood:"Bridgeport",score:86,price:1,tags:["Chinese","Craft Beer","Casual","Local Favorites","Patio"],description:"Chinese-American food and craft beer in Bridgeport. Creative Chinese dishes alongside house and guest beers. The patio is a neighborhood hangout.",dishes:["Chinese-American Plates","Craft Beer","Patio"],address:"2515 S Wentworth Ave, Chicago, IL 60616",hours:"",lat:41.8478,lng:-87.6318,instagram:"bixibeer",website:"",reservation:"walk-in",phone:""});

add({name:"Pizza Friendly Pizza",cuisine:"Sicilian Pizza",neighborhood:"Ukrainian Village",score:87,price:1,tags:["Pizza","Casual","Local Favorites"],description:"Fantastic Sicilian-style pizza in Ukrainian Village with thick, airy slices at just $6. One of the best pizza values in the city.",dishes:["Sicilian Slice","Cheese Pizza","Pepperoni"],address:"1416 W Chicago Ave, Chicago, IL 60642",hours:"",lat:41.8966,lng:-87.6616,instagram:"pizzafriendlypizza",website:"",reservation:"walk-in",phone:""});

add({name:"Harold's Chicken Shack",cuisine:"Fried Chicken",neighborhood:"Multiple Locations",score:86,price:1,tags:["Fried Chicken","Casual","Iconic","Local Favorites"],description:"Chicago fried chicken institution with multiple South and West Side locations. The half chicken with mild sauce and white bread is a Chicago rite of passage. Cash only at most locations.",dishes:["Half Chicken","Mild Sauce","Fried Perch"],address:"multiple locations, Chicago",hours:"",lat:41.7993,lng:-87.5880,instagram:"",website:"",reservation:"walk-in",phone:""});

add({name:"Ricobene's",cuisine:"Italian / Breaded Steak",neighborhood:"Bridgeport",score:86,price:1,tags:["Italian","Casual","Iconic","Local Favorites"],description:"Home of the famous breaded steak sandwich -- a massive, crispy breaded pork cutlet on Italian bread. A Chicago South Side icon. Cash only.",dishes:["Breaded Steak Sandwich","Italian Beef","Pizza"],address:"252 W 26th St, Chicago, IL 60616",hours:"",lat:41.8442,lng:-87.6336,instagram:"ricobenes",website:"",reservation:"walk-in",phone:"(312) 225-5555"});

add({name:"Carnitas Don Pedro",cuisine:"Mexican",neighborhood:"Pilsen",score:87,price:1,tags:["Mexican","Local Favorites","Casual","Hole in the Wall"],description:"Pilsen carnitas specialist with slow-cooked pork that is crispy-edged and deeply flavored. Order by the pound and make your own tacos. Cash only, weekend lines.",dishes:["Carnitas by the Pound","Tacos","Weekend Special"],address:"1113 W 18th St, Chicago, IL 60608",hours:"",lat:41.8579,lng:-87.6562,instagram:"",website:"",reservation:"walk-in",phone:""});

add({name:"Elske",cuisine:"New American / Scandinavian",neighborhood:"West Loop",score:91,price:3,tags:["Fine Dining","Scandinavian","Date Night","Critics Pick"],description:"One-Michelin-star from the husband-and-wife team with Scandinavian influences. The tasting menu is poetic and the pastry program is world-class.",dishes:["Scandinavian Tasting Menu","Pastry Course","Natural Wine"],address:"1350 W Randolph St, Chicago, IL 60607",hours:"",lat:41.8841,lng:-87.6599,instagram:"elskechicago",website:"https://www.elskerestaurant.com",reservation:"Tock",phone:"(312) 733-1314",awards:"One Michelin Star"});

add({name:"Esmé",cuisine:"New American",neighborhood:"Lincoln Park",score:91,price:4,tags:["Fine Dining","Date Night","Exclusive","Critics Pick"],description:"One-Michelin-star from chef Jenner Tomaska with creative tasting menus in Lincoln Park. Intimate, beautiful, and one of Chicago most exciting fine dining restaurants.",dishes:["Creative Tasting Menu","Seasonal Courses","Wine Pairing"],address:"2200 N Clark St, Chicago, IL 60614",hours:"",lat:41.9228,lng:-87.6371,instagram:"esmechicago",website:"https://www.esmechicago.com",reservation:"Tock",phone:"",awards:"One Michelin Star"});

add({name:"North Pond",cuisine:"New American",neighborhood:"Lincoln Park",score:90,price:3,tags:["Fine Dining","Scenic","Date Night","Celebrations","Critics Pick"],description:"Stunning setting in a former warming house on a Lincoln Park pond. Seasonal farm-to-table tasting menu with views of the Chicago skyline reflected in the water. Magical.",dishes:["Seasonal Tasting","Pond-Side Dining","Skyline Views"],address:"2610 N Cannon Dr, Chicago, IL 60614",hours:"",lat:41.9290,lng:-87.6342,instagram:"northpondrestaurant",website:"https://www.northpondrestaurant.com",reservation:"Resy",phone:"(773) 477-5845"});

add({name:"Ever",cuisine:"New American",neighborhood:"West Loop",score:95,price:4,tags:["Fine Dining","Exclusive","Date Night","Critics Pick"],description:"Two-Michelin-star from chef Curtis Duffy on a quiet Fulton Market corner. The tasting menu is one of the most refined dining experiences in America.",dishes:["Multi-Course Tasting","Refined American","Wine Pairing"],address:"1340 W Fulton St, Chicago, IL 60607",hours:"",lat:41.8867,lng:-87.6596,instagram:"everrestaurant",website:"https://www.everrestaurant.com",reservation:"Tock",phone:"",awards:"Two Michelin Stars"});

add({name:"Oriole",cuisine:"New American",neighborhood:"West Loop",score:96,price:4,tags:["Fine Dining","Exclusive","Date Night","Critics Pick"],description:"Two-Michelin-star from chef Noah Sandoval. Hidden in a West Loop alley, the tasting menu is extraordinary -- 15+ courses of creative American cuisine. James Beard Award winner 2025.",dishes:["15+ Course Tasting","Hidden Alley Setting","Wine Pairing"],address:"661 W Walnut St, Chicago, IL 60661",hours:"",lat:41.8864,lng:-87.6454,instagram:"oriolechicago",website:"https://www.oriolechicago.com",reservation:"Tock",phone:"",awards:"Two Michelin Stars, James Beard 2025"});

add({name:"Mako",cuisine:"Japanese Omakase",neighborhood:"Lincoln Park",score:91,price:4,tags:["Japanese","Fine Dining","Exclusive","Date Night"],description:"One-Michelin-star omakase in Lincoln Park with pristine fish and refined technique. Intimate counter seating and seasonal preparations.",dishes:["Omakase Course","Seasonal Nigiri","Sake Pairing"],address:"731 W Lake St, Chicago, IL 60661",hours:"",lat:41.8857,lng:-87.6455,instagram:"makochicago",website:"",reservation:"Tock",phone:"",awards:"One Michelin Star"});

add({name:"EL Ideas",cuisine:"New American / BYOB",neighborhood:"South Side",score:91,price:3,tags:["Fine Dining","BYOB","Date Night","Exclusive","Critics Pick"],description:"One-Michelin-star BYOB tasting menu on the South Side. Chef Phillip Foss cooks in an open kitchen and the experience is intimate and personal. BYOB means you can bring great wine without corkage.",dishes:["BYOB Tasting Menu","Open Kitchen","Interactive Dining"],address:"2419 W 14th St, Chicago, IL 60608",hours:"",lat:41.8623,lng:-87.6858,instagram:"elideasrestaurant",website:"",reservation:"Tock",phone:"",awards:"One Michelin Star"});

add({name:"Tzuco",cuisine:"Mexican Fine Dining",neighborhood:"River North",score:90,price:3,tags:["Mexican","Fine Dining","Date Night","Critics Pick"],description:"Chef Carlos Gaytán Mexican fine dining in River North. Creative Mexican tasting menu with refined technique. Gaytán was the first Mexican-born chef to earn a Michelin star.",dishes:["Mexican Tasting Menu","Creative Mole","Mexican Desserts"],address:"720 N State St, Chicago, IL 60654",hours:"",lat:41.8960,lng:-87.6278,instagram:"tzucochicago",website:"",reservation:"Resy",phone:""});

add({name:"Next",cuisine:"Rotating Concept",neighborhood:"West Loop",score:91,price:4,tags:["Fine Dining","Exclusive","Date Night","Critics Pick"],description:"Grant Achatz rotating concept restaurant that completely changes its menu, decor, and experience every few months. From Thai street food to Parisian bistro -- no two visits are alike. One Michelin star.",dishes:["Rotating Concept","Tasting Menu","Theatrical Dining"],address:"953 W Fulton Market, Chicago, IL 60607",hours:"",lat:41.8867,lng:-87.6519,instagram:"nextrestaurant",website:"https://www.nextrestaurant.com",reservation:"Tock",phone:"",awards:"One Michelin Star",group:"Alinea Group"});

add({name:"Sepia",cuisine:"New American",neighborhood:"West Loop",score:90,price:3,tags:["Fine Dining","Date Night","Celebrations","Critics Pick"],description:"One-Michelin-star New American in a gorgeous West Loop space. Seasonal tasting and a la carte with refined technique. One of Chicago most consistently excellent fine dining restaurants.",dishes:["Seasonal Tasting","A La Carte","Classic Cocktails"],address:"123 N Jefferson St, Chicago, IL 60661",hours:"",lat:41.8840,lng:-87.6423,instagram:"sepiachicago",website:"https://www.sepiachicago.com",reservation:"OpenTable",phone:"(312) 441-1920",awards:"One Michelin Star"});

add({name:"Parachute",cuisine:"Korean-American",neighborhood:"Avondale",score:91,price:2,tags:["Korean","New American","Date Night","Critics Pick","Local Favorites"],description:"Beverly Kim and Johnny Clark Korean-American in Avondale. The bing bread with butter is legendary. Creative dishes that blend Korean tradition with Midwestern ingredients. The team behind Anelya.",dishes:["Bing Bread","Korean-American Plates","Seasonal Menu"],address:"3500 N Elston Ave, Chicago, IL 60618",hours:"",lat:41.9462,lng:-87.7078,instagram:"parachutechicago",website:"https://www.parachuterestaurant.com",reservation:"Resy",phone:"(773) 654-1460",group:"Parachute"});

add({name:"Mi Tocaya Antojeria",cuisine:"Mexican",neighborhood:"Logan Square",score:89,price:2,tags:["Mexican","Date Night","Local Favorites","Critics Pick"],description:"Diana Davila Mexican in Logan Square with fun, lively ambiance and dishes influenced by Aztec cuisine. Michelin Bib Gourmand. Creative cocktails and bold flavors.",dishes:["Antojitos","Mezcal Cocktails","Creative Mexican"],address:"2800 W Logan Blvd, Chicago, IL 60647",hours:"",lat:41.9295,lng:-87.6970,instagram:"mitocaya",website:"https://www.mitocaya.com",reservation:"Resy",phone:"(773) 289-4445",awards:"Michelin Bib Gourmand"});

add({name:"Bungalow by Middle Brow",cuisine:"Farm-to-Table / Brewery",neighborhood:"Logan Square",score:88,price:2,tags:["Farm-to-Table","Craft Beer","Pizza","Date Night","Local Favorites"],description:"Farm-to-table restaurant and brewery in Logan Square where everything is sourced within 150 miles. Great pizza, house-brewed beer, and a commitment to local agriculture.",dishes:["Farm-to-Table Pizza","House Beer","Local Ingredients"],address:"2840 W Armitage Ave, Chicago, IL 60647",hours:"",lat:41.9172,lng:-87.6987,instagram:"middlebrow",website:"https://www.middlebrowbeer.com",reservation:"walk-in",phone:"(773) 687-9076"});

add({name:"Daisies",cuisine:"New American / Italian",neighborhood:"Logan Square",score:88,price:2,tags:["Italian","New American","Date Night","Local Favorites","Critics Pick"],description:"Michelin Bib Gourmand with handmade pasta and housemade baked goods in Logan Square. Creative seasonal menu that blends Italian and New American. The bread basket alone is worth the visit.",dishes:["Housemade Pasta","Bread Basket","Seasonal Menu"],address:"2523 N Milwaukee Ave, Chicago, IL 60647",hours:"",lat:41.9261,lng:-87.6952,instagram:"daisieschicago",website:"https://www.daisieschicago.com",reservation:"Resy",phone:"(773) 661-1671",awards:"Michelin Bib Gourmand"});

add({name:"Joe's Seafood, Prime Steak & Stone Crab",cuisine:"Seafood / Steakhouse",neighborhood:"River North",score:89,price:3,tags:["Seafood","Steakhouse","Celebrations","Date Night"],description:"River North surf-and-turf institution. Stone crabs, sugar prawns, bone-in ribeye, and Alaskan king crab legs. Upscale without being stuffy.",dishes:["Stone Crab","Prime Steak","King Crab"],address:"60 E Grand Ave, Chicago, IL 60611",hours:"",lat:41.8917,lng:-87.6260,instagram:"joes_restaurants",website:"",reservation:"OpenTable",phone:"(312) 379-5637"});

add({name:"Moody Tongue",cuisine:"Brewery / Fine Dining",neighborhood:"Pilsen",score:90,price:3,tags:["Fine Dining","Craft Beer","Date Night","Critics Pick"],description:"One-Michelin-star brewery and fine dining restaurant in Pilsen. Chef Jared Rouben pairs tasting menu courses with house-brewed beers. A unique concept executed at the highest level.",dishes:["Beer-Paired Tasting Menu","House-Brewed Beer","Fine Dining"],address:"2515 S Wabash Ave, Chicago, IL 60616",hours:"",lat:41.8478,lng:-87.6257,instagram:"moodytongue",website:"https://www.moodytongue.com",reservation:"Tock",phone:"",awards:"One Michelin Star"});

console.log('Added', added, 'new Chicago spots. Total:', arr.length);
html = html.substring(0, arrS) + JSON.stringify(arr) + html.substring(arrE);
fs.writeFileSync('index.html', html, 'utf8');
console.log('Chicago to 400 complete!');
