const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');

// 1. Build CHICAGO_DATA array
const CHICAGO_DATA = [
  // === FINE DINING ===
  {name:"Alinea",phone:"(312) 867-0110",cuisine:"Molecular Gastronomy",neighborhood:"Lincoln Park",score:99,price:4,tags:["Fine Dining","Critics Pick","Exclusive","Celebrations"],indicators:[],description:"Grant Achatz three-Michelin-star temple of molecular gastronomy that redefined what American fine dining could be. The multi-course tasting menu is a theatrical journey -- edible balloons, tablecloth desserts, and flavors that challenge everything you think you know about food. The most important restaurant in Chicago and one of the most important in the world.",dishes:["Multi-Course Tasting Menu","Edible Balloon","Tablecloth Dessert"],address:"1723 N Halsted St, Chicago, IL 60614",hours:"Wed-Sun 5PM-10PM",lat:41.9133,lng:-87.6483,reservation:"Tock",hh:"",instagram:"aaboroughlinea",website:"https://www.alinearestaurant.com",reserveUrl:"https://www.exploretock.com/alinea",awards:"3 Michelin Stars",group:"Alinea Group",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:5},
  {name:"Smyth",phone:"(773) 913-3011",cuisine:"New American Tasting Menu",neighborhood:"West Loop",score:97,price:4,tags:["Fine Dining","Critics Pick","Exclusive"],indicators:[],description:"Two Michelin stars for John and Karen Shields farm-driven tasting menu that is as much about the land as the plate. Ingredients come from their own farm in Door County, Wisconsin, and every course tells a seasonal story. Intimate, personal, and one of the most meaningful dining experiences in America.",dishes:["Farm Tasting Menu","Seasonal Courses","Wine Pairing"],address:"177 N Ada St, Chicago, IL 60607",hours:"Wed-Sat 5:30PM-9PM",lat:41.8856,lng:-87.6554,reservation:"Tock",hh:"",instagram:"smythchicago",website:"https://www.smythandtheloyalist.com",reserveUrl:"https://www.exploretock.com/smyth",awards:"2 Michelin Stars",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:5},
  {name:"Ever",phone:"(312) 733-3837",cuisine:"New American Tasting Menu",neighborhood:"West Loop",score:96,price:4,tags:["Fine Dining","Critics Pick","Exclusive"],indicators:[],description:"Curtis Duffy two-Michelin-star West Loop tasting menu that represents decades of refinement from one of Chicago most focused chefs. The 10-course menu is pristine, precise, and deeply personal. The room is serene and the service is flawless. A quiet masterpiece.",dishes:["10-Course Tasting","Seasonal Fish Course","Dessert Progression"],address:"1340 W Fulton St, Chicago, IL 60607",hours:"Tue-Sat 5PM-9PM",lat:41.8867,lng:-87.6618,reservation:"Tock",hh:"",instagram:"everrestaurant",website:"https://www.everrestaurant.com",reserveUrl:"https://www.exploretock.com/ever",awards:"2 Michelin Stars",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:5},
  {name:"Oriole",phone:"(312) 877-5339",cuisine:"New American Tasting Menu",neighborhood:"West Loop",score:97,price:4,tags:["Fine Dining","Critics Pick","Exclusive"],indicators:[],description:"Two Michelin stars hidden down a West Loop alley -- you literally walk through a parking lot to find it, which makes the gorgeous room inside even more dramatic. Noah Sandoval tasting menu weaves Japanese technique with American ingredients in ways that feel both intellectual and deeply satisfying. One of the best meals in Chicago.",dishes:["Multi-Course Tasting","A5 Wagyu Course","Dessert Course"],address:"661 W Walnut St, Chicago, IL 60661",hours:"Tue-Sat 5PM-9PM",lat:41.8865,lng:-87.6449,reservation:"Tock",hh:"",instagram:"oriolechicago",website:"https://www.oriolechicago.com",reserveUrl:"https://www.exploretock.com/oriole",awards:"2 Michelin Stars",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:5},

  // === HOT/TRENDY ===
  {name:"Girl & the Goat",phone:"(312) 492-6262",cuisine:"New American",neighborhood:"West Loop",score:93,price:3,tags:["Date Night","Local Favorites","Critics Pick","Casual"],indicators:[],description:"Stephanie Izard Top Chef winner restaurant that put the West Loop on the map and never stopped being one of the hardest reservations in Chicago. The goat empanadas are iconic, the wood-roasted vegetables are revelatory, and the energy in the room is infectious. Still essential after all these years.",dishes:["Goat Empanadas","Wood-Roasted Cauliflower","Hamachi Crudo"],address:"809 W Randolph St, Chicago, IL 60607",hours:"Mon-Sun 4:30PM-11PM",lat:41.8841,lng:-87.6478,reservation:"OpenTable",hh:"",instagram:"girlandthegoat",website:"https://www.girlandthegoat.com",reserveUrl:"",awards:"James Beard Award",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:4},
  {name:"Monteverde",phone:"(312) 888-3041",cuisine:"Italian Pasta",neighborhood:"West Loop",score:94,price:3,tags:["Date Night","Italian","Critics Pick","Local Favorites"],indicators:[],description:"Sarah Grueneberg handmade pasta temple in the West Loop that serves some of the best noodles in America. The cacio e pepe is transcendent, the tortelloni in brodo is comfort in a bowl, and every single pasta shape is made with the kind of obsessive care that makes you want to weep. The wait is worth it.",dishes:["Cacio e Pepe","Tortelloni in Brodo","Burrata"],address:"1020 W Madison St, Chicago, IL 60607",hours:"Tue-Sun 5PM-10PM",lat:41.8816,lng:-87.6527,reservation:"Resy",hh:"",instagram:"monteverdechicago",website:"https://www.monteverdechicago.com",reserveUrl:"https://resy.com/cities/chi/monteverde",awards:"James Beard Award",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:4},
  {name:"Kasama",phone:"(773) 506-8818",cuisine:"Filipino Tasting Menu / Bakery",neighborhood:"Ukrainian Village",score:95,price:3,tags:["Fine Dining","Critics Pick","Brunch","Bakery/Coffee"],indicators:[],description:"The first Filipino restaurant to earn a Michelin star in America, and it operates as a bakery-cafe by day and a tasting menu by night. The longanisa breakfast sandwich in the morning is one of the best sandwiches in Chicago. The evening tasting menu fuses Filipino traditions with fine-dining technique. Tim Flores and Genie Kwon created something truly special.",dishes:["Longanisa Breakfast Sandwich","Filipino Tasting Menu","Ube Crinkle Cookie"],address:"1001 N Winchester Ave, Chicago, IL 60622",hours:"Bakery 8AM-2PM, Dinner Thu-Sat 5PM",lat:41.9006,lng:-87.6752,reservation:"Tock",hh:"",instagram:"kasamachicago",website:"https://www.kasamachicago.com",reserveUrl:"https://www.exploretock.com/kasama",awards:"1 Michelin Star",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:true,suburb:false,menuUrl:"",res_tier:4},
  {name:"Avec",phone:"(312) 377-2002",cuisine:"Mediterranean",neighborhood:"West Loop",score:92,price:2,tags:["Date Night","Local Favorites","Critics Pick","Casual"],indicators:[],description:"The communal-table wine bar that helped launch Randolph Street as a dining destination. Paul Kahan wood-oven Mediterranean shares are perfect for groups -- the chorizo-stuffed medjool dates are one of the most famous dishes in Chicago. The wine list is thoughtful, the vibe is convivial, and it still feels as essential as the day it opened.",dishes:["Chorizo-Stuffed Dates","Focaccia","Wood-Roasted Fish"],address:"615 W Randolph St, Chicago, IL 60661",hours:"Mon-Sun 3:30PM-12AM",lat:41.8842,lng:-87.6438,reservation:"Resy",hh:"",instagram:"avecrestaurant",website:"https://www.avecrestaurant.com",reserveUrl:"",awards:"James Beard Award",group:"One Off Hospitality",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:3},

  // === CHICAGO CLASSICS ===
  {name:"Lou Malnati's Pizzeria",phone:"(312) 786-1000",cuisine:"Deep Dish Pizza",neighborhood:"River North",score:90,price:1,tags:["Pizza","Local Favorites","Casual","Family","Iconic"],indicators:[],description:"The deep dish that Chicagoans actually eat -- buttery crust, chunky tomato sauce on TOP of the cheese, and a sausage patty that covers the entire pie. Lou Malnati has been doing this since 1971 and the recipe has not changed because it does not need to. The Buttercrust with sausage is the canonical order. Multiple locations.",dishes:["Buttercrust Deep Dish","Sausage Deep Dish","Thin Crust"],address:"439 N Wells St, Chicago, IL 60654",hours:"Mon-Sun 11AM-11PM",lat:41.8904,lng:-87.6339,reservation:"walk-in",hh:"",instagram:"loumalnatis",website:"https://www.loumalnatis.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
  {name:"Portillo's",phone:"(312) 587-8910",cuisine:"Chicago Hot Dogs / Italian Beef",neighborhood:"River North",score:88,price:1,tags:["Local Favorites","Casual","Family","Iconic","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"The Chicago fast food institution that locals defend with their lives. The Italian beef dipped with hot giardiniera is a religious experience, the Chicago-style hot dog is textbook (mustard, onions, relish, tomato, pickle, sport peppers, celery salt, NO KETCHUP), and the chocolate cake shake is an act of beautiful madness.",dishes:["Italian Beef Dipped Hot","Chicago Dog","Chocolate Cake Shake"],address:"100 W Ontario St, Chicago, IL 60654",hours:"Mon-Sun 10AM-11PM",lat:41.8932,lng:-87.6317,reservation:"walk-in",hh:"",instagram:"portilloshotdogs",website:"https://www.portillos.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
  {name:"Giordano's",phone:"(312) 951-0747",cuisine:"Stuffed Deep Dish Pizza",neighborhood:"The Loop",score:85,price:1,tags:["Pizza","Local Favorites","Casual","Family"],indicators:[],description:"The stuffed pizza that tourists flock to and locals begrudgingly admit is good. Giordano differs from Lou Malnati in that it is STUFFED -- two layers of crust with a mountain of cheese in between. The wait time for a fresh pie is 45 minutes which feels like an eternity when you are hungry but the result justifies it.",dishes:["Stuffed Deep Dish","Classic Cheese","Spinach Stuffed"],address:"130 E Randolph St, Chicago, IL 60601",hours:"Mon-Sun 11AM-11PM",lat:41.8844,lng:-87.6248,reservation:"walk-in",hh:"",instagram:"giordanospizza",website:"https://giordanos.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
  {name:"Pequod's Pizza",phone:"(773) 327-1512",cuisine:"Caramelized Deep Dish Pizza",neighborhood:"Lincoln Park",score:92,price:1,tags:["Pizza","Local Favorites","Casual","Critics Pick","Late Night"],indicators:[],description:"The deep dish that actual pizza nerds argue is the best in Chicago -- and they might be right. Pequod secret weapon is the caramelized cheese crust that forms a dark, crunchy, almost-burnt ring around the edge that is absolutely addictive. Less touristy than Lou and Giordano, more beloved by locals. The wait can be brutal.",dishes:["Caramelized Crust Deep Dish","Sausage & Mushroom","Pan Pizza"],address:"2207 N Clybourn Ave, Chicago, IL 60614",hours:"Mon-Sun 11AM-2AM",lat:41.9214,lng:-87.6645,reservation:"walk-in",hh:"",instagram:"pequodspizza",website:"https://pequodspizza.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
  {name:"Al's #1 Italian Beef",phone:"(312) 733-8896",cuisine:"Italian Beef",neighborhood:"West Loop",score:89,price:1,tags:["Local Favorites","Casual","Hole in the Wall","Iconic"],indicators:["hole-in-the-wall"],description:"The original Italian beef since 1938 -- thin-sliced roast beef piled on Italian bread, dipped in jus, with sweet or hot peppers. Order it dipped (the bread soaked in gravy) with hot giardiniera and eat it leaning forward because it WILL drip everywhere. No seats, no pretension, just perfection.",dishes:["Italian Beef Dipped Hot","Combo (Beef + Sausage)","Italian Ice"],address:"1079 W Taylor St, Chicago, IL 60607",hours:"Mon-Sat 9AM-1AM",lat:41.8695,lng:-87.6556,reservation:"walk-in",hh:"",instagram:"",website:"https://www.alsbeef.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
  {name:"Superdawg Drive-In",phone:"(773) 763-0660",cuisine:"Chicago Hot Dogs",neighborhood:"Norwood Park",score:87,price:1,tags:["Local Favorites","Casual","Iconic","Family"],indicators:[],description:"The most photogenic hot dog stand in America -- two giant hot dog statues (Maurie and Flaurie) have watched over this drive-in since 1948. The Superdawg is a pure Chicago dog with all the fixings served in a box with those perfect crinkle fries. Pull up, flash your lights, and a carhop brings your food. Pure Americana.",dishes:["Superdawg","Crinkle Cut Fries","Whoopercheesie"],address:"6363 N Milwaukee Ave, Chicago, IL 60646",hours:"Sun-Thu 11AM-1AM, Fri-Sat 11AM-2AM",lat:41.9972,lng:-87.7834,reservation:"walk-in",hh:"",instagram:"superdawg",website:"https://www.superdawg.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:true,menuUrl:"",res_tier:2},

  // === NEIGHBORHOOD FAVORITES ===
  {name:"Big Star",phone:"(773) 235-4039",cuisine:"Tacos / Whiskey Bar",neighborhood:"Wicker Park",score:88,price:1,tags:["Casual","Local Favorites","Patio","Late Night","Cocktails"],indicators:[],description:"Wicker Park taco and whiskey joint that has one of the best patios in Chicago -- a sprawling, string-lit space that becomes the center of the neighborhood on warm evenings. The tacos are legit (the pork belly is the move), the whiskey list is deep, and the vibe is pure Chicago cool. Paul Kahan One Off Hospitality strikes again.",dishes:["Pork Belly Taco","Whiskey Sour","Guacamole"],address:"1531 N Damen Ave, Chicago, IL 60622",hours:"Mon-Sun 11:30AM-2AM",lat:41.9093,lng:-87.6771,reservation:"walk-in",hh:"",instagram:"bigstarchicago",website:"https://www.bigstarchicago.com",reserveUrl:"",awards:"",group:"One Off Hospitality",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
  {name:"The Violet Hour",phone:"",cuisine:"Craft Cocktails",neighborhood:"Wicker Park",score:91,price:2,tags:["Cocktails","Date Night","Exclusive","Late Night"],indicators:[],description:"The bar that launched Chicago craft cocktail revolution -- a speakeasy-style lounge hidden behind an unmarked facade on North Damen. No standing allowed, no phone calls, and cocktails that are among the most technically perfect in the country. The rotating seasonal menu is always inventive. A masterclass in how a bar should feel.",dishes:["Seasonal Craft Cocktails","Classic Cocktails","Whiskey Selection"],address:"1520 N Damen Ave, Chicago, IL 60622",hours:"Sun-Fri 6PM-2AM, Sat 6PM-3AM",lat:41.9093,lng:-87.6773,reservation:"walk-in",hh:"",instagram:"theviolethour",website:"https://www.theviolethour.com",reserveUrl:"",awards:"James Beard Award",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:3},
  {name:"Lula Cafe",phone:"(773) 489-9554",cuisine:"New American / Farm to Table",neighborhood:"Logan Square",score:90,price:2,tags:["Brunch","Local Favorites","Critics Pick","Date Night"],indicators:[],description:"The restaurant that made Logan Square a dining destination before anyone else showed up. Jason Hammel has been cooking seasonal, farm-driven food here since 2001 with a warmth and consistency that newer spots cannot replicate. The Monday Farm Dinner prix fixe is legendary. Brunch is one of the best in Chicago.",dishes:["Farm Dinner (Monday)","Pasta of the Day","Weekend Brunch"],address:"2537 N Kedzie Blvd, Chicago, IL 60647",hours:"Wed-Mon, hours vary",lat:41.9272,lng:-87.7080,reservation:"Resy",hh:"",instagram:"lulacafe",website:"https://www.lulacafe.com",reserveUrl:"",awards:"James Beard Semifinalist",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:3},
  {name:"Publican",phone:"(312) 733-9555",cuisine:"Beer Hall / Pork",neighborhood:"West Loop",score:91,price:2,tags:["Local Favorites","Casual","Critics Pick","Happy Hour"],indicators:[],description:"Paul Kahan European-style beer hall dedicated to beer, pork, and oysters -- three things Chicago does exceptionally well. The communal tables, massive beer list, and whole-hog mentality make it feel like a celebration every night. The pork rinds are addictive, the frites are perfect, and the oyster selection is among the best in the city.",dishes:["Pork Rinds","Frites with Aioli","Oysters"],address:"837 W Fulton Market, Chicago, IL 60607",hours:"Mon-Sun 4PM-11PM",lat:41.8868,lng:-87.6489,reservation:"Resy",hh:"Mon-Fri 4-6PM",instagram:"publicanchi",website:"https://www.thepublicanrestaurant.com",reserveUrl:"",awards:"James Beard Award",group:"One Off Hospitality",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:3},
  {name:"Joe's Seafood, Prime Steak & Stone Crab",phone:"(312) 379-5637",cuisine:"Seafood / Steakhouse",neighborhood:"River North",score:89,price:3,tags:["Seafood","Steakhouse","Date Night","Celebrations"],indicators:[],description:"The Chicago outpost of the legendary Miami Beach stone crab house, and it delivers the goods. The stone crab claws (seasonal) are the star, served cold with mustard sauce exactly as God intended. The steaks are prime, the sides are generous, and the Old Hollywood ambiance makes every meal feel like an occasion.",dishes:["Stone Crab Claws","Prime Bone-In Ribeye","Key Lime Pie"],address:"60 E Grand Ave, Chicago, IL 60611",hours:"Mon-Sun 11:30AM-10PM",lat:41.8917,lng:-87.6250,reservation:"OpenTable",hh:"",instagram:"joesrestaurants",website:"https://www.joes.net/chicago",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:4},

  // === MORE ESSENTIALS ===
  {name:"Au Cheval",phone:"(312) 929-4580",cuisine:"Burgers / Diner",neighborhood:"West Loop",score:93,price:2,tags:["Local Favorites","Casual","Critics Pick","Late Night"],indicators:[],description:"The best burger in Chicago and one of the best in America -- a double cheeseburger with a fried egg on a perfectly squishy bun that has inspired a thousand imitations. The wait can stretch past two hours on weekends with no reservations. The thick-cut bacon is the add-on that separates amateurs from professionals. Worth every minute.",dishes:["Single Cheeseburger with Egg","Double Cheeseburger","Hash Browns"],address:"800 W Randolph St, Chicago, IL 60607",hours:"Mon-Sun 10AM-2AM",lat:41.8841,lng:-87.6476,reservation:"walk-in",hh:"",instagram:"aucheval",website:"https://www.auchevalchicago.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:3},
  {name:"Frontera Grill",phone:"(312) 661-1434",cuisine:"Mexican",neighborhood:"River North",score:91,price:2,tags:["Mexican","Local Favorites","Critics Pick"],indicators:[],description:"Rick Bayless flagship Mexican restaurant that introduced Chicago to the depth and sophistication of regional Mexican cuisine. The moles are complex, the salsas are vibrant, and the margaritas are dangerously good. Topolobampo next door is the fine-dining sibling, but Frontera is where the soul lives.",dishes:["Mole Negro","Carne Asada","Margarita"],address:"445 N Clark St, Chicago, IL 60654",hours:"Tue-Sat 11:30AM-10PM",lat:41.8907,lng:-87.6310,reservation:"OpenTable",hh:"",instagram:"rickbayless",website:"https://www.rickbayless.com",reserveUrl:"",awards:"James Beard Award",group:"Bayless Restaurants",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:3},
  {name:"Bavette's Bar & Boeuf",phone:"(312) 624-8154",cuisine:"Steakhouse",neighborhood:"River North",score:92,price:3,tags:["Steakhouse","Date Night","Cocktails","Late Night"],indicators:[],description:"The sexiest steakhouse in Chicago -- dim lighting, jazz on the speakers, and a clientele that looks like they stepped out of a prohibition-era film. The bone-in ribeye is perfectly crusted, the shrimp DeJonghe is a Chicago classic done right, and the foie gras is decadent. Dress up. This is an event.",dishes:["Bone-In Ribeye","Shrimp DeJonghe","Foie Gras"],address:"218 W Kinzie St, Chicago, IL 60654",hours:"Mon-Sun 5PM-12AM",lat:41.8893,lng:-87.6355,reservation:"Resy",hh:"",instagram:"bavettes",website:"https://www.bavetteschicago.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:4},
  {name:"Pilsen Rooftop",phone:"",cuisine:"Rooftop Bar",neighborhood:"Pilsen",score:85,price:2,tags:["Rooftop","Cocktails","Patio","Date Night","Local Favorites"],indicators:["outdoor-seating"],description:"Pilsen open-air rooftop bar with skyline views and a laid-back neighborhood vibe that is the opposite of River North velvet-rope nonsense. Craft cocktails, Mexican-inspired bites, and a crowd that actually lives in the neighborhood. One of the best sunset spots in the city without the tourist markup.",dishes:["Craft Cocktails","Mexican Bites","Sunset Views"],address:"1641 S Allport St, Chicago, IL 60608",hours:"Thu-Sun 4PM-12AM (seasonal)",lat:41.8580,lng:-87.6576,reservation:"walk-in",hh:"",instagram:"pilsenrooftop",website:"",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
  {name:"Intelligentsia Coffee",phone:"(312) 920-9332",cuisine:"Coffee",neighborhood:"The Loop",score:86,price:1,tags:["Bakery/Coffee","Casual","Local Favorites"],indicators:[],description:"The Chicago coffee roaster that helped define third-wave coffee in America. The Millennium Park location is the flagship, with baristas pulling shots with the kind of precision that makes Starbucks feel like a war crime. The Black Cat espresso blend is the standard. Multiple locations across the city.",dishes:["Black Cat Espresso","Cortado","Drip Coffee"],address:"53 E Randolph St, Chicago, IL 60601",hours:"Mon-Fri 6AM-7PM, Sat-Sun 7AM-7PM",lat:41.8844,lng:-87.6260,reservation:"walk-in",hh:"",instagram:"intelligentsiacoffee",website:"https://www.intelligentsia.com",reserveUrl:"",awards:"",group:"",bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:false,suburb:false,menuUrl:"",res_tier:2},
];

// Add IDs
let id = 1;
CHICAGO_DATA.forEach(r => { r.id = id++; });

// 2. Add to CITY_DATA
const cityDataMarker = "const CITY_DATA = {";
const cdIdx = html.indexOf(cityDataMarker);
if(cdIdx === -1){ console.error('Could not find CITY_DATA'); process.exit(1); }
// Find closing of CITY_DATA
const cdClose = html.indexOf('};', cdIdx);
// Check if chicago already exists
if(html.substring(cdIdx, cdClose).includes("'Chicago'")){
  console.log('Chicago already in CITY_DATA, updating...');
  // Replace the chicago entry
  const chiStart = html.indexOf("'Chicago':", cdIdx);
  if(chiStart > -1){
    const chiEnd = html.indexOf("],", chiStart) + 2;
    html = html.substring(0, chiStart) + "'Chicago': " + JSON.stringify(CHICAGO_DATA) + "," + html.substring(chiEnd);
  }
} else {
  // Add chicago before the closing
  const insertPoint = cdClose;
  html = html.substring(0, insertPoint) + "  'Chicago': " + JSON.stringify(CHICAGO_DATA) + ",\n" + html.substring(insertPoint);
  console.log('Added Chicago to CITY_DATA');
}

// 3. Add Chicago tourist attractions
const attractions = JSON.parse(fs.readFileSync('scripts/chicago-attractions.json','utf8'));
// Find Chicago in CITY_DATA and add attractions
const chiIdx = html.indexOf("'Chicago':");
if(chiIdx > -1){
  const arrStartChi = html.indexOf('[', chiIdx);
  let d2=0, arrEndChi=arrStartChi;
  for(let j=arrStartChi;j<html.length;j++){
    if(html[j]==='[')d2++;if(html[j]===']'){d2--;if(d2===0){arrEndChi=j+1;break;}}
  }
  let chiArr = JSON.parse(html.substring(arrStartChi, arrEndChi));
  const maxChiId = Math.max(...chiArr.map(r=>r.id));
  let nextChiId = maxChiId + 1;
  const existingNames = new Set(chiArr.map(r=>r.name.toLowerCase()));
  let addedAttr = 0;
  attractions.forEach(a => {
    if(!existingNames.has(a.name.toLowerCase())){
      a.id = nextChiId++;
      a.bestOf=[];a.busyness=null;a.waitTime=null;a.popularTimes=null;a.lastUpdated=null;a.trending=false;a.group='';a.suburb=false;a.menuUrl='';a.res_tier=2;
      chiArr.push(a);
      addedAttr++;
    }
  });
  html = html.substring(0, arrStartChi) + JSON.stringify(chiArr) + html.substring(arrEndChi);
  console.log('Added', addedAttr, 'Chicago attractions. Total Chicago spots:', chiArr.length);
}

// 4. Add Chicago neighborhoods
const nHoodMarker = "const CITY_NEIGHBORHOODS = {";
const nhIdx = html.indexOf(nHoodMarker);
if(nhIdx > -1 && !html.substring(nhIdx, nhIdx+2000).includes("'Chicago'")){
  // Find where to insert - before the closing }
  const nhClose = html.indexOf('};', nhIdx);
  const chiNeighborhoods = `
  'Chicago':{
    'West Loop / Fulton Market':{emoji:'🔥',vibe:'The undisputed dining capital of Chicago. Randolph Street and Fulton Market pack more Michelin stars per block than anywhere in the Midwest.',bestFor:'Fine Dining, Trendy, Date Night',knownFor:'Girl & the Goat, Avec, Au Cheval, Publican',mustVisit:'Monteverde, Smyth, Girl & the Goat, Au Cheval',tip:'Restaurant Row is Randolph between Halsted and Ogden. Book ahead -- walk-ins are tough.'},
    'River North':{emoji:'🏙️',vibe:'Chicago flashiest dining neighborhood with steakhouses, deep dish, and nightlife. Tourist-heavy but some genuine gems.',bestFor:'Steakhouses, Deep Dish, Nightlife',knownFor:'Lou Malnati\\'s, Bavette\\'s, Portillo\\'s, RPM Italian',mustVisit:'Bavette\\'s, Joe\\'s, Frontera Grill, Portillo\\'s',tip:'Avoid the generic sports bars on Division. The real restaurants are on Kinzie and Hubbard.'},
    'Lincoln Park':{emoji:'🌳',vibe:'Upscale residential with the zoo, DePaul, and some of Chicago most important restaurants hiding on quiet streets.',bestFor:'Fine Dining, Brunch, Family',knownFor:'Alinea, Pequod\\'s, Lincoln Park Zoo, North Avenue Beach',mustVisit:'Alinea, Pequod\\'s, R.J. Grunts',tip:'Alinea is here but books months out. Pequod\\'s is walk-in only and the wait is always worth it.'},
    'Wicker Park':{emoji:'🎨',vibe:'The creative heart of Chicago -- indie shops, cocktail bars, and restaurants with real personality. Still cool despite the gentrification.',bestFor:'Cocktails, Casual, Late Night, Patio',knownFor:'Big Star, The Violet Hour, Piece Pizza, record shops',mustVisit:'Big Star, The Violet Hour, Dove\\'s Luncheonette',tip:'Big Star patio on a summer evening is peak Chicago. The Violet Hour has no sign -- look for the address.'},
    'Logan Square':{emoji:'🌮',vibe:'The neighborhood that stole Wicker Park\\'s cool factor. Diverse, creative, and home to some of Chicago most exciting young chefs.',bestFor:'Trendy, Local Favorites, Mexican, Brunch',knownFor:'Lula Cafe, Fat Rice, Logan Theatre, Palmer Square',mustVisit:'Lula Cafe, Mi Tocaya Antojeria, Longman & Eagle',tip:'The 2800 block of Logan Blvd has the most restaurants per block. Monday Farm Dinner at Lula Cafe is a local secret.'},
    'Pilsen':{emoji:'🇲🇽',vibe:'Chicago most vibrant Mexican neighborhood with incredible street art, authentic taquerias, and a growing creative scene.',bestFor:'Mexican, Street Food, Art, Local Favorites',knownFor:'18th Street murals, National Museum of Mexican Art, taquerias',mustVisit:'Don Pedro Carnitas, Dusek\\'s, Pilsen Rooftop',tip:'Walk 18th Street for the murals and taquerias. The National Museum of Mexican Art is free and outstanding.'},
    'Chinatown':{emoji:'🏮',vibe:'One of the oldest and largest Chinatowns in the US with authentic Cantonese, Sichuan, and dim sum that rivals either coast.',bestFor:'Chinese, Dim Sum, Cheap Eats',knownFor:'Chinatown Square, dim sum halls, bakeries',mustVisit:'MingHin Cuisine, Lao Sze Chuan, Chiu Quon Bakery',tip:'MingHin for dim sum on weekends -- go before 11 AM to avoid the massive line. The bakeries on Wentworth have $1 pork buns.'},
    'Gold Coast':{emoji:'💎',vibe:'Chicago most affluent neighborhood with Oak Street boutiques, lakefront mansions, and upscale dining along Rush Street.',bestFor:'Upscale Dining, Brunch, Shopping',knownFor:'Oak Street shopping, Rush Street, Drake Hotel',mustVisit:'Maple & Ash, Gibson\\'s, Le Colonial',tip:'Gibson\\'s is the power steakhouse. Maple & Ash brunch is one of the best in the city.'},
  },`;
  html = html.substring(0, nhClose) + chiNeighborhoods + '\n' + html.substring(nhClose);
  console.log('Added Chicago neighborhoods');
}

// 5. Add Chicago to CURATED_ACTIVITIES
const actMarker = "const CURATED_ACTIVITIES = {";
const actIdx = html.indexOf(actMarker);
if(actIdx > -1 && !html.substring(actIdx, actIdx+5000).includes("'chicago'")){
  const actClose = html.indexOf('};', actIdx);
  const chiActivities = `
  'chicago': [
    {name:'Chicago Architecture River Cruise',category:'Landmark',price:'From $45',rating:'4.9',reviews:'20K+',emoji:'🏙️',url:'https://www.viator.com/Chicago-tours/Architecture-Tours/d673-g4-c26967?utm_source=appetyt&utm_medium=referral',desc:'The #1 thing to do in Chicago. 90-minute cruise with expert guides on 130+ years of architectural history.'},
    {name:'Skydeck Chicago at Willis Tower',category:'Observation',price:'From $35',rating:'4.7',reviews:'15K+',emoji:'🏢',url:'https://www.viator.com/Chicago-attractions/Skydeck-Chicago-Willis-Tower/d673-a834?utm_source=appetyt&utm_medium=referral',desc:'103rd floor with The Ledge glass box extending 4.3 feet out. See four states on a clear day.'},
    {name:'Art Institute of Chicago',category:'Museum',price:'From $35',rating:'4.9',reviews:'25K+',emoji:'🎨',url:'https://www.viator.com/Chicago-attractions/Art-Institute-of-Chicago/d673-a833?utm_source=appetyt&utm_medium=referral',desc:'World-class museum with Nighthawks, American Gothic, and A Sunday on La Grande Jatte. Allow 3+ hours.'},
    {name:'Chicago Deep Dish Pizza Tour',category:'Food Tour',price:'From $65',rating:'4.8',reviews:'3K+',emoji:'🍕',url:'https://www.viator.com/Chicago-tours/Food-Tours/d673-g6-c80?utm_source=appetyt&utm_medium=referral',desc:'Taste deep dish from multiple legendary spots and settle the Lou vs Giordano debate once and for all.'},
    {name:'Chicago Gangster & Crime Tour',category:'History',price:'From $35',rating:'4.7',reviews:'5K+',emoji:'🔫',url:'https://www.viator.com/Chicago-tours/Historical-and-Heritage-Tours/d673-g4-c12?utm_source=appetyt&utm_medium=referral',desc:'Al Capone, John Dillinger, and the Valentine Day Massacre. Drive to real crime sites with expert narration.'},
    {name:'Wrigley Field Tour',category:'Sports',price:'From $30',rating:'4.8',reviews:'4K+',emoji:'⚾',url:'https://www.viator.com/Chicago-attractions/Wrigley-Field/d673-a12133?utm_source=appetyt&utm_medium=referral',desc:'Behind-the-scenes of the Friendly Confines. Walk the dugout, see the press box, touch the ivy.'},
    {name:'Navy Pier Centennial Wheel',category:'Entertainment',price:'From $18',rating:'4.6',reviews:'8K+',emoji:'🎡',url:'https://www.viator.com/Chicago-attractions/Navy-Pier/d673-a835?utm_source=appetyt&utm_medium=referral',desc:'200-foot Ferris wheel with enclosed gondolas and stunning Lake Michigan views. Best at sunset.'},
    {name:'Chicago Speakeasy & Cocktail Tour',category:'Nightlife',price:'From $85',rating:'4.8',reviews:'2K+',emoji:'🍸',url:'https://www.viator.com/Chicago-tours/Nightlife/d673-g12-c20?utm_source=appetyt&utm_medium=referral',desc:'Visit hidden bars including The Violet Hour. Includes cocktails at 3 stops with Prohibition history.'},
  ],`;
  html = html.substring(0, actClose) + chiActivities + '\n' + html.substring(actClose);
  console.log('Added Chicago curated activities');
}

fs.writeFileSync('index.html', html, 'utf8');
fs.copyFileSync('index.html', 'index');
console.log('Chicago build complete!');
