// Chicago 401 → 500
const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');
const cdStart = html.indexOf('CITY_DATA');
const chiPos = html.indexOf("'Chicago':", cdStart);
const arrS = html.indexOf('[', chiPos);
let d=0,arrE=arrS;
for(let j=arrS;j<html.length;j++){if(html[j]==='[')d++;if(html[j]===']'){d--;if(d===0){arrE=j+1;break;}}}
let arr = JSON.parse(html.substring(arrS, arrE));
console.log('Chicago start:', arr.length);
let maxId = Math.max(...arr.map(r=>r.id)), nextId = maxId+1;
const ex = new Set(arr.map(r=>r.name.toLowerCase()));
let added=0;
function add(s){
  if(ex.has(s.name.toLowerCase()))return;
  s.id=nextId++;s.bestOf=[];s.busyness=null;s.waitTime=null;s.popularTimes=null;s.lastUpdated=null;s.trending=false;s.group=s.group||'';s.suburb=s.suburb||false;s.menuUrl='';s.res_tier=s.price>=3?4:2;s.indicators=[];s.awards=s.awards||'';s.phone=s.phone||'';s.reserveUrl='';s.hh='';s.verified=true;s.instagram=s.instagram||'';s.website=s.website||'';s.reservation=s.reservation||'walk-in';s.hours=s.hours||'';
  arr.push(s);ex.add(s.name.toLowerCase());added++;
}

// 2025-2026 openings, neighborhood gems, deeper cuts
add({name:"Midōsuji",cuisine:"Japanese Omakase",neighborhood:"West Loop",score:91,price:4,tags:["Japanese","Sushi","Fine Dining","Exclusive"],description:"Eight-seat omakase that opened September 2025. One of Chicago most intimate and exclusive dining experiences.",dishes:["8-Seat Omakase","Seasonal Nigiri"],address:"West Loop, Chicago, IL 60607",lat:41.8867,lng:-87.6517,reservation:"Tock"});
add({name:"Il Carciofo",cuisine:"Roman Italian",neighborhood:"West Loop",score:88,price:2,tags:["Italian","Date Night","Critics Pick"],description:"Top Chef winner Joe Flamm spotlights Roman cuisine in the West Loop. Opened December 2024.",dishes:["Roman Pastas","Carciofi","Italian Wine"],address:"1040 W Randolph St, Chicago, IL 60607",lat:41.8841,lng:-87.6538,reservation:"Resy"});
add({name:"Roll Up by Oui",cuisine:"Hand Roll Sushi",neighborhood:"River North",score:86,price:2,tags:["Japanese","Sushi","Casual"],description:"Hand rolls and sushi with a dozen combinations plus small plates like chicken karaage and furikake fries.",dishes:["Hand Rolls","Chicken Karaage","Furikake Fries"],address:"River North, Chicago, IL 60654",lat:41.8897,lng:-87.6300,reservation:"walk-in"});
add({name:"The Radicle",cuisine:"Coastal Italian",neighborhood:"Logan Square",score:87,price:2,tags:["Italian","Cocktails","Oysters","Date Night"],description:"Chef Joe Frillman coastal Italian meets Midwest with oysters, veggie plates, and artisanal pizzas in Logan Square.",dishes:["Oysters","Artisan Pizza","Veggie Plates"],address:"2738 W Fullerton Ave, Chicago, IL 60647",lat:41.9249,lng:-87.6980,reservation:"Resy"});
add({name:"La Lunita",cuisine:"Mexican / Bar",neighborhood:"Logan Square",score:86,price:1,tags:["Mexican","Cocktails","Local Favorites"],description:"Mexican bar and restaurant in Logan Square. Casual with great margaritas and authentic Mexican food.",dishes:["Margaritas","Mexican Plates","Bar Food"],address:"Logan Square, Chicago, IL 60647",lat:41.9249,lng:-87.7080,reservation:"walk-in"});
add({name:"Little Lark",cuisine:"Pizza / Sandwiches",neighborhood:"Avondale",score:85,price:1,tags:["Pizza","Casual","Local Favorites"],description:"Pizza and sandwich spot in Avondale from the acclaimed Meadowlark group.",dishes:["Pizza","Sandwiches","Coffee"],address:"Avondale, Chicago, IL 60618",lat:41.9360,lng:-87.7108,reservation:"walk-in"});
add({name:"Gingie",cuisine:"Japanese-European Fusion",neighborhood:"River North",score:88,price:3,tags:["Japanese","European","Fine Dining","Date Night"],description:"Chef Brian Lockwood first brick-and-mortar. Shareable dishes blending European technique with Japanese influences. From the Boka team.",dishes:["Japanese-European Fusion","Shareable Plates"],address:"701 N Wells St, Chicago, IL 60654",lat:41.8938,lng:-87.6340,reservation:"Resy",group:"Boka"});
add({name:"Hokkaido Ramen Santouka",cuisine:"Japanese Ramen",neighborhood:"West Loop",score:87,price:1,tags:["Japanese","Ramen","Casual"],description:"43-seat West Loop location of the famed Japanese ramen chain known for signature scratch-made tonkotsu broths. Opened April 2026.",dishes:["Tonkotsu Ramen","Shio Ramen","Japanese Sides"],address:"West Loop, Chicago, IL 60607",lat:41.8867,lng:-87.6517,reservation:"walk-in"});
add({name:"The Alley Cat",cuisine:"Dive Bar",neighborhood:"Wicker Park",score:85,price:1,tags:["Casual","Late Night","Cocktails"],description:"New Wicker Park dive bar with classic cocktails, wines, and crispy taters with black walnut aioli.",dishes:["Classic Cocktails","Crispy Taters","Bar Snacks"],address:"Wicker Park, Chicago, IL 60622",lat:41.9096,lng:-87.6771,reservation:"walk-in"});
// More neighborhoods
add({name:"Bad Hunter",cuisine:"Vegetable-Forward",neighborhood:"West Loop",score:87,price:2,tags:["Vegetarian","New American","Date Night"],description:"Vegetable-forward restaurant in the West Loop celebrating produce with creative technique.",dishes:["Seasonal Vegetables","Creative Plates","Natural Wine"],address:"802 W Randolph St, Chicago, IL 60607",lat:41.8841,lng:-87.6479,reservation:"Resy"});
add({name:"Mariscos El Veneno Pilsen",cuisine:"Mexican Seafood",neighborhood:"Pilsen",score:86,price:1,tags:["Mexican","Seafood","Casual"],description:"Pilsen seafood with aguachile, ceviche, and campechanas.",dishes:["Aguachile","Ceviche","Campechana"],address:"1024 W 18th St, Chicago, IL 60608",lat:41.8579,lng:-87.6548,reservation:"walk-in"});
add({name:"Cemitas Puebla",cuisine:"Mexican / Pueblan",neighborhood:"Humboldt Park",score:87,price:1,tags:["Mexican","Casual","Local Favorites","Hole in the Wall"],description:"Pueblan-style cemitas and other specialties from the Puebla region. The cemita sandwich is loaded and authentic.",dishes:["Cemita Poblana","Tacos Arabes","Mole"],address:"3619 W North Ave, Chicago, IL 60647",lat:41.9104,lng:-87.7189,reservation:"walk-in"});
add({name:"Taqueria Los Comales",cuisine:"Mexican",neighborhood:"Pilsen",score:85,price:1,tags:["Mexican","Casual","Local Favorites"],description:"Pilsen taqueria with excellent al pastor on the trompo and cheap, filling tacos.",dishes:["Al Pastor","Street Tacos","Tortas"],address:"1544 W 18th St, Chicago, IL 60608",lat:41.8579,lng:-87.6650,reservation:"walk-in"});
add({name:"Mango Pickle",cuisine:"Indian",neighborhood:"Edgewater",score:86,price:1,tags:["Indian","Local Favorites","Casual"],description:"Modern Indian in Edgewater with creative takes on subcontinental classics.",dishes:["Creative Indian","Biryani","Street Food"],address:"5842 N Broadway, Chicago, IL 60660",lat:41.9856,lng:-87.6588,reservation:"walk-in"});
add({name:"Pho Viet",cuisine:"Vietnamese",neighborhood:"Uptown",score:85,price:1,tags:["Vietnamese","Casual","Local Favorites"],description:"Uptown pho shop on Argyle with rich, deeply flavored broth.",dishes:["Pho","Banh Mi","Bun"],address:"4941 N Broadway, Chicago, IL 60640",lat:41.9724,lng:-87.6588,reservation:"walk-in"});
add({name:"Tank Noodle",cuisine:"Vietnamese",neighborhood:"Uptown",score:87,price:1,tags:["Vietnamese","Local Favorites","Casual"],description:"Argyle Street Vietnamese institution with massive pho bowls and an extensive menu. Always packed.",dishes:["Pho","Spring Rolls","Vietnamese Plates"],address:"4953 N Broadway, Chicago, IL 60640",lat:41.9726,lng:-87.6588,reservation:"walk-in"});
add({name:"Hai Yen",cuisine:"Vietnamese / Chinese",neighborhood:"Uptown",score:85,price:1,tags:["Vietnamese","Chinese","Casual"],description:"Argyle Street Vietnamese-Chinese with quality dishes at low prices.",dishes:["Pho","Chinese-Vietnamese","Noodles"],address:"1055 W Argyle St, Chicago, IL 60640",lat:41.9718,lng:-87.6579,reservation:"walk-in"});
add({name:"Lawrence Fish Market",cuisine:"Sushi / Japanese",neighborhood:"Albany Park",score:86,price:1,tags:["Sushi","Japanese","Casual","Local Favorites","Hole in the Wall"],description:"Cash-only Albany Park fish market with incredibly cheap sushi rolls. No seats, takeout only, massive portions.",dishes:["Cheap Sushi Rolls","Sashimi","Takeout Only"],address:"2120 W Lawrence Ave, Chicago, IL 60625",lat:41.9686,lng:-87.6808,reservation:"walk-in"});
add({name:"Reno Pilsen",cuisine:"Tavern-Style Pizza",neighborhood:"Pilsen",score:87,price:1,tags:["Pizza","Late Night","Local Favorites","Natural Wine"],description:"Pilsen tavern-style pizza with creative toppings and natural wine. Pepperoni cups with hot honey is the TikTok order.",dishes:["Pepperoni Hot Honey","Tavern Pizza","Natural Wine"],address:"2607 S Blue Island Ave, Chicago, IL 60608",lat:41.8454,lng:-87.6621,reservation:"walk-in"});
add({name:"Bungalow by Middle Brow North",cuisine:"Farm-to-Table Brewery",neighborhood:"Logan Square",score:87,price:2,tags:["Farm-to-Table","Craft Beer","Pizza"],description:"Farm-to-table brewery with everything sourced within 150 miles. Great pizza and house beer.",dishes:["Farm Pizza","House Beer","Local"],address:"2840 W Armitage Ave, Chicago, IL 60647",lat:41.9172,lng:-87.6987,reservation:"walk-in"});
add({name:"Mott St.",cuisine:"Asian Fusion",neighborhood:"Wicker Park",score:88,price:2,tags:["Asian Fusion","Date Night","Late Night"],description:"Edward Kim Asian small plates. The whole fried chicken is legendary. Cocktails and late-night energy.",dishes:["Whole Fried Chicken","Pork Belly Ssam"],address:"1401 N Ashland Ave, Chicago, IL 60622",lat:41.9072,lng:-87.6690,reservation:"walk-in"});
add({name:"Luella's Southern Kitchen",cuisine:"Southern",neighborhood:"Lincoln Square",score:86,price:1,tags:["Southern","Brunch","Local Favorites","Black-Owned"],description:"Southern comfort food in Lincoln Square with fried chicken, biscuits, and mac and cheese.",dishes:["Fried Chicken","Biscuits","Mac & Cheese"],address:"4609 N Lincoln Ave, Chicago, IL 60625",lat:41.9658,lng:-87.6879,reservation:"walk-in"});
add({name:"Fat Chris's Pizza & Such",cuisine:"Pizza",neighborhood:"Bucktown",score:85,price:1,tags:["Pizza","Casual","Local Favorites"],description:"Bucktown pizza with creative slices and a fun atmosphere.",dishes:["Creative Slices","Whole Pies"],address:"2052 W Division St, Chicago, IL 60622",lat:41.9032,lng:-87.6793,reservation:"walk-in"});
add({name:"The Dawson",cuisine:"American / Cocktails",neighborhood:"West Town",score:86,price:2,tags:["New American","Cocktails","Date Night","Patio"],description:"West Town American restaurant with strong cocktail program and a beautiful patio.",dishes:["Craft Cocktails","Seasonal American","Patio"],address:"730 W Grand Ave, Chicago, IL 60654",lat:41.8912,lng:-87.6462,reservation:"OpenTable"});
add({name:"Lonesome Rose",cuisine:"Tex-Mex / Bar",neighborhood:"Wicker Park",score:85,price:1,tags:["Mexican","Cocktails","Casual","Late Night"],description:"Tex-Mex and cocktails in Wicker Park. Queso, tacos, and frozen margaritas.",dishes:["Queso","Frozen Margaritas","Tacos"],address:"2101 N California Ave, Chicago, IL 60647",lat:41.9207,lng:-87.6976,reservation:"walk-in"});
add({name:"Nando Milano Trattoria",cuisine:"Italian",neighborhood:"River North",score:86,price:2,tags:["Italian","Date Night","Local Favorites"],description:"Milanese-style Italian in River North with handmade pasta and cotoletta alla milanese.",dishes:["Cotoletta Milanese","Handmade Pasta"],address:"337 N Wells St, Chicago, IL 60654",lat:41.8889,lng:-87.6339,reservation:"OpenTable"});
add({name:"Lupo Pizzeria",cuisine:"Neapolitan Pizza",neighborhood:"Wicker Park",score:86,price:1,tags:["Pizza","Italian","Casual"],description:"Neapolitan pizza in Wicker Park with proper charred crusts and quality toppings.",dishes:["Neapolitan Pizza","Salads","Wine"],address:"1914 W Division St, Chicago, IL 60622",lat:41.9032,lng:-87.6773,reservation:"walk-in"});
add({name:"Blackbird",cuisine:"New American",neighborhood:"West Loop",score:89,price:3,tags:["Fine Dining","Date Night","Critics Pick"],description:"Pioneering West Loop fine dining that helped define the Randolph Street restaurant boom. One of Chicago most important restaurants.",dishes:["Seasonal Tasting","Refined American"],address:"619 W Randolph St, Chicago, IL 60661",lat:41.8841,lng:-87.6446,reservation:"OpenTable"});
add({name:"Fat Rice",cuisine:"Macanese",neighborhood:"Logan Square",score:88,price:2,tags:["Asian Fusion","Date Night","Local Favorites","Critics Pick"],description:"Macanese cuisine in Logan Square blending Portuguese and Chinese flavors. Unique in all of America.",dishes:["Arroz Gordo","Macanese Plates","Portuguese-Chinese"],address:"2957 W Diversey Ave, Chicago, IL 60647",lat:41.9316,lng:-87.7031,reservation:"walk-in"});
add({name:"Pacific Standard Time",cuisine:"California / Mediterranean",neighborhood:"River North",score:87,price:2,tags:["Mediterranean","Date Night","Local Favorites"],description:"California-Mediterranean with wood-fired dishes in River North. Bright, seasonal, and produce-forward.",dishes:["Wood-Fired Dishes","Seasonal Plates"],address:"141 W Erie St, Chicago, IL 60654",lat:41.8940,lng:-87.6319,reservation:"Resy"});
add({name:"Temporis",cuisine:"Fine Dining / Tasting Menu",neighborhood:"Noble Square",score:91,price:4,tags:["Fine Dining","Exclusive","Date Night"],description:"Intimate BYOB tasting menu in Noble Square. 28 seats, 10 courses. One of Chicago most underrated fine dining spots.",dishes:["10-Course Tasting","BYOB","Intimate Dining"],address:"933 N Ashland Ave, Chicago, IL 60622",lat:41.8988,lng:-87.6679,reservation:"Tock"});
add({name:"Monteverde West Loop",cuisine:"Italian",neighborhood:"West Loop",score:90,price:2,tags:["Italian","Date Night","Critics Pick"],description:"Chef Sarah Grueneberg handmade pasta in the West Loop. The tortelli is heavenly and the tiramisu is perfect.",dishes:["Handmade Pasta","Tortelli","Tiramisu"],address:"1020 W Madison St, Chicago, IL 60607",lat:41.8818,lng:-87.6529,reservation:"Resy"});
add({name:"Etta",cuisine:"Wood-Fired",neighborhood:"Bucktown",score:87,price:2,tags:["New American","Date Night","Patio"],description:"Wood-fired cooking in Bucktown with seasonal vegetables and meats. From the Boka group.",dishes:["Wood-Fired Dishes","Seasonal Menu"],address:"1840 W North Ave, Chicago, IL 60622",lat:41.9104,lng:-87.6740,reservation:"Resy",group:"Boka"});
add({name:"GT Fish & Oyster",cuisine:"Seafood",neighborhood:"River North",score:87,price:2,tags:["Seafood","Oysters","Date Night"],description:"River North oyster bar and seafood restaurant from the Boka group. Fresh oysters and creative seafood plates.",dishes:["Oyster Bar","Seafood Plates"],address:"531 N Wells St, Chicago, IL 60654",lat:41.8912,lng:-87.6339,reservation:"OpenTable",group:"Boka"});
add({name:"Kai Zan Omakase",cuisine:"Japanese Omakase",neighborhood:"Humboldt Park",score:91,price:3,tags:["Japanese","Sushi","Fine Dining","BYOB"],description:"Twin brothers intimate BYOB omakase in Humboldt Park. 16-course menu with fish from Tsukiji at a fraction of comparable omakase prices.",dishes:["16-Course Omakase","BYOB","Seasonal Nigiri"],address:"2557 W Chicago Ave, Chicago, IL 60622",lat:41.8967,lng:-87.6896,reservation:"Resy"});
add({name:"Lula Cafe Logan Square",cuisine:"New American",neighborhood:"Logan Square",score:88,price:2,tags:["New American","Brunch","Date Night","Local Favorites"],description:"Logan Square institution with seasonal menus and legendary brunch. The Monday night prix fixe is a neighborhood tradition.",dishes:["Monday Prix Fixe","Seasonal Menu","Brunch"],address:"2537 N Kedzie Ave, Chicago, IL 60647",lat:41.9274,lng:-87.7080,reservation:"Resy"});
add({name:"Adalina",cuisine:"Italian Steakhouse",neighborhood:"Gold Coast",score:88,price:4,tags:["Steakhouse","Italian","Fine Dining"],description:"Gold Coast Italian steakhouse with prime cuts and Italian classics in an opulent setting.",dishes:["Prime Steak","Italian Classics"],address:"11 E Walton St, Chicago, IL 60611",lat:41.9005,lng:-87.6268,reservation:"OpenTable"});
add({name:"Split-Rail",cuisine:"Southern / American",neighborhood:"Humboldt Park",score:86,price:1,tags:["Southern","Casual","Local Favorites"],description:"Humboldt Park Southern-influenced American with fried chicken, catfish, and sides.",dishes:["Fried Chicken","Catfish","Southern Sides"],address:"2500 W Chicago Ave, Chicago, IL 60622",lat:41.8967,lng:-87.6884,reservation:"walk-in"});
add({name:"Cafe Cancale",cuisine:"French Seafood",neighborhood:"Logan Square",score:87,price:2,tags:["French","Seafood","Date Night"],description:"French seafood cafe in Logan Square with oysters, moules frites, and French wine.",dishes:["Oysters","Moules Frites","French Wine"],address:"1576 N Milwaukee Ave, Chicago, IL 60622",lat:41.9093,lng:-87.6743,reservation:"walk-in"});
add({name:"Ruxbin",cuisine:"New American / BYOB",neighborhood:"Noble Square",score:87,price:2,tags:["New American","BYOB","Date Night"],description:"BYOB neighborhood restaurant in Noble Square with creative seasonal plates.",dishes:["Seasonal Plates","BYOB","Creative American"],address:"851 N Ashland Ave, Chicago, IL 60622",lat:41.8975,lng:-87.6690,reservation:"walk-in"});
add({name:"Arbella",cuisine:"Mediterranean / Cocktails",neighborhood:"River North",score:86,price:2,tags:["Mediterranean","Cocktails","Date Night"],description:"River North Mediterranean cocktail bar with mezze and creative drinks.",dishes:["Mezze","Craft Cocktails"],address:"112 W Grand Ave, Chicago, IL 60654",lat:41.8912,lng:-87.6310,reservation:"walk-in"});
add({name:"The Signature Room",cuisine:"American / Views",neighborhood:"Streeterville",score:85,price:3,tags:["American","Scenic","Date Night","Iconic"],description:"95th floor of the former Hancock building with stunning skyline views. The food is secondary to the views but the cocktails are good.",dishes:["Skyline Views","American Plates","Cocktails"],address:"875 N Michigan Ave, 95th Fl, Chicago, IL 60611",lat:41.8988,lng:-87.6231,reservation:"OpenTable"});
add({name:"Avli River North",cuisine:"Greek",neighborhood:"River North",score:87,price:2,tags:["Greek","Date Night","Local Favorites"],description:"Modern Greek in River North with excellent seafood and a vibrant atmosphere.",dishes:["Greek Seafood","Mezze","Ouzo"],address:"615 N Wells St, Chicago, IL 60654",lat:41.8933,lng:-87.6339,reservation:"OpenTable"});
add({name:"Porto",cuisine:"Portuguese",neighborhood:"Bucktown",score:86,price:2,tags:["Portuguese","Date Night","Local Favorites"],description:"Portuguese restaurant in Bucktown with piri piri chicken, pasteis de nata, and Portuguese wine.",dishes:["Piri Piri Chicken","Pasteis de Nata","Portuguese Wine"],address:"1portal N Damen Ave, Chicago, IL 60622",lat:41.9095,lng:-87.6771,reservation:"OpenTable"});
add({name:"Taste of Lebanon",cuisine:"Lebanese",neighborhood:"Lincoln Square",score:85,price:1,tags:["Lebanese","Casual","Local Favorites"],description:"Lincoln Square Lebanese with excellent hummus, shawarma, and falafel at fair prices.",dishes:["Hummus","Shawarma","Falafel"],address:"4647 N Rockwell St, Chicago, IL 60625",lat:41.9658,lng:-87.6937,reservation:"walk-in"});
add({name:"Virtue Hyde Park",cuisine:"Southern",neighborhood:"Hyde Park",score:89,price:2,tags:["Southern","Date Night","Critics Pick","Black-Owned"],description:"Erick Williams Michelin Bib Gourmand Southern in Hyde Park. Fried catfish, biscuits, and genuine hospitality.",dishes:["Fried Catfish","Biscuits","Shrimp & Grits"],address:"1462 E 53rd St, Chicago, IL 60615",lat:41.7993,lng:-87.5880,reservation:"Resy",awards:"Michelin Bib Gourmand"});
add({name:"Bayan Ko",cuisine:"Filipino",neighborhood:"Ravenswood",score:87,price:1,tags:["Filipino","Brunch","Local Favorites"],description:"Filipino diner in Ravenswood with longsilog breakfast plates and adobo bowls.",dishes:["Longsilog","Adobo Bowl","Ube Pancakes"],address:"1820 W Montrose Ave, Chicago, IL 60613",lat:41.9616,lng:-87.6749,reservation:"walk-in"});
add({name:"Noodlebird",cuisine:"Thai / Noodles",neighborhood:"Lakeview",score:85,price:1,tags:["Thai","Noodles","Casual"],description:"Thai noodle shop in Lakeview with quick, affordable noodle dishes.",dishes:["Thai Noodles","Pad See Ew","Soup"],address:"3124 N Broadway, Chicago, IL 60657",lat:41.9393,lng:-87.6445,reservation:"walk-in"});
add({name:"Lettuce Entertain You Hub 51",cuisine:"American",neighborhood:"River North",score:85,price:2,tags:["American","Casual","Late Night"],description:"Lettuce Entertain You American restaurant and bar in River North. Fun atmosphere and late-night menu.",dishes:["American Plates","Sushi","Late Night"],address:"51 W Hubbard St, Chicago, IL 60654",lat:41.8897,lng:-87.6305,reservation:"OpenTable",group:"Lettuce Entertain You"});
add({name:"Traspasada",cuisine:"Mexican Seafood",neighborhood:"Hermosa",score:86,price:1,tags:["Mexican","Seafood","Local Favorites"],description:"Mexican seafood restaurant in Hermosa with excellent cocteles de mariscos and aguachile.",dishes:["Coctel de Mariscos","Aguachile","Fish Tacos"],address:"4259 W Armitage Ave, Chicago, IL 60639",lat:41.9172,lng:-87.7321,reservation:"walk-in"});
add({name:"Doña Naty",cuisine:"Mexican / Tamales",neighborhood:"Humboldt Park",score:85,price:1,tags:["Mexican","Casual","Local Favorites"],description:"Humboldt Park tamale and Mexican food spot with quality home-cooked Mexican.",dishes:["Tamales","Tacos","Mexican Plates"],address:"2510 W Division St, Chicago, IL 60622",lat:41.9029,lng:-87.6890,reservation:"walk-in"});
add({name:"Ocean's Pizza",cuisine:"Pizza",neighborhood:"Albany Park",score:85,price:1,tags:["Pizza","Casual","Local Favorites"],description:"Albany Park pizza with oversized slices and late-night hours. Neighborhood staple.",dishes:["Giant Slices","Whole Pies"],address:"4657 N Kedzie Ave, Chicago, IL 60625",lat:41.9658,lng:-87.7083,reservation:"walk-in"});
add({name:"Brown Bag Seafood",cuisine:"Seafood / Casual",neighborhood:"West Loop",score:85,price:1,tags:["Seafood","Casual","Healthy"],description:"Sustainable seafood bowls and tacos in the West Loop. Quick, healthy, and well-sourced.",dishes:["Seafood Bowls","Fish Tacos","Sustainable"],address:"340 N Clark St, Chicago, IL 60654",lat:41.8889,lng:-87.6312,reservation:"walk-in"});
add({name:"Pizano's Deep Dish",cuisine:"Deep Dish Pizza",neighborhood:"Loop",score:85,price:1,tags:["Pizza","Casual","Iconic"],description:"Deep dish from the Malnati family. Buttery crust and generous toppings.",dishes:["Deep Dish","Thin Crust"],address:"61 E Madison St, Chicago, IL 60602",lat:41.8818,lng:-87.6258,reservation:"walk-in"});
add({name:"Yusho Logan Square",cuisine:"Japanese / American",neighborhood:"Logan Square",score:86,price:2,tags:["Japanese","American","Casual","Late Night"],description:"Japanese-American izakaya in Logan Square with ramen, wings, and late-night eats.",dishes:["Ramen","Chicken Wings","Late Night"],address:"2853 N Kedzie Ave, Chicago, IL 60618",lat:41.9316,lng:-87.7080,reservation:"walk-in"});
add({name:"Dear Margaret",cuisine:"French-Canadian",neighborhood:"Lincoln Square",score:87,price:2,tags:["French","Date Night","Local Favorites"],description:"French-Canadian restaurant in Lincoln Square with Quebecois-inspired dishes. Unique in Chicago.",dishes:["Tourtiere","Quebecois Plates","French Wine"],address:"2965 N Lincoln Ave, Chicago, IL 60657",lat:41.9350,lng:-87.6620,reservation:"Resy"});
add({name:"Cafe Orchid",cuisine:"Turkish",neighborhood:"Bucktown",score:86,price:2,tags:["Turkish","Date Night","Local Favorites"],description:"Turkish restaurant in Bucktown with excellent kebabs and mezes. BYOB.",dishes:["Kebabs","Mezze","Turkish Coffee"],address:"1746 W Armitage Ave, Chicago, IL 60622",lat:41.9176,lng:-87.6735,reservation:"walk-in"});
add({name:"Herb",cuisine:"Thai",neighborhood:"Lakeview",score:86,price:1,tags:["Thai","Casual","Local Favorites"],description:"Lakeview Thai with authentic dishes and BYOB. The pad kra pao and curries are excellent.",dishes:["Pad Kra Pao","Thai Curry","BYOB Thai"],address:"1313 W Belmont Ave, Chicago, IL 60657",lat:41.9396,lng:-87.6606,reservation:"walk-in"});
add({name:"Le Bouchon Bucktown",cuisine:"French Bistro",neighborhood:"Bucktown",score:87,price:2,tags:["French","Date Night","Iconic"],description:"The original Bucktown French bistro. Steak frites, onion soup, and escargot since 1993.",dishes:["Steak Frites","Onion Soup","Escargot"],address:"1958 N Damen Ave, Chicago, IL 60647",lat:41.9163,lng:-87.6772,reservation:"walk-in"});
add({name:"Terzo Piano",cuisine:"Italian / Museum Dining",neighborhood:"The Loop",score:86,price:2,tags:["Italian","Scenic","Date Night"],description:"Modern Italian inside the Art Institute Modern Wing. Views of Millennium Park and excellent pasta.",dishes:["Italian Plates","Museum Views","Pasta"],address:"159 E Monroe St, Chicago, IL 60603",lat:41.8800,lng:-87.6232,reservation:"OpenTable"});
add({name:"RL Restaurant",cuisine:"American",neighborhood:"Gold Coast",score:86,price:3,tags:["American","Iconic","Date Night"],description:"Ralph Lauren restaurant on Michigan Ave. American classics in a clubby atmosphere. The Ralph Lauren aesthetic in restaurant form.",dishes:["American Classics","Steak","Power Lunch"],address:"115 E Chicago Ave, Chicago, IL 60611",lat:41.8967,lng:-87.6248,reservation:"OpenTable"});

console.log('Chicago added:', added, 'total:', arr.length);
html = html.substring(0, arrS) + JSON.stringify(arr) + html.substring(arrE);
fs.writeFileSync('index.html', html, 'utf8');
console.log('Chicago to 500 complete!');
