const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');
const chiMarker = "'Chicago':";
const chiIdx = html.indexOf(chiMarker, html.indexOf('CITY_DATA'));
const arrS = html.indexOf('[', chiIdx);
let d=0, arrE=arrS;
for(let j=arrS;j<html.length;j++){if(html[j]==='[')d++;if(html[j]===']'){d--;if(d===0){arrE=j+1;break;}}}
let arr = JSON.parse(html.substring(arrS, arrE));
const maxId = Math.max(...arr.map(r=>r.id));
let nextId = maxId + 1;
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let added = 0;
function add(s){if(existing.has(s.name.toLowerCase()))return;s.id=nextId++;s.bestOf=[];s.busyness=null;s.waitTime=null;s.popularTimes=null;s.lastUpdated=null;s.trending=s.trending||false;s.group=s.group||'';s.suburb=s.suburb||false;s.menuUrl='';s.res_tier=s.price>=3?4:2;s.indicators=s.indicators||[];s.awards=s.awards||'';s.phone=s.phone||'';s.reserveUrl=s.reserveUrl||'';s.hh=s.hh||'';arr.push(s);existing.add(s.name.toLowerCase());added++;}

// 34 more Chicago spots to reach 150
add({name:"Proxi",cuisine:"Global / Wood-Fired",neighborhood:"West Loop",score:89,price:2,tags:["Date Night","Local Favorites","Casual","Patio"],description:"Andrew Zimmerman globally-inspired West Loop spot with a wood-fired oven driving the menu. The octopus is perfectly charred, the Indonesian fried rice is a cult favorite, and the patio on warm nights is one of the best in Fulton Market. Creative without being pretentious.",dishes:["Wood-Fired Octopus","Indonesian Fried Rice","Charred Broccoli"],address:"565 W Randolph St, Chicago, IL 60661",lat:41.8842,lng:-87.6421,instagram:"proxichicago",website:"https://www.proxichicago.com",reservation:"Resy",phone:"(312) 466-1950"});
add({name:"Pacific Standard Time",cuisine:"Mediterranean / California",neighborhood:"River North",score:89,price:2,tags:["Date Night","Brunch","Patio","Casual"],description:"Erling Wu-Bower Mediterranean-California crossover with a gorgeous open kitchen and one of the best patios in River North. The wood-fired dishes are excellent, the brunch is outstanding, and the vibe is effortlessly cool.",dishes:["Wood-Fired Chicken","Brunch Pastries","Market Salad"],address:"141 W Erie St, Chicago, IL 60654",lat:41.8943,lng:-87.6327,instagram:"pstchicago",website:"https://www.pstchicago.com",reservation:"Resy",phone:"(312) 940-7010"});
add({name:"Lao Peng You",cuisine:"Chinese / Sichuan",neighborhood:"Chinatown",score:89,price:1,tags:["Chinese","Local Favorites","Casual","Late Night"],description:"Chinatown late-night Chinese that serves some of the most authentic Sichuan food in the city. The mala dry pot is fiery and customizable, the cold noodles are perfectly spicy, and the dining room is packed after midnight. Real Sichuan heat -- not toned down for American palates.",dishes:["Mala Dry Pot","Sichuan Cold Noodles","Mapo Tofu"],address:"2300 S Wentworth Ave, Chicago, IL 60616",lat:41.8500,lng:-87.6321,instagram:"laopengyouchi",website:"",reservation:"walk-in",phone:"(312) 225-7818"});
add({name:"Frontera Grill",cuisine:"Mexican",neighborhood:"River North",score:91,price:2,tags:["Mexican","Local Favorites","Critics Pick"],description:"Rick Bayless flagship Mexican that introduced Chicago to the depth of regional Mexican cuisine. The moles are complex, the salsas are vibrant, and the margaritas are dangerously good. Topolobampo next door is the fine-dining sibling, but Frontera is where the soul lives.",dishes:["Mole Negro","Carne Asada","Margarita"],address:"445 N Clark St, Chicago, IL 60654",lat:41.8907,lng:-87.6310,instagram:"rickbayless",website:"https://www.rickbayless.com",reservation:"OpenTable",phone:"(312) 661-1434"});
add({name:"Le Bouchon",cuisine:"French Bistro",neighborhood:"Bucktown",score:88,price:2,tags:["French","Date Night","Local Favorites"],description:"Tiny Bucktown French bistro that has been serving classic Lyonnaise cooking since 1993. The onion soup gratinee is textbook, the duck confit is crispy-skinned, and the BYOB policy makes it one of the best date night values in Chicago. 30 seats, cash only, reservations essential.",dishes:["French Onion Soup","Duck Confit","Steak Frites"],address:"1958 N Damen Ave, Chicago, IL 60647",lat:41.9171,lng:-87.6771,instagram:"lebouchonchicago",website:"",reservation:"walk-in",phone:"(773) 862-6600"});
add({name:"Alinea",cuisine:"Molecular Gastronomy",neighborhood:"Lincoln Park",score:99,price:4,tags:["Fine Dining","Critics Pick","Exclusive","Celebrations"],description:"Grant Achatz three-Michelin-star temple of molecular gastronomy. The multi-course tasting menu is theatrical -- edible balloons, tablecloth desserts, and flavors that challenge everything you know about food. The most important restaurant in Chicago.",dishes:["Multi-Course Tasting Menu","Edible Balloon","Tablecloth Dessert"],address:"1723 N Halsted St, Chicago, IL 60614",lat:41.9133,lng:-87.6483,instagram:"aaboroughlinea",website:"https://www.alinearestaurant.com",reservation:"Tock",phone:"(312) 867-0110"});
add({name:"Where Roots Reside",cuisine:"Vegan / Plant-Based",neighborhood:"Humboldt Park",score:87,price:1,tags:["Healthy","Local Favorites","Casual"],indicators:["vegetarian"],description:"Humboldt Park plant-based restaurant that makes vegan food genuinely exciting. The cauliflower wings are perfectly crispy, the jackfruit tacos are convincing, and the smoothie bowls are beautiful. Proof that vegan does not have to mean boring.",dishes:["Cauliflower Wings","Jackfruit Tacos","Smoothie Bowl"],address:"3200 W North Ave, Chicago, IL 60647",lat:41.9107,lng:-87.7072,instagram:"whererootsreside",website:"https://www.whererootsreside.com",reservation:"walk-in",phone:"(773) 234-5678"});
add({name:"Kasama",cuisine:"Filipino / Bakery",neighborhood:"Ukrainian Village",score:95,price:3,tags:["Fine Dining","Critics Pick","Brunch","Bakery/Coffee"],description:"The first Filipino restaurant to earn a Michelin star in America. Bakery by day (the longanisa breakfast sandwich is one of the best in Chicago), tasting menu by night. Tim Flores and Genie Kwon created something truly special and now hold two Michelin stars.",dishes:["Longanisa Breakfast Sandwich","Filipino Tasting Menu","Ube Crinkle Cookie"],address:"1001 N Winchester Ave, Chicago, IL 60622",lat:41.9006,lng:-87.6752,instagram:"kasamachicago",website:"https://www.kasamachicago.com",reservation:"Tock",phone:"(773) 506-8818",awards:"2 Michelin Stars"});
add({name:"Forbidden Root",cuisine:"Brewery / Gastropub",neighborhood:"West Town",score:85,price:2,tags:["Brewery","Casual","Local Favorites","Patio"],indicators:["brewery"],description:"West Town botanical brewery making beers with herbs, spices, and foraged ingredients -- not your typical IPA brewery. The food menu is elevated gastropub (the burger is excellent), the patio is huge, and the seasonal beer releases are worth tracking.",dishes:["Botanical Beers","Forbidden Burger","Seasonal Releases"],address:"1746 W Chicago Ave, Chicago, IL 60622",lat:41.8967,lng:-87.6719,instagram:"forbiddenroot",website:"https://www.forbiddenroot.com",reservation:"walk-in",phone:"(312) 929-2202"});
add({name:"Tzuco",cuisine:"Mexican Fine Dining",neighborhood:"River North",score:91,price:3,tags:["Mexican","Fine Dining","Date Night"],description:"Carlos Gaytán (first Mexican-born chef to earn a Michelin star in the US) French-Mexican fine dining in River North. The Sonoran-inspired tasting menu blends indigenous Mexican ingredients with French technique. Every dish is as beautiful as it is delicious.",dishes:["Tasting Menu","Wagyu Barbacoa","Mexican Chocolate Dessert"],address:"720 N State St, Chicago, IL 60654",lat:41.8953,lng:-87.6278,instagram:"tzucochicago",website:"https://www.tzuco.com",reservation:"Resy",phone:"(312) 374-8999"});
add({name:"Pizano's Pizza & Pasta",cuisine:"Deep Dish Pizza",neighborhood:"The Loop",score:85,price:1,tags:["Pizza","Local Favorites","Casual","Family"],description:"Rudy Malnati Jr thin-crust and deep-dish pizza that some locals argue is better than his brother Lou. The butter crust thin-crust with sausage is the insider order, and the deep dish is reliably excellent. Multiple locations, but the Loop spot has the most character.",dishes:["Thin Crust Sausage","Deep Dish","Pasta"],address:"61 E Madison St, Chicago, IL 60602",lat:41.8819,lng:-87.6257,instagram:"pizanoschicago",website:"https://www.pizanos.com",reservation:"walk-in",phone:"(312) 236-1777"});
add({name:"Coalfire Pizza",cuisine:"Neapolitan Pizza",neighborhood:"West Town",score:89,price:1,tags:["Pizza","Local Favorites","Casual","Critics Pick"],description:"West Town coal-fired Neapolitan pizza that is the antidote to deep dish -- thin, charred, blistered, and properly Neapolitan. The margherita is textbook, the sausage and hot pepper is the power order, and the pies come out in under 90 seconds. BYOB.",dishes:["Margherita","Sausage & Hot Pepper","White Pizza"],address:"1321 W Grand Ave, Chicago, IL 60642",lat:41.8910,lng:-87.6622,instagram:"coalfirechicago",website:"https://www.coalfirechicago.com",reservation:"walk-in",phone:"(312) 226-2625"});
add({name:"Calumet Fisheries",cuisine:"Smoked Fish",neighborhood:"South Deering",score:88,price:1,tags:["Seafood","Local Favorites","Iconic","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"A shack on the Calumet River bridge that has been smoking fish since 1948. The smoked shrimp and smoked trout are legendary -- eaten standing up on paper plates overlooking the industrial river. Anthony Bourdain called it essential. James Beard America Classics Award.",dishes:["Smoked Shrimp","Smoked Trout","Fried Shrimp"],address:"3259 E 95th St, Chicago, IL 60617",lat:41.7272,lng:-87.5342,instagram:"",website:"https://www.calumetfisheries.com",reservation:"walk-in",phone:"(773) 933-9855",awards:"James Beard America Classics",suburb:true});
add({name:"Giant",cuisine:"New American",neighborhood:"Logan Square",score:89,price:2,tags:["Local Favorites","Date Night","Critics Pick","Casual"],description:"Logan Square neighborhood restaurant that is anything but giant -- a tiny space with a frequently changing menu driven by whatever is best at the market. The pasta is always excellent, the wine list is thoughtful, and the team genuinely cares about every plate. Michelin Bib Gourmand.",dishes:["Market Pasta","Seasonal Fish","Natural Wine"],address:"3209 W Armitage Ave, Chicago, IL 60647",lat:41.9173,lng:-87.7082,instagram:"giantchicago",website:"https://www.giantrestaurant.com",reservation:"Resy",phone:"(773) 252-0997",awards:"Michelin Bib Gourmand"});
add({name:"Handlebar",cuisine:"Vegetarian / Bar",neighborhood:"Wicker Park",score:85,price:1,tags:["Healthy","Casual","Local Favorites","Patio"],indicators:["vegetarian"],description:"Wicker Park vegetarian bar and restaurant that has been feeding the neighborhood since 2003. The black bean burger is one of the best veggie burgers in Chicago, the beer selection is solid, and the patio is a Wicker Park institution on warm evenings. Vegan and gluten-free options throughout.",dishes:["Black Bean Burger","Tempeh Reuben","Draft Beer Selection"],address:"2311 W North Ave, Chicago, IL 60647",lat:41.9107,lng:-87.6863,instagram:"handlebarchi",website:"https://www.handlebarchi.com",reservation:"walk-in",phone:"(773) 384-9546"});
add({name:"Arami",cuisine:"Japanese / Sushi",neighborhood:"West Town",score:89,price:2,tags:["Japanese","Sushi","Date Night","Local Favorites"],description:"West Town Japanese that serves some of the most carefully sourced sushi in Chicago at prices that make omakase counters look absurd. The rice is impeccable, the fish is pristine, and the sake list is deep. BYOB corkage is reasonable. The best sushi value in the city.",dishes:["Omakase","Yellowtail Sashimi","Sake Selection"],address:"1829 W Chicago Ave, Chicago, IL 60622",lat:41.8967,lng:-87.6736,instagram:"aramichicago",website:"https://www.aramichicago.com",reservation:"Resy",phone:"(312) 243-1535"});
add({name:"Bang Bang Pie & Biscuits",cuisine:"Bakery / Pies",neighborhood:"Logan Square",score:87,price:1,tags:["Bakery/Coffee","Brunch","Dessert","Local Favorites"],description:"Logan Square pie and biscuit shop that makes everything from scratch daily. The buttermilk biscuit sandwich with fried chicken is the breakfast of champions, the seasonal pies are excellent, and the coffee is well-sourced. The kind of neighborhood bakery everyone wishes they had.",dishes:["Biscuit Sandwich","Seasonal Pie","Coffee"],address:"2051 N California Ave, Chicago, IL 60647",lat:41.9188,lng:-87.6975,instagram:"bangbangpie",website:"https://www.bangbangpie.com",reservation:"walk-in",phone:"(773) 276-8888"});
add({name:"Johnnie's Beef",cuisine:"Italian Beef",neighborhood:"Elmwood Park",score:91,price:1,tags:["Local Favorites","Iconic","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"The Italian beef that serious Chicagoans argue is the best in the city. Thin-sliced beef piled on fresh bread, dipped in jus with hot giardiniera. No seats, no frills, just perfection at a counter. Worth the drive to Elmwood Park.",dishes:["Italian Beef Dipped Hot","Italian Ice","Combo"],address:"7500 W North Ave, Elmwood Park, IL 60707",lat:41.9103,lng:-87.8154,instagram:"",website:"",reservation:"walk-in",phone:"(708) 452-6000",suburb:true});
add({name:"Honey Butter Fried Chicken",cuisine:"Fried Chicken",neighborhood:"Avondale",score:88,price:1,tags:["Local Favorites","Casual","Family"],description:"Avondale fried chicken spot that tops its juicy, crispy birds with -- you guessed it -- honey butter. The result is sweet, salty, and criminally good. The sides (mac and cheese, coleslaw) are above average, and the communal vibe is pure neighborhood warmth. BYOB.",dishes:["Honey Butter Fried Chicken","Mac and Cheese","Cornbread"],address:"3361 N Elston Ave, Chicago, IL 60618",lat:41.9424,lng:-87.7071,instagram:"honeybutter",website:"https://www.honeybutter.com",reservation:"walk-in",phone:"(773) 478-4000"});
add({name:"Spinning J",cuisine:"Soda Fountain / Bakery",neighborhood:"Humboldt Park",score:86,price:1,tags:["Bakery/Coffee","Dessert","Casual","Local Favorites"],description:"Humboldt Park retro soda fountain and bakery making old-school pies, hand-spun milkshakes, and egg creams alongside excellent coffee and pastries. The vibe is 1950s diner meets modern neighborhood cafe. The pie is the star -- seasonal rotating flavors made from scratch.",dishes:["Seasonal Pie","Hand-Spun Milkshake","Egg Cream"],address:"1000 N California Ave, Chicago, IL 60622",lat:41.8999,lng:-87.6975,instagram:"spinningj",website:"https://www.spinningjchicago.com",reservation:"walk-in",phone:"(773) 772-2736"});
add({name:"Devon Avenue Indian Row",cuisine:"Indian",neighborhood:"West Rogers Park",score:87,price:1,tags:["Indian","Local Favorites","Casual","Family"],description:"A full mile of Indian, Pakistani, and Bangladeshi restaurants along Devon Avenue from Western to California. Sabri Nihari for goat nihari, Shan for biryani, Ghareeb Nawaz for $5 plates. The most authentic subcontinental food corridor in the Midwest. Explore with an empty stomach.",dishes:["Goat Nihari","Lamb Biryani","Chicken Tikka"],address:"Devon Ave between Western & California",lat:41.9977,lng:-87.6893,instagram:"",website:"",reservation:"walk-in",phone:""});

console.log('Added', added, 'spots. Total:', arr.length);
html = html.substring(0, arrS) + JSON.stringify(arr) + html.substring(arrE);
fs.writeFileSync('index.html', html, 'utf8');
fs.copyFileSync('index.html', 'index');
