const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');

// Find Chicago in CITY_DATA
const chiMarker = "'Chicago':";
const chiIdx = html.indexOf(chiMarker);
if(chiIdx === -1){ console.error('Chicago not found in CITY_DATA'); process.exit(1); }
const arrS = html.indexOf('[', chiIdx);
let d=0, arrE=arrS;
for(let j=arrS;j<html.length;j++){if(html[j]==='[')d++;if(html[j]===']'){d--;if(d===0){arrE=j+1;break;}}}
let arr = JSON.parse(html.substring(arrS, arrE));
console.log('Existing Chicago spots:', arr.length);
const maxId = Math.max(...arr.map(r=>r.id));
let nextId = maxId + 1;
const existing = new Set(arr.map(r=>r.name.toLowerCase()));

function add(spot){
  if(existing.has(spot.name.toLowerCase())) return;
  spot.id = nextId++;
  spot.bestOf=spot.bestOf||[];spot.busyness=null;spot.waitTime=null;spot.popularTimes=null;spot.lastUpdated=null;spot.trending=spot.trending||false;spot.group=spot.group||'';spot.suburb=spot.suburb||false;spot.menuUrl='';spot.res_tier=spot.price>=3?4:2;spot.indicators=spot.indicators||[];spot.awards=spot.awards||'';spot.phone=spot.phone||'';spot.reserveUrl=spot.reserveUrl||'';spot.hh=spot.hh||'';
  arr.push(spot);
  existing.add(spot.name.toLowerCase());
}

// STEP 2: UPSCALE CASUAL & DATE NIGHT
add({name:"RPM Italian",cuisine:"Italian",neighborhood:"River North",score:91,price:3,tags:["Italian","Date Night","Celebrations"],description:"Bill and Giuliana Rancic glossy River North Italian with handmade pasta that rivals anything in the West Loop. The cacio e pepe is tableside, the veal chop is massive, and the scene on a Saturday night is peak Chicago. Power dining meets pasta perfection.",dishes:["Cacio e Pepe (Tableside)","Veal Chop","Burrata"],address:"52 W Illinois St, Chicago, IL 60654",lat:41.8910,lng:-87.6318,instagram:"rpmitalian",website:"https://www.rpmrestaurants.com/rpm-italian",reservation:"OpenTable"});
add({name:"Maple & Ash",cuisine:"Steakhouse / New American",neighborhood:"Gold Coast",score:92,price:3,tags:["Steakhouse","Date Night","Brunch","Celebrations"],description:"Danny Grant wood-fired Gold Coast stunner where the whole branzino and massive steaks are cooked over open flames. The brunch is legendary -- a Choose Your Own Adventure prix fixe that is pure Chicago excess. The most fun steakhouse in the city.",dishes:["Whole Branzino","Prime Bone-In Ribeye","Brunch Prix Fixe"],address:"8 W Maple St, Chicago, IL 60610",lat:41.9009,lng:-87.6284,instagram:"mapleandash",website:"https://www.mapleandash.com",reservation:"OpenTable"});
add({name:"Boka",cuisine:"New American",neighborhood:"Lincoln Park",score:91,price:3,tags:["Fine Dining","Date Night","Critics Pick"],description:"The Boka Restaurant Group flagship that launched an empire. Lee Wolen seasonal New American menu is refined without being stuffy, and the Lincoln Park brownstone setting is one of the most romantic in Chicago. A stalwart that keeps evolving.",dishes:["Duck Breast","Seasonal Tasting","Handmade Pasta"],address:"1729 N Halsted St, Chicago, IL 60614",lat:41.9128,lng:-87.6483,instagram:"bokarestaurant",website:"https://www.bokachicago.com",reservation:"OpenTable"});
add({name:"Elske",cuisine:"Scandinavian / New American",neighborhood:"West Loop",score:93,price:3,tags:["Fine Dining","Date Night","Critics Pick"],description:"David and Anna Posey Scandinavian-inspired West Loop gem with a tasting menu option and an a la carte bar menu. The flavors are clean, precise, and deeply seasonal. The kringle pastries at dessert are a signature. One of the most underrated restaurants in Chicago.",dishes:["Seasonal Tasting Menu","Kringle Pastries","Lamb"],address:"1350 W Randolph St, Chicago, IL 60607",lat:41.8841,lng:-87.6620,instagram:"elskerestaurant",website:"https://www.elskerestaurant.com",reservation:"Tock"});
add({name:"Pacific Standard Time",cuisine:"Mediterranean / California",neighborhood:"River North",score:89,price:2,tags:["Date Night","Brunch","Patio","Casual"],description:"Erling Wu-Bower Mediterranean-California crossover in River North with a gorgeous open kitchen and one of the best patios in the neighborhood. The wood-fired dishes are excellent, the brunch is outstanding, and the vibe is effortlessly cool. PST makes River North feel like Venice Beach.",dishes:["Wood-Fired Chicken","Brunch Pastries","Market Salad"],address:"141 W Erie St, Chicago, IL 60654",lat:41.8943,lng:-87.6327,instagram:"pstchicago",website:"https://www.pstchicago.com",reservation:"Resy"});

// STEP 3: NEIGHBORHOOD FAVORITES
add({name:"Dove's Luncheonette",cuisine:"Tex-Mex Diner",neighborhood:"Wicker Park",score:89,price:1,tags:["Brunch","Local Favorites","Casual"],description:"A Wicker Park counter-service diner serving elevated Tex-Mex with a killer vinyl soundtrack. The migas are perfect, the chorizo gravy biscuits are a revelation, and the mezcal list is shockingly deep for a diner. Sunday brunch here is a neighborhood institution.",dishes:["Migas","Chorizo Gravy Biscuits","Mezcal Selection"],address:"1545 N Damen Ave, Chicago, IL 60622",lat:41.9096,lng:-87.6771,instagram:"dovesluncheonette",website:"https://www.doveschicago.com",reservation:"walk-in"});
add({name:"Mi Tocaya Antojeria",cuisine:"Mexican",neighborhood:"Logan Square",score:91,price:2,tags:["Mexican","Date Night","Local Favorites","Critics Pick"],description:"Diana Davila creative Mexican that earned universal praise and a Michelin Bib Gourmand. The esquites with bone marrow are unforgettable, the mole is complex, and the cocktail program is excellent. One of the most exciting Mexican restaurants outside of Mexico City.",dishes:["Esquites with Bone Marrow","Mole","Cochinita Pibil"],address:"2800 N Logan Blvd, Chicago, IL 60647",lat:41.9319,lng:-87.7066,instagram:"mitocaya",website:"https://www.mitocaya.com",reservation:"Resy"});
add({name:"Longman & Eagle",cuisine:"New American / Whiskey Bar",neighborhood:"Logan Square",score:89,price:2,tags:["Local Favorites","Cocktails","Casual","Late Night"],description:"Logan Square gastropub and whiskey bar with rooms upstairs that make it the coolest place to sleep in the neighborhood. The wild boar sloppy joe is a cult classic, the whiskey list is encyclopedic, and the late-night scene at the bar is pure Logan Square energy.",dishes:["Wild Boar Sloppy Joe","Bone Marrow","Whiskey Flight"],address:"2657 N Kedzie Ave, Chicago, IL 60647",lat:41.9296,lng:-87.7080,instagram:"longmanandeagle",website:"https://www.longmanandeagle.com",reservation:"walk-in"});
add({name:"Mott St",cuisine:"Asian Fusion",neighborhood:"Wicker Park",score:88,price:2,tags:["Date Night","Local Favorites","Late Night","Casual"],description:"Edward Kim Asian-inspired small plates in a dark, moody Wicker Park space that feels like a late-night secret. The whole fried chicken is legendary -- crispy, juicy, and served with gochujang sauce. The cocktails are inventive and the energy is electric after 10 PM.",dishes:["Whole Fried Chicken","Pork Belly Ssam","Late Night Menu"],address:"1401 N Ashland Ave, Chicago, IL 60622",lat:41.9072,lng:-87.6690,instagram:"mottstchicago",website:"https://www.mottstreetchicago.com",reservation:"walk-in"});
add({name:"MingHin Cuisine",cuisine:"Chinese / Dim Sum",neighborhood:"Chinatown",score:90,price:2,tags:["Chinese","Local Favorites","Family","Brunch"],description:"The dim sum destination in Chicago Chinatown with carts rolling through a massive dining room on weekend mornings. The har gow and siu mai are textbook, the turnip cake is crispy perfection, and the Peking duck is excellent. Go before 11 AM or prepare for a serious wait.",dishes:["Dim Sum Carts","Har Gow","Peking Duck"],address:"2168 S Archer Ave, Chicago, IL 60616",lat:41.8535,lng:-87.6326,instagram:"minghin",website:"https://www.minghincuisine.com",reservation:"walk-in"});
add({name:"Lao Sze Chuan",cuisine:"Sichuan Chinese",neighborhood:"Chinatown",score:88,price:2,tags:["Chinese","Local Favorites","Casual"],description:"Tony Hu Sichuan empire flagship in Chinatown where the dry chili chicken is so famous Obama ordered it. The ma po tofu has proper mala numbing heat, and the menu is 200+ items deep. Not every dish is a winner, but the highs are extraordinary. Ask for the Chinese menu.",dishes:["Dry Chili Chicken","Ma Po Tofu","Dan Dan Noodles"],address:"2172 S Archer Ave, Chicago, IL 60616",lat:41.8534,lng:-87.6328,instagram:"laoszechuan",website:"https://www.laoszechuanchicago.com",reservation:"walk-in"});
add({name:"Piece Brewery & Pizzeria",cuisine:"Pizza / Brewery",neighborhood:"Wicker Park",score:87,price:1,tags:["Pizza","Local Favorites","Casual","Patio"],description:"New Haven-style pizza in Chicago -- thin, charred, white clam pie and all. The in-house brewery makes award-winning beers to go with the pies, and the massive Wicker Park space with outdoor patio is perfect for groups. The plain tomato pie is the purist order.",dishes:["White Clam Pie","Plain Tomato Pie","Craft Beer"],address:"1927 W North Ave, Chicago, IL 60622",lat:41.9107,lng:-87.6778,instagram:"piecechicago",website:"https://www.piecechicago.com",reservation:"walk-in"});

// STEP 4: CHEAP EATS
add({name:"Jim's Original",cuisine:"Chicago Hot Dogs / Polish",neighborhood:"Maxwell Street",score:86,price:1,tags:["Local Favorites","Casual","Iconic","Hole in the Wall","Late Night"],indicators:["hole-in-the-wall"],description:"The original Maxwell Street Polish sausage stand that has been grilling on the South Side since 1939. The Polish with grilled onions and sport peppers is a Chicago institution. Open until 4 AM on weekends. Cash only. Pure Chicago.",dishes:["Maxwell Street Polish","Chicago Dog","Pork Chop Sandwich"],address:"1250 S Union Ave, Chicago, IL 60607",lat:41.8651,lng:-87.6533,instagram:"",website:"https://www.jimsoriginal.com",reservation:"walk-in"});
add({name:"Johnnie's Beef",cuisine:"Italian Beef",neighborhood:"Elmwood Park",score:91,price:1,tags:["Local Favorites","Iconic","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"The Italian beef that serious Chicagoans argue is the best in the city -- and it might be right. Thin-sliced beef piled on fresh Italian bread, dipped in jus with hot giardiniera. No seats, no frills, just perfection at a counter. Worth the drive to Elmwood Park.",dishes:["Italian Beef Dipped Hot","Italian Ice","Combo"],address:"7500 W North Ave, Elmwood Park, IL 60707",lat:41.9103,lng:-87.8154,instagram:"",website:"",reservation:"walk-in",suburb:true});
add({name:"Birrieria Zaragoza",cuisine:"Mexican / Birria",neighborhood:"Archer Heights",score:92,price:1,tags:["Mexican","Local Favorites","Critics Pick","Hole in the Wall"],indicators:["hole-in-the-wall"],description:"The best birria in Chicago -- slow-braised goat served in a tiny South Side storefront that Michelin inspectors discovered and the rest of the city followed. The consomme is deeply flavored, the tortillas are handmade, and the horchata is cooling perfection. Cash only. A pilgrimage.",dishes:["Birria de Chivo (Goat)","Consomme","Handmade Tortillas"],address:"4852 S Pulaski Rd, Chicago, IL 60632",lat:41.8047,lng:-87.7221,instagram:"birrieriazaragoza",website:"",reservation:"walk-in",awards:"Michelin Bib Gourmand"});
add({name:"Ricobene's",cuisine:"Breaded Steak Sandwich",neighborhood:"Bridgeport",score:87,price:1,tags:["Local Favorites","Casual","Iconic"],description:"The breaded steak sandwich that Chicago swears by -- a massive, hand-pounded, breaded and fried steak cutlet on Italian bread with marinara and mozzarella. This is not health food. This is not fine dining. This is Chicago at its most gloriously excessive.",dishes:["Breaded Steak Sandwich","Italian Beef","Pizza Puffs"],address:"252 W 26th St, Chicago, IL 60616",lat:41.8462,lng:-87.6340,instagram:"ricobenes",website:"https://www.ricobenes.com",reservation:"walk-in"});

// STEP 5: BARS & COCKTAILS
add({name:"The Aviary",cuisine:"Molecular Cocktails",neighborhood:"West Loop",score:95,price:3,tags:["Cocktails","Exclusive","Date Night","Fine Dining"],description:"Grant Achatz cocktail bar where drinks are served in custom vessels, some requiring tools to consume. The ice program alone is worth a PhD. This is the Alinea of cocktails -- inventive, theatrical, and unlike anything you have experienced. The Office speakeasy below is even more exclusive.",dishes:["Seasonal Cocktail Menu","The Office (Speakeasy)","Bar Snacks"],address:"955 W Fulton Market, Chicago, IL 60607",lat:41.8867,lng:-87.6519,instagram:"theaviarychicago",website:"https://www.theaviary.com",reservation:"Tock"});
add({name:"Lost Lake",cuisine:"Tiki Bar",neighborhood:"Logan Square",score:89,price:2,tags:["Cocktails","Late Night","Local Favorites"],description:"Paul McGee tiki bar that put Chicago on the national cocktail map with drinks that are both technically brilliant and genuinely fun. The tropical decor is maximal, the rum list is extensive, and the Zombie will absolutely live up to its name. The best tiki bar in the Midwest.",dishes:["Zombie","Navy Grog","Seasonal Tiki"],address:"3154 W Diversey Ave, Chicago, IL 60647",lat:41.9316,lng:-87.7082,instagram:"lostlakechicago",website:"https://www.lostlaketiki.com",reservation:"walk-in"});
add({name:"Cindy's Rooftop",cuisine:"Rooftop Bar",neighborhood:"The Loop",score:88,price:2,tags:["Rooftop","Cocktails","Date Night","Patio"],indicators:["outdoor-seating"],description:"The rooftop bar atop the Chicago Athletic Association hotel with jaw-dropping views of Millennium Park, The Bean, and Lake Michigan. The cocktails are well-crafted, the terrace is gorgeous, and the view at sunset is one of the best in the city. Get there early -- it fills fast.",dishes:["Craft Cocktails","Sunset Views","Bar Snacks"],address:"12 S Michigan Ave, Chicago, IL 60603",lat:41.8821,lng:-87.6247,instagram:"cindysrooftop",website:"https://www.cindysrooftop.com",reservation:"walk-in"});
add({name:"Three Dots and a Dash",cuisine:"Tiki / Speakeasy",neighborhood:"River North",score:88,price:2,tags:["Cocktails","Late Night","Exclusive"],description:"Hidden below a River North alley, this tiki speakeasy serves tropical drinks in an underground bamboo-and-neon paradise. The presentation is Instagram-ready, the drinks are genuinely good, and the treasure chest cocktail for groups is a showstopper. Find the unmarked door.",dishes:["Treasure Chest (Group)","Jet Pilot","Painkiller"],address:"435 N Clark St, Chicago, IL 60654",lat:41.8907,lng:-87.6310,instagram:"threedotsandadash",website:"https://www.threedotschicago.com",reservation:"Resy"});
add({name:"London House Rooftop",cuisine:"Rooftop Bar",neighborhood:"River North",score:87,price:2,tags:["Rooftop","Cocktails","Date Night","Patio"],indicators:["outdoor-seating"],description:"Three-tiered rooftop at the LondonHouse hotel with the most dramatic view in Chicago -- directly overlooking the Chicago River, Michigan Avenue bridge, and the Mag Mile. The cocktails are decent, but you are here for the view. Sunset on the terrace is non-negotiable.",dishes:["Signature Cocktails","Sunset Views","Bar Bites"],address:"85 E Wacker Dr, Chicago, IL 60601",lat:41.8875,lng:-87.6248,instagram:"londonhousechicago",website:"https://www.londonhousechicago.com",reservation:"walk-in"});

// STEP 6: COFFEE & DESSERT
add({name:"Metric Coffee Co.",cuisine:"Coffee",neighborhood:"West Loop",score:86,price:1,tags:["Bakery/Coffee","Casual","Local Favorites"],description:"West Loop coffee roaster with a massive industrial space and some of the best single-origin pour-overs in the city. The baristas know their craft, the pastries are fresh, and the warehouse setting makes you feel like you are discovering something. A perfect Fulton Market morning.",dishes:["Single Origin Pour Over","Espresso","Pastries"],address:"2021 W Fulton St, Chicago, IL 60612",lat:41.8866,lng:-87.6772,instagram:"metriccoffee",website:"https://www.metriccoffee.com",reservation:"walk-in"});
add({name:"Hoosier Mama Pie Company",cuisine:"Bakery / Pie",neighborhood:"Wicker Park",score:89,price:1,tags:["Bakery/Coffee","Dessert","Local Favorites"],description:"The best pie shop in Chicago and one of the best in America. Every pie is made from scratch with seasonal fillings -- the sugar cream pie is the signature, the sour cherry is transcendent, and the savory chicken pot pie is comfort food perfection. Slices available daily.",dishes:["Sugar Cream Pie","Sour Cherry Pie","Chicken Pot Pie"],address:"1618 1/2 W Chicago Ave, Chicago, IL 60622",lat:41.8965,lng:-87.6691,instagram:"hoosiermamapie",website:"https://www.hoosiermamapie.com",reservation:"walk-in"});
add({name:"Black Dog Gelato",cuisine:"Gelato / Dessert",neighborhood:"Ukrainian Village",score:88,price:1,tags:["Dessert","Local Favorites","Casual"],description:"Tiny Ukrainian Village gelato shop with inventive flavors that push boundaries -- goat cheese cashew caramel, Thai iced tea, and a rotating lineup that makes every visit different. The texture is impeccable and the portions are generous. The best gelato in Chicago.",dishes:["Goat Cheese Cashew Caramel","Chocolate","Seasonal Flavors"],address:"859 N Damen Ave, Chicago, IL 60622",lat:41.8981,lng:-87.6771,instagram:"blackdoggelato",website:"https://www.blackdoggelato.com",reservation:"walk-in"});

// STEP 7: ENTERTAINMENT
add({name:"Kingston Mines",cuisine:"Blues Club",neighborhood:"Lincoln Park",score:87,price:1,tags:["Live Music","Late Night","Local Favorites","Casual"],description:"Two stages of live blues every single night in Lincoln Park -- when one band takes a break, the other starts. It has been going since 1968 and the energy at midnight is pure electric Chicago blues. The kind of venue that reminds you why Chicago is the blues capital of the world.",dishes:["Live Blues","Craft Beer","Late Night Sets"],address:"2548 N Halsted St, Chicago, IL 60614",lat:41.9290,lng:-87.6487,instagram:"kingstonmines",website:"https://www.kingstonmines.com",reservation:"walk-in"});
add({name:"Second City",cuisine:"Comedy Club",neighborhood:"Old Town",score:91,price:2,tags:["Entertainment","Local Favorites","Iconic","Date Night"],description:"The comedy institution that launched Tina Fey, Steve Carell, Bill Murray, and basically every funny person in America. The mainstage shows are excellent, but the free improv sets after the main show are where the magic happens. A Chicago bucket list essential.",dishes:["Mainstage Show","Free Improv After Show","Craft Cocktails"],address:"1616 N Wells St, Chicago, IL 60614",lat:41.9112,lng:-87.6346,instagram:"secondcity",website:"https://www.secondcity.com",reservation:"Tock"});
add({name:"Green Mill Cocktail Lounge",cuisine:"Jazz Club",neighborhood:"Uptown",score:90,price:1,tags:["Jazz Club","Live Music","Late Night","Historic","Cocktails"],description:"Al Capone old hangout that has been serving jazz and cocktails since 1907. The Sunday night poetry slam is legendary, the live jazz is nightly, and the Art Deco interior is a time capsule. The most atmospheric bar in Chicago. Arrive early for a booth.",dishes:["Live Jazz Nightly","Classic Cocktails","Sunday Poetry Slam"],address:"4802 N Broadway, Chicago, IL 60640",lat:41.9718,lng:-87.6604,instagram:"greenmilljazz",website:"https://www.greenmilljazz.com",reservation:"walk-in"});
add({name:"Thalia Hall",cuisine:"Live Music Venue",neighborhood:"Pilsen",score:89,price:2,tags:["Live Music","Entertainment","Local Favorites"],description:"A gorgeous 1892 Pilsen theater turned indie music venue with a restaurant (Dusek) and bar (Punch House) in the same building. The 800-capacity hall has perfect sound and an ornate ceiling that makes every show feel special. The best mid-size music venue in Chicago.",dishes:["Concert Tickets","Dusek Restaurant","Punch House Bar"],address:"1807 S Allport St, Chicago, IL 60608",lat:41.8577,lng:-87.6576,instagram:"thaliahallchicago",website:"https://www.thaliahallchicago.com",reservation:"walk-in"});

console.log('Added', arr.length - 34, 'new Chicago spots. Total:', arr.length);

html = html.substring(0, arrS) + JSON.stringify(arr) + html.substring(arrE);
fs.writeFileSync('index.html', html, 'utf8');
fs.copyFileSync('index.html', 'index');
console.log('Done!');
