// Expand NYC restaurant descriptions — spicy, specific, opinionated
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");

const re = /const NYC_DATA\s*=\s*(\[[\s\S]*?\]);/;
const match = html.match(re);
const data = eval(match[1]);

const expansions = {
  "Le Bernardin": "Eric Ripert's temple to seafood has held three Michelin stars for over two decades — the longest streak in New York — because every piece of fish is treated with a reverence bordering on religious. The barely-cooked tuna with foie gras and the black bass ceviche are dishes that have been imitated worldwide but never matched. The dining room is power-lunch formal at noon and romantically lit at night, attracting everyone from Wall Street titans to food pilgrims from Tokyo. If you eat seafood anywhere in America, this should be the place.",
  "Eleven Madison Park": "Daniel Humm's plant-based reinvention of one of the world's most famous restaurants was controversial, but the cooking remains at a level few chefs on earth can match — three Michelin stars and a former #1 World's Best ranking. The multi-course tasting menu transforms vegetables, grains, and fruits into dishes of astonishing complexity and beauty in a soaring Art Deco dining room overlooking Madison Square Park. The sunflower butter course has become iconic, and the service — warm, choreographed, never stuffy — sets the standard for American fine dining. Love it or debate it, EMP remains essential.",
  "Carbone": "Major Food Group's red-sauce Italian blockbuster is the restaurant that launched a thousand imitations — and none of them come close to the original's swagger. Tuxedoed captains serve tableside Caesar salads and veal parmesan the size of a baseball mitt in a space dripping with 1950s Rat Pack energy. The spicy rigatoni vodka is the most famous pasta dish in New York, and the reservation is accordingly one of the hardest to get — Resy drops go in seconds. Dress up, bring your appetite, and don't skip the cheesecake.",
  "Via Carota": "Jody Williams and Rita Sodi's West Village Italian is the restaurant every New Yorker wishes was on their block — a place where the carciofi (fried artichokes) are so perfect they've spawned an actual cult following. No reservations, just a wait that's become a social ritual on Grove Street, where the line itself is part of the experience. The menu is deceptively simple — roasted chicken, handmade pasta, seasonal vegetables — but every dish hits with a precision that earned the 2023 James Beard Outstanding Restaurant award. The candlelit room with its mismatched chairs and Italian wine list is the platonic ideal of a neighborhood restaurant.",
  "Lilia": "Missy Robbins turned a Williamsburg auto body shop into the most sought-after pasta restaurant in Brooklyn, and possibly all of New York. The mafaldini with pink peppercorn and the sheep's milk cheese agnolotti are transcendent — pasta so good it makes you reconsider whether you've ever actually had great pasta before. There are no reservations for the bar, which means showing up at 5 PM sharp is a viable strategy and a minor competitive sport. James Beard Best Chef and a Michelin star confirm what the nightly crowds already knew.",
  "Don Angie": "Angie Rito and Scott Tacinelli's West Village Italian-American restaurant serves food that's simultaneously nostalgic and wildly creative — their signature pinwheel lasagna is a visual stunner that actually delivers on flavor. The Michelin-starred menu riffs on Italian-American classics with a winking, maximalist energy: mozzarella en carozza, chile-crisp fried chicken, and a bread basket that people literally photograph. The tiny corner space on Greenwich Avenue buzzes with an energy that feels like the best house party you've ever attended. Don't sleep on the desserts — the coconut cake is absurd.",
  "Crown Shy": "Chef James Kent built one of the most important restaurants of the last decade in a stunning Art Deco space at the base of 70 Pine Street in FiDi. The Michelin-starred menu is technically New American but draws confidently from global traditions — the tandoori-spiced duck breast and the uni toast are signature moves that have been endlessly imitated. The cocktail program is one of the best in the city, and the late-night bar scene draws an industry crowd that knows great food when they taste it. Crown Shy proved that downtown Manhattan could support world-class dining outside of Tribeca.",
  "Cosme": "Enrique Olvera brought the intellectual rigor of Mexico City's fine dining scene to the Flatiron District, and the result is one of the most important Mexican restaurants ever opened outside of Mexico. The duck carnitas and the corn husk meringue dessert are dishes that redefined what Mexican food could be in New York — technically brilliant, deeply rooted in tradition, and absolutely delicious. A Michelin star and World's 50 Best recognition are deserved, but the real magic is in how Cosme makes elevated food feel completely approachable. The mezcal program alone is worth the visit.",
  "Peter Luger Steak House": "The most famous steakhouse in America has been serving porterhouse for two on Driggs Avenue since 1887 — and despite what one controversial New York Times review said, the steak is still magnificent. The USDA Prime beef is dry-aged in-house and broiled under extreme heat, arriving at your table sizzling in its own juices on a tilted platter. Cash only, the waiters are legendarily gruff, and the German beer hall decor hasn't changed in decades — that's all part of the charm. The thick-cut bacon appetizer and the creamed spinach are non-negotiable sides.",
  "Tatiana by Kwame Onwuachi": "Kwame Onwuachi's Lincoln Center restaurant is one of the most important openings in recent New York history — a Michelin-starred celebration of Afro-Caribbean and American cuisine that draws on his Bronx upbringing and Nigerian, Jamaican, and Trinidadian heritage. The jerk-spiced lamb and the egusi soup are dishes that expand the vocabulary of fine dining in America, served in a glamorous room overlooking the Lincoln Center fountain. Onwuachi's 2024 James Beard Best Chef win was one of the most popular in the award's history. This is the restaurant New York needed.",
  "Atomix": "Junghyun and Ellia Park's two-Michelin-starred Korean tasting menu in a minimalist NoMad townhouse is one of the most extraordinary dining experiences in America. Each course arrives with a card explaining its Korean cultural context — the food is intellectual but never cold, technical but deeply soulful. The menu changes completely with the seasons, but the precision of the cooking and the elegance of the presentations remain constant. At around $400 per person it's a splurge, but this is cooking at the absolute highest level.",
  "Le Coucou": "Daniel Rose's SoHo French restaurant brought classic haute cuisine back to New York with a swagger that felt both timeless and modern. The Michelin-starred menu reads like a greatest hits of French cooking — sole meunière, chicken for two, duck à l'orange — but every dish is executed with a lightness and precision that makes these warhorses feel new again. The soaring Lafayette Street dining room with its Belle Époque chandeliers is one of the most beautiful rooms in the city. James Beard Best New Restaurant confirmed what the packed dining room made obvious.",
  "Sushi Nakazawa": "Daisuke Nakazawa — who appeared in the documentary Jiro Dreams of Sushi as the apprentice who spent 200 attempts perfecting his tamago — runs one of the most revered omakase counters in New York. The 20-course omakase at the intimate West Village counter is a masterclass in Edomae technique, with fish sourced from Tokyo's Tsukiji market and local waters. Every piece of nigiri is served at the precise temperature and seasoning that brings out the fish's best qualities. The Michelin star barely captures how special this experience is.",
  "I Sodi": "Rita Sodi's tiny West Village Tuscan restaurant serves the kind of food that makes you want to move to Florence — rustic, ingredient-driven, and executed with a quiet perfection. The pappardelle with wild boar ragù and the butter-roasted chicken are signature dishes that have remained unchanged for years because they don't need to change. Getting a reservation is a genuine challenge, but walk-ins at the bar are possible if you're lucky and patient. Michelin-recognized and James Beard-nominated, I Sodi proves that simplicity done perfectly is the highest form of cooking.",
  "4 Charles Prime Rib": "Brendan Sodikoff's subterranean West Village steakhouse channels old New York with its velvet booths, candlelight, and a salt-crusted prime rib that's become one of the most talked-about dishes in the city. The menu is deliberately retro — shrimp cocktail, wedge salad, creamed spinach — but the execution is flawless, and the moody, romantic atmosphere makes every dinner feel like a scene from a movie. The bar serves one of the best martinis downtown, and the late-night crowd gives the place an electric energy. Book through Resy and dress the part.",
  "Gramercy Tavern": "Danny Meyer's Gramercy Tavern has been the gold standard of upscale American dining since 1994 — a Michelin-starred, James Beard Outstanding Restaurant that never feels pretentious. Chef Michael Anthony's seasonal menu celebrates farmers market ingredients with a sophistication that makes simple food taste extraordinary, from the roasted chicken to the chocolate bread pudding. The tavern room (no reservations) is one of the great walk-in dining experiences in New York, with a gorgeous bar and a crackling fireplace in winter. Three decades in, this is still one of the most reliable great meals in Manhattan.",
  "Dhamaka": "Chintan Pandya's Essex Market Indian restaurant exploded onto the New York scene by serving the bold, regional dishes that most Indian restaurants won't touch — goat brain, smoked rabbit, and a whole baby goat leg that feeds four. The Michelin-recognized menu draws from across India's vast culinary traditions, with a focus on the kind of ancestral cooking that's disappearing even in India. The raan — a slow-roasted whole leg of baby goat — requires 24-hour notice and is one of the most dramatic dishes in New York. This is not your local curry house, and that's exactly the point.",
  "Olmsted": "Chef Greg Baxter transforms his intimate Prospect Heights backyard garden into one of Brooklyn's most creative dining experiences, earning a Michelin star for cooking that blurs the line between restaurant and urban farm. The garden provides herbs and vegetables that appear on plates the same day they're harvested, and the menu changes almost daily based on what's growing. Signature dishes like the carrot crepe have become iconic, proving that vegetable-forward cooking can be thrilling. James Beard Best Chef nominee and one of the most important voices in sustainable dining.",
  "Balthazar": "Keith McNally's SoHo brasserie has been the center of New York's social universe since 1997 — a place where models, writers, actors, and civilians share the same burgundy banquettes over steak frites and raw shellfish towers. The bread basket alone — from the in-house Balthazar Bakery — is better than most restaurant's entire menus, and the breakfast is arguably the best in Manhattan. The zinc bar, the mirror-lined walls, and the controlled chaos of a packed Saturday night are peak New York energy. Some restaurants are trendy; Balthazar is eternal.",
  "Russ & Daughters": "The most famous appetizing store in America has been slicing smoked salmon and hand-rolling herring on Houston Street since 1914 — four generations of the Russ family serving the platonic ideal of New York Jewish food. The classic board — nova, sturgeon, whitefish salad, cream cheese, and bagels — is a religious experience for anyone who cares about food, and the chopped liver and borscht are equally essential. The Café on Orchard Street offers a sit-down experience with the same products. James Beard America's Classics recognition is richly deserved for a place that defines New York as much as the skyline.",
  "Katz's Delicatessen": "The most famous deli in the world has been serving pastrami on rye from the same Ludlow Street counter since 1888 — and the pastrami is still hand-carved, still piled impossibly high, and still worth every penny of the $28 sandwich. The cafeteria-style ordering system is chaotic and wonderful: grab a ticket at the door, order from the cutter, tip him a dollar, and don't lose your ticket. The matzo ball soup, the hot dogs, and the Reuben are all excellent, but the pastrami is why you're here. When Harry Met Sally was filmed here; the table has a sign.",
  "Dante": "This century-old Greenwich Village café was reborn as the World's Best Bar (#1 in 2019) under Linden Pride and Nathalie Hudson, serving cocktails that are as beautiful as they are balanced. The Negroni menu alone runs 20+ variations — from classic to white to barrel-aged — and the aperitivo-style food (burrata, crudo, small plates) is far better than bar food has any right to be. The sidewalk café on MacDougal Street is one of the great people-watching spots in the Village, especially on a warm evening. James Beard-nominated and still the best place for a drink in downtown Manhattan.",
  "Lucali": "Mark Iacono's Carroll Gardens pizzeria is consistently called the best pizza in New York — and in a city with 30,000 pizza joints, that's not a claim made lightly. The thin, blistered crust is made from a closely guarded dough recipe, topped simply with fresh mozzarella and basil, and slid into a coal-fired oven that Iacono built himself. Cash only, no reservations, and the wait can stretch past two hours — but the pizza, plus the calzone stuffed with ricotta and chocolate, make it worth every minute. Jay-Z is a regular, which tells you everything.",
  "Gage & Tollner": "This 1879 Downtown Brooklyn landmark was resurrected in 2021 with its original gas-lit chandeliers and mahogany bar intact, serving updated American classics that honor the restaurant's 145-year history. The Michelin-recognized menu features oysters Rockefeller, baked Alaska, and a bone-in ribeye that rival any steakhouse in the city, all served under the warm glow of 100+ original gaslights. Chef Sana Javeri Kadri brings a modern sensibility to the old-school menu without losing the soul of what made Gage & Tollner a Brooklyn institution. James Beard-nominated and hauntingly beautiful.",
  "Di An Di": "This Greenpoint Vietnamese restaurant from Dennis Ngo serves refined, deeply personal Vietnamese cuisine in one of Brooklyn's most beautiful dining rooms — all white tiles, natural light, and hanging plants. The pho is rich and nuanced, the summer rolls are pristine, and the Vietnamese coffee soft serve has become a neighborhood obsession. It's the rare restaurant that manages to feel both hip and soulful, modern and traditional, casual and carefully considered. Michelin-recognized and Eater Essential — one of the best Vietnamese restaurants in the five boroughs.",
  "The Red Rooster": "Marcus Samuelsson's Harlem restaurant is as much a community gathering place as it is a dining destination, blending African American, Ethiopian, Swedish, and Southern flavors in a space that pulses with live music and neighborhood energy. The fried chicken and cornbread are legendary, but Samuelsson's heritage dishes — like the doro wat and the meatballs — reveal the deeper layers of his cooking. Downstairs, Ginny's Supper Club hosts live jazz and R&B in a velvet-draped speakeasy that channels Harlem's golden era. James Beard-nominated and one of the most important cultural restaurants in New York.",
  "Thai Diner": "Ann Redding and Matt Danzer's Lower East Side spot reimagines Thai food through the lens of a classic American diner — and the result is one of the most fun, creative restaurants in downtown Manhattan. Khao soi French dip sandwiches, Thai-spiced hash browns, and pad Thai carbonara sound gimmicky but are executed with a chef's precision that makes every dish genuinely delicious. The counter seats overlooking the open kitchen are the best in the house, and the all-day format means you can eat here at any hour. Michelin-recognized for a reason — this is Thai food like you've never had it.",
  "Joe's Pizza": "Joe Pozzuoli opened this Carmine Street slice shop in 1975 and it's been serving what many consider the quintessential New York slice ever since — thin, foldable, with a crispy bottom and just the right amount of sauce and cheese. No frills, no gimmicks, just a perfectly calibrated slice that costs a few dollars and satisfies on a molecular level. The late-night line after bar close is a West Village institution, and tourists and locals stand shoulder to shoulder at the tiny counter. If you only eat one slice in New York, make it this one.",
  "Los Tacos No. 1": "This tiny Chelsea Market counter serves tacos that transport you directly to a Mexico City street corner — handmade corn tortillas, adobo-marinated pork, fresh cilantro, and salsas that range from mild to face-melting. The adobada (al pastor) is the move, charred on the trompo and folded into a tortilla so fresh it's still warm from the press. Lines form daily at this no-frills counter, but they move fast and the $4 tacos are the best value in Manhattan. No seats, no pretension, just the best tacos in New York.",
  "Raoul's": "This SoHo French bistro has been a candlelit institution since 1975 — the kind of place where artists, models, and neighborhood regulars share banquettes over steak au poivre and the famous artichoke gratin. The menu hasn't changed much in five decades because it doesn't need to — the cooking is classically French, robustly seasoned, and served with the confidence of a kitchen that knows exactly what it does well. The back garden is one of SoHo's best-kept secrets, especially in warm weather. Late-night at the bar is where SoHo's old-guard creative class still gathers.",
};

let updated = 0;
for (const [name, desc] of Object.entries(expansions)) {
  const r = data.find(r => r.name === name);
  if (r) { r.description = desc; updated++; }
}

const newData = JSON.stringify(data);
html = html.replace(match[0], "const NYC_DATA=" + newData + ";");
fs.writeFileSync("index.html", html);
console.log("NYC: " + updated + " descriptions expanded");
console.log("Done!");
