const fs = require('fs');
let html = fs.readFileSync('index.html','utf8');
const hdIdx = html.indexOf('const HOUSTON_DATA');
const arrS = html.indexOf('[', hdIdx);
let d=0, arrE=arrS;
for(let j=arrS;j<html.length;j++){if(html[j]==='[')d++;if(html[j]===']'){d--;if(d===0){arrE=j+1;break;}}}
let arr = JSON.parse(html.substring(arrS, arrE));
const maxId = Math.max(...arr.map(r=>r.id));
let nextId = maxId + 1;
const existing = new Set(arr.map(r=>r.name.toLowerCase()));

function add(spot){
  if(existing.has(spot.name.toLowerCase())) return;
  spot.id=nextId++;spot.bestOf=spot.bestOf||[];spot.busyness=null;spot.waitTime=null;spot.popularTimes=null;spot.lastUpdated=null;spot.trending=spot.trending||false;spot.group=spot.group||'';spot.suburb=spot.suburb||false;spot.menuUrl='';spot.res_tier=spot.price>=3?4:2;spot.indicators=spot.indicators||[];spot.awards=spot.awards||'';spot.phone=spot.phone||'';spot.reserveUrl=spot.reserveUrl||'';spot.hh=spot.hh||'';
  arr.push(spot);existing.add(spot.name.toLowerCase());
}

// STEP 2: UPSCALE CASUAL & DATE NIGHT
add({name:"Turner's",cuisine:"American Fine Dining",neighborhood:"Montrose",score:93,price:3,tags:["Fine Dining","Date Night","Critics Pick","Steakhouse"],description:"Chef-owner Ben McPherson intimate Montrose fine dining with one of the best dry-aged steak programs in Texas. The 32-day dry-aged ribeye is a masterwork, the wine list is deep and personal, and the 36-seat room feels like a private dinner party. One of Houston most important restaurants.",dishes:["32-Day Dry-Aged Ribeye","Wagyu Tartare","Seasonal Tasting"],address:"1800 Post Oak Blvd, Houston, TX 77056",lat:29.7466,lng:-95.4614,instagram:"turnershouston",website:"https://www.turnershouston.com",reservation:"Resy",phone:"(713) 622-2220"});
add({name:"State of Grace",cuisine:"Southern / New American",neighborhood:"River Oaks",score:91,price:3,tags:["Date Night","Southern","Local Favorites","Brunch"],description:"Ford Fry gorgeous River Oaks spot serving elevated Southern cuisine in a stunning dining room with soaring ceilings and a wraparound patio. The Gulf oysters are pristine, the fried chicken is brined and perfectly crispy, and Sunday brunch is one of the best in Houston.",dishes:["Gulf Oysters","Fried Chicken","Pimento Cheese"],address:"3258 Westheimer Rd, Houston, TX 77098",lat:29.7401,lng:-95.4266,instagram:"stateofgracehtx",website:"https://www.stateofgracehtx.com",reservation:"OpenTable",phone:"(832) 942-5080"});
add({name:"Nobie's",cuisine:"New American",neighborhood:"Upper Kirby",score:90,price:2,tags:["Date Night","Local Favorites","Casual","Critics Pick"],description:"Chef-owner Martin Stayer neighborhood gem in Upper Kirby with a seasonal menu that changes weekly and a wine list curated with genuine love. The fried chicken night is legendary, the handmade pasta is excellent, and the vibe is unpretentious and warm. Houston at its best.",dishes:["Weekly Fried Chicken Night","Handmade Pasta","Seasonal Menu"],address:"2048 Colquitt St, Houston, TX 77098",lat:29.7384,lng:-95.4098,instagram:"nobieshouston",website:"https://www.nobieshouston.com",reservation:"Resy",phone:"(713) 864-2332"});
add({name:"Underbelly Hospitality / Wild Oats",cuisine:"Southern / Global",neighborhood:"Montrose",score:91,price:2,tags:["Local Favorites","Critics Pick","Casual","Brunch"],description:"Chris Shepherd latest Montrose concept focusing on Southern comfort with global accents. The Korean braised goat is a signature, the bread service is outstanding, and the brunch is one of the most exciting in the city. From the James Beard Award winner who keeps reinventing Houston dining.",dishes:["Korean Braised Goat","Bread Service","Brunch Menu"],address:"3408 Harrisburg Blvd, Houston, TX 77003",lat:29.7385,lng:-95.3480,instagram:"wildoatshouston",website:"https://www.wildoatshouston.com",reservation:"Resy",phone:"(346) 406-3663"});
add({name:"Trattoria Sofia",cuisine:"Italian",neighborhood:"Montrose",score:89,price:2,tags:["Italian","Date Night","Local Favorites","Patio"],description:"Montrose neighborhood Italian with handmade pasta, wood-fired pizzas, and a gorgeous patio that feels like a secret garden. The cacio e pepe is properly Roman, the burrata is creamy perfection, and the wine list is all-Italian and well-priced. The date night spot Houston was missing.",dishes:["Cacio e Pepe","Burrata","Wood-Fired Pizza"],address:"903 Richmond Ave, Houston, TX 77006",lat:29.7382,lng:-95.3889,instagram:"trattoriasofiahtx",website:"https://www.trattoriasofia.com",reservation:"Resy",phone:"(713) 524-2222"});

// STEP 3: NEIGHBORHOOD FAVORITES
add({name:"El Tiempo Cantina",cuisine:"Tex-Mex",neighborhood:"Washington Corridor",score:89,price:2,tags:["Mexican","Local Favorites","Family","Margaritas"],description:"The Laurenzo family Tex-Mex dynasty -- descended from the original Ninfa who invented fajitas in Houston. The beef fajitas sizzle louder than anywhere in town, the margaritas are potent, and the green sauce is legendary. This is the Tex-Mex that Houstonians fight about.",dishes:["Beef Fajitas","Green Sauce","Margaritas"],address:"2814 Navigation Blvd, Houston, TX 77003",lat:29.7541,lng:-95.3517,instagram:"eltiempocantina",website:"https://www.eltiempocantina.com",reservation:"walk-in",phone:"(713) 222-5463"});
add({name:"Goode Company BBQ",cuisine:"Texas BBQ",neighborhood:"West University",score:87,price:1,tags:["BBQ","Local Favorites","Casual","Family","Iconic"],description:"Houston BBQ institution since 1977 with mesquite-smoked brisket, Czech sausage, and pecan pie that is borderline religious. The barn-style dining room on Kirby Drive is a Houston landmark. Not the trendiest BBQ in town, but arguably the most consistent over four decades.",dishes:["Mesquite Brisket","Czech Sausage","Pecan Pie"],address:"5109 Kirby Dr, Houston, TX 77098",lat:29.7309,lng:-95.4142,instagram:"goodecompany",website:"https://www.goodecompany.com",reservation:"walk-in",phone:"(713) 522-2530"});
add({name:"Himalaya",cuisine:"Pakistani / Indian",neighborhood:"Hillcroft",score:91,price:1,tags:["Indian","Local Favorites","Critics Pick","Casual","Hole in the Wall"],indicators:["hole-in-the-wall","halal"],description:"Kaiser Lashkari legendary Pakistani-Indian restaurant on the Hillcroft corridor that has been dazzling critics and feeding the community for decades. The lamb biryani is the best in Texas, the nihari is soul food of the highest order, and the fried chicken is a beautiful cross-cultural surprise. A James Beard semifinalist hiding in a strip mall.",dishes:["Lamb Biryani","Nihari","Fried Chicken"],address:"6652 Southwest Fwy, Houston, TX 77074",lat:29.7000,lng:-95.5224,instagram:"himalayarestaurant",website:"https://www.himalayarestauranthouston.com",reservation:"walk-in",phone:"(713) 532-2837",awards:"James Beard Semifinalist"});
add({name:"Vietopia",cuisine:"Vietnamese",neighborhood:"Chinatown / Bellaire",score:87,price:1,tags:["Vietnamese","Local Favorites","Casual","Family"],description:"Bellaire Boulevard Vietnamese that takes the breadth of Vietnamese cuisine seriously -- from pho to banh mi to broken rice plates to clay pot dishes. The shaking beef is excellent, the spring rolls are fresh, and the prices are absurdly reasonable for the quality. The Chinatown strip mall exterior hides a genuinely great restaurant.",dishes:["Shaking Beef","Pho Tai","Broken Rice Plate"],address:"5176 Buffalo Speedway, Houston, TX 77005",lat:29.7186,lng:-95.4254,instagram:"vietopiahtx",website:"https://www.vietopiarestaurant.com",reservation:"walk-in",phone:"(713) 664-7303"});
add({name:"Cafe Annie / The Annie Cafe & Bar",cuisine:"Southwestern / New American",neighborhood:"Galleria",score:90,price:3,tags:["Fine Dining","Local Favorites","Date Night","Critics Pick"],description:"Robert Del Grande reinvention of his legendary Cafe Annie -- now The Annie Cafe and Bar at the Hotel Granduca. The Southwestern-inflected menu still features his famous tamales and Gulf Coast seafood, but the room is sleeker and more modern. A Houston dining legend continues.",dishes:["Tamales","Gulf Seafood","Wood-Grilled Ribeye"],address:"1728 Post Oak Blvd, Houston, TX 77056",lat:29.7459,lng:-95.4612,instagram:"theanniehouston",website:"https://www.theanniehouston.com",reservation:"OpenTable",phone:"(713) 840-1111"});

// STEP 4: CHEAP EATS
add({name:"Tacos Tierra Caliente",cuisine:"Mexican / Street Tacos",neighborhood:"Navigation District",score:89,price:1,tags:["Mexican","Local Favorites","Casual","Hole in the Wall","Late Night"],indicators:["hole-in-the-wall"],description:"The bright orange taco truck on Navigation Boulevard that has been serving some of Houston best street tacos for years. The al pastor is properly marinated and carved from the trompo, the barbacoa is rich and gelatinous, and the green salsa has real heat. Open late. Cash preferred.",dishes:["Al Pastor Tacos","Barbacoa Tacos","Carnitas"],address:"1401 Navigation Blvd, Houston, TX 77003",lat:29.7559,lng:-95.3530,instagram:"tacostierracaliente",website:"",reservation:"walk-in",phone:""});
add({name:"Sinh Sinh",cuisine:"Chinese / Vietnamese",neighborhood:"Chinatown / Bellaire",score:88,price:1,tags:["Chinese","Vietnamese","Local Favorites","Late Night","Seafood"],description:"Chinatown late-night institution serving Cantonese-Vietnamese seafood until 4 AM. The salt and pepper crab is legendary, the garlic noodles are addictive, and the dining room at midnight is as packed as most restaurants at 7 PM. This is where Houston goes after everything else closes.",dishes:["Salt & Pepper Crab","Garlic Noodles","Crawfish"],address:"9788 Bellaire Blvd, Houston, TX 77036",lat:29.7061,lng:-95.5530,instagram:"",website:"",reservation:"walk-in",phone:"(713) 541-4888"});
add({name:"Roostar Vietnamese Grill",cuisine:"Vietnamese Sandwiches",neighborhood:"Midtown",score:87,price:1,tags:["Vietnamese","Local Favorites","Casual","Healthy"],description:"Midtown banh mi shop with creative Vietnamese sandwiches that go way beyond the classic. The lemongrass chicken is the bestseller, the chargrilled pork is smoky and sweet, and the fries are addictively crispy. Fast, fresh, and the perfect Houston lunch.",dishes:["Lemongrass Chicken Banh Mi","Chargrilled Pork","Garlic Fries"],address:"1400 Montrose Blvd, Houston, TX 77019",lat:29.7467,lng:-95.3927,instagram:"roostar_vietgrill",website:"https://www.roostarvietgrill.com",reservation:"walk-in",phone:"(713) 521-1500"});
add({name:"Torchy's Tacos",cuisine:"Tex-Mex / Creative Tacos",neighborhood:"Montrose",score:84,price:1,tags:["Mexican","Casual","Local Favorites","Brunch"],description:"Austin-born taco chain that Houstonians adopted as their own. The Trailer Park (fried chicken, green chiles, queso) is the cult favorite, the breakfast tacos are solid, and the queso is dangerously addictive. Multiple locations. Not traditional, but consistently good.",dishes:["Trailer Park Taco","Green Chile Queso","Breakfast Tacos"],address:"1900 Westheimer Rd, Houston, TX 77098",lat:29.7438,lng:-95.3984,instagram:"torchystacos",website:"https://www.torchystacos.com",reservation:"walk-in",phone:"(713) 595-8226"});

// STEP 5: BARS & COCKTAILS
add({name:"Julep",cuisine:"Cocktail Bar / Southern",neighborhood:"Washington Corridor",score:90,price:2,tags:["Cocktails","Date Night","Local Favorites","Southern"],description:"Alba Huerta James Beard Award-winning cocktail bar that celebrates the American South through spirits. The julep variations are extraordinary, the whiskey list is one of the deepest in Texas, and the charming patio is perfect for a Houston evening. The most important bar in the city.",dishes:["Mint Julep Variations","Whiskey Selection","Southern Bar Snacks"],address:"1919 Washington Ave, Houston, TX 77007",lat:29.7634,lng:-95.3874,instagram:"julephouston",website:"https://www.julephouston.com",reservation:"walk-in",phone:"(713) 869-4383",awards:"James Beard Award"});
add({name:"Better Luck Tomorrow",cuisine:"Cocktail Bar / Asian",neighborhood:"Heights",score:89,price:2,tags:["Cocktails","Late Night","Local Favorites","Casual"],description:"Bobby Heugel and Justin Yu Heights dive-bar-meets-cocktail-bar with Asian-inspired snacks that punch way above their weight. The cocktails are serious but the vibe is not -- neon signs, loud music, and a crowd that ranges from chefs to neighbors. The crispy rice is the sleeper hit.",dishes:["Craft Cocktails","Crispy Rice","Asian Snacks"],address:"544 Yale St, Houston, TX 77007",lat:29.7718,lng:-95.3963,instagram:"betterlucktmrw",website:"https://www.betterlucktmrw.com",reservation:"walk-in",phone:"(713) 862-7654"});
add({name:"La Grange",cuisine:"Cocktail Bar / Whiskey",neighborhood:"Midtown",score:87,price:2,tags:["Cocktails","Late Night","Casual","Local Favorites"],description:"Midtown Texas dancehall-inspired bar with craft cocktails, a massive whiskey selection, and live country music on weekends. The patio is huge, the vibe is authentically Texan, and the frozen ranch water is dangerously drinkable. Two-stepping optional but encouraged.",dishes:["Ranch Water","Whiskey Selection","Live Country Music"],address:"2517 Ralph St, Houston, TX 77006",lat:29.7420,lng:-95.3851,instagram:"lagrangehouston",website:"https://www.lagrangehouston.com",reservation:"walk-in",phone:"(713) 526-4677"});
add({name:"Wooster's Garden",cuisine:"Rooftop Bar / American",neighborhood:"Midtown",score:86,price:2,tags:["Rooftop","Cocktails","Patio","Date Night"],indicators:["outdoor-seating"],description:"Midtown rooftop bar and restaurant with one of the best outdoor spaces in Houston -- string lights, skyline views, and a breeze that makes summer bearable. The cocktails are well-crafted, the food is solid New American, and the vibe on a Saturday night is pure Houston energy.",dishes:["Craft Cocktails","Rooftop Views","Bar Bites"],address:"3315 Milam St, Houston, TX 77006",lat:29.7429,lng:-95.3837,instagram:"woostersgarden",website:"https://www.woostersgarden.com",reservation:"walk-in",phone:"(713) 485-0497"});

// STEP 6: COFFEE & DESSERT
add({name:"Boomtown Coffee",cuisine:"Coffee",neighborhood:"Heights",score:86,price:1,tags:["Bakery/Coffee","Casual","Local Favorites"],description:"Heights specialty coffee roaster with a massive patio, excellent single-origin pour-overs, and some of the best baristas in Houston. The space is airy and welcoming, the pastries are sourced well, and the cold brew is dangerously smooth. The coffee shop the Heights deserved.",dishes:["Single Origin Pour Over","Cold Brew","Espresso"],address:"242 W 19th St, Houston, TX 77008",lat:29.8033,lng:-95.3977,instagram:"boomtowncoffee",website:"https://www.boomtowncoffee.com",reservation:"walk-in",phone:"(713) 862-8550"});
add({name:"Common Bond",cuisine:"Bakery / Cafe",neighborhood:"Montrose",score:88,price:1,tags:["Bakery/Coffee","Brunch","Local Favorites","Casual"],description:"The bakery that elevated Houston baked goods to a national level. The croissants are perfectly laminated, the kouign-amann is a butter bomb of the highest order, and the coffee program is serious. Multiple locations, but the original Montrose spot has the most character.",dishes:["Kouign-Amann","Croissant","Avocado Toast"],address:"1706 Westheimer Rd, Houston, TX 77098",lat:29.7442,lng:-95.3948,instagram:"commonbondhtx",website:"https://www.commonbondcafe.com",reservation:"walk-in",phone:"(713) 529-3535"});
add({name:"Fat Cat Creamery",cuisine:"Ice Cream",neighborhood:"Heights",score:87,price:1,tags:["Dessert","Local Favorites","Casual"],description:"Heights small-batch ice cream shop with creative flavors that rotate seasonally. The Mexican hot chocolate is the signature, the Vietnamese coffee is bold and sweet, and the waffle cones are made fresh. Local ingredients, no artificial anything, and a line out the door on summer evenings.",dishes:["Mexican Hot Chocolate","Vietnamese Coffee","Seasonal Flavor"],address:"1003 E 11th St, Houston, TX 77009",lat:29.7902,lng:-95.3561,instagram:"fatcatcreamery",website:"https://www.fatcatcreamery.com",reservation:"walk-in",phone:"(832) 856-1247"});

// STEP 7: ENTERTAINMENT
add({name:"White Oak Music Hall",cuisine:"Live Music Venue",neighborhood:"Heights",score:89,price:2,tags:["Live Music","Entertainment","Local Favorites","Patio"],description:"Houston premier indie music venue with indoor and outdoor stages, a massive lawn, and a rooftop bar. The outdoor shows in spring and fall are magical. Books everything from local bands to national touring acts. The most important mid-size venue in the city.",dishes:["Indoor Stage","Outdoor Lawn","Rooftop Bar"],address:"2915 N Main St, Houston, TX 77009",lat:29.7838,lng:-95.3652,instagram:"whiteoakmusichall",website:"https://www.whiteoakmusichall.com",reservation:"walk-in",phone:"(713) 237-0370"});
add({name:"8th Wonder Brewery",cuisine:"Brewery",neighborhood:"East Downtown / EaDo",score:86,price:1,tags:["Brewery","Casual","Local Favorites","Patio"],indicators:["brewery"],description:"EaDo craft brewery with a massive taproom, food trucks, and an outdoor area that is basically a neighborhood park. The Dome Faux'm cream ale is the flagship, and the rotating IPAs are solid. Free brewery tours on weekends. The social anchor of the EaDo neighborhood.",dishes:["Dome Faux'm Cream Ale","Rotating IPAs","Food Trucks"],address:"2202 Dallas St, Houston, TX 77003",lat:29.7519,lng:-95.3491,instagram:"8thwonderbrewery",website:"https://www.8thwonder.com",reservation:"walk-in",phone:"(713) 229-0868"});
add({name:"The Improv Houston",cuisine:"Comedy Club",neighborhood:"Galleria",score:85,price:2,tags:["Entertainment","Comedy Club","Date Night"],description:"Houston outpost of the national comedy chain booking touring headliners and local rising talent. The showroom is intimate enough that every seat feels close, and the two-drink minimum keeps the crowd loose. National acts rotate weekly -- check the calendar for surprise drop-ins.",dishes:["Comedy Shows","Craft Cocktails","Date Night"],address:"7620 Katy Fwy, Houston, TX 77024",lat:29.7819,lng:-95.4813,instagram:"improvhouston",website:"https://www.improv.com/houston",reservation:"OpenTable",phone:"(713) 333-8800"});

const added = arr.length - 33;
console.log('Added', added, 'new Houston spots. Total:', arr.length);

// Upgrade the 13 short descriptions
const shortFixes = {
  7002: "Chef Aldo Espinosa tasting menu hidden in a Spring Branch strip mall that fuses Mexican tradition with avant-garde technique. The 10+ course menu changes constantly, with dishes like huitlacoche in corn silk and wagyu with mole that blur the line between heritage and innovation. One of the most ambitious restaurants in Houston.",
  7003: "Alain Verzeroli vegetable-forward French restaurant inside the Museum of Fine Arts Houston. The produce is treated with the reverence most restaurants reserve for wagyu, the garden terrace is one of the most elegant dining settings in the city, and the seasonal menu changes with genuine intention. A Michelin-level experience in Houston museum district.",
  7004: "The first Michelin-starred Spanish restaurant in Houston, bringing authentic Catalan cuisine to Montrose with a deep wine list and impeccable tapas. The paella takes 45 minutes and is worth every second, the jamon iberico is carved tableside, and the crema catalana is a perfect closer. Spain in Houston.",
  7006: "Spring BBQ trailer that earned a cult following smoking everything over Texas post oak with obsessive attention to detail. The brisket bark is shatteringly crisp, the pork ribs are fall-off-the-bone tender, and the sides are above average. The line forms early and they sell out daily. Worth the drive north.",
  7007: "Leonard Botello brought his Brenham BBQ operation to the Heights and immediately became one of the best in Houston. The brisket has a clean smoke ring and buttery texture, the ribs are competition-quality, and the banana pudding is transcendent. Opens at 11, sells out daily.",
  7008: "Hugo Ortega flagship Montrose Mexican that introduced Houston to the depth and sophistication of regional Mexican cooking. The moles take days to prepare, the cochinita pibil is wrapped in banana leaves, and the Sunday brunch buffet is a Houston institution. James Beard Award-winning and still essential.",
  7012: "Heights Vietnamese that serves some of the best pho in a city drowning in excellent pho. The broth is clear, deeply flavored, and the product of hours of simmering. The banh mi is excellent, the spring rolls are fresh, and the prices are absurdly fair. A neighborhood staple.",
  7014: "Justin Yu downtown tasting menu spot that broke boundaries when it opened and continues to push Houston dining forward. The hyper-seasonal menu draws from local farms and global technique, and the open kitchen lets you watch every plate come together. Intimate, inventive, and one of Houston most important restaurants.",
  7015: "Hugo Ortega love letter to Oaxacan cuisine inside the Marriott Marquis that is one of the most important Mexican restaurants in America. The mole negro takes days to make and tastes like it. The chocolate desserts are world-class. The cacao nib crusted lamb is a signature.",
  7016: "The best steakhouse in Houston and a genuine contender for best in Texas. The dry-aged prime cuts are impeccable, the lobster bisque is a starter that could be a main, and the old-school clubhouse atmosphere makes every dinner feel like an event. The Pappas family takes steak very seriously.",
  7020: "The Sichuan restaurant that made Chinatown a destination for adventurous eaters. The dan dan noodles have proper mala numbing heat, the mapo tofu is authentically fiery, and the cumin lamb is addictive. Deep menu with 150+ items. Ask for extra spice -- they will respect you for it.",
  7021: "Hugo Ortega coastal Mexican seafood in the Galleria area with Gulf shrimp, whole grilled fish, and ceviches that transport you to a Mexican beach town. The octopus is perfectly tender, the guacamole is tableside, and the margaritas are perfectly balanced. A seafood destination.",
  7022: "Heights BBQ from Grant Pinkerton that earned praise for its brisket and creative sides. The prime brisket is smoked low and slow over post oak, the jalapeño cheese grits are a perfect complement, and the peach cobbler is excellent. A worthy addition to Houston legendary BBQ scene.",
};

Object.entries(shortFixes).forEach(([id, desc]) => {
  const spot = arr.find(r => r.id === parseInt(id));
  if(spot) spot.description = desc;
});
console.log('Upgraded', Object.keys(shortFixes).length, 'short descriptions');

html = html.substring(0, arrS) + JSON.stringify(arr) + html.substring(arrE);
fs.writeFileSync('index.html', html, 'utf8');
fs.copyFileSync('index.html', 'index');
console.log('Done!');
