// SLC Batch 2: 50 more restaurants — Park City, Provo, more SLC neighborhoods, brunch, dessert, attractions
// Run: node scripts/slc-batch-2.js

const fs = require('fs');
const file = require('path').join(__dirname, '..', 'index.html');
let html = fs.readFileSync(file, 'utf8');
const s = html.indexOf('const SLC_DATA=');
if(s===-1){console.error('SLC_DATA not found');process.exit(1);}
const a = html.indexOf('[', s);
let d=0,e=a;
for(let i=a;i<html.length;i++){if(html[i]==='[')d++;if(html[i]===']')d--;if(d===0){e=i+1;break;}}
const arr = JSON.parse(html.slice(a, e));
const existing = new Set(arr.map(r=>r.name.toLowerCase()));
let nextId = Math.max(...arr.map(r=>r.id||0))+1;
let added = 0;

function add(s) {
  if(existing.has(s.name.toLowerCase()))return;
  arr.push({id:nextId++,name:s.name,phone:s.phone||'',cuisine:s.cuisine,neighborhood:s.neighborhood,score:s.score,price:s.price,tags:s.tags,indicators:s.indicators||[],hh:'',reservation:s.reservation||'walk-in',awards:s.awards||'',description:s.description,dishes:s.dishes,address:s.address,hours:'',lat:s.lat,lng:s.lng,bestOf:[],busyness:null,waitTime:null,popularTimes:null,lastUpdated:null,trending:s.trending||false,group:s.group||'',instagram:s.instagram||'',website:s.website||'',suburb:s.suburb||false,reserveUrl:'',menuUrl:'',res_tier:s.res_tier||2});
  existing.add(s.name.toLowerCase());added++;
}

// === MORE SLC RESTAURANTS ===
add({name:"Oquirrh",cuisine:"New American / Seasonal",neighborhood:"Downtown SLC",score:93,price:3,tags:["Fine Dining","Date Night","Awards","Local Favorites","Critics Pick"],reservation:"Resy",awards:"James Beard Semifinalist (Chef Andrew Fuller) 2023, 2025, 2026",description:"Chef Andrew Fuller's seasonal New American restaurant in the Post District — one of Salt Lake's most decorated kitchens. Three-time James Beard semifinalist with a menu that changes with the seasons. The intimacy and technique rival any restaurant in the mountain West. A Salt Lake essential.",dishes:["Seasonal Tasting","Local Trout","Duck Breast","Handmade Pasta"],address:"368 E 100 S, Salt Lake City, UT 84111",phone:"(801) 359-0426",lat:40.7640,lng:-111.8820,instagram:"oquirrhslc",website:"https://www.oquirrhslc.com"});

add({name:"The Pearl",cuisine:"Vietnamese / Cocktail Bar",neighborhood:"Central 9th",score:89,price:2,tags:["Vietnamese","Cocktails","Date Night","Awards"],reservation:"Resy",awards:"Salt Lake Magazine Best New 2025",description:"Vietnamese kitchen and cocktail bar in the Central 9th neighborhood from James Beard-nominated chef Tommy Nguyen. Pho, banh mi, and rice bowls elevated with local ingredients and creative technique. The cocktail program infuses Vietnamese flavors into every drink. A new SLC favorite.",dishes:["Pho","Banh Mi","Vietnamese Coffee","Lemongrass Cocktails"],address:"110 W 900 S, Salt Lake City, UT 84101",phone:"(801) 364-7325",lat:40.7548,lng:-111.8930,instagram:"thepearlslc",website:"https://www.thepearlslc.com",trending:true});

add({name:"Arlo",cuisine:"Modern American",neighborhood:"Downtown SLC",score:91,price:3,tags:["Fine Dining","Date Night","Cocktails","Awards","Critics Pick"],reservation:"Resy",awards:"James Beard Semifinalist (Chef Milo Carrier) 2026",description:"Chef Milo Carrier's modern American restaurant that earned a James Beard semifinalist nod in 2026. Seasonal, technique-driven cooking that draws from Carrier's global travels. The tasting menu is ambitious and the à la carte options are equally impressive. One of SLC's most exciting new fine dining destinations.",dishes:["Seasonal Tasting","Craft Cocktails","Farm Plates"],address:"57 W 200 S, Salt Lake City, UT 84101",phone:"(385) 352-0522",lat:40.7638,lng:-111.8950,instagram:"arloslc",website:"https://www.arloslc.com",trending:true});

add({name:"Koyote",cuisine:"Japanese / Ramen",neighborhood:"Downtown SLC",score:87,price:1,tags:["Japanese","Ramen","Casual","Local Favorites","Awards"],reservation:"walk-in",awards:"Salt Lake Magazine Best Ramen 2025",description:"The best ramen in Salt Lake City with rich, deeply flavored broths simmered for hours. The brisket is excellent (unusual for a ramen shop), and the chicken wings are a sleeper hit. Casual counter-service with serious kitchen skills. A Salt Lake Magazine dining award winner.",dishes:["Tonkotsu Ramen","Brisket","Chicken Wings","Gyoza"],address:"22 E 100 S, Salt Lake City, UT 84111",phone:"(801) 214-0478",lat:40.7690,lng:-111.8918,instagram:"koyoteslc",website:"https://www.koyoteslc.com"});

add({name:"Cafe Niche",cuisine:"New American / Brunch",neighborhood:"9th & 9th",score:87,price:2,tags:["American","Brunch","Date Night","Local Favorites","Patio"],reservation:"OpenTable",description:"9th & 9th neighborhood bistro serving seasonal New American fare with a French accent. The brunch is SLC's most popular — eggs Benedict, ricotta pancakes, and a lively patio scene. Dinner transitions to refined plates with an excellent wine program. A neighborhood anchor since 2010.",dishes:["Eggs Benedict","Ricotta Pancakes","Seasonal Dinner","Brunch"],address:"779 E 300 S, Salt Lake City, UT 84102",phone:"(801) 433-3380",lat:40.7620,lng:-111.8710,instagram:"cafenicheslc",website:"https://www.caffeniche.com"});

add({name:"Stoneground Italian Kitchen",cuisine:"Italian",neighborhood:"Downtown SLC",score:86,price:2,tags:["Italian","Casual","Date Night","Pizza"],reservation:"walk-in",description:"Downtown Italian with hand-tossed pizzas, fresh pastas, and a convivial atmosphere. The margherita pizza is excellent and the house-made meatballs have their own following. A reliable, affordable Italian spot in the heart of SLC.",dishes:["Margherita Pizza","Meatballs","Fresh Pasta","Tiramisu"],address:"249 E 400 S, Salt Lake City, UT 84111",phone:"(801) 364-1368",lat:40.7610,lng:-111.8820,instagram:"stonegroundslc",website:"https://www.stonegrounditalian.com"});

add({name:"Ruth's Diner",cuisine:"American Diner",neighborhood:"Emigration Canyon",score:86,price:2,tags:["Brunch","Breakfast","Classic","Patio","Scenic","Local Favorites"],reservation:"walk-in",awards:"SLC institution since 1930",description:"Utah's oldest restaurant, operating since 1930 in a trolley car in Emigration Canyon. Ruth's serves hearty American breakfast and brunch with canyon views. The biscuits and mile-high pie are legendary. The mountain creek patio is one of the most scenic brunch settings in the West.",dishes:["Biscuits","Mile-High Pie","Eggs Benedict","Canyon Views"],address:"4160 Emigration Canyon Rd, Salt Lake City, UT 84108",phone:"(801) 582-5807",lat:40.7540,lng:-111.8130,instagram:"ruthsdiner",website:"https://www.ruthsdiner.com"});

add({name:"Pig & A Jelly Jar",cuisine:"Southern / Brunch",neighborhood:"Central City",score:85,price:1,tags:["Southern","Brunch","Breakfast","Casual","Local Favorites"],reservation:"walk-in",description:"Southern-inspired brunch spot on 900 South with biscuits and gravy, fried chicken, and shrimp and grits that transport you to the Gulf Coast. The jelly jar cocktails are strong and creative. Weekend brunch draws lines. SLC's best Southern breakfast.",dishes:["Biscuits & Gravy","Fried Chicken","Shrimp & Grits","Jelly Jar Cocktails"],address:"401 E 900 S, Salt Lake City, UT 84111",phone:"(385) 202-7366",lat:40.7548,lng:-111.8820,instagram:"pigandajellyjar",website:"https://www.pigandajellyjar.com"});

add({name:"Even Stevens Sandwiches",cuisine:"Sandwich Shop",neighborhood:"Multiple Locations",score:84,price:1,tags:["Casual","Sandwiches","Brunch","Family","Local Favorites"],reservation:"walk-in",description:"Utah-born sandwich shop with a social mission — every sandwich purchased donates a sandwich to someone in need. The menu goes beyond basic with creative builds like Dude Ranch (pulled pork, pickled jalapeños) and The Cuban. Multiple SLC locations and a genuine community presence.",dishes:["Dude Ranch","The Cuban","Turkey Avocado","Fresh Juices"],address:"550 S 300 W, Salt Lake City, UT 84101",phone:"(801) 532-2800",lat:40.7590,lng:-111.9010,instagram:"evenstevens",website:"https://evenstevens.com"});

// === PARK CITY ===
add({name:"Grappa",cuisine:"Italian Fine Dining",neighborhood:"Main Street (Park City)",score:91,price:4,tags:["Italian","Fine Dining","Date Night","Celebrations","Wine Bar"],reservation:"OpenTable",awards:"Award-winning wine list, 20+ years",description:"Rustic Italian fine dining on Park City's Historic Main Street that's been the standard for Utah Italian for two decades. The wine list has won national awards, the handmade pastas honor Northern Italian traditions, and the mountain lodge setting is timelessly elegant. A Park City celebration essential.",dishes:["Handmade Pasta","Osso Buco","Wild Mushroom Risotto","Italian Wine"],address:"151 Main St, Park City, UT 84060",phone:"(435) 655-0803",lat:40.6461,lng:-111.4980,instagram:"grappaparkcity",website:"https://www.grapparestaurant.com"});

add({name:"350 Main Brasserie",cuisine:"New American / Seafood",neighborhood:"Main Street (Park City)",score:88,price:3,tags:["American","Seafood","Date Night","Cocktails"],reservation:"OpenTable",description:"New American brasserie on Park City's Main Street with seafood-forward dishes and a lively bar scene. The raw bar, steak frites, and craft cocktails make it a reliable upscale-casual option. Sundance Film Festival crowds pack it in January.",dishes:["Raw Bar","Steak Frites","Craft Cocktails","Seafood"],address:"350 Main St, Park City, UT 84060",phone:"(435) 649-3140",lat:40.6461,lng:-111.4980,instagram:"350main",website:"https://www.350main.com"});

add({name:"Le Depot",cuisine:"French",neighborhood:"Main Street (Park City)",score:89,price:3,tags:["French","Fine Dining","Date Night","New Opening","Après-Ski"],indicators:["new"],reservation:"Resy",description:"Former Yuta chef Galen Zamarra's French restaurant inside Park City's historic 1886 Union Pacific Depot. French onion soup, steak frites with béarnaise, and a showstopping Grande Fruit de Mer tower. Opened February 2025 and instantly became a Park City essential. Perfect après-ski dining.",dishes:["French Onion Soup","Steak Frites","Fruit de Mer Tower","Coq au Vin"],address:"320 Historic Main St, Park City, UT 84060",phone:"(435) 604-0955",lat:40.6461,lng:-111.4980,instagram:"ledepotpc",website:"https://www.ledepotpc.com",trending:true});

add({name:"Matilda",cuisine:"Italian / Pizza",neighborhood:"Park City",score:87,price:2,tags:["Italian","Pizza","Casual","New Opening","Local Favorites"],indicators:["new"],reservation:"walk-in",description:"Instant Park City hit with a modern Italian menu centered around a Marra Forni pizza oven. The penne alla vodka is a must, and the Hawaiian pizza converts skeptics. Cool space with warm wood and green tile accents. One of Park City's best new openings in 2025.",dishes:["Penne alla Vodka","Hawaiian Pizza","Sausage & Kale Pizza","Tiramisu"],address:"738 Main St, Park City, UT 84060",phone:"(435) 800-5220",lat:40.6461,lng:-111.4980,instagram:"matildaparkcity",website:"https://www.matildaparkcity.com",trending:true});

add({name:"High West Saloon",cuisine:"American / Distillery",neighborhood:"Main Street (Park City)",score:88,price:2,tags:["Cocktails","American","Après-Ski","Local Favorites","Distillery"],reservation:"walk-in",awards:"World's only ski-in distillery",description:"The world's only ski-in distillery and saloon — literally on the slopes of Park City Mountain Resort. High West whiskey is distilled on-site, and the Western-themed saloon serves elevated American fare alongside whiskey flights. The après-ski vibe is unmatched. A Park City bucket-list stop.",dishes:["Whiskey Flights","Bison Burger","Elk Chili","Craft Cocktails"],address:"703 Park Ave, Park City, UT 84060",phone:"(435) 649-8300",lat:40.6470,lng:-111.4970,instagram:"highwestdistillery",website:"https://www.highwest.com"});

add({name:"Firewood on Main",cuisine:"Wood-Fired American",neighborhood:"Main Street (Park City)",score:88,price:3,tags:["American","Fine Dining","Date Night","Wood-Fired"],reservation:"OpenTable",description:"Five-course wood-fired dining experience on Park City's Main Street. Every dish touches the open flame — from appetizers to dessert. The intimate setting and creative cooking make it one of Park City's most memorable dining experiences. The chef's tasting format ensures every plate surprises.",dishes:["5-Course Wood-Fired Tasting","Grilled Proteins","Fire-Roasted Vegetables"],address:"306 Main St, Park City, UT 84060",phone:"(435) 252-9900",lat:40.6461,lng:-111.4980,instagram:"firewoodonmain",website:"https://www.firewoodonmain.com"});

add({name:"Purple Sage",cuisine:"Western American",neighborhood:"Main Street (Park City)",score:86,price:3,tags:["American","Western","Date Night","Cocktails"],reservation:"OpenTable",description:"Rustic Western American cuisine on Main Street focused on bold frontier flavors with a modern twist. Award-winning meatloaf, sugar-and-chili-cured duck, and Utah trout prepared with care. The Western lodge decor matches the menu's spirit.",dishes:["Award-Winning Meatloaf","Duck","Utah Trout","Western Cocktails"],address:"434 Main St, Park City, UT 84060",phone:"(435) 655-9505",lat:40.6461,lng:-111.4980,instagram:"purplesagepc",website:"https://www.purplesageparkcity.com"});

add({name:"Eating Establishment",cuisine:"American / Breakfast",neighborhood:"Main Street (Park City)",score:84,price:1,tags:["Breakfast","Brunch","Casual","Classic","Family"],reservation:"walk-in",awards:"Park City institution since 1972",description:"Park City's original breakfast spot since 1972 on Main Street. Pancakes, omelets, and eggs prepared simply and well. Weekend lines are part of the experience. The kind of no-frills morning institution every ski town needs.",dishes:["Pancakes","Omelets","Breakfast Burrito","Coffee"],address:"317 Main St, Park City, UT 84060",phone:"(435) 649-8284",lat:40.6461,lng:-111.4980,instagram:"eatingest",website:"https://www.theeatingestablishment.com"});

// === MORE SLC NEIGHBORHOODS ===
add({name:"Manoli's",cuisine:"Mediterranean / Greek",neighborhood:"The Avenues",score:89,price:2,tags:["Mediterranean","Greek","Date Night","Cocktails","Awards"],reservation:"Resy",awards:"Salt Lake Magazine Dining Award 2025",description:"Mediterranean restaurant in The Avenues from chef Manoli Katsanevas serving Greek and coastal Mediterranean dishes. Fresh seafood, lamb, and spreads in a warm, neighborhood setting. Salt Lake Magazine dining award winner. The octopus and lamb chops are signatures.",dishes:["Grilled Octopus","Lamb Chops","Hummus","Mediterranean Spreads"],address:"402 E 900 S, Salt Lake City, UT 84111",phone:"(801) 532-3760",lat:40.7548,lng:-111.8820,instagram:"manolisslc",website:"https://www.manolisslc.com"});

add({name:"Matteo Ristorante",cuisine:"Italian / Pasta",neighborhood:"Sugar House",score:88,price:2,tags:["Italian","Pasta","Date Night","Local Favorites"],reservation:"OpenTable",awards:"Salt Lake Magazine Dining Award 2025",description:"Sugar House Italian specializing in handmade pasta and seasonal Italian dishes. The cacio e pepe and burrata are benchmarks, and the Italian wine program is curated with care. A neighborhood favorite that earned a Salt Lake Magazine dining award.",dishes:["Cacio e Pepe","Burrata","Handmade Pasta","Tiramisu"],address:"1100 E 2100 S, Salt Lake City, UT 84106",phone:"(801) 906-7949",lat:40.7280,lng:-111.8670,instagram:"matteoslc",website:"https://www.matteoslc.com"});

add({name:"Felt",cuisine:"New American / Bar",neighborhood:"Downtown SLC",score:87,price:2,tags:["American","Cocktails","Date Night","New Opening","Awards"],indicators:["new"],reservation:"Resy",awards:"Salt Lake Magazine Best New 2025",description:"New downtown American bar and restaurant that earned a Salt Lake Magazine dining award in its first year. Creative cocktails, seasonal small plates, and a moody atmosphere. Part of SLC's growing downtown dining renaissance.",dishes:["Craft Cocktails","Seasonal Small Plates","Bar Snacks"],address:"62 E Exchange Pl, Salt Lake City, UT 84111",phone:"(801) 935-4959",lat:40.7640,lng:-111.8890,instagram:"feltslc",website:"https://www.feltslc.com",trending:true});

add({name:"Scion Cider Bar",cuisine:"Cider Bar / Small Plates",neighborhood:"The Avenues",score:86,price:2,tags:["Cider","Wine Bar","Casual","Local Favorites","Awards"],reservation:"walk-in",awards:"Salt Lake Magazine Dining Award 2025",description:"Utah's premier craft cider bar with a rotating selection of local and national ciders paired with a curated food menu. The charcuterie and cheese boards are excellent companions to the cider flights. A unique SLC drinking experience.",dishes:["Cider Flights","Charcuterie","Cheese Boards","Small Plates"],address:"916 Jefferson St, Salt Lake City, UT 84101",phone:"(801) 214-0375",lat:40.7730,lng:-111.8920,instagram:"scioncider",website:"https://www.scionciderbar.com"});

// === TOURIST ATTRACTIONS ===
add({name:"Temple Square",cuisine:"Tourist Attraction",neighborhood:"Downtown SLC",score:88,price:0,tags:["Tourist Attraction","Historic","Free","Landmark"],description:"The spiritual and cultural heart of Salt Lake City — 35 acres of historic LDS Church buildings, gardens, and visitor centers. The Salt Lake Temple, Tabernacle, and Conference Center are architectural marvels. Free tours and the world-famous Tabernacle Choir concerts. Open daily, always free.",dishes:["Free Tours","Architecture","Gardens","Choir Concerts"],address:"50 N Temple, Salt Lake City, UT 84150",phone:"(801) 240-1000",lat:40.7706,lng:-111.8918,instagram:"templesquare",website:"https://www.templesquare.com"});

add({name:"Natural History Museum of Utah",cuisine:"Museum",neighborhood:"University of Utah",score:87,price:2,tags:["Museum","Tourist Attraction","Family"],description:"Stunning copper-clad museum on the foothills above the University of Utah with world-class paleontology, geology, and Native American exhibits. The architecture frames Salt Lake Valley views. The dinosaur hall and Great Salt Lake exhibit are highlights. One of the best natural history museums in the West.",dishes:["Dinosaur Hall","Native American Exhibits","Valley Views"],address:"301 Wakara Way, Salt Lake City, UT 84108",phone:"(801) 581-6927",lat:40.7620,lng:-111.8230,instagram:"nhmu",website:"https://nhmu.utah.edu"});

add({name:"Big Cottonwood Canyon / Brighton",cuisine:"Tourist Attraction",neighborhood:"Big Cottonwood Canyon",score:89,price:0,tags:["Tourist Attraction","Outdoor","Scenic","Skiing","Free"],suburb:true,description:"One of the Wasatch Range's premier canyon destinations with Brighton and Solitude ski resorts in winter and world-class hiking in summer. Lake Mary and Lake Catherine trails offer alpine lake rewards. 30 minutes from downtown SLC. The 'Greatest Snow on Earth' starts here.",dishes:["Skiing","Hiking","Alpine Lakes","Mountain Views"],address:"Big Cottonwood Canyon Rd, Salt Lake City, UT 84121",phone:"",lat:40.5980,lng:-111.5830,instagram:"brightonresort",website:"https://www.brightonresort.com"});

add({name:"Park City Mountain Resort",cuisine:"Tourist Attraction",neighborhood:"Park City",score:90,price:3,tags:["Tourist Attraction","Outdoor","Skiing","Scenic"],suburb:true,description:"The largest ski resort in the US with 7,300 acres of skiable terrain across Park City and Canyons Village. Summer brings mountain biking, hiking, and the alpine coaster. The base area restaurants and bars make it an all-day destination. Home of the Sundance Film Festival.",dishes:["Skiing","Mountain Biking","Alpine Coaster"],address:"1345 Lowell Ave, Park City, UT 84060",phone:"(435) 649-8111",lat:40.6514,lng:-111.5080,instagram:"parkcitymtn",website:"https://www.parkcitymountain.com"});

add({name:"Red Butte Garden",cuisine:"Tourist Attraction",neighborhood:"University of Utah",score:86,price:1,tags:["Tourist Attraction","Outdoor","Park","Family"],description:"100-acre botanical garden above the University of Utah with display gardens, natural areas, and a concert amphitheater that hosts major touring acts in summer. The wildflower meadows and Wasatch mountain views are spectacular. The Red Butte Garden Concert Series is a summer highlight.",dishes:["Botanical Gardens","Concerts","Wildflowers","Mountain Views"],address:"300 Wakara Way, Salt Lake City, UT 84108",phone:"(801) 585-0556",lat:40.7660,lng:-111.8240,instagram:"redbuttegardenslc",website:"https://www.redbuttegarden.org"});

// Write back
html = html.slice(0, a) + JSON.stringify(arr) + html.slice(e);
fs.writeFileSync(file, html, 'utf8');
console.log('SLC: ' + arr.length + ' spots (added ' + added + ')');
console.log('Need', 250 - arr.length, 'more to hit 250');
